// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplyperiods.sql

package store

import (
	"context"
	"time"
)

const endSupplyPeriod = `-- name: EndSupplyPeriod :one
UPDATE energy.supply_periods SET "end" = $1::timestamptz, status = $2 WHERE id = $3
RETURNING id, metering_point_id, customer_id, start, "end", status
`

type EndSupplyPeriodParams struct {
	EndAt  time.Time
	Status string
	ID     int32
}

// EndSupplyPeriod sets end and status together: EndSupplyPeriodEndpoint's
// own transition (status always 'Ended') and SwitchSupplyPeriodEndpoint's
// close-the-active-period step (also always 'Ended') both use it.
func (q *Queries) EndSupplyPeriod(ctx context.Context, arg EndSupplyPeriodParams) (EnergySupplyPeriod, error) {
	row := q.db.QueryRow(ctx, endSupplyPeriod, arg.EndAt, arg.Status, arg.ID)
	var i EnergySupplyPeriod
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.CustomerID,
		&i.Start,
		&i.End,
		&i.Status,
	)
	return i, err
}

const getActiveOpenSupplyPeriod = `-- name: GetActiveOpenSupplyPeriod :one
SELECT id, metering_point_id, customer_id, start, "end", status
FROM energy.supply_periods
WHERE metering_point_id = $1 AND status = 'Active' AND "end" IS NULL
LIMIT 1
`

// GetActiveOpenSupplyPeriod finds the one open (end IS NULL), Active period
// for a metering point, if any (SwitchSupplyPeriodEndpoint.cs:31-32; energy
// inventory §2.3 — at most one can ever exist per metering point, the
// exclusion constraint's own invariant, so LIMIT 1 never discards a second
// candidate).
func (q *Queries) GetActiveOpenSupplyPeriod(ctx context.Context, meteringPointID int32) (EnergySupplyPeriod, error) {
	row := q.db.QueryRow(ctx, getActiveOpenSupplyPeriod, meteringPointID)
	var i EnergySupplyPeriod
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.CustomerID,
		&i.Start,
		&i.End,
		&i.Status,
	)
	return i, err
}

const getSupplyPeriod = `-- name: GetSupplyPeriod :one
SELECT id, metering_point_id, customer_id, start, "end", status
FROM energy.supply_periods
WHERE id = $1 AND metering_point_id = $2
`

type GetSupplyPeriodParams struct {
	ID              int32
	MeteringPointID int32
}

// GetSupplyPeriod is the (periodId, meteringPointId) lookup both
// EndSupplyPeriodEndpoint and CancelSupplyPeriodEndpoint run (:15).
func (q *Queries) GetSupplyPeriod(ctx context.Context, arg GetSupplyPeriodParams) (EnergySupplyPeriod, error) {
	row := q.db.QueryRow(ctx, getSupplyPeriod, arg.ID, arg.MeteringPointID)
	var i EnergySupplyPeriod
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.CustomerID,
		&i.Start,
		&i.End,
		&i.Status,
	)
	return i, err
}

const insertSupplyPeriod = `-- name: InsertSupplyPeriod :one
INSERT INTO energy.supply_periods (metering_point_id, customer_id, start, status)
VALUES ($1, $2, $3::timestamptz, $4)
RETURNING id, metering_point_id, customer_id, start, "end", status
`

type InsertSupplyPeriodParams struct {
	MeteringPointID int32
	CustomerID      int32
	Start           time.Time
	Status          string
}

// InsertSupplyPeriod creates a new, always open-ended (end NULL) supply
// period (CreateSupplyPeriodEndpoint.cs:25-26, SwitchSupplyPeriodEndpoint.cs:59-65).
func (q *Queries) InsertSupplyPeriod(ctx context.Context, arg InsertSupplyPeriodParams) (EnergySupplyPeriod, error) {
	row := q.db.QueryRow(ctx, insertSupplyPeriod,
		arg.MeteringPointID,
		arg.CustomerID,
		arg.Start,
		arg.Status,
	)
	var i EnergySupplyPeriod
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.CustomerID,
		&i.Start,
		&i.End,
		&i.Status,
	)
	return i, err
}

const listSupplyPeriodsByMeteringPoint = `-- name: ListSupplyPeriodsByMeteringPoint :many
SELECT id, metering_point_id, customer_id, start, "end", status
FROM energy.supply_periods
WHERE metering_point_id = $1
ORDER BY start
`

// ListSupplyPeriodsByMeteringPoint is GetSupplyPeriodsEndpoint's history,
// ordered by Start (:15).
func (q *Queries) ListSupplyPeriodsByMeteringPoint(ctx context.Context, meteringPointID int32) ([]EnergySupplyPeriod, error) {
	rows, err := q.db.Query(ctx, listSupplyPeriodsByMeteringPoint, meteringPointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnergySupplyPeriod
	for rows.Next() {
		var i EnergySupplyPeriod
		if err := rows.Scan(
			&i.ID,
			&i.MeteringPointID,
			&i.CustomerID,
			&i.Start,
			&i.End,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSupplyPeriodStatus = `-- name: SetSupplyPeriodStatus :one
UPDATE energy.supply_periods SET status = $1 WHERE id = $2
RETURNING id, metering_point_id, customer_id, start, "end", status
`

type SetSupplyPeriodStatusParams struct {
	Status string
	ID     int32
}

// SetSupplyPeriodStatus is CancelSupplyPeriodEndpoint's unconditional
// transition (:15) — no status guard, an already-Ended or already-Cancelled
// period can be cancelled again (energy inventory §1.1/§8 oddity 5).
func (q *Queries) SetSupplyPeriodStatus(ctx context.Context, arg SetSupplyPeriodStatusParams) (EnergySupplyPeriod, error) {
	row := q.db.QueryRow(ctx, setSupplyPeriodStatus, arg.Status, arg.ID)
	var i EnergySupplyPeriod
	err := row.Scan(
		&i.ID,
		&i.MeteringPointID,
		&i.CustomerID,
		&i.Start,
		&i.End,
		&i.Status,
	)
	return i, err
}

const supplyPeriodOverlapExists = `-- name: SupplyPeriodOverlapExists :one
SELECT EXISTS (
    SELECT 1 FROM energy.supply_periods
    WHERE metering_point_id = $1
      AND status <> 'Cancelled'
      AND $2::timestamptz < COALESCE("end", 'infinity'::timestamptz)
)
`

type SupplyPeriodOverlapExistsParams struct {
	MeteringPointID int32
	Start           time.Time
}

// SupplyPeriodOverlapExists is the "friendly" advisory overlap pre-check
// Create and Switch's move-in branch both run
// (CreateSupplyPeriodEndpoint.cs:22-23, SwitchSupplyPeriodEndpoint.cs:50-51):
// true when a non-Cancelled period on this metering point overlaps
// [start, +infinity) — the new period is always open-ended at creation
// time, so this is SupplyPeriod.Overlaps(existing, new) simplified because
// new.End is always null (energy inventory §2.3). This includes a
// historical (Ended) period whose own end is still in the future relative
// to start: COALESCE("end", 'infinity') treats a null end as +infinity but
// does not otherwise care about status beyond "not Cancelled". The GiST
// exclusion constraint (§3.2) is what actually decides a race (§5); this
// query reduces to the exact predicate it encodes and is only ever the
// advisory layer in front of it.
func (q *Queries) SupplyPeriodOverlapExists(ctx context.Context, arg SupplyPeriodOverlapExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, supplyPeriodOverlapExists, arg.MeteringPointID, arg.Start)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
