// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLiveAttachmentUploads = `-- name: CountLiveAttachmentUploads :one
SELECT count(*)
FROM communications.attachment_uploads
WHERE conversation_id = $1 AND uploaded_by_user_id = $2
  AND scan_status NOT IN ('expired', 'quarantined')
`

type CountLiveAttachmentUploadsParams struct {
	ConversationID   uuid.UUID
	UploadedByUserID uuid.UUID
}

// CountLiveAttachmentUploads is the per-(conversation, user) cap check
// (`:128`): every upload except one already `expired` or `quarantined`
// counts against the limit of 20. Post-port every staged upload is born
// `clean` (design doc D2), so in practice this simply counts every upload
// for the pair — the exclusion stays because a hand-inserted fixture or a
// future scanner can still produce those two statuses.
func (q *Queries) CountLiveAttachmentUploads(ctx context.Context, arg CountLiveAttachmentUploadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveAttachmentUploads, arg.ConversationID, arg.UploadedByUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAttachmentUploadByUploaderAndKey = `-- name: FindAttachmentUploadByUploaderAndKey :one

SELECT id, conversation_id, uploaded_by_user_id, file_name, content_type, size_bytes,
       content_hash, content_id, storage_key, scan_status, is_inline, idempotency_key,
       expires_at, created_at
FROM communications.attachment_uploads
WHERE uploaded_by_user_id = $1 AND idempotency_key = $2
`

type FindAttachmentUploadByUploaderAndKeyParams struct {
	UploadedByUserID uuid.UUID
	IdempotencyKey   string
}

// Attachment staging and download: postCommunicationsConversationsByIdAttachments,
// getCommunicationsConversationsByConversationIdAttachmentsByAttachmentId,
// getCommunicationsAttachmentsByIdDownload (communications inventory §5,
// §12.3; EP/ConversationEndpoints.cs:103-236). Task 6's brief and dispatch
// are the authority for the behaviour these back.
// FindAttachmentUploadByUploaderAndKey is StageAttachment's replay lookup
// (`:112-113`), keyed by (UploadedByUserId, IdempotencyKey) — per-user,
// deliberately asymmetric with idempotency_records' global key (inventory
// §5.1, §8's closing note). Checked before the conversation is even known to
// exist: a replayed key returns the prior upload for a since-deleted
// conversation too.
func (q *Queries) FindAttachmentUploadByUploaderAndKey(ctx context.Context, arg FindAttachmentUploadByUploaderAndKeyParams) (CommunicationsAttachmentUpload, error) {
	row := q.db.QueryRow(ctx, findAttachmentUploadByUploaderAndKey, arg.UploadedByUserID, arg.IdempotencyKey)
	var i CommunicationsAttachmentUpload
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UploadedByUserID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ContentID,
		&i.StorageKey,
		&i.ScanStatus,
		&i.IsInline,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findLatestCleanupRecordByStorageKey = `-- name: FindLatestCleanupRecordByStorageKey :one
SELECT id, message_id, storage_key, status, attempts, next_attempt_at, lease_id,
       lease_until, reservation_expires_at, last_error, created_at
FROM communications.attachment_cleanup_records
WHERE storage_key = $1 AND status != 'completed'
ORDER BY created_at DESC
LIMIT 1
`

// FindLatestCleanupRecordByStorageKey is ObjectOwnershipLifecycle.ReserveAsync's
// own lookup (`:38-83`, inventory §12.3): the newest non-completed record for
// storage_key. No unique index on storage_key backs this — a completed
// historical row may legitimately coexist with a live reservation for a
// reused key (migration 00006's comment on attachment_cleanup_records).
func (q *Queries) FindLatestCleanupRecordByStorageKey(ctx context.Context, storageKey string) (CommunicationsAttachmentCleanupRecord, error) {
	row := q.db.QueryRow(ctx, findLatestCleanupRecordByStorageKey, storageKey)
	var i CommunicationsAttachmentCleanupRecord
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.StorageKey,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.ReservationExpiresAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentUploadForCaller = `-- name: GetAttachmentUploadForCaller :one
SELECT id, conversation_id, uploaded_by_user_id, file_name, content_type, size_bytes,
       content_hash, content_id, storage_key, scan_status, is_inline, idempotency_key,
       expires_at, created_at
FROM communications.attachment_uploads
WHERE id = $1 AND conversation_id = $2 AND uploaded_by_user_id = $3
  AND scan_status != 'expired'
`

type GetAttachmentUploadForCallerParams struct {
	ID               uuid.UUID
	ConversationID   uuid.UUID
	UploadedByUserID uuid.UUID
}

// GetAttachmentUploadForCaller is GetAttachmentUploadStatus's scoped lookup
// (`:205-207`): (attachmentId, conversationId, uploaderUserId, scanStatus !=
// 'expired') together, so a valid upload id cannot be used to probe another
// conversation or another uploader's row (inventory §5.2).
func (q *Queries) GetAttachmentUploadForCaller(ctx context.Context, arg GetAttachmentUploadForCallerParams) (CommunicationsAttachmentUpload, error) {
	row := q.db.QueryRow(ctx, getAttachmentUploadForCaller, arg.ID, arg.ConversationID, arg.UploadedByUserID)
	var i CommunicationsAttachmentUpload
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UploadedByUserID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ContentID,
		&i.StorageKey,
		&i.ScanStatus,
		&i.IsInline,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCleanMessageAttachmentByID = `-- name: GetCleanMessageAttachmentByID :one
SELECT id, message_id, file_name, content_type, size_bytes, storage_key
FROM communications.message_attachments
WHERE id = $1 AND scan_status = 'clean'
`

type GetCleanMessageAttachmentByIDRow struct {
	ID          uuid.UUID
	MessageID   uuid.UUID
	FileName    string
	ContentType string
	SizeBytes   int64
	StorageKey  string
}

// GetCleanMessageAttachmentByID is DownloadAttachment's lookup (`:215-216`):
// scan_status = 'clean' only, with no per-conversation scoping at all — any
// conversations-view holder may fetch any clean attachment by id (inventory
// §19.2 item 22, deliberately not "fixed"). message_attachments.message_id
// is NOT NULL and conversation_messages.conversation_id is NOT NULL with an
// ON DELETE CASCADE from conversations, so a row here already implies a live
// conversation — .NET's `Message.Conversation != null` guard has no
// reachable false case to reproduce.
func (q *Queries) GetCleanMessageAttachmentByID(ctx context.Context, id uuid.UUID) (GetCleanMessageAttachmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCleanMessageAttachmentByID, id)
	var i GetCleanMessageAttachmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
	)
	return i, err
}

const insertAttachmentUpload = `-- name: InsertAttachmentUpload :one
INSERT INTO communications.attachment_uploads
    (id, conversation_id, uploaded_by_user_id, file_name, content_type, size_bytes,
     content_hash, content_id, storage_key, scan_status, is_inline, idempotency_key,
     expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, 'clean', $10, $11,
        $12, $13)
RETURNING id, conversation_id, uploaded_by_user_id, file_name, content_type, size_bytes,
          content_hash, content_id, storage_key, scan_status, is_inline, idempotency_key,
          expires_at, created_at
`

type InsertAttachmentUploadParams struct {
	ID               uuid.UUID
	ConversationID   uuid.UUID
	UploadedByUserID uuid.UUID
	FileName         string
	ContentType      string
	SizeBytes        int64
	ContentHash      string
	ContentID        *string
	StorageKey       string
	IsInline         bool
	IdempotencyKey   string
	ExpiresAt        time.Time
	CreatedAt        time.Time
}

// InsertAttachmentUpload is StageAttachment's own row insert (`:158-175`).
// scan_status is passed explicitly as 'clean' (design doc D2) rather than
// relying on the column default, so the value is visible at the call site
// that is the actual reason for it, not implicit in the schema.
func (q *Queries) InsertAttachmentUpload(ctx context.Context, arg InsertAttachmentUploadParams) (CommunicationsAttachmentUpload, error) {
	row := q.db.QueryRow(ctx, insertAttachmentUpload,
		arg.ID,
		arg.ConversationID,
		arg.UploadedByUserID,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
		arg.ContentHash,
		arg.ContentID,
		arg.StorageKey,
		arg.IsInline,
		arg.IdempotencyKey,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i CommunicationsAttachmentUpload
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UploadedByUserID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ContentID,
		&i.StorageKey,
		&i.ScanStatus,
		&i.IsInline,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCleanupRecord = `-- name: InsertCleanupRecord :exec
INSERT INTO communications.attachment_cleanup_records
    (id, message_id, storage_key, status, attempts, next_attempt_at, reservation_expires_at, created_at)
VALUES ($1, NULL, $2, 'staged', 0, $3, $4, $5)
`

type InsertCleanupRecordParams struct {
	ID                   uuid.UUID
	StorageKey           string
	NextAttemptAt        time.Time
	ReservationExpiresAt *time.Time
	CreatedAt            time.Time
}

// InsertCleanupRecord is ReserveAsync's insert path (no existing record):
// status 'staged', a fresh 10-minute reservation_expires_at (inventory
// §12.3's ReservationLifetime). Written and committed *before* the
// object-store write it guards (inventory §5.4 step 8) — the caller runs
// this outside any transaction shared with the later attachment_uploads
// insert, so it is durable on its own.
func (q *Queries) InsertCleanupRecord(ctx context.Context, arg InsertCleanupRecordParams) error {
	_, err := q.db.Exec(ctx, insertCleanupRecord,
		arg.ID,
		arg.StorageKey,
		arg.NextAttemptAt,
		arg.ReservationExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const markCleanupRecordOwned = `-- name: MarkCleanupRecordOwned :exec
UPDATE communications.attachment_cleanup_records
SET status = 'owned', reservation_expires_at = NULL, lease_id = NULL, lease_until = NULL, last_error = NULL
WHERE storage_key = $1
`

// MarkCleanupRecordOwned is ObjectOwnershipLifecycle.MarkOwnedAsync
// (`:86-123`), called inside the same transaction and commit as the
// attachment_uploads insert (inventory §5.4 step 11): the reservation
// transitions to 'owned', its expiry clears, and any lease/error is
// discarded.
func (q *Queries) MarkCleanupRecordOwned(ctx context.Context, storageKey string) error {
	_, err := q.db.Exec(ctx, markCleanupRecordOwned, storageKey)
	return err
}

const resetCleanupRecordToStaged = `-- name: ResetCleanupRecordToStaged :exec
UPDATE communications.attachment_cleanup_records
SET status = 'staged', next_attempt_at = $1, reservation_expires_at = $2,
    last_error = NULL
WHERE id = $3
`

type ResetCleanupRecordToStagedParams struct {
	NextAttemptAt        time.Time
	ReservationExpiresAt *time.Time
	ID                   uuid.UUID
}

// ResetCleanupRecordToStaged is ReserveAsync's reuse path: an existing
// non-completed, non-owned, non-deleting record for the same key (a
// crash-retry that reserved and committed but never reached PutAsync) is
// reset to 'staged' with a fresh reservation window, the same row rather
// than a second one.
func (q *Queries) ResetCleanupRecordToStaged(ctx context.Context, arg ResetCleanupRecordToStagedParams) error {
	_, err := q.db.Exec(ctx, resetCleanupRecordToStaged, arg.NextAttemptAt, arg.ReservationExpiresAt, arg.ID)
	return err
}
