// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteConversationMessagesByIDs = `-- name: DeleteConversationMessagesByIDs :execrows
DELETE FROM communications.conversation_messages WHERE id = ANY($1::uuid[])
`

// Step 6's last delete (`:106`) and the batch's return value: post-port the
// deleted-message count IS the whole return value, since the two inbound
// tables that also contributed to it are gone. The drain loop keys off it.
func (q *Queries) DeleteConversationMessagesByIDs(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversationMessagesByIDs, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyRecordsByMessageIDs = `-- name: DeleteIdempotencyRecordsByMessageIDs :exec
DELETE FROM communications.idempotency_records WHERE message_id = ANY($1::uuid[])
`

// Step 6 (`:104`), and mandatory rather than incidental:
// idempotency_records.message_id has NO foreign key at all, only an index
// (migration 00006, inventory §12.1), so nothing cascades these rows. Drop
// this statement and every deleted message leaks one idempotency record
// forever.
func (q *Queries) DeleteIdempotencyRecordsByMessageIDs(ctx context.Context, messageIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyRecordsByMessageIDs, messageIds)
	return err
}

const deleteMessageAttachmentsByMessageIDs = `-- name: DeleteMessageAttachmentsByMessageIDs :exec
DELETE FROM communications.message_attachments WHERE message_id = ANY($1::uuid[])
`

// Step 6 (`:103`), after every reservation for those attachments is written.
func (q *Queries) DeleteMessageAttachmentsByMessageIDs(ctx context.Context, messageIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageAttachmentsByMessageIDs, messageIds)
	return err
}

const deleteMessageDeliveriesByMessageIDs = `-- name: DeleteMessageDeliveriesByMessageIDs :exec
DELETE FROM communications.message_deliveries WHERE message_id = ANY($1::uuid[])
`

// Step 2 (`:86`). See the ordering note above.
func (q *Queries) DeleteMessageDeliveriesByMessageIDs(ctx context.Context, messageIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageDeliveriesByMessageIDs, messageIds)
	return err
}

const deleteMessageEventsByMessageIDs = `-- name: DeleteMessageEventsByMessageIDs :exec
DELETE FROM communications.message_events WHERE message_id = ANY($1::uuid[])
`

// Step 1 (`:85`), and it MUST run before DeleteMessageDeliveriesByMessageIDs.
// message_events.delivery_id -> message_deliveries.id is ON DELETE RESTRICT
// (migration 00006, inventory §10 item 8, §19.1 item 6) — the only Restrict FK
// between two tables retention deletes together, every other FK in the schema
// being Cascade or SetNull. Deleting the deliveries first raises SQLSTATE
// 23001, and since the whole batch is one transaction the batch rolls back:
// retention would never drain and never recover on its own. Pinned by
// TestRetention_DeletesEventsBeforeDeliveries.
func (q *Queries) DeleteMessageEventsByMessageIDs(ctx context.Context, messageIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageEventsByMessageIDs, messageIds)
	return err
}

const deleteOrphanConversationParticipants = `-- name: DeleteOrphanConversationParticipants :exec
DELETE FROM communications.conversation_participants cp
WHERE NOT EXISTS (
    SELECT 1 FROM communications.conversation_messages m WHERE m.conversation_id = cp.conversation_id
)
`

// Step 7 (`:111`): a conversation left with no messages loses its participant
// links. Deliberately unconditional — .NET runs it on every batch, not only
// when the batch deleted something.
func (q *Queries) DeleteOrphanConversationParticipants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOrphanConversationParticipants)
	return err
}

const deleteOrphanParticipants = `-- name: DeleteOrphanParticipants :exec
DELETE FROM communications.participants p
WHERE NOT EXISTS (
    SELECT 1 FROM communications.conversation_participants cp WHERE cp.participant_id = p.id
)
`

// Step 7 (`:112`): a participant left with no remaining link goes too.
func (q *Queries) DeleteOrphanParticipants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOrphanParticipants)
	return err
}

const deleteOutboxJobsByMessageIDs = `-- name: DeleteOutboxJobsByMessageIDs :exec
DELETE FROM communications.outbox_jobs WHERE message_id = ANY($1::uuid[])
`

// Step 6 (`:105`). outbox_jobs.message_id IS a Cascade FK, so this is
// redundant against the message delete that follows — .NET issues it anyway
// and so do we, because the batch's own ordering should not depend on a
// cascade to be correct.
func (q *Queries) DeleteOutboxJobsByMessageIDs(ctx context.Context, messageIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutboxJobsByMessageIDs, messageIds)
	return err
}

const expireAttachmentUpload = `-- name: ExpireAttachmentUpload :execrows
UPDATE communications.attachment_uploads
SET scan_status = 'expired'
WHERE id = $1 AND expires_at < $2 AND scan_status NOT IN ('quarantined', 'expired', 'claimed')
`

type ExpireAttachmentUploadParams struct {
	ID  uuid.UUID
	Now time.Time
}

// The sweep's conditional claim (`:268-274`): the same predicate as the select
// above, re-asserted as an UPDATE. .NET's comment says why it must be
// conditional — "A concurrent reply can win with the clean -> claimed
// transition, in which case this worker must not enqueue that object's
// deletion" — so the caller queues the object only when this reports one row.
// scan_lease_id / scan_lease_until are not cleared here because the port drops
// both columns.
func (q *Queries) ExpireAttachmentUpload(ctx context.Context, arg ExpireAttachmentUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireAttachmentUpload, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRetentionAttachments = `-- name: ListRetentionAttachments :many
SELECT id, message_id, storage_key
FROM communications.message_attachments
WHERE message_id = ANY($1::uuid[])
ORDER BY created_at ASC, id ASC
`

type ListRetentionAttachmentsRow struct {
	ID         uuid.UUID
	MessageID  uuid.UUID
	StorageKey string
}

// Step 3's attachment read (`:87`): every attachment object in the batch,
// with the message that owns it, so its key can be queued for deletion before
// the rows identifying the owner are gone.
func (q *Queries) ListRetentionAttachments(ctx context.Context, messageIds []uuid.UUID) ([]ListRetentionAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listRetentionAttachments, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRetentionAttachmentsRow
	for rows.Next() {
		var i ListRetentionAttachmentsRow
		if err := rows.Scan(&i.ID, &i.MessageID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetentionRawPayloadKeys = `-- name: ListRetentionRawPayloadKeys :many
SELECT id, raw_payload_storage_key
FROM communications.conversation_messages
WHERE id = ANY($1::uuid[]) AND raw_payload_storage_key IS NOT NULL
ORDER BY created_at ASC, id ASC
`

type ListRetentionRawPayloadKeysRow struct {
	ID                   uuid.UUID
	RawPayloadStorageKey *string
}

// Step 3's raw-payload read (`:88-91`): the non-null
// conversation_messages.raw_payload_storage_key values in the batch. Nothing
// in this port writes that column — its only .NET writer was the inbound
// processor (migration 00006's comment) — so this returns nothing in
// production today and is kept because the column is, for the day an inbound
// provider lands.
func (q *Queries) ListRetentionRawPayloadKeys(ctx context.Context, messageIds []uuid.UUID) ([]ListRetentionRawPayloadKeysRow, error) {
	rows, err := q.db.Query(ctx, listRetentionRawPayloadKeys, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRetentionRawPayloadKeysRow
	for rows.Next() {
		var i ListRetentionRawPayloadKeysRow
		if err := rows.Scan(&i.ID, &i.RawPayloadStorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectExpiredAttachmentUploads = `-- name: SelectExpiredAttachmentUploads :many
SELECT id, storage_key
FROM communications.attachment_uploads
WHERE expires_at < $1 AND scan_status NOT IN ('quarantined', 'expired', 'claimed')
ORDER BY expires_at ASC, id ASC
LIMIT $2
`

type SelectExpiredAttachmentUploadsParams struct {
	Now       time.Time
	BatchSize int32
}

type SelectExpiredAttachmentUploadsRow struct {
	ID         uuid.UUID
	StorageKey string
}

// The staged-upload expiry sweep re-homed from the deleted scanner
// (ExpireUploadsAsync, SV/AttachmentScanning.cs:251-280; design doc D3,
// inventory §5.8 and §19.1 item 2). Without it nothing expires a staged upload
// or queues its object, and staged objects leak despite expires_at being set.
//
// .NET's predicate also carried `(scan_status != 'scanning' OR
// scan_lease_until <= now)`; that disjunct dies with the five scan columns the
// port drops (migration 00006) — no row can be 'scanning' when nothing writes
// it. 'quarantined', 'expired' and 'claimed' are excluded exactly as .NET
// excludes them: 'claimed' in particular is a reply holding the upload inside
// its own transaction, and expiring it would queue a live message's object for
// deletion.
func (q *Queries) SelectExpiredAttachmentUploads(ctx context.Context, arg SelectExpiredAttachmentUploadsParams) ([]SelectExpiredAttachmentUploadsRow, error) {
	rows, err := q.db.Query(ctx, selectExpiredAttachmentUploads, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectExpiredAttachmentUploadsRow
	for rows.Next() {
		var i SelectExpiredAttachmentUploadsRow
		if err := rows.Scan(&i.ID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectRetentionMessageIDs = `-- name: SelectRetentionMessageIDs :many

SELECT m.id
FROM communications.conversation_messages m
WHERE m.created_at < $1
  AND NOT EXISTS (
      SELECT 1 FROM communications.outbox_jobs j
      WHERE j.message_id = m.id
        AND j.status NOT IN ('completed', 'cancelled', 'failed')
  )
ORDER BY m.created_at ASC, m.id ASC
LIMIT $2
`

type SelectRetentionMessageIDsParams struct {
	Cutoff    time.Time
	BatchSize int32
}

// Task 12 (the retention worker, SV/CommunicationsRetentionWorker.cs:9-44 +
// SV/RetentionCleanupService.cs:15-116; communications inventory §12.1, design
// doc §4 and D3). Every query here belongs to retention.go.
//
// THE ORDER OF THE TWO DELETES BELOW IS LOAD-BEARING. See
// DeleteMessageEventsByMessageIDs.
// Candidate set 1 (`:53-61`), the only one that survives the scope cut: .NET's
// sets 2 and 3 select inbound_email_jobs and orphan inbound_receipts, and both
// tables are dropped with the inbound subsystem (inventory §9, §12.1).
//
// "Terminal" for a message means it has no outbox job at all, or every job it
// has is completed/cancelled/failed. .NET writes that as
// `!Any(job) || All(job => terminal)`; the NOT EXISTS below is the same
// predicate stated once — a message is a candidate exactly when no
// non-terminal job references it. Queued and retryable work is deliberately
// excluded so retention cannot interrupt delivery
// (SV/RetentionCleanupService.cs:11-14, pinned by
// TS/Integration/RetentionCleanupTests.cs:11-17): a message with a pending,
// retry or processing job is never deleted, however old it is.
//
// The id tiebreaker is this port's own addition to .NET's bare
// `OrderBy(CreatedAt)`: it cannot change which rows are eligible, only make
// the batch boundary deterministic when several messages share a timestamp.
func (q *Queries) SelectRetentionMessageIDs(ctx context.Context, arg SelectRetentionMessageIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, selectRetentionMessageIDs, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
