// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acquireRoleMutationLock = `-- name: AcquireRoleMutationLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// AcquireRoleMutationLock takes one role's transaction advisory lock
// (AZ/AuthorizationMutationService.cs:20-25); the key is
// roleMutationLockKey's.
func (q *Queries) AcquireRoleMutationLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, acquireRoleMutationLock, lockKey)
	return err
}

const assignUserRoleLocks = `-- name: AssignUserRoleLocks :many
SELECT id, is_system, is_built_in
FROM identity.roles
WHERE id = ANY($1::uuid[])
FOR KEY SHARE
`

type AssignUserRoleLocksRow struct {
	ID        uuid.UUID
	IsSystem  bool
	IsBuiltIn bool
}

// AssignUserRoleLocks reads the roles an assignment names and holds a key
// share on each until the transaction ends: a role deleted first is missing
// here, and one read here cannot be deleted before the assignment commits.
func (q *Queries) AssignUserRoleLocks(ctx context.Context, ids []uuid.UUID) ([]AssignUserRoleLocksRow, error) {
	rows, err := q.db.Query(ctx, assignUserRoleLocks, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssignUserRoleLocksRow
	for rows.Next() {
		var i AssignUserRoleLocksRow
		if err := rows.Scan(&i.ID, &i.IsSystem, &i.IsBuiltIn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM identity.roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM identity.role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRolePermissionKeys = `-- name: GetRolePermissionKeys :many
SELECT permission_key
FROM identity.role_permissions
WHERE role_id = $1
ORDER BY permission_key COLLATE "C"
`

func (q *Queries) GetRolePermissionKeys(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolePermissionKeys, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRole = `-- name: InsertRole :exec
INSERT INTO identity.roles (
    id, name, normalized_name, display_name, description, is_system, is_built_in,
    steward_user_id, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, false, false,
    $6, $7, $8::timestamptz, $8::timestamptz
)
`

type InsertRoleParams struct {
	ID             uuid.UUID
	Name           string
	NormalizedName string
	DisplayName    string
	Description    string
	StewardUserID  *uuid.UUID
	Version        uuid.UUID
	Now            time.Time
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) error {
	_, err := q.db.Exec(ctx, insertRole,
		arg.ID,
		arg.Name,
		arg.NormalizedName,
		arg.DisplayName,
		arg.Description,
		arg.StewardUserID,
		arg.Version,
		arg.Now,
	)
	return err
}

const insertRolePermissions = `-- name: InsertRolePermissions :exec
INSERT INTO identity.role_permissions (role_id, permission_key)
SELECT $1, k FROM unnest($2::text[]) AS k
ON CONFLICT DO NOTHING
`

type InsertRolePermissionsParams struct {
	RoleID uuid.UUID
	Keys   []string
}

// InsertRolePermissions gives the role each key once.
func (q *Queries) InsertRolePermissions(ctx context.Context, arg InsertRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, insertRolePermissions, arg.RoleID, arg.Keys)
	return err
}

const listAccessUsers = `-- name: ListAccessUsers :many
SELECT id, display_name, email, is_disabled, lockout_end, version
FROM identity.users
ORDER BY display_name COLLATE "C", id
`

type ListAccessUsersRow struct {
	ID          uuid.UUID
	DisplayName string
	Email       string
	IsDisabled  bool
	LockoutEnd  *time.Time
	Version     uuid.UUID
}

// ListAccessUsers is the authorization user directory
// (EA/AuthorizationManagementEndpoints.cs:475-487): every user, by display
// name (ordinal), then id.
func (q *Queries) ListAccessUsers(ctx context.Context) ([]ListAccessUsersRow, error) {
	rows, err := q.db.Query(ctx, listAccessUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessUsersRow
	for rows.Next() {
		var i ListAccessUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Email,
			&i.IsDisabled,
			&i.LockoutEnd,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUserRoleAssignments = `-- name: ListAllUserRoleAssignments :many
SELECT ur.user_id, r.id AS role_id, r.name
FROM identity.user_roles ur
JOIN identity.roles r ON r.id = ur.role_id
ORDER BY ur.user_id, r.name COLLATE "C", r.id
`

type ListAllUserRoleAssignmentsRow struct {
	UserID uuid.UUID
	RoleID uuid.UUID
	Name   string
}

// ListAllUserRoleAssignments is every direct role assignment, each user's
// by role name (ordinal).
func (q *Queries) ListAllUserRoleAssignments(ctx context.Context) ([]ListAllUserRoleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAllUserRoleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUserRoleAssignmentsRow
	for rows.Next() {
		var i ListAllUserRoleAssignmentsRow
		if err := rows.Scan(&i.UserID, &i.RoleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_user_id, target_user_id, target_role_id, action, details,
       coalesce(before_json, '') AS before_json, coalesce(after_json, '') AS after_json,
       coalesce(correlation_id, '') AS correlation_id, mfa_authenticated, occurred_at
FROM identity.authorization_audit_events
ORDER BY occurred_at DESC, id DESC
LIMIT 500
`

type ListAuditEventsRow struct {
	ID               int64
	ActorUserID      *uuid.UUID
	TargetUserID     *uuid.UUID
	TargetRoleID     *uuid.UUID
	Action           string
	Details          string
	BeforeJson       string
	AfterJson        string
	CorrelationID    string
	MfaAuthenticated bool
	OccurredAt       time.Time
}

// ListAuditEvents is GET /access/audit (EA/AuthorizationManagementEndpoints.cs:552-554):
// the latest 500 rows, newest first; id breaks ties between rows written at
// the same instant, the later write first.
func (q *Queries) ListAuditEvents(ctx context.Context) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.TargetUserID,
			&i.TargetRoleID,
			&i.Action,
			&i.Details,
			&i.BeforeJson,
			&i.AfterJson,
			&i.CorrelationID,
			&i.MfaAuthenticated,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManageableRoles = `-- name: ListManageableRoles :many
SELECT r.id, r.name, r.normalized_name, r.display_name, r.description, r.is_system, r.is_built_in,
       r.steward_user_id, r.version,
       coalesce((
           SELECT array_agg(rp.permission_key ORDER BY rp.permission_key COLLATE "C")
           FROM identity.role_permissions rp
           WHERE rp.role_id = r.id
       ), '{}')::text[] AS permissions
FROM identity.roles r
WHERE r.name <> 'SystemAdmin'
ORDER BY r.name COLLATE "C", r.id
`

type ListManageableRolesRow struct {
	ID             uuid.UUID
	Name           string
	NormalizedName string
	DisplayName    string
	Description    string
	IsSystem       bool
	IsBuiltIn      bool
	StewardUserID  *uuid.UUID
	Version        uuid.UUID
	Permissions    []string
}

// ListManageableRoles is GET /access/roles (EA/AuthorizationManagementEndpoints.cs:61-104):
// every role but SystemAdmin, by name (ordinal), with its permission keys
// in ordinal order.
func (q *Queries) ListManageableRoles(ctx context.Context) ([]ListManageableRolesRow, error) {
	rows, err := q.db.Query(ctx, listManageableRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManageableRolesRow
	for rows.Next() {
		var i ListManageableRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.DisplayName,
			&i.Description,
			&i.IsSystem,
			&i.IsBuiltIn,
			&i.StewardUserID,
			&i.Version,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDirectPermissionKeys = `-- name: ListUserDirectPermissionKeys :many
SELECT k.permission_key
FROM (
    SELECT DISTINCT rp.permission_key
    FROM identity.user_roles ur
    JOIN identity.role_permissions rp ON rp.role_id = ur.role_id
    WHERE ur.user_id = $1
) k
ORDER BY k.permission_key COLLATE "C"
`

// ListUserDirectPermissionKeys is the distinct permission keys of a user's
// direct roles only, in ordinal order: /access/me's projection
// (EA/AuthorizationManagementEndpoints.cs:529-543), which leaves out the
// roles access groups grant.
func (q *Queries) ListUserDirectPermissionKeys(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserDirectPermissionKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleAssignments = `-- name: ListUserRoleAssignments :many
SELECT r.id, r.name, r.is_system, r.is_built_in
FROM identity.user_roles ur
JOIN identity.roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name COLLATE "C", r.id
`

type ListUserRoleAssignmentsRow struct {
	ID        uuid.UUID
	Name      string
	IsSystem  bool
	IsBuiltIn bool
}

// ListUserRoleAssignments is a user's direct roles, by name (ordinal).
func (q *Queries) ListUserRoleAssignments(ctx context.Context, userID uuid.UUID) ([]ListUserRoleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listUserRoleAssignments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoleAssignmentsRow
	for rows.Next() {
		var i ListUserRoleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsSystem,
			&i.IsBuiltIn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRole = `-- name: LockRole :one
SELECT id, name, normalized_name, display_name, description, is_system, is_built_in,
       steward_user_id, version, created_at, updated_at
FROM identity.roles
WHERE id = $1
FOR UPDATE
`

// LockRole reads a role and holds its row until the transaction ends, so
// no assignment can take it (AssignUserRoleLocks) while it is deleted.
func (q *Queries) LockRole(ctx context.Context, id uuid.UUID) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, lockRole, id)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.DisplayName,
		&i.Description,
		&i.IsSystem,
		&i.IsBuiltIn,
		&i.StewardUserID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUserVersion = `-- name: LockUserVersion :one
SELECT version FROM identity.users WHERE id = $1 FOR UPDATE
`

// LockUserVersion reads a user's version and holds the users row until the
// transaction ends, so concurrent role replacements for one user take
// turns and each compares the version the one before it left.
func (q *Queries) LockUserVersion(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockUserVersion, id)
	var version uuid.UUID
	err := row.Scan(&version)
	return version, err
}

const roleIsAssigned = `-- name: RoleIsAssigned :one
SELECT EXISTS (
    SELECT 1 FROM identity.user_roles WHERE role_id = $1
) AS assigned
`

// RoleIsAssigned reports whether any user holds the role directly.
func (q *Queries) RoleIsAssigned(ctx context.Context, roleID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, roleIsAssigned, roleID)
	var assigned bool
	err := row.Scan(&assigned)
	return assigned, err
}

const roleIsMapped = `-- name: RoleIsMapped :one
SELECT EXISTS (
    SELECT 1 FROM identity.access_group_role_mappings WHERE role_id = $1
) AS mapped
`

// RoleIsMapped reports whether any access group maps the role.
func (q *Queries) RoleIsMapped(ctx context.Context, roleID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, roleIsMapped, roleID)
	var mapped bool
	err := row.Scan(&mapped)
	return mapped, err
}

const roleNameTaken = `-- name: RoleNameTaken :one
SELECT EXISTS (
    SELECT 1 FROM identity.roles
    WHERE normalized_name = $1 AND id <> $2
) AS taken
`

type RoleNameTakenParams struct {
	NormalizedName string
	ID             uuid.UUID
}

// RoleNameTaken reports whether a role other than @id has the normalized
// name; a create passes the nil uuid.
func (q *Queries) RoleNameTaken(ctx context.Context, arg RoleNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, roleNameTaken, arg.NormalizedName, arg.ID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE identity.roles
SET name = $1, normalized_name = $2, display_name = $3,
    description = $4, version = $5, updated_at = $6::timestamptz
WHERE id = $7 AND version = $8
`

type UpdateRoleParams struct {
	Name            string
	NormalizedName  string
	DisplayName     string
	Description     string
	Version         uuid.UUID
	Now             time.Time
	ID              uuid.UUID
	ExpectedVersion uuid.UUID
}

// UpdateRole writes a role's metadata and its new version, only while it
// still has the version the caller read: zero rows is a concurrent change.
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRole,
		arg.Name,
		arg.NormalizedName,
		arg.DisplayName,
		arg.Description,
		arg.Version,
		arg.Now,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
