// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteProfileAvatar = `-- name: DeleteProfileAvatar :exec
DELETE FROM identity.profile_avatars WHERE user_id = $1
`

func (q *Queries) DeleteProfileAvatar(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileAvatar, userID)
	return err
}

const deleteUserPasswordResetTokens = `-- name: DeleteUserPasswordResetTokens :exec
DELETE FROM identity.password_reset_tokens WHERE user_id = $1
`

// DeleteUserPasswordResetTokens keeps a changed password from being
// undone by a reset token minted before it (spec *Credentials*).
func (q *Queries) DeleteUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPasswordResetTokens, userID)
	return err
}

const getProfileAvatar = `-- name: GetProfileAvatar :one
SELECT data, content_type FROM identity.profile_avatars WHERE user_id = $1
`

type GetProfileAvatarRow struct {
	Data        []byte
	ContentType string
}

func (q *Queries) GetProfileAvatar(ctx context.Context, userID uuid.UUID) (GetProfileAvatarRow, error) {
	row := q.db.QueryRow(ctx, getProfileAvatar, userID)
	var i GetProfileAvatarRow
	err := row.Scan(&i.Data, &i.ContentType)
	return i, err
}

const hasProfileAvatar = `-- name: HasProfileAvatar :one
SELECT (EXISTS (SELECT 1 FROM identity.profile_avatars WHERE user_id = $1))::boolean
`

func (q *Queries) HasProfileAvatar(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasProfileAvatar, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :execrows
UPDATE identity.users
SET password_hash = $1, version = $2, updated_at = $3::timestamptz
WHERE id = $4
`

type UpdateAccountPasswordParams struct {
	PasswordHash *string
	Version      uuid.UUID
	Now          time.Time
	ID           uuid.UUID
}

// UpdateAccountPassword stores the new hash and bumps version, the
// concurrency-stamp analogue (EA/AccountSettingsEndpoints.cs:157). It
// affects no row when the user has been deleted.
func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountPassword,
		arg.PasswordHash,
		arg.Version,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE identity.users
SET display_name = $1, preferred_language = $2, updated_at = $3::timestamptz
WHERE id = $4
RETURNING id, display_name, email, preferred_language
`

type UpdateAccountProfileParams struct {
	DisplayName       string
	PreferredLanguage *string
	Now               time.Time
	ID                uuid.UUID
}

type UpdateAccountProfileRow struct {
	ID                uuid.UUID
	DisplayName       string
	Email             string
	PreferredLanguage *string
}

// UpdateAccountProfile is the self-service profile edit
// (EA/AccountSettingsEndpoints.cs:93-131): display name and preferred
// language only. Unlike .NET's UpdateSecurityStampAsync, it deliberately
// does not touch version or any session (spec *Sessions*, a divergence).
func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (UpdateAccountProfileRow, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile,
		arg.DisplayName,
		arg.PreferredLanguage,
		arg.Now,
		arg.ID,
	)
	var i UpdateAccountProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.PreferredLanguage,
	)
	return i, err
}

const upsertProfileAvatar = `-- name: UpsertProfileAvatar :exec
INSERT INTO identity.profile_avatars (user_id, data, content_type, version, updated_at)
VALUES ($1, $2, $3, 1, $4::timestamptz)
ON CONFLICT (user_id) DO UPDATE
SET data = excluded.data,
    content_type = excluded.content_type,
    version = identity.profile_avatars.version + 1,
    updated_at = excluded.updated_at
`

type UpsertProfileAvatarParams struct {
	UserID      uuid.UUID
	Data        []byte
	ContentType string
	Now         time.Time
}

// UpsertProfileAvatar stores an upload, starting version at 1 or
// incrementing it on a replace (EA/AccountSettingsEndpoints.cs:218-236).
func (q *Queries) UpsertProfileAvatar(ctx context.Context, arg UpsertProfileAvatarParams) error {
	_, err := q.db.Exec(ctx, upsertProfileAvatar,
		arg.UserID,
		arg.Data,
		arg.ContentType,
		arg.Now,
	)
	return err
}
