// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPendingOwnerInvitationsForEmail = `-- name: CountPendingOwnerInvitationsForEmail :one
SELECT count(*)::int
FROM identity.invitations
WHERE role = 'Owner' AND normalized_email = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > $2::timestamptz
`

type CountPendingOwnerInvitationsForEmailParams struct {
	NormalizedEmail string
	Now             time.Time
}

// CountPendingOwnerInvitationsForEmail is how many Owner invitations to
// @normalized_email can still be accepted at @now. BOOTSTRAP_OWNER_EMAIL's
// startup step issues one to the configured address only when this is 0, and
// the management status reports "invited" only when it is above 0 for that
// same configured address.
func (q *Queries) CountPendingOwnerInvitationsForEmail(ctx context.Context, arg CountPendingOwnerInvitationsForEmailParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingOwnerInvitationsForEmail, arg.NormalizedEmail, arg.Now)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getActiveInvitationByTokenHash = `-- name: GetActiveInvitationByTokenHash :one
SELECT id, email, normalized_email, role, display_name, token_hash, invited_by_user_id, created_at, expires_at, revoked_at, accepted_at FROM identity.invitations
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND accepted_at IS NULL
  AND expires_at > $2::timestamptz
`

type GetActiveInvitationByTokenHashParams struct {
	TokenHash []byte
	Now       time.Time
}

// GetActiveInvitationByTokenHash finds the invitation a token names while
// it can still be accepted: neither revoked nor accepted, and not expired at
// now (EA/AuthAccountEndpoints.cs:1469-1478).
func (q *Queries) GetActiveInvitationByTokenHash(ctx context.Context, arg GetActiveInvitationByTokenHashParams) (IdentityInvitation, error) {
	row := q.db.QueryRow(ctx, getActiveInvitationByTokenHash, arg.TokenHash, arg.Now)
	var i IdentityInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.Role,
		&i.DisplayName,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, email, normalized_email, role, display_name, token_hash, invited_by_user_id, created_at, expires_at, revoked_at, accepted_at FROM identity.invitations WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (IdentityInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i IdentityInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.Role,
		&i.DisplayName,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const insertInvitation = `-- name: InsertInvitation :one
INSERT INTO identity.invitations (
    id, email, normalized_email, role, display_name, token_hash, invited_by_user_id, created_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8::timestamptz, $9::timestamptz
)
RETURNING id, email, normalized_email, role, display_name, token_hash, invited_by_user_id, created_at, expires_at, revoked_at, accepted_at
`

type InsertInvitationParams struct {
	ID              uuid.UUID
	Email           string
	NormalizedEmail string
	Role            string
	DisplayName     *string
	TokenHash       []byte
	InvitedByUserID *uuid.UUID
	CreatedAt       time.Time
	ExpiresAt       time.Time
}

func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) (IdentityInvitation, error) {
	row := q.db.QueryRow(ctx, insertInvitation,
		arg.ID,
		arg.Email,
		arg.NormalizedEmail,
		arg.Role,
		arg.DisplayName,
		arg.TokenHash,
		arg.InvitedByUserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i IdentityInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.Role,
		&i.DisplayName,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, email, normalized_email, role, display_name, token_hash, invited_by_user_id, created_at, expires_at, revoked_at, accepted_at FROM identity.invitations
ORDER BY created_at DESC, id
`

// ListInvitations is every invitation, newest first
// (EA/AuthAccountEndpoints.cs:1148-1174).
func (q *Queries) ListInvitations(ctx context.Context) ([]IdentityInvitation, error) {
	rows, err := q.db.Query(ctx, listInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityInvitation
	for rows.Next() {
		var i IdentityInvitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.NormalizedEmail,
			&i.Role,
			&i.DisplayName,
			&i.TokenHash,
			&i.InvitedByUserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvitationByTokenHash = `-- name: LockInvitationByTokenHash :one
SELECT id, email, normalized_email, role, display_name, token_hash, invited_by_user_id, created_at, expires_at, revoked_at, accepted_at FROM identity.invitations WHERE token_hash = $1 FOR UPDATE
`

// LockInvitationByTokenHash is acceptance's SELECT … FOR UPDATE
// (EA/AuthAccountEndpoints.cs:1299-1302): a concurrent acceptance of the
// same token waits here, then fails to serialize.
func (q *Queries) LockInvitationByTokenHash(ctx context.Context, tokenHash []byte) (IdentityInvitation, error) {
	row := q.db.QueryRow(ctx, lockInvitationByTokenHash, tokenHash)
	var i IdentityInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.Role,
		&i.DisplayName,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE identity.invitations SET accepted_at = $1::timestamptz WHERE id = $2
`

type MarkInvitationAcceptedParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, arg.Now, arg.ID)
	return err
}

const revokeActiveInvitationsForEmail = `-- name: RevokeActiveInvitationsForEmail :exec
UPDATE identity.invitations
SET revoked_at = $1::timestamptz
WHERE normalized_email = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeActiveInvitationsForEmailParams struct {
	Now             time.Time
	NormalizedEmail string
}

// RevokeActiveInvitationsForEmail ends every pending invitation for one
// normalized email (EA/AuthAccountEndpoints.cs:673-681), so at most one is
// ever active (ux_invitations_active_email).
func (q *Queries) RevokeActiveInvitationsForEmail(ctx context.Context, arg RevokeActiveInvitationsForEmailParams) error {
	_, err := q.db.Exec(ctx, revokeActiveInvitationsForEmail, arg.Now, arg.NormalizedEmail)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE identity.invitations
SET revoked_at = CASE WHEN accepted_at IS NULL AND revoked_at IS NULL THEN $1::timestamptz ELSE revoked_at END
WHERE id = $2
RETURNING id, email, normalized_email, role, display_name, token_hash, invited_by_user_id, created_at, expires_at, revoked_at, accepted_at
`

type RevokeInvitationParams struct {
	Now time.Time
	ID  uuid.UUID
}

// RevokeInvitation revokes a pending invitation and leaves an accepted or
// already revoked one as it is (EA/AuthAccountEndpoints.cs:1176-1201).
func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (IdentityInvitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.Now, arg.ID)
	var i IdentityInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.NormalizedEmail,
		&i.Role,
		&i.DisplayName,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const revokePendingOwnerInvitationsExceptEmail = `-- name: RevokePendingOwnerInvitationsExceptEmail :execrows
UPDATE identity.invitations
SET revoked_at = $1::timestamptz
WHERE role = 'Owner' AND normalized_email != $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokePendingOwnerInvitationsExceptEmailParams struct {
	Now             time.Time
	NormalizedEmail string
}

// RevokePendingOwnerInvitationsExceptEmail revokes every pending Owner
// invitation not addressed to @normalized_email, expired ones included.
// BOOTSTRAP_OWNER_EMAIL's startup step calls this before deciding whether to
// issue: a corrected value then retires the token a previous, mistyped one
// mailed out, instead of leaving it live for up to INVITATION_LIFETIME.
func (q *Queries) RevokePendingOwnerInvitationsExceptEmail(ctx context.Context, arg RevokePendingOwnerInvitationsExceptEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePendingOwnerInvitationsExceptEmail, arg.Now, arg.NormalizedEmail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
