// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :execrows
DELETE FROM identity.password_reset_tokens
WHERE token_hash = $1 AND user_id = $2 AND expires_at > $3::timestamptz
`

type ConsumePasswordResetTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	Now       time.Time
}

// ConsumePasswordResetToken spends the token once: of two resets racing
// with it, only one deletes the row.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, arg ConsumePasswordResetTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumePasswordResetToken, arg.TokenHash, arg.UserID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM identity.password_reset_tokens
WHERE expires_at <= $1::timestamptz
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context, now time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens, now)
	return err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :exec
INSERT INTO identity.password_reset_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3::timestamptz)
`

type InsertPasswordResetTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const passwordResetTokenValid = `-- name: PasswordResetTokenValid :one
SELECT (EXISTS (
    SELECT 1 FROM identity.password_reset_tokens
    WHERE token_hash = $1 AND user_id = $2 AND expires_at > $3::timestamptz
))::boolean AS valid
`

type PasswordResetTokenValidParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	Now       time.Time
}

// PasswordResetTokenValid reports whether the token is the user's and still
// unexpired at now, without consuming it.
func (q *Queries) PasswordResetTokenValid(ctx context.Context, arg PasswordResetTokenValidParams) (bool, error) {
	row := q.db.QueryRow(ctx, passwordResetTokenValid, arg.TokenHash, arg.UserID, arg.Now)
	var valid bool
	err := row.Scan(&valid)
	return valid, err
}
