import type { CatalogResources } from "@vantigo/frontend-shell";

const en = {
  communications: "Communications",
  status: "Status",
  created: "Created",
  cancel: "Cancel",
  displayName: "Display name",
  provider: "Provider",
  default: "Default",
  active: "Active",
  inactive: "Inactive",
  smtp: "SMTP",
  mailgun: "Mailgun",
  smtpHost: "SMTP host",
  smtpPort: "SMTP port",
  username: "Username",
  password: "Password",
  mailgunDomain: "Mailgun domain",
  region: "Region",
  us: "US",
  eu: "EU",
  apiKey: "API key",
  inboundSigningKey: "Inbound signing key",
  deactivate: "Deactivate",
  activate: "Activate",
  verify: "Verify",
  suppressions: "Suppressions",
  suppressionsDescription: "Addresses that are blocked from receiving messages, and why.",
  emailAddress: "Email address",
  reasonOptional: "Reason (optional)",
  addSuppression: "Add suppression",
  suppressionAdded: "Suppression added",
  addressWillNotReceive: "The address will not receive messages.",
  suppressionNotAdded: "Suppression not added",
  suppressionDeleted: "Suppression deleted",
  addressCanReceive: "The address can receive messages again.",
  suppressionNotDeleted: "Suppression not deleted",
  search: "Search",
  searchEmailOrReason: "Search email or reason",
  email: "Email",
  reason: "Reason",
  noReason: "—",
  delete: "Delete",
  noSuppressionsFound: "No suppressions found.",
  deleteSuppression: "Delete suppression",
  allowAddressAgain: "Allow this address to receive messages again?",
  validEmailAddress: "Enter a valid email address",
  channelCreated: "Channel created",
  emailChannelReady: "Your email channel is ready.",
  channelVerified: "Channel verified",
  channelConnectionValid: "The channel connection is valid.",
  channels: "Channels",
  channelsDescription: "Configure the email addresses that power your shared inbox.",
  addChannel: "Add channel",
  couldNotLoadChannels: "Could not load channels",
  address: "Address",
  actions: "Actions",
  addEmailChannel: "Add email channel",
  createChannel: "Create channel",
  inbox: "Inbox",
  inboxDescription: "Keep every customer conversation moving.",
  sharedInbox: "Shared inbox",
  filters: "Filters",
  searchConversations: "Search conversations",
  views: "Views",
  allConversations: "All conversations",
  unread: "Unread",
  tags: "Tags",
  conversationsCount: "{{count}} conversations",
  refresh: "Refresh",
  couldNotLoadConversations: "Could not load conversations: {{error}}",
  noConversationsMatch: "No conversations match these filters.",
  selectConversation: "Select a conversation",
  repliesAndNotesTogether: "Your replies and notes will stay together here.",
  couldNotLoadConversation: "Could not load this conversation.",
  customerAssociation: "Customer #{{id}} · {{source}}",
  suggestedCustomer: "Suggested customer #{{id}}",
  customerCandidates: "{{count}} customer candidates",
  suggestCustomer: "Suggest customer",
  noCustomerAssociation: "No customer association",
  aiSuggestion: "AI suggestion",
  confirmCustomer: "Confirm customer",
  aiSuggestionsUnavailable: "AI customer suggestions are currently unavailable.",
  statusLabel: "Status",
  markRead: "Mark read",
  archive: "Archive",
  addTag: "Add tag",
  messageHtml: "Message HTML",
  scanning: "Scanning",
  attachmentUnavailable: "Attachment unavailable",
  draftWithAi: "Draft with AI",
  aiTone: "AI tone",
  aiReplyInstruction: "What should this reply cover? (required)",
  regenerateDraft: "Regenerate draft",
  aiDraftReview: "AI draft — review before sending. Nothing has been sent.",
  aiDraftUnavailable: "AI drafting is currently unavailable. You can still write and send a reply manually.",
  reply: "Reply",
  replyAll: "Reply all · {{count}}",
  replyMode: "Reply mode",
  internalNote: "Internal note",
  addNote: "Add note",
  replyingTo: "Replying to {{address}}",
  additionalRecipient: " and {{count}} additional recipient{{suffix}}",
  attachFile: "Attach file",
  unavailable: "Unavailable",
  attachmentCouldNotBeStaged: "Attachment could not be staged. Your draft is unchanged.",
  waitingForAttachmentScan: "Waiting for attachment scan",
  sendReply: "Send reply",
} as const;

const nb: { [Key in keyof typeof en]: string } = {
  communications: "Kommunikasjon",
  status: "Status",
  created: "Opprettet",
  cancel: "Avbryt",
  displayName: "Visningsnavn",
  provider: "Leverandør",
  default: "Standard",
  active: "Aktiv",
  inactive: "Inaktiv",
  smtp: "SMTP",
  mailgun: "Mailgun",
  smtpHost: "SMTP-vert",
  smtpPort: "SMTP-port",
  username: "Brukernavn",
  password: "Passord",
  mailgunDomain: "Mailgun-domene",
  region: "Region",
  us: "USA",
  eu: "EU",
  apiKey: "API-nøkkel",
  inboundSigningKey: "Signeringsnøkkel for innkommende e-post",
  deactivate: "Deaktiver",
  activate: "Aktiver",
  verify: "Bekreft",
  suppressions: "Blokkeringer",
  suppressionsDescription: "Adresser som er blokkert fra å motta meldinger, og hvorfor.",
  emailAddress: "E-postadresse",
  reasonOptional: "Årsak (valgfritt)",
  addSuppression: "Legg til blokkering",
  suppressionAdded: "Blokkering lagt til",
  addressWillNotReceive: "Adressen vil ikke motta meldinger.",
  suppressionNotAdded: "Blokkeringen ble ikke lagt til",
  suppressionDeleted: "Blokkering slettet",
  addressCanReceive: "Adressen kan motta meldinger igjen.",
  suppressionNotDeleted: "Blokkeringen ble ikke slettet",
  search: "Søk",
  searchEmailOrReason: "Søk etter e-post eller årsak",
  email: "E-post",
  reason: "Årsak",
  noReason: "—",
  delete: "Slett",
  noSuppressionsFound: "Ingen blokkeringer funnet.",
  deleteSuppression: "Slett blokkering",
  allowAddressAgain: "Tillat denne adressen å motta meldinger igjen?",
  validEmailAddress: "Skriv inn en gyldig e-postadresse",
  channelCreated: "Kanal opprettet",
  emailChannelReady: "E-postkanalen er klar.",
  channelVerified: "Kanal bekreftet",
  channelConnectionValid: "Kanaltilkoblingen er gyldig.",
  channels: "Kanaler",
  channelsDescription: "Konfigurer e-postadressene som driver den delte innboksen.",
  addChannel: "Legg til kanal",
  couldNotLoadChannels: "Kunne ikke laste kanaler",
  address: "Adresse",
  actions: "Handlinger",
  addEmailChannel: "Legg til e-postkanal",
  createChannel: "Opprett kanal",
  inbox: "Innboks",
  inboxDescription: "Hold alle kundesamtaler i gang.",
  sharedInbox: "Delt innboks",
  filters: "Filtre",
  searchConversations: "Søk i samtaler",
  views: "Visninger",
  allConversations: "Alle samtaler",
  unread: "Uleste",
  tags: "Tagger",
  conversationsCount: "{{count}} samtaler",
  refresh: "Oppdater",
  couldNotLoadConversations: "Kunne ikke laste samtaler: {{error}}",
  noConversationsMatch: "Ingen samtaler samsvarer med disse filtrene.",
  selectConversation: "Velg en samtale",
  repliesAndNotesTogether: "Svarene og notatene dine holdes samlet her.",
  couldNotLoadConversation: "Kunne ikke laste denne samtalen.",
  customerAssociation: "Kunde nr. {{id}} · {{source}}",
  suggestedCustomer: "Foreslått kunde nr. {{id}}",
  customerCandidates: "{{count}} kundekandidater",
  suggestCustomer: "Foreslå kunde",
  noCustomerAssociation: "Ingen kundetilknytning",
  aiSuggestion: "KI-forslag",
  confirmCustomer: "Bekreft kunde",
  aiSuggestionsUnavailable: "KI-kundeforslag er ikke tilgjengelige nå.",
  statusLabel: "Status",
  markRead: "Marker som lest",
  archive: "Arkiver",
  addTag: "Legg til tagg",
  messageHtml: "Meldings-HTML",
  scanning: "Skanner",
  attachmentUnavailable: "Vedlegg utilgjengelig",
  draftWithAi: "Skriv utkast med KI",
  aiTone: "KI-tone",
  aiReplyInstruction: "Hva skal dette svaret dekke? (obligatorisk)",
  regenerateDraft: "Lag utkast på nytt",
  aiDraftReview: "KI-utkast — se gjennom før sending. Ingenting er sendt.",
  aiDraftUnavailable: "KI-utkast er ikke tilgjengelig nå. Du kan fortsatt skrive og sende et svar manuelt.",
  reply: "Svar",
  replyAll: "Svar alle · {{count}}",
  replyMode: "Svarmodus",
  internalNote: "Internt notat",
  addNote: "Legg til notat",
  replyingTo: "Svarer til {{address}}",
  additionalRecipient: " og {{count}} ekstra mottaker{{suffix}}",
  attachFile: "Legg ved fil",
  unavailable: "Utilgjengelig",
  attachmentCouldNotBeStaged: "Vedlegget kunne ikke klargjøres. Utkastet ditt er uendret.",
  waitingForAttachmentScan: "Venter på vedleggsskanning",
  sendReply: "Send svar",
};

export const communicationsCatalog = { en, nb } as const satisfies CatalogResources;
