import type { CatalogResources } from "@vantigo/frontend-shell";

const en = {
  communications: "Communications",
  messages: "Messages",
  messagesDescription: "Every message sent through your services, from submission to reply.",
  messageCountSingular: "{{count}} message",
  messageCountPlural: "{{count}} messages",
  searchHistory: "Search history",
  searchHistoryComingSoon: "Search history (coming soon)",
  showArchived: "Show archived",
  couldNotLoadMessages: "Could not load messages",
  noMessagesYet: "No messages yet",
  messagesWillAppear: "Messages sent through your service will appear here.",
  message: "Message",
  recipients: "Recipients",
  status: "Status",
  created: "Created",
  archived: "Archived",
  messageFallback: "Message {{id}}",
  newMessage: "New message",
  newMessageDescription: "Write and send a message to one or more recipients.",
  subject: "Subject",
  subjectRequired: "Subject is required",
  sendFrom: "Send from",
  selectMailbox: "Select a mailbox",
  to: "To",
  addRecipient: "Add recipient",
  addCcOrBcc: "Add Cc or Bcc",
  hideCcAndBcc: "Hide Cc and Bcc",
  cc: "Cc",
  addCcRecipient: "Add Cc recipient",
  bcc: "Bcc",
  addBccRecipient: "Add Bcc recipient",
  body: "Body",
  sendMessage: "Send message",
  messageQueued: "Message queued",
  messageSubmitted: "Your message has been submitted.",
  validEmailAddresses: "Enter valid email addresses",
  recipientRequired: "At least one recipient is required",
  duplicateRecipient: "Duplicate recipient: {{recipients}}",
  suppressedRecipients: "Suppressed recipients: {{recipients}}",
  messageNotSent: "Message not sent",
  noActiveMailbox: "No active mailbox",
  configureActiveMailbox: "Configure an active mailbox before sending.",
  noActiveMailboxConfigured: "No active mailbox is configured",
  askOwnerToConfigure: "Ask an Owner to configure an active mailbox before sending messages.",
  messageRequeued: "Message re-queued",
  recipientsQueuedSingular: "{{count}} recipient queued for sending.",
  recipientsQueuedPlural: "{{count}} recipients queued for sending.",
  couldNotResend: "Could not resend",
  messageArchived: "Message archived",
  messageMovedToArchive: "The message was moved to the archive.",
  couldNotArchive: "Could not archive",
  messageRestored: "Message restored",
  messageBackInHistory: "The message is back in the history.",
  couldNotRestore: "Could not restore",
  messageUnavailable: "Message unavailable",
  unknownSource: "Unknown source",
  sentFrom: "Sent from",
  resend: "Resend",
  sendInProgress: "A send is already in progress.",
  resendFailedRecipients: "Resend failed recipients only",
  resendAllRecipients: "Resend to all recipients",
  unarchive: "Unarchive",
  archive: "Archive",
  archiveMessage: "Archive message",
  archiveMessageDescription:
    "The message will be hidden from the default history view.{{pendingText}} You can unarchive it later.",
  pendingSendCancelled: " Any pending send will be cancelled.",
  cancel: "Cancel",
  messageBody: "Message body",
  noMessageBody: "No message body was provided.",
  noRecipientsRecorded: "No recipients recorded.",
  externalReferences: "External references",
  deliveryTimeline: "Delivery timeline",
  couldNotLoadDeliveryEvents: "Could not load delivery events.",
  noEventsRecorded: "No events recorded.",
  statusRecorded: "Status recorded by the service.",
  statusQueued: "Queued",
  statusRelayAccepted: "Relay accepted",
  statusSubmissionFailed: "Submission failed",
  statusSending: "Sending",
  statusRetrying: "Retrying",
  statusCancelled: "Cancelled",
  statusSuppressed: "Suppressed",
  eventMessageQueued: "Message queued",
  recipientTo: "To",
  recipientCc: "Cc",
  recipientBcc: "Bcc",
  mailboxes: "Mailboxes",
  mailboxesDescription: "Configure the mailboxes that send and receive messages.",
  addMailbox: "Add Mailbox",
  fromAddress: "From address",
  displayName: "Display name",
  provider: "Provider",
  default: "Default",
  active: "Active",
  inactive: "Inactive",
  smtp: "SMTP",
  mailgun: "Mailgun",
  smtpHost: "SMTP host",
  smtpPort: "SMTP port",
  useSsl: "Use SSL",
  username: "Username",
  password: "Password",
  mailgunDomain: "Mailgun domain",
  region: "Region",
  us: "US",
  eu: "EU",
  apiKey: "API key",
  mailboxCreated: "Mailbox created",
  workspaceMailboxReady: "The workspace mailbox is ready.",
  mailboxNotCreated: "Mailbox not created",
  mailboxUpdated: "Mailbox updated",
  mailboxSettingsSaved: "Mailbox settings saved.",
  defaultMailboxRequired: "Default mailbox required",
  mailboxNotUpdated: "Mailbox not updated",
  mailboxVerified: "Mailbox verified",
  mailboxConnectionValid: "The mailbox connection is valid.",
  verificationFailed: "Verification failed",
  deactivateThisMailbox: "Deactivate this mailbox?",
  mailboxInactiveDescription: "Messages cannot be sent from this mailbox while it is inactive.",
  deactivate: "Deactivate",
  activate: "Activate",
  verify: "Verify",
  setDefault: "Set default",
  editCredentials: "Edit credentials",
  addMailboxTitle: "Add mailbox",
  createMailbox: "Create mailbox",
  editCredentialsTitle: "Edit credentials",
  saveCredentials: "Save credentials",
  displayNameFor: "Display name for {{address}}",
  suppressions: "Suppressions",
  suppressionsDescription: "Addresses that are blocked from receiving messages, and why.",
  emailAddress: "Email address",
  reasonOptional: "Reason (optional)",
  addSuppression: "Add suppression",
  suppressionAdded: "Suppression added",
  addressWillNotReceive: "The address will not receive messages.",
  suppressionNotAdded: "Suppression not added",
  suppressionDeleted: "Suppression deleted",
  addressCanReceive: "The address can receive messages again.",
  suppressionNotDeleted: "Suppression not deleted",
  search: "Search",
  searchEmailOrReason: "Search email or reason",
  email: "Email",
  reason: "Reason",
  noReason: "—",
  delete: "Delete",
  noSuppressionsFound: "No suppressions found.",
  deleteSuppression: "Delete suppression",
  allowAddressAgain: "Allow this address to receive messages again?",
  validEmailAddress: "Enter a valid email address",
} as const;

const nb: { [Key in keyof typeof en]: string } = {
  communications: "Kommunikasjon",
  messages: "Meldinger",
  messagesDescription: "Alle meldinger som sendes gjennom tjenestene dine, fra innsending til svar.",
  messageCountSingular: "{{count}} melding",
  messageCountPlural: "{{count}} meldinger",
  searchHistory: "Søk i historikken",
  searchHistoryComingSoon: "Søk i historikken (kommer snart)",
  showArchived: "Vis arkiverte",
  couldNotLoadMessages: "Kunne ikke laste meldinger",
  noMessagesYet: "Ingen meldinger ennå",
  messagesWillAppear: "Meldinger som sendes gjennom tjenesten din, vises her.",
  message: "Melding",
  recipients: "Mottakere",
  status: "Status",
  created: "Opprettet",
  archived: "Arkivert",
  messageFallback: "Melding {{id}}",
  newMessage: "Ny melding",
  newMessageDescription: "Skriv og send en melding til én eller flere mottakere.",
  subject: "Emne",
  subjectRequired: "Emne er obligatorisk",
  sendFrom: "Send fra",
  selectMailbox: "Velg en postkasse",
  to: "Til",
  addRecipient: "Legg til mottaker",
  addCcOrBcc: "Legg til Cc eller Bcc",
  hideCcAndBcc: "Skjul Cc og Bcc",
  cc: "Cc",
  addCcRecipient: "Legg til Cc-mottaker",
  bcc: "Bcc",
  addBccRecipient: "Legg til Bcc-mottaker",
  body: "Brødtekst",
  sendMessage: "Send melding",
  messageQueued: "Melding lagt i kø",
  messageSubmitted: "Meldingen din er sendt inn.",
  validEmailAddresses: "Skriv inn gyldige e-postadresser",
  recipientRequired: "Minst én mottaker er obligatorisk",
  duplicateRecipient: "Duplikatmottaker: {{recipients}}",
  suppressedRecipients: "Undertrykte mottakere: {{recipients}}",
  messageNotSent: "Meldingen ble ikke sendt",
  noActiveMailbox: "Ingen aktiv postkasse",
  configureActiveMailbox: "Konfigurer en aktiv postkasse før du sender.",
  noActiveMailboxConfigured: "Ingen aktiv postkasse er konfigurert",
  askOwnerToConfigure: "Be en eier om å konfigurere en aktiv postkasse før du sender meldinger.",
  messageRequeued: "Melding lagt i kø på nytt",
  recipientsQueuedSingular: "{{count}} mottaker lagt i kø for sending.",
  recipientsQueuedPlural: "{{count}} mottakere lagt i kø for sending.",
  couldNotResend: "Kunne ikke sende på nytt",
  messageArchived: "Melding arkivert",
  messageMovedToArchive: "Meldingen ble flyttet til arkivet.",
  couldNotArchive: "Kunne ikke arkivere",
  messageRestored: "Melding gjenopprettet",
  messageBackInHistory: "Meldingen er tilbake i historikken.",
  couldNotRestore: "Kunne ikke gjenopprette",
  messageUnavailable: "Meldingen er utilgjengelig",
  unknownSource: "Ukjent kilde",
  sentFrom: "Sendt fra",
  resend: "Send på nytt",
  sendInProgress: "En sending pågår allerede.",
  resendFailedRecipients: "Send bare mislykkede mottakere på nytt",
  resendAllRecipients: "Send på nytt til alle mottakere",
  unarchive: "Fjern fra arkivet",
  archive: "Arkiver",
  archiveMessage: "Arkiver melding",
  archiveMessageDescription:
    "Meldingen skjules fra standardvisningen av historikken.{{pendingText}} Du kan fjerne den fra arkivet senere.",
  pendingSendCancelled: " En eventuell ventende sending avbrytes.",
  cancel: "Avbryt",
  messageBody: "Meldingstekst",
  noMessageBody: "Ingen meldingstekst ble oppgitt.",
  noRecipientsRecorded: "Ingen mottakere er registrert.",
  externalReferences: "Eksterne referanser",
  deliveryTimeline: "Leveringstidslinje",
  couldNotLoadDeliveryEvents: "Kunne ikke laste leveringshendelser.",
  noEventsRecorded: "Ingen hendelser er registrert.",
  statusRecorded: "Status registrert av tjenesten.",
  statusQueued: "Lagt i kø",
  statusRelayAccepted: "Relé godtok",
  statusSubmissionFailed: "Innsending mislyktes",
  statusSending: "Sender",
  statusRetrying: "Prøver på nytt",
  statusCancelled: "Avbrutt",
  statusSuppressed: "Undertrykt",
  eventMessageQueued: "Melding lagt i kø",
  recipientTo: "Til",
  recipientCc: "Cc",
  recipientBcc: "Bcc",
  mailboxes: "Postkasser",
  mailboxesDescription: "Konfigurer postkassene som sender og mottar meldinger.",
  addMailbox: "Legg til postkasse",
  fromAddress: "Fra-adresse",
  displayName: "Visningsnavn",
  provider: "Leverandør",
  default: "Standard",
  active: "Aktiv",
  inactive: "Inaktiv",
  smtp: "SMTP",
  mailgun: "Mailgun",
  smtpHost: "SMTP-vert",
  smtpPort: "SMTP-port",
  useSsl: "Bruk SSL",
  username: "Brukernavn",
  password: "Passord",
  mailgunDomain: "Mailgun-domene",
  region: "Region",
  us: "USA",
  eu: "EU",
  apiKey: "API-nøkkel",
  mailboxCreated: "Postkasse opprettet",
  workspaceMailboxReady: "Postkassen er klar for arbeidsområdet.",
  mailboxNotCreated: "Postkassen ble ikke opprettet",
  mailboxUpdated: "Postkasse oppdatert",
  mailboxSettingsSaved: "Postkasseinnstillingene er lagret.",
  defaultMailboxRequired: "Standardpostkasse kreves",
  mailboxNotUpdated: "Postkassen ble ikke oppdatert",
  mailboxVerified: "Postkasse bekreftet",
  mailboxConnectionValid: "Postkasseforbindelsen er gyldig.",
  verificationFailed: "Bekreftelsen mislyktes",
  deactivateThisMailbox: "Deaktivere denne postkassen?",
  mailboxInactiveDescription: "Meldinger kan ikke sendes fra denne postkassen når den er inaktiv.",
  deactivate: "Deaktiver",
  activate: "Aktiver",
  verify: "Bekreft",
  setDefault: "Angi som standard",
  editCredentials: "Rediger påloggingsinformasjon",
  addMailboxTitle: "Legg til postkasse",
  createMailbox: "Opprett postkasse",
  editCredentialsTitle: "Rediger påloggingsinformasjon",
  saveCredentials: "Lagre påloggingsinformasjon",
  displayNameFor: "Visningsnavn for {{address}}",
  suppressions: "Blokkeringer",
  suppressionsDescription: "Adresser som er blokkert fra å motta meldinger, og hvorfor.",
  emailAddress: "E-postadresse",
  reasonOptional: "Årsak (valgfritt)",
  addSuppression: "Legg til blokkering",
  suppressionAdded: "Blokkering lagt til",
  addressWillNotReceive: "Adressen vil ikke motta meldinger.",
  suppressionNotAdded: "Blokkeringen ble ikke lagt til",
  suppressionDeleted: "Blokkering slettet",
  addressCanReceive: "Adressen kan motta meldinger igjen.",
  suppressionNotDeleted: "Blokkeringen ble ikke slettet",
  search: "Søk",
  searchEmailOrReason: "Søk etter e-post eller årsak",
  email: "E-post",
  reason: "Årsak",
  noReason: "—",
  delete: "Slett",
  noSuppressionsFound: "Ingen blokkeringer funnet.",
  deleteSuppression: "Slett blokkering",
  allowAddressAgain: "Tillat denne adressen å motta meldinger igjen?",
  validEmailAddress: "Skriv inn en gyldig e-postadresse",
};

export const communicationsCatalog = { en, nb } as const satisfies CatalogResources;
