/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminMailboxesRouteImport } from './routes/admin.mailboxes'
import { Route as AdminSuppressionsRouteImport } from './routes/admin.suppressions'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesMessageIdRouteImport } from './routes/messages.$messageId'
import { Route as MessagesComposeRouteImport } from './routes/messages.compose'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMailboxesRoute = AdminMailboxesRouteImport.update({
  id: '/admin/mailboxes',
  path: '/admin/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppressionsRoute = AdminSuppressionsRouteImport.update({
  id: '/admin/suppressions',
  path: '/admin/suppressions',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesMessageIdRoute = MessagesMessageIdRouteImport.update({
  id: '/messages/$messageId',
  path: '/messages/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesComposeRoute = MessagesComposeRouteImport.update({
  id: '/messages/compose',
  path: '/messages/compose',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin/suppressions': typeof AdminSuppressionsRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/compose': typeof MessagesComposeRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin/suppressions': typeof AdminSuppressionsRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/compose': typeof MessagesComposeRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin/suppressions': typeof AdminSuppressionsRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/compose': typeof MessagesComposeRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/setup'
    | '/sign-in'
    | '/admin/mailboxes'
    | '/admin/suppressions'
    | '/messages/$messageId'
    | '/messages/compose'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/setup'
    | '/sign-in'
    | '/admin/mailboxes'
    | '/admin/suppressions'
    | '/messages/$messageId'
    | '/messages/compose'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/setup'
    | '/sign-in'
    | '/admin/mailboxes'
    | '/admin/suppressions'
    | '/messages/$messageId'
    | '/messages/compose'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  AdminMailboxesRoute: typeof AdminMailboxesRoute
  AdminSuppressionsRoute: typeof AdminSuppressionsRoute
  MessagesMessageIdRoute: typeof MessagesMessageIdRoute
  MessagesComposeRoute: typeof MessagesComposeRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mailboxes': {
      id: '/admin/mailboxes'
      path: '/admin/mailboxes'
      fullPath: '/admin/mailboxes'
      preLoaderRoute: typeof AdminMailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppressions': {
      id: '/admin/suppressions'
      path: '/admin/suppressions'
      fullPath: '/admin/suppressions'
      preLoaderRoute: typeof AdminSuppressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$messageId': {
      id: '/messages/$messageId'
      path: '/messages/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof MessagesMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/compose': {
      id: '/messages/compose'
      path: '/messages/compose'
      fullPath: '/messages/compose'
      preLoaderRoute: typeof MessagesComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  AdminMailboxesRoute: AdminMailboxesRoute,
  AdminSuppressionsRoute: AdminSuppressionsRoute,
  MessagesMessageIdRoute: MessagesMessageIdRoute,
  MessagesComposeRoute: MessagesComposeRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
