version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "Europe/Oslo"

    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      framework:
        patterns:
          - "next"
          - "react*"
      backend-core:
        patterns:
          - "drizzle-orm"
          - "better-auth"
          - "zod"
      mantine-ui:
        patterns:
          - "@mantine/*"
          - "mantine"
      development-tooling:
        dependency-type: "development"

  - package-ecosystem: "docker"
    directories:
      - "/apps/*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
