using System;

using Microsoft.EntityFrameworkCore.Migrations;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

using Vantigo.Tenancy.EntityFramework;

#nullable disable

namespace Vantigo.Energy.Database.Energy.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "energy");

            migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS btree_gist;");

            migrationBuilder.CreateTable(
                name: "metering_points",
                schema: "energy",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:IdentitySequenceOptions", "'1001', '1', '', '', 'False', '1'")
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    gsrn = table.Column<string>(type: "character varying(18)", unicode: false, maxLength: 18, nullable: false),
                    street_address = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    postal_code = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    city = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    country_code = table.Column<string>(type: "character varying(2)", unicode: false, maxLength: 2, nullable: false),
                    price_area = table.Column<string>(type: "character varying(4)", unicode: false, maxLength: 4, nullable: false),
                    grid_area = table.Column<string>(type: "character varying(64)", unicode: false, maxLength: 64, nullable: true),
                    expected_annual_consumption_kwh = table.Column<decimal>(type: "numeric(14,3)", precision: 14, scale: 3, nullable: true),
                    latitude = table.Column<double>(type: "double precision", precision: 9, scale: 6, nullable: true),
                    longitude = table.Column<double>(type: "double precision", precision: 9, scale: 6, nullable: true),
                    connection_status = table.Column<string>(type: "character varying(20)", unicode: false, maxLength: 20, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_metering_points", x => new { x.tenant_id, x.id });
                });

            // PostgreSQL native monthly partitioning is maintained by
            // energy.ensure_consumption_partition(date). Schedule that function
            // (or call it before inserting a new month) as the range advances.
            migrationBuilder.Sql("""
                CREATE TABLE energy.consumption_intervals (
                    tenant_id uuid NOT NULL,
                    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    start timestamp with time zone NOT NULL,
                    metering_point_id integer NOT NULL,
                    "end" timestamp with time zone NOT NULL,
                    quantity_kwh numeric(14,3) NOT NULL,
                    quality varchar(20) NOT NULL,
                    source varchar(20) NOT NULL,
                    received_at timestamp with time zone NOT NULL,
                    is_current boolean NOT NULL,
                    supersedes_id bigint NULL,
                    supersedes_start timestamp with time zone NULL,
                    CONSTRAINT "PK_consumption_intervals" PRIMARY KEY (tenant_id, id, start),
                    CONSTRAINT "FK_consumption_intervals_metering_points" FOREIGN KEY (tenant_id, metering_point_id)
                        REFERENCES energy.metering_points (tenant_id, id) ON DELETE CASCADE,
                    CONSTRAINT "FK_consumption_intervals_supersedes" FOREIGN KEY (tenant_id, supersedes_id, supersedes_start)
                        REFERENCES energy.consumption_intervals (tenant_id, id, start) ON DELETE RESTRICT
                ) PARTITION BY RANGE (start);

                CREATE INDEX "IX_consumption_intervals_tenant_id_supersedes_id_supersedes_start"
                    ON energy.consumption_intervals (tenant_id, supersedes_id, supersedes_start);

                CREATE UNIQUE INDEX "IX_consumption_intervals_tenant_id_metering_point_id_start_end"
                    ON energy.consumption_intervals (tenant_id, metering_point_id, start, "end")
                    WHERE is_current = TRUE;

                CREATE OR REPLACE FUNCTION energy.ensure_consumption_partition(partition_month date)
                RETURNS void LANGUAGE plpgsql AS $function$
                DECLARE
                    partition_start date := date_trunc('month', partition_month)::date;
                    partition_end date := (partition_start + interval '1 month')::date;
                    partition_name text := format('consumption_intervals_%s', to_char(partition_start, 'YYYY_MM'));
                BEGIN
                    EXECUTE format(
                        'CREATE TABLE IF NOT EXISTS energy.%I PARTITION OF energy.consumption_intervals FOR VALUES FROM (%L) TO (%L)',
                        partition_name, partition_start, partition_end);
                END;
                $function$;
                """);

            migrationBuilder.Sql("""
                SELECT energy.ensure_consumption_partition((date_trunc('month', current_date) + offset_months * interval '1 month')::date)
                FROM generate_series(-12, 12) AS offset_months;
                """);

            migrationBuilder.CreateTable(
                name: "meters",
                schema: "energy",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:IdentitySequenceOptions", "'1001', '1', '', '', 'False', '1'")
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    metering_point_id = table.Column<int>(type: "integer", nullable: false),
                    meter_number = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    installed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    removed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_meters", x => new { x.tenant_id, x.id });
                    table.ForeignKey(
                        name: "FK_meters_metering_points_tenant_id_metering_point_id",
                        columns: x => new { x.tenant_id, x.metering_point_id },
                        principalSchema: "energy",
                        principalTable: "metering_points",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "supply_periods",
                schema: "energy",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:IdentitySequenceOptions", "'1001', '1', '', '', 'False', '1'")
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    metering_point_id = table.Column<int>(type: "integer", nullable: false),
                    customer_id = table.Column<int>(type: "integer", nullable: false),
                    start = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    end = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    status = table.Column<string>(type: "character varying(20)", unicode: false, maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_supply_periods", x => new { x.tenant_id, x.id });
                    table.ForeignKey(
                        name: "FK_supply_periods_metering_points_tenant_id_metering_point_id",
                        columns: x => new { x.tenant_id, x.metering_point_id },
                        principalSchema: "energy",
                        principalTable: "metering_points",
                        principalColumns: new[] { "tenant_id", "id" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_metering_points_tenant_id_gsrn",
                schema: "energy",
                table: "metering_points",
                columns: new[] { "tenant_id", "gsrn" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_meters_tenant_id_metering_point_id",
                schema: "energy",
                table: "meters",
                columns: new[] { "tenant_id", "metering_point_id" },
                unique: true,
                filter: "removed_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "IX_supply_periods_tenant_id_metering_point_id",
                schema: "energy",
                table: "supply_periods",
                columns: new[] { "tenant_id", "metering_point_id" });

            migrationBuilder.Sql("ALTER TABLE energy.supply_periods ADD CONSTRAINT supply_periods_no_overlap EXCLUDE USING gist (tenant_id WITH =, metering_point_id WITH =, tstzrange(start, COALESCE(\"end\", 'infinity'::timestamptz), '[)') WITH &&) WHERE (status <> 'Cancelled');");

            migrationBuilder.EnableTenantRls("energy", "metering_points");
            migrationBuilder.EnableTenantRls("energy", "meters");
            migrationBuilder.EnableTenantRls("energy", "consumption_intervals");
            migrationBuilder.EnableTenantRls("energy", "supply_periods");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "consumption_intervals",
                schema: "energy");

            migrationBuilder.Sql("DROP FUNCTION IF EXISTS energy.ensure_consumption_partition(date);");

            migrationBuilder.DropTable(
                name: "meters",
                schema: "energy");

            migrationBuilder.DropTable(
                name: "supply_periods",
                schema: "energy");

            migrationBuilder.DropTable(
                name: "metering_points",
                schema: "energy");
        }
    }
}