// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package store

import (
	"context"
	"time"
)

const associationExists = `-- name: AssociationExists :one
SELECT EXISTS (
    SELECT 1 FROM customers.customers_contacts WHERE customer_id = $1 AND contact_id = $2
)
`

type AssociationExistsParams struct {
	CustomerID int32
	ContactID  int32
}

// AssociationExists is AttachCustomerContactEndpoint's already-attached
// check (:50-51), run only after both the customer and the (now locked)
// contact are confirmed to exist.
func (q *Queries) AssociationExists(ctx context.Context, arg AssociationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, associationExists, arg.CustomerID, arg.ContactID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const associationsForContacts = `-- name: AssociationsForContacts :many
SELECT cc.contact_id, cu.id AS customer_id, cu.customer_number, cu.name AS customer_name
FROM customers.customers_contacts cc
JOIN customers.customers cu ON cu.id = cc.customer_id
WHERE cc.contact_id = ANY($1::int[])
`

type AssociationsForContactsRow struct {
	ContactID      int32
	CustomerID     int32
	CustomerNumber int64
	CustomerName   string
}

// AssociationsForContacts is GetContactsEndpoint's LoadAssociations
// (GetContactsEndpoint.cs:85-110): every customer association of the given
// page of contacts, in one query, so the per-contact customerCount and
// single-customer projection never fan out per row.
func (q *Queries) AssociationsForContacts(ctx context.Context, contactIds []int32) ([]AssociationsForContactsRow, error) {
	rows, err := q.db.Query(ctx, associationsForContacts, contactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssociationsForContactsRow
	for rows.Next() {
		var i AssociationsForContactsRow
		if err := rows.Scan(
			&i.ContactID,
			&i.CustomerID,
			&i.CustomerNumber,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countContacts = `-- name: CountContacts :one
SELECT count(*)
FROM customers.contacts
WHERE NOT EXISTS (
    SELECT 1 FROM unnest($1::text[]) AS p(pattern)
    WHERE NOT (
        first_name ILIKE p.pattern OR
        last_name ILIKE p.pattern OR
        (middle_name IS NOT NULL AND middle_name ILIKE p.pattern) OR
        (prefix IS NOT NULL AND prefix ILIKE p.pattern) OR
        (suffix IS NOT NULL AND suffix ILIKE p.pattern) OR
        (phone IS NOT NULL AND phone ILIKE p.pattern) OR
        (email IS NOT NULL AND email ILIKE p.pattern)
    )
)
`

// CountContacts is GetContactsEndpoint's total row count. @patterns holds one
// already-ILIKE-escaped "%term%" glob per whitespace-separated search term
// (empty when the caller sent none); a contact passes only when every
// pattern matches at least one of its searchable fields
// (GetContactsEndpoint.cs:41-56, "every term must match at least one of the
// searchable fields"). unnest() of an empty or NULL array yields no rows, so
// NOT EXISTS is trivially true and every contact passes when there is no
// search at all.
func (q *Queries) CountContacts(ctx context.Context, patterns []string) (int64, error) {
	row := q.db.QueryRow(ctx, countContacts, patterns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAssociation = `-- name: DeleteAssociation :exec
DELETE FROM customers.customers_contacts WHERE customer_id = $1 AND contact_id = $2
`

type DeleteAssociationParams struct {
	CustomerID int32
	ContactID  int32
}

// DeleteAssociation is DetachCustomerContactEndpoint's row removal (:31).
func (q *Queries) DeleteAssociation(ctx context.Context, arg DeleteAssociationParams) error {
	_, err := q.db.Exec(ctx, deleteAssociation, arg.CustomerID, arg.ContactID)
	return err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM customers.contacts WHERE id = $1
`

// DeleteContact removes a contact row (DeleteContactEndpoint.cs:38); the FK
// ON DELETE CASCADE on customers_contacts removes its associations. The
// "removed" timeline event per association is the caller's responsibility to
// record first, in the same transaction — this statement carries none of its
// own.
func (q *Queries) DeleteContact(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const getAssociationWithContact = `-- name: GetAssociationWithContact :one
SELECT cc.role, cc.phone AS association_phone, cc.email AS association_email,
       c.id, c.first_name, c.last_name, c.middle_name, c.prefix, c.suffix,
       c.phone AS contact_phone, c.email AS contact_email, c.created_at
FROM customers.customers_contacts cc
JOIN customers.contacts c ON c.id = cc.contact_id
WHERE cc.customer_id = $1 AND cc.contact_id = $2
`

type GetAssociationWithContactParams struct {
	CustomerID int32
	ContactID  int32
}

type GetAssociationWithContactRow struct {
	Role             string
	AssociationPhone *string
	AssociationEmail *string
	ID               int32
	FirstName        string
	LastName         string
	MiddleName       *string
	Prefix           *string
	Suffix           *string
	ContactPhone     *string
	ContactEmail     *string
	CreatedAt        time.Time
}

// GetAssociationWithContact is UpdateCustomerContactEndpoint's and
// DetachCustomerContactEndpoint's shared lookup; the contact's own fields are
// included since both callers need them for their response or their
// timeline event.
func (q *Queries) GetAssociationWithContact(ctx context.Context, arg GetAssociationWithContactParams) (GetAssociationWithContactRow, error) {
	row := q.db.QueryRow(ctx, getAssociationWithContact, arg.CustomerID, arg.ContactID)
	var i GetAssociationWithContactRow
	err := row.Scan(
		&i.Role,
		&i.AssociationPhone,
		&i.AssociationEmail,
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Prefix,
		&i.Suffix,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, first_name, last_name, middle_name, prefix, suffix, phone, email, created_at
FROM customers.contacts
WHERE id = $1
`

// GetContact fetches one contact by id (GetContactEndpoint.cs), unlocked.
func (q *Queries) GetContact(ctx context.Context, id int32) (CustomersContact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i CustomersContact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Prefix,
		&i.Suffix,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getContactForUpdate = `-- name: GetContactForUpdate :one
SELECT id, first_name, last_name, middle_name, prefix, suffix, phone, email, created_at
FROM customers.contacts
WHERE id = $1
FOR UPDATE
`

// GetContactForUpdate is the pessimistic row lock customers inventory §4
// describes (AttachCustomerContactEndpoint.cs:42, DeleteContactEndpoint.cs:22):
// it serializes an attach against a concurrent delete of the same contact, so
// one of the two always observes the other's effect instead of racing to an
// orphaned association or a silently-lost one.
func (q *Queries) GetContactForUpdate(ctx context.Context, id int32) (CustomersContact, error) {
	row := q.db.QueryRow(ctx, getContactForUpdate, id)
	var i CustomersContact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Prefix,
		&i.Suffix,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssociation = `-- name: InsertAssociation :exec
INSERT INTO customers.customers_contacts (customer_id, contact_id, role, phone, email)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAssociationParams struct {
	CustomerID int32
	ContactID  int32
	Role       string
	Phone      *string
	Email      *string
}

// InsertAssociation creates the customer-contact row
// (AttachCustomerContactEndpoint.cs:61-62).
func (q *Queries) InsertAssociation(ctx context.Context, arg InsertAssociationParams) error {
	_, err := q.db.Exec(ctx, insertAssociation,
		arg.CustomerID,
		arg.ContactID,
		arg.Role,
		arg.Phone,
		arg.Email,
	)
	return err
}

const insertContact = `-- name: InsertContact :one
INSERT INTO customers.contacts (first_name, last_name, middle_name, prefix, suffix, phone, email, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::timestamptz)
RETURNING id, first_name, last_name, middle_name, prefix, suffix, phone, email, created_at
`

type InsertContactParams struct {
	FirstName  string
	LastName   string
	MiddleName *string
	Prefix     *string
	Suffix     *string
	Phone      *string
	Email      *string
	Now        time.Time
}

// InsertContact creates a contact row (CreateContactEndpoint.cs): every name
// part and connection detail has already been validated and normalized by
// the caller; a blank optional arrives here as NULL, never an empty string.
func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (CustomersContact, error) {
	row := q.db.QueryRow(ctx, insertContact,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Prefix,
		arg.Suffix,
		arg.Phone,
		arg.Email,
		arg.Now,
	)
	var i CustomersContact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Prefix,
		&i.Suffix,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listAssociationsForContact = `-- name: ListAssociationsForContact :many
SELECT customer_id, role, phone, email
FROM customers.customers_contacts
WHERE contact_id = $1
`

type ListAssociationsForContactRow struct {
	CustomerID int32
	Role       string
	Phone      *string
	Email      *string
}

// ListAssociationsForContact is DeleteContactEndpoint's cascade source
// (:29-32): every customer this contact is attached to, for the "removed"
// timeline event DeleteContact records against each one before the contact
// row (and its associations, via ON DELETE CASCADE) are deleted.
func (q *Queries) ListAssociationsForContact(ctx context.Context, contactID int32) ([]ListAssociationsForContactRow, error) {
	rows, err := q.db.Query(ctx, listAssociationsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssociationsForContactRow
	for rows.Next() {
		var i ListAssociationsForContactRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.Role,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactAssociationsForCustomer = `-- name: ListContactAssociationsForCustomer :many
SELECT c.id, c.first_name, c.last_name, c.middle_name, c.prefix, c.suffix,
       c.phone AS contact_phone, c.email AS contact_email,
       cc.role, cc.phone AS association_phone, cc.email AS association_email
FROM customers.customers_contacts cc
JOIN customers.contacts c ON c.id = cc.contact_id
WHERE cc.customer_id = $1
ORDER BY c.first_name, c.last_name, c.id
`

type ListContactAssociationsForCustomerRow struct {
	ID               int32
	FirstName        string
	LastName         string
	MiddleName       *string
	Prefix           *string
	Suffix           *string
	ContactPhone     *string
	ContactEmail     *string
	Role             string
	AssociationPhone *string
	AssociationEmail *string
}

// ListContactAssociationsForCustomer is GetCustomerContactsEndpoint's
// listing, sorted by the contact's name (GetCustomerContactsEndpoint.cs:29-36).
func (q *Queries) ListContactAssociationsForCustomer(ctx context.Context, customerID int32) ([]ListContactAssociationsForCustomerRow, error) {
	rows, err := q.db.Query(ctx, listContactAssociationsForCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactAssociationsForCustomerRow
	for rows.Next() {
		var i ListContactAssociationsForCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Prefix,
			&i.Suffix,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.Role,
			&i.AssociationPhone,
			&i.AssociationEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByID = `-- name: ListContactsByID :many
SELECT id, first_name, last_name, middle_name, prefix, suffix, phone, email, created_at
FROM customers.contacts
WHERE NOT EXISTS (
    SELECT 1 FROM unnest($1::text[]) AS p(pattern)
    WHERE NOT (
        first_name ILIKE p.pattern OR
        last_name ILIKE p.pattern OR
        (middle_name IS NOT NULL AND middle_name ILIKE p.pattern) OR
        (prefix IS NOT NULL AND prefix ILIKE p.pattern) OR
        (suffix IS NOT NULL AND suffix ILIKE p.pattern) OR
        (phone IS NOT NULL AND phone ILIKE p.pattern) OR
        (email IS NOT NULL AND email ILIKE p.pattern)
    )
)
ORDER BY
    CASE WHEN NOT $2::bool THEN id END ASC,
    CASE WHEN $2::bool THEN id END DESC
LIMIT $4::int OFFSET $3::int
`

type ListContactsByIDParams struct {
	Patterns   []string
	Descending bool
	RowOffset  int32
	PageSize   int32
}

// ListContactsByID is GetContacts's sortBy=id path, the same search
// predicate as CountContacts.
func (q *Queries) ListContactsByID(ctx context.Context, arg ListContactsByIDParams) ([]CustomersContact, error) {
	rows, err := q.db.Query(ctx, listContactsByID,
		arg.Patterns,
		arg.Descending,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomersContact
	for rows.Next() {
		var i CustomersContact
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Prefix,
			&i.Suffix,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByName = `-- name: ListContactsByName :many
SELECT id, first_name, last_name, middle_name, prefix, suffix, phone, email, created_at
FROM customers.contacts
WHERE NOT EXISTS (
    SELECT 1 FROM unnest($1::text[]) AS p(pattern)
    WHERE NOT (
        first_name ILIKE p.pattern OR
        last_name ILIKE p.pattern OR
        (middle_name IS NOT NULL AND middle_name ILIKE p.pattern) OR
        (prefix IS NOT NULL AND prefix ILIKE p.pattern) OR
        (suffix IS NOT NULL AND suffix ILIKE p.pattern) OR
        (phone IS NOT NULL AND phone ILIKE p.pattern) OR
        (email IS NOT NULL AND email ILIKE p.pattern)
    )
)
ORDER BY
    CASE WHEN NOT $2::bool THEN first_name END ASC,
    CASE WHEN $2::bool THEN first_name END DESC,
    CASE WHEN NOT $2::bool THEN last_name END ASC,
    CASE WHEN $2::bool THEN last_name END DESC,
    CASE WHEN NOT $2::bool THEN id END ASC,
    CASE WHEN $2::bool THEN id END DESC
LIMIT $4::int OFFSET $3::int
`

type ListContactsByNameParams struct {
	Patterns   []string
	Descending bool
	RowOffset  int32
	PageSize   int32
}

// ListContactsByName is GetContacts's default sort: first name, then last
// name, then id as the tie-break (GetContactsEndpoint.cs:147-157).
func (q *Queries) ListContactsByName(ctx context.Context, arg ListContactsByNameParams) ([]CustomersContact, error) {
	rows, err := q.db.Query(ctx, listContactsByName,
		arg.Patterns,
		arg.Descending,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomersContact
	for rows.Next() {
		var i CustomersContact
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Prefix,
			&i.Suffix,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerAssociationsForContact = `-- name: ListCustomerAssociationsForContact :many
SELECT cu.id, cu.customer_number, cu.name, cc.role, cc.phone, cc.email
FROM customers.customers_contacts cc
JOIN customers.customers cu ON cu.id = cc.customer_id
WHERE cc.contact_id = $1
ORDER BY cu.name, cu.id
`

type ListCustomerAssociationsForContactRow struct {
	ID             int32
	CustomerNumber int64
	Name           string
	Role           string
	Phone          *string
	Email          *string
}

// ListCustomerAssociationsForContact is GetContactCustomersEndpoint's
// listing, sorted by the customer's name (GetContactCustomersEndpoint.cs:29-33).
func (q *Queries) ListCustomerAssociationsForContact(ctx context.Context, contactID int32) ([]ListCustomerAssociationsForContactRow, error) {
	rows, err := q.db.Query(ctx, listCustomerAssociationsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerAssociationsForContactRow
	for rows.Next() {
		var i ListCustomerAssociationsForContactRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerNumber,
			&i.Name,
			&i.Role,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssociation = `-- name: UpdateAssociation :exec
UPDATE customers.customers_contacts
SET role = $1, phone = $2, email = $3
WHERE customer_id = $4 AND contact_id = $5
`

type UpdateAssociationParams struct {
	Role       string
	Phone      *string
	Email      *string
	CustomerID int32
	ContactID  int32
}

// UpdateAssociation applies PUT .../contacts/{contactId}'s validated fields
// (UpdateCustomerContactEndpoint.cs:38-50); whether the caller also records a
// timeline event is decided by comparing the row this statement replaces
// against the new values, not by this statement itself.
func (q *Queries) UpdateAssociation(ctx context.Context, arg UpdateAssociationParams) error {
	_, err := q.db.Exec(ctx, updateAssociation,
		arg.Role,
		arg.Phone,
		arg.Email,
		arg.CustomerID,
		arg.ContactID,
	)
	return err
}

const updateContact = `-- name: UpdateContact :one
UPDATE customers.contacts
SET first_name = $1, last_name = $2, middle_name = $3,
    prefix = $4, suffix = $5, phone = $6, email = $7
WHERE id = $8
RETURNING id, first_name, last_name, middle_name, prefix, suffix, phone, email, created_at
`

type UpdateContactParams struct {
	FirstName  string
	LastName   string
	MiddleName *string
	Prefix     *string
	Suffix     *string
	Phone      *string
	Email      *string
	ID         int32
}

// UpdateContact is UpdateContactEndpoint's full replace: ContactRequest
// carries the desired final state of every field, so this always overwrites
// every optional column rather than preserving what the request omitted.
// Zero rows affected (id not found) surfaces to the caller as pgx.ErrNoRows,
// the endpoint's 404.
func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (CustomersContact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Prefix,
		arg.Suffix,
		arg.Phone,
		arg.Email,
		arg.ID,
	)
	var i CustomersContact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Prefix,
		&i.Suffix,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
