// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CustomersContact struct {
	ID         int32
	FirstName  string
	LastName   string
	MiddleName *string
	Prefix     *string
	Suffix     *string
	Phone      *string
	Email      *string
	CreatedAt  time.Time
}

type CustomersCounter struct {
	CounterName string
	NextValue   int64
}

type CustomersCustomer struct {
	ID             int32
	CustomerNumber int64
	Name           string
	Status         string
	LegalCountry   *string
	LegalID        *string
	LegalName      *string
	LegalSource    *string
	LegalType      *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Type           string
}

type CustomersCustomersContact struct {
	CustomerID int32
	ContactID  int32
	Role       string
	Phone      *string
	Email      *string
}

type CustomersCustomersTimelineEntriesRevision struct {
	ID                      int32
	CustomerTimelineEntryID int32
	RevisionNumber          int32
	CustomerID              int32
	Provenance              string
	Producer                string
	EventType               string
	OccurredOn              pgtype.Date
	OccurredAt              *time.Time
	Summary                 string
	Note                    *string
	SourceUrl               *string
	PayloadJson             []byte
	PayloadVersion          int32
	CurrentRevision         int32
	State                   string
	ActorKind               string
	ActorDisplay            string
	CreatedAt               time.Time
	UpdatedAt               time.Time
	DeletedAt               *time.Time
}

type CustomersCustomersTimelineEntry struct {
	ID              int32
	CustomerID      int32
	Provenance      string
	Producer        string
	EventType       string
	OccurredOn      pgtype.Date
	OccurredAt      *time.Time
	Summary         string
	Note            *string
	SourceUrl       *string
	PayloadJson     []byte
	PayloadVersion  int32
	CurrentRevision int32
	State           string
	ActorKind       string
	ActorDisplay    string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}
