// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCustomerRegistryRecord = `-- name: DeleteCustomerRegistryRecord :exec
DELETE FROM customers.customer_registry_records
WHERE customer_id = $1
`

// DeleteCustomerRegistryRecord is what a 410 from the registry means
// (design D2): the entity is gone from open data entirely, so the copy goes
// too and only the timeline keeps the fact that it once existed. Deleting a
// row that is not there is not an error — a customer whose very first
// refresh answers 410 never had one.
func (q *Queries) DeleteCustomerRegistryRecord(ctx context.Context, customerID int32) error {
	_, err := q.db.Exec(ctx, deleteCustomerRegistryRecord, customerID)
	return err
}

const getCustomerRegistryRecord = `-- name: GetCustomerRegistryRecord :one
SELECT customer_id, organisation_number, name, organisation_form_code, organisation_form,
       industry_code, industry, employees, vat_registered, bankrupt, under_liquidation,
       under_forced_liquidation, deleted_on, founded_on, website, email, phone, mobile,
       parent_organisation_number, business_address, postal_address, fetched_at, registry_updated_hint
FROM customers.customer_registry_records
WHERE customer_id = $1
`

// GetCustomerRegistryRecord is GET .../registry-record's own read (Brreg in
// full design D1, D2): unlocked, since that path never writes. pgx.ErrNoRows
// means "never fetched", not an error — the endpoint answers 204 for it.
func (q *Queries) GetCustomerRegistryRecord(ctx context.Context, customerID int32) (CustomersCustomerRegistryRecord, error) {
	row := q.db.QueryRow(ctx, getCustomerRegistryRecord, customerID)
	var i CustomersCustomerRegistryRecord
	err := row.Scan(
		&i.CustomerID,
		&i.OrganisationNumber,
		&i.Name,
		&i.OrganisationFormCode,
		&i.OrganisationForm,
		&i.IndustryCode,
		&i.Industry,
		&i.Employees,
		&i.VatRegistered,
		&i.Bankrupt,
		&i.UnderLiquidation,
		&i.UnderForcedLiquidation,
		&i.DeletedOn,
		&i.FoundedOn,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.ParentOrganisationNumber,
		&i.BusinessAddress,
		&i.PostalAddress,
		&i.FetchedAt,
		&i.RegistryUpdatedHint,
	)
	return i, err
}

const getCustomerRegistryRecordForUpdate = `-- name: GetCustomerRegistryRecordForUpdate :one
SELECT customer_id, organisation_number, name, organisation_form_code, organisation_form,
       industry_code, industry, employees, vat_registered, bankrupt, under_liquidation,
       under_forced_liquidation, deleted_on, founded_on, website, email, phone, mobile,
       parent_organisation_number, business_address, postal_address, fetched_at, registry_updated_hint
FROM customers.customer_registry_records
WHERE customer_id = $1
FOR UPDATE
`

// GetCustomerRegistryRecordForUpdate is the read a refresh makes inside the
// transaction that also writes the row (design D2, D4): the FOR UPDATE lock,
// the same shape GetCustomerPeppolLookupForUpdate gives peppol_lookup.go,
// serializes two concurrent refreshes of the same customer so neither
// diffs against a before-state the other has already overtaken.
// pgx.ErrNoRows means "first fetch ever" — the handler then compares the
// registry's name with the legal identity's, and nothing else.
func (q *Queries) GetCustomerRegistryRecordForUpdate(ctx context.Context, customerID int32) (CustomersCustomerRegistryRecord, error) {
	row := q.db.QueryRow(ctx, getCustomerRegistryRecordForUpdate, customerID)
	var i CustomersCustomerRegistryRecord
	err := row.Scan(
		&i.CustomerID,
		&i.OrganisationNumber,
		&i.Name,
		&i.OrganisationFormCode,
		&i.OrganisationForm,
		&i.IndustryCode,
		&i.Industry,
		&i.Employees,
		&i.VatRegistered,
		&i.Bankrupt,
		&i.UnderLiquidation,
		&i.UnderForcedLiquidation,
		&i.DeletedOn,
		&i.FoundedOn,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.ParentOrganisationNumber,
		&i.BusinessAddress,
		&i.PostalAddress,
		&i.FetchedAt,
		&i.RegistryUpdatedHint,
	)
	return i, err
}

const upsertCustomerRegistryRecord = `-- name: UpsertCustomerRegistryRecord :exec
INSERT INTO customers.customer_registry_records (
    customer_id, organisation_number, name, organisation_form_code, organisation_form,
    industry_code, industry, employees, vat_registered, bankrupt, under_liquidation,
    under_forced_liquidation, deleted_on, founded_on, website, email, phone, mobile,
    parent_organisation_number, business_address, postal_address, fetched_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22::timestamptz
)
ON CONFLICT (customer_id) DO UPDATE SET
    organisation_number        = EXCLUDED.organisation_number,
    name                       = EXCLUDED.name,
    organisation_form_code     = EXCLUDED.organisation_form_code,
    organisation_form          = EXCLUDED.organisation_form,
    industry_code              = EXCLUDED.industry_code,
    industry                   = EXCLUDED.industry,
    employees                  = EXCLUDED.employees,
    vat_registered             = EXCLUDED.vat_registered,
    bankrupt                   = EXCLUDED.bankrupt,
    under_liquidation          = EXCLUDED.under_liquidation,
    under_forced_liquidation   = EXCLUDED.under_forced_liquidation,
    deleted_on                 = EXCLUDED.deleted_on,
    founded_on                 = EXCLUDED.founded_on,
    website                    = EXCLUDED.website,
    email                      = EXCLUDED.email,
    phone                      = EXCLUDED.phone,
    mobile                     = EXCLUDED.mobile,
    parent_organisation_number = EXCLUDED.parent_organisation_number,
    business_address           = EXCLUDED.business_address,
    postal_address             = EXCLUDED.postal_address,
    fetched_at                 = EXCLUDED.fetched_at
`

type UpsertCustomerRegistryRecordParams struct {
	CustomerID               int32
	OrganisationNumber       string
	Name                     string
	OrganisationFormCode     *string
	OrganisationForm         *string
	IndustryCode             *string
	Industry                 *string
	Employees                *int32
	VatRegistered            bool
	Bankrupt                 bool
	UnderLiquidation         bool
	UnderForcedLiquidation   bool
	DeletedOn                pgtype.Date
	FoundedOn                pgtype.Date
	Website                  *string
	Email                    *string
	Phone                    *string
	Mobile                   *string
	ParentOrganisationNumber *string
	BusinessAddress          []byte
	PostalAddress            []byte
	FetchedAt                time.Time
}

// UpsertCustomerRegistryRecord writes what the registry just said (design
// D1): one row per customer, so a refresh always overwrites the last record
// rather than growing a history — the timeline keeps the history, as the
// registry.change events. Never touches customers.customers, so a fetch can
// never bump the customer row's own revision.
//
// registry_updated_hint is deliberately absent from both the insert and the
// update: delivery B's update-feed worker owns that column, and a fetch made
// here must neither invent a hint nor erase the one the worker left.
func (q *Queries) UpsertCustomerRegistryRecord(ctx context.Context, arg UpsertCustomerRegistryRecordParams) error {
	_, err := q.db.Exec(ctx, upsertCustomerRegistryRecord,
		arg.CustomerID,
		arg.OrganisationNumber,
		arg.Name,
		arg.OrganisationFormCode,
		arg.OrganisationForm,
		arg.IndustryCode,
		arg.Industry,
		arg.Employees,
		arg.VatRegistered,
		arg.Bankrupt,
		arg.UnderLiquidation,
		arg.UnderForcedLiquidation,
		arg.DeletedOn,
		arg.FoundedOn,
		arg.Website,
		arg.Email,
		arg.Phone,
		arg.Mobile,
		arg.ParentOrganisationNumber,
		arg.BusinessAddress,
		arg.PostalAddress,
		arg.FetchedAt,
	)
	return err
}
