package identity_test

import (
	"os"
	"testing"

	"github.com/vantigo-io/vantigo/server/internal/openapi/contracttest"
)

// pendingOperations are the identity operations still stubbed in
// unimplemented.go (TestPendingOperationsAreExactlyTheStubs keeps the two
// lists equal). The coverage gate excuses them; each area removes the
// operations it implements, and an entry a successful exchange exercised
// fails the run. The list was generated from the contract's operationIds;
// it goes away once every operation is implemented.
var pendingOperations = []string{
	"deleteIdentityAccessGroupsByGroupIdMembersByUserId",
	"deleteIdentityAccessGroupsByGroupIdRoleMappingsByRoleId",
	"deleteIdentityAccessGroupsById",
	"deleteIdentityAccessRolesById",
	"deleteIdentityAccountAvatar",
	"deleteIdentityAccountPasskeysByCredentialId",
	"deleteIdentityOwnerUsersById",
	"deleteIdentityScimV2GroupsById",
	"deleteIdentityScimV2UsersById",
	"getIdentityAccessAudit",
	"getIdentityAccessCatalog",
	"getIdentityAccessDelegations",
	"getIdentityAccessGroups",
	"getIdentityAccessGroupsById",
	"getIdentityAccessMe",
	"getIdentityAccessRoles",
	"getIdentityAccessUsers",
	"getIdentityAccessUsersById",
	"getIdentityAccount",
	"getIdentityAccountAvatar",
	"getIdentityAccountMfa",
	"getIdentityAccountMfaSetup",
	"getIdentityAccountPasskeys",
	"getIdentityInvitationsValidate",
	"getIdentityOidcCallback",
	"getIdentityOidcChallenge",
	"getIdentityOidcComplete",
	"getIdentityOwnerInvitations",
	"getIdentityOwnerMfa",
	"getIdentityOwnerMfaSetup",
	"getIdentityOwnerSystemStatus",
	"getIdentityOwnerUsers",
	"getIdentityOwnerUsersByIdAvatar",
	"getIdentityScimV2Groups",
	"getIdentityScimV2GroupsById",
	"getIdentityScimV2ResourceTypes",
	"getIdentityScimV2Schemas",
	"getIdentityScimV2ServiceProviderConfig",
	"getIdentityScimV2Users",
	"getIdentityScimV2UsersById",
	"getIdentitySystemStatus",
	"patchIdentityAccountProfile",
	"patchIdentityScimV2GroupsById",
	"patchIdentityScimV2UsersById",
	"postIdentityAccessDelegations",
	"postIdentityAccessDelegationsByIdRevoke",
	"postIdentityAccessGroups",
	"postIdentityAccessGroupsByGroupIdMembersByUserId",
	"postIdentityAccessGroupsByGroupIdRoleMappingsByRoleId",
	"postIdentityAccessRoles",
	"postIdentityAccountAvatar",
	"postIdentityAccountMfaDisable",
	"postIdentityAccountMfaEnable",
	"postIdentityAccountMfaRecoveryCodes",
	"postIdentityAccountMfaSetup",
	"postIdentityAccountPasskeysBegin",
	"postIdentityAccountPasskeysComplete",
	"postIdentityAccountPassword",
	"postIdentityInvitationsAccept",
	"postIdentityLogin2fa",
	"postIdentityOidcCallback",
	"postIdentityOwnerInvitations",
	"postIdentityOwnerInvitationsByIdResend",
	"postIdentityOwnerInvitationsByIdRevoke",
	"postIdentityOwnerMfaDisable",
	"postIdentityOwnerMfaEnable",
	"postIdentityOwnerMfaRecoveryCodes",
	"postIdentityOwnerMfaResetByUserId",
	"postIdentityOwnerMfaSetup",
	"postIdentityOwnerUsers",
	"postIdentityOwnerUsersByIdDisable",
	"postIdentityOwnerUsersByIdEnable",
	"postIdentityOwnerUsersByIdPassword",
	"postIdentityOwnerUsersByIdPasswordReset",
	"postIdentityPasskeysLoginBegin",
	"postIdentityPasskeysLoginComplete",
	"postIdentityPasswordRecoveryRequest",
	"postIdentityPasswordRecoveryReset",
	"postIdentityScimV2Groups",
	"postIdentityScimV2Users",
	"putIdentityAccessDelegationsById",
	"putIdentityAccessGroupsByGroupIdMembersByUserId",
	"putIdentityAccessGroupsByGroupIdRoleMappingsByRoleId",
	"putIdentityAccessGroupsById",
	"putIdentityAccessRolesById",
	"putIdentityAccessRolesByIdPermissions",
	"putIdentityAccessUsersByIdRoles",
	"putIdentityAccount",
	"putIdentityAccountAvatar",
	"putIdentityAccountProfile",
	"putIdentityOwnerUsersById",
	"putIdentityScimV2UsersById",
	"putIdentitySystemMaintenance",
}

func TestMain(m *testing.M) {
	os.Exit(contracttest.RequireCoverage(m, recorder, pendingOperations...))
}
