// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credits.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const copyLinesToCredit = `-- name: CopyLinesToCredit :exec
INSERT INTO invoices.lines (
    invoice_id, position, description, quantity, unit, unit_price, discount_percent, vat_code_id,
    credits_line_id, line_gross, line_allowance, line_net
)
SELECT $1::bigint, src.position, src.description, src.quantity, src.unit, src.unit_price,
       src.discount_percent, src.vat_code_id, src.id, src.line_gross, src.line_allowance, src.line_net
FROM invoices.lines src
WHERE src.invoice_id = $2::bigint AND src.quantity > 0
ORDER BY src.position
`

type CopyLinesToCreditParams struct {
	CreditID   int64
	OriginalID int64
}

// CopyLinesToCredit copies every line of the original onto its credit-note
// draft, each pointing at the line it credits (D8). The VAT snapshot is the
// credit note's issue's to write, from the original line's.
func (q *Queries) CopyLinesToCredit(ctx context.Context, arg CopyLinesToCreditParams) error {
	_, err := q.db.Exec(ctx, copyLinesToCredit, arg.CreditID, arg.OriginalID)
	return err
}

const creditNotesOf = `-- name: CreditNotesOf :many
SELECT id, number, issue_date, gross_total, status FROM invoices.invoices
WHERE credits_invoice_id = $1
ORDER BY id
`

type CreditNotesOfRow struct {
	ID         int64
	Number     *int64
	IssueDate  pgtype.Date
	GrossTotal pgtype.Numeric
	Status     string
}

// CreditNotesOf is every credit note of an invoice, drafts included, the
// oldest first.
func (q *Queries) CreditNotesOf(ctx context.Context, originalID *int64) ([]CreditNotesOfRow, error) {
	rows, err := q.db.Query(ctx, creditNotesOf, originalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditNotesOfRow
	for rows.Next() {
		var i CreditNotesOfRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.IssueDate,
			&i.GrossTotal,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const creditedGross = `-- name: CreditedGross :one
SELECT coalesce(sum(gross_total), 0)::numeric(14,2) AS credited FROM invoices.invoices
WHERE credits_invoice_id = $1 AND status = 'issued'
`

// CreditedGross is what an invoice's issued credit notes credit, gross.
func (q *Queries) CreditedGross(ctx context.Context, originalID *int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, creditedGross, originalID)
	var credited pgtype.Numeric
	err := row.Scan(&credited)
	return credited, err
}

const creditedPerLine = `-- name: CreditedPerLine :many
SELECT l.credits_line_id::bigint AS line_id,
       sum(l.quantity)::numeric(14,3) AS quantity,
       sum(l.line_net)::numeric(14,2) AS net,
       sum(l.line_gross)::numeric(14,2) AS gross,
       sum(l.line_allowance)::numeric(14,2) AS allowance,
       bool_and(l.unit_price = o.unit_price AND l.discount_percent = o.discount_percent)::boolean AS returns
FROM invoices.lines l
JOIN invoices.invoices c ON c.id = l.invoice_id
JOIN invoices.lines o ON o.id = l.credits_line_id
WHERE c.credits_invoice_id = $1 AND c.status = 'issued' AND l.credits_line_id IS NOT NULL
GROUP BY l.credits_line_id
`

type CreditedPerLineRow struct {
	LineID    int64
	Quantity  pgtype.Numeric
	Net       pgtype.Numeric
	Gross     pgtype.Numeric
	Allowance pgtype.Numeric
	Returns   bool
}

// CreditedPerLine is, per line of an invoice, what its issued credit notes
// credit: the quantity and the net the per-line cap is judged against (D8),
// the gross and the allowance a final credit note's line takes the rest of,
// and whether every one of them was a return at the line's own price and
// discount — only then are the rest's øre rounding, and the final note's.
func (q *Queries) CreditedPerLine(ctx context.Context, originalID *int64) ([]CreditedPerLineRow, error) {
	rows, err := q.db.Query(ctx, creditedPerLine, originalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditedPerLineRow
	for rows.Next() {
		var i CreditedPerLineRow
		if err := rows.Scan(
			&i.LineID,
			&i.Quantity,
			&i.Net,
			&i.Gross,
			&i.Allowance,
			&i.Returns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const creditedVatPerRate = `-- name: CreditedVatPerRate :many
SELECT s.vat_category, s.rate_percent,
       sum(s.vat_amount)::numeric(14,2) AS vat,
       sum(s.vat_amount_nok)::numeric(14,2) AS vat_nok
FROM invoices.vat_summaries s
JOIN invoices.invoices c ON c.id = s.invoice_id
WHERE c.credits_invoice_id = $1 AND c.status = 'issued'
GROUP BY s.vat_category, s.rate_percent
`

type CreditedVatPerRateRow struct {
	VatCategory string
	RatePercent pgtype.Numeric
	Vat         pgtype.Numeric
	VatNok      pgtype.Numeric
}

// CreditedVatPerRate is, per (category, rate) row of an invoice, the VAT its
// issued credit notes reversed: what a final credit note takes from the
// original's row, so the credits sum to what was charged, øre for øre (D8).
func (q *Queries) CreditedVatPerRate(ctx context.Context, originalID *int64) ([]CreditedVatPerRateRow, error) {
	rows, err := q.db.Query(ctx, creditedVatPerRate, originalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditedVatPerRateRow
	for rows.Next() {
		var i CreditedVatPerRateRow
		if err := rows.Scan(
			&i.VatCategory,
			&i.RatePercent,
			&i.Vat,
			&i.VatNok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCreditDraft = `-- name: InsertCreditDraft :one
INSERT INTO invoices.invoices (
    kind, customer_id, credits_invoice_id, delivery_date, delivery_from, delivery_to,
    delivery_address_line1, delivery_address_line2, delivery_postal_code, delivery_city, delivery_country,
    currency, exchange_rate, exchange_rate_date, your_reference, our_reference, order_reference,
    buyer_customer_number, buyer_type, buyer_name, buyer_organisation_number, buyer_foreign_id,
    buyer_address_line1, buyer_address_line2, buyer_postal_code, buyer_city, buyer_region, buyer_country,
    buyer_peppol_id, buyer_gln, buyer_language,
    net_total, vat_total, gross_total, vat_total_nok, created_by_user_id, created_at, updated_at
)
SELECT
    'credit_note', o.customer_id, o.id, o.delivery_date, o.delivery_from, o.delivery_to,
    o.delivery_address_line1, o.delivery_address_line2, o.delivery_postal_code, o.delivery_city, o.delivery_country,
    o.currency, o.exchange_rate, o.exchange_rate_date, o.your_reference, o.our_reference, o.order_reference,
    o.buyer_customer_number, o.buyer_type, o.buyer_name, o.buyer_organisation_number, o.buyer_foreign_id,
    o.buyer_address_line1, o.buyer_address_line2, o.buyer_postal_code, o.buyer_city, o.buyer_region, o.buyer_country,
    o.buyer_peppol_id, o.buyer_gln, o.buyer_language,
    o.net_total, o.vat_total, o.gross_total, o.vat_total_nok, $1, $2::timestamptz, $2::timestamptz
FROM invoices.invoices o
WHERE o.id = $3 AND o.kind = 'invoice' AND o.status = 'issued'
RETURNING id, kind, status, number, customer_id, credits_invoice_id, issue_date, delivery_date, delivery_from, delivery_to, delivery_address_line1, delivery_address_line2, delivery_postal_code, delivery_city, delivery_country, payment_terms_days, due_date, currency, exchange_rate, exchange_rate_date, your_reference, our_reference, order_reference, note, internal_note, buyer_customer_number, buyer_type, buyer_name, buyer_organisation_number, buyer_foreign_id, buyer_address_line1, buyer_address_line2, buyer_postal_code, buyer_city, buyer_region, buyer_country, buyer_peppol_id, buyer_gln, buyer_language, seller_legal_name, seller_organisation_number, seller_vat_registered, seller_in_foretaksregisteret, seller_address_line1, seller_address_line2, seller_postal_code, seller_city, seller_country, seller_bank_account, seller_iban, seller_bic, seller_email, seller_footer_text, net_total, vat_total, gross_total, vat_total_nok, pdf_object_key, pdf_sha256, issued_at, issued_by_user_id, created_by_user_id, created_at, updated_at, revision, kid, kid_algorithm
`

type InsertCreditDraftParams struct {
	CreatedByUserID uuid.UUID
	Now             time.Time
	OriginalID      int64
}

// InsertCreditDraft writes a credit-note draft for an issued invoice (D8),
// copying what the correction must name: the customer, the currency, the rate
// and the date it was taken on, the delivery and its place, the references,
// and the buyer snapshot. It reads no directory: the original's snapshot is
// what the correction names, an anonymised customer's included.
func (q *Queries) InsertCreditDraft(ctx context.Context, arg InsertCreditDraftParams) (InvoicesInvoice, error) {
	row := q.db.QueryRow(ctx, insertCreditDraft, arg.CreatedByUserID, arg.Now, arg.OriginalID)
	var i InvoicesInvoice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Number,
		&i.CustomerID,
		&i.CreditsInvoiceID,
		&i.IssueDate,
		&i.DeliveryDate,
		&i.DeliveryFrom,
		&i.DeliveryTo,
		&i.DeliveryAddressLine1,
		&i.DeliveryAddressLine2,
		&i.DeliveryPostalCode,
		&i.DeliveryCity,
		&i.DeliveryCountry,
		&i.PaymentTermsDays,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.YourReference,
		&i.OurReference,
		&i.OrderReference,
		&i.Note,
		&i.InternalNote,
		&i.BuyerCustomerNumber,
		&i.BuyerType,
		&i.BuyerName,
		&i.BuyerOrganisationNumber,
		&i.BuyerForeignID,
		&i.BuyerAddressLine1,
		&i.BuyerAddressLine2,
		&i.BuyerPostalCode,
		&i.BuyerCity,
		&i.BuyerRegion,
		&i.BuyerCountry,
		&i.BuyerPeppolID,
		&i.BuyerGln,
		&i.BuyerLanguage,
		&i.SellerLegalName,
		&i.SellerOrganisationNumber,
		&i.SellerVatRegistered,
		&i.SellerInForetaksregisteret,
		&i.SellerAddressLine1,
		&i.SellerAddressLine2,
		&i.SellerPostalCode,
		&i.SellerCity,
		&i.SellerCountry,
		&i.SellerBankAccount,
		&i.SellerIban,
		&i.SellerBic,
		&i.SellerEmail,
		&i.SellerFooterText,
		&i.NetTotal,
		&i.VatTotal,
		&i.GrossTotal,
		&i.VatTotalNok,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.IssuedAt,
		&i.IssuedByUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.Kid,
		&i.KidAlgorithm,
	)
	return i, err
}

const squareCreditLine = `-- name: SquareCreditLine :exec
UPDATE invoices.lines SET
    line_gross = $1,
    line_allowance = $2,
    line_net = $3
WHERE id = $4
`

type SquareCreditLineParams struct {
	LineGross     pgtype.Numeric
	LineAllowance pgtype.Numeric
	LineNet       pgtype.Numeric
	ID            int64
}

// SquareCreditLine gives a credit note's line that returns its original line's
// last unit what that line has left — gross, allowance and net — in place of
// its own rounding (D8). It runs while the credit note is still a draft; the
// trigger refuses it afterwards.
func (q *Queries) SquareCreditLine(ctx context.Context, arg SquareCreditLineParams) error {
	_, err := q.db.Exec(ctx, squareCreditLine,
		arg.LineGross,
		arg.LineAllowance,
		arg.LineNet,
		arg.ID,
	)
	return err
}
