// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoices = `-- name: CountInvoices :one
SELECT count(*)::int FROM invoices.invoices
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR kind = $2::text)
  AND ($3::int IS NULL OR customer_id = $3::int)
  AND (($4::bigint IS NULL AND $5::text IS NULL)
       OR number = $4::bigint
       OR buyer_name ILIKE $5::text)
  AND ($6::date IS NULL OR issue_date >= $6::date)
  AND ($7::date IS NULL OR issue_date <= $7::date)
`

type CountInvoicesParams struct {
	Status        *string
	Kind          *string
	CustomerID    *int32
	SearchNumber  *int64
	SearchPattern *string
	IssuedFrom    pgtype.Date
	IssuedTo      pgtype.Date
}

// CountInvoices is ListInvoices' total, over the same filters.
func (q *Queries) CountInvoices(ctx context.Context, arg CountInvoicesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countInvoices,
		arg.Status,
		arg.Kind,
		arg.CustomerID,
		arg.SearchNumber,
		arg.SearchPattern,
		arg.IssuedFrom,
		arg.IssuedTo,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteDraft = `-- name: DeleteDraft :execrows
DELETE FROM invoices.invoices WHERE id = $1 AND status = 'draft'
`

// DeleteDraft removes a draft and, by the cascade, its lines. An issued
// document is never matched; the trigger would refuse it anyway (D9).
func (q *Queries) DeleteDraft(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraft, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, kind, status, number, customer_id, credits_invoice_id, issue_date, delivery_date, delivery_from, delivery_to, delivery_address_line1, delivery_address_line2, delivery_postal_code, delivery_city, delivery_country, payment_terms_days, due_date, currency, exchange_rate, exchange_rate_date, your_reference, our_reference, order_reference, note, internal_note, buyer_customer_number, buyer_type, buyer_name, buyer_organisation_number, buyer_foreign_id, buyer_address_line1, buyer_address_line2, buyer_postal_code, buyer_city, buyer_region, buyer_country, buyer_peppol_id, buyer_gln, buyer_language, seller_legal_name, seller_organisation_number, seller_vat_registered, seller_in_foretaksregisteret, seller_address_line1, seller_address_line2, seller_postal_code, seller_city, seller_country, seller_bank_account, seller_iban, seller_bic, seller_email, seller_footer_text, net_total, vat_total, gross_total, vat_total_nok, pdf_object_key, pdf_sha256, issued_at, issued_by_user_id, created_by_user_id, created_at, updated_at, revision FROM invoices.invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id int64) (InvoicesInvoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i InvoicesInvoice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Number,
		&i.CustomerID,
		&i.CreditsInvoiceID,
		&i.IssueDate,
		&i.DeliveryDate,
		&i.DeliveryFrom,
		&i.DeliveryTo,
		&i.DeliveryAddressLine1,
		&i.DeliveryAddressLine2,
		&i.DeliveryPostalCode,
		&i.DeliveryCity,
		&i.DeliveryCountry,
		&i.PaymentTermsDays,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.YourReference,
		&i.OurReference,
		&i.OrderReference,
		&i.Note,
		&i.InternalNote,
		&i.BuyerCustomerNumber,
		&i.BuyerType,
		&i.BuyerName,
		&i.BuyerOrganisationNumber,
		&i.BuyerForeignID,
		&i.BuyerAddressLine1,
		&i.BuyerAddressLine2,
		&i.BuyerPostalCode,
		&i.BuyerCity,
		&i.BuyerRegion,
		&i.BuyerCountry,
		&i.BuyerPeppolID,
		&i.BuyerGln,
		&i.BuyerLanguage,
		&i.SellerLegalName,
		&i.SellerOrganisationNumber,
		&i.SellerVatRegistered,
		&i.SellerInForetaksregisteret,
		&i.SellerAddressLine1,
		&i.SellerAddressLine2,
		&i.SellerPostalCode,
		&i.SellerCity,
		&i.SellerCountry,
		&i.SellerBankAccount,
		&i.SellerIban,
		&i.SellerBic,
		&i.SellerEmail,
		&i.SellerFooterText,
		&i.NetTotal,
		&i.VatTotal,
		&i.GrossTotal,
		&i.VatTotalNok,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.IssuedAt,
		&i.IssuedByUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const insertInvoiceDraft = `-- name: InsertInvoiceDraft :one
INSERT INTO invoices.invoices (
    kind, customer_id, delivery_date, delivery_from, delivery_to,
    delivery_address_line1, delivery_address_line2, delivery_postal_code, delivery_city, delivery_country,
    payment_terms_days, currency, your_reference, our_reference, order_reference, note, internal_note,
    net_total, vat_total, gross_total, vat_total_nok, created_by_user_id, created_at, updated_at
) VALUES (
    'invoice', $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22::timestamptz, $22::timestamptz
)
RETURNING id, kind, status, number, customer_id, credits_invoice_id, issue_date, delivery_date, delivery_from, delivery_to, delivery_address_line1, delivery_address_line2, delivery_postal_code, delivery_city, delivery_country, payment_terms_days, due_date, currency, exchange_rate, exchange_rate_date, your_reference, our_reference, order_reference, note, internal_note, buyer_customer_number, buyer_type, buyer_name, buyer_organisation_number, buyer_foreign_id, buyer_address_line1, buyer_address_line2, buyer_postal_code, buyer_city, buyer_region, buyer_country, buyer_peppol_id, buyer_gln, buyer_language, seller_legal_name, seller_organisation_number, seller_vat_registered, seller_in_foretaksregisteret, seller_address_line1, seller_address_line2, seller_postal_code, seller_city, seller_country, seller_bank_account, seller_iban, seller_bic, seller_email, seller_footer_text, net_total, vat_total, gross_total, vat_total_nok, pdf_object_key, pdf_sha256, issued_at, issued_by_user_id, created_by_user_id, created_at, updated_at, revision
`

type InsertInvoiceDraftParams struct {
	CustomerID           int32
	DeliveryDate         pgtype.Date
	DeliveryFrom         pgtype.Date
	DeliveryTo           pgtype.Date
	DeliveryAddressLine1 *string
	DeliveryAddressLine2 *string
	DeliveryPostalCode   *string
	DeliveryCity         *string
	DeliveryCountry      *string
	PaymentTermsDays     *int32
	Currency             string
	YourReference        string
	OurReference         string
	OrderReference       string
	Note                 string
	InternalNote         string
	NetTotal             pgtype.Numeric
	VatTotal             pgtype.Numeric
	GrossTotal           pgtype.Numeric
	VatTotalNok          pgtype.Numeric
	CreatedByUserID      uuid.UUID
	Now                  time.Time
}

// InsertInvoiceDraft writes an invoice draft (D4). It has no number, no issue
// date and no snapshots; its totals are the ones computed with today's rates,
// which the issue computes again for the issue date.
func (q *Queries) InsertInvoiceDraft(ctx context.Context, arg InsertInvoiceDraftParams) (InvoicesInvoice, error) {
	row := q.db.QueryRow(ctx, insertInvoiceDraft,
		arg.CustomerID,
		arg.DeliveryDate,
		arg.DeliveryFrom,
		arg.DeliveryTo,
		arg.DeliveryAddressLine1,
		arg.DeliveryAddressLine2,
		arg.DeliveryPostalCode,
		arg.DeliveryCity,
		arg.DeliveryCountry,
		arg.PaymentTermsDays,
		arg.Currency,
		arg.YourReference,
		arg.OurReference,
		arg.OrderReference,
		arg.Note,
		arg.InternalNote,
		arg.NetTotal,
		arg.VatTotal,
		arg.GrossTotal,
		arg.VatTotalNok,
		arg.CreatedByUserID,
		arg.Now,
	)
	var i InvoicesInvoice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Number,
		&i.CustomerID,
		&i.CreditsInvoiceID,
		&i.IssueDate,
		&i.DeliveryDate,
		&i.DeliveryFrom,
		&i.DeliveryTo,
		&i.DeliveryAddressLine1,
		&i.DeliveryAddressLine2,
		&i.DeliveryPostalCode,
		&i.DeliveryCity,
		&i.DeliveryCountry,
		&i.PaymentTermsDays,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.YourReference,
		&i.OurReference,
		&i.OrderReference,
		&i.Note,
		&i.InternalNote,
		&i.BuyerCustomerNumber,
		&i.BuyerType,
		&i.BuyerName,
		&i.BuyerOrganisationNumber,
		&i.BuyerForeignID,
		&i.BuyerAddressLine1,
		&i.BuyerAddressLine2,
		&i.BuyerPostalCode,
		&i.BuyerCity,
		&i.BuyerRegion,
		&i.BuyerCountry,
		&i.BuyerPeppolID,
		&i.BuyerGln,
		&i.BuyerLanguage,
		&i.SellerLegalName,
		&i.SellerOrganisationNumber,
		&i.SellerVatRegistered,
		&i.SellerInForetaksregisteret,
		&i.SellerAddressLine1,
		&i.SellerAddressLine2,
		&i.SellerPostalCode,
		&i.SellerCity,
		&i.SellerCountry,
		&i.SellerBankAccount,
		&i.SellerIban,
		&i.SellerBic,
		&i.SellerEmail,
		&i.SellerFooterText,
		&i.NetTotal,
		&i.VatTotal,
		&i.GrossTotal,
		&i.VatTotalNok,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.IssuedAt,
		&i.IssuedByUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, kind, status, number, customer_id, credits_invoice_id, issue_date, delivery_date, delivery_from, delivery_to, delivery_address_line1, delivery_address_line2, delivery_postal_code, delivery_city, delivery_country, payment_terms_days, due_date, currency, exchange_rate, exchange_rate_date, your_reference, our_reference, order_reference, note, internal_note, buyer_customer_number, buyer_type, buyer_name, buyer_organisation_number, buyer_foreign_id, buyer_address_line1, buyer_address_line2, buyer_postal_code, buyer_city, buyer_region, buyer_country, buyer_peppol_id, buyer_gln, buyer_language, seller_legal_name, seller_organisation_number, seller_vat_registered, seller_in_foretaksregisteret, seller_address_line1, seller_address_line2, seller_postal_code, seller_city, seller_country, seller_bank_account, seller_iban, seller_bic, seller_email, seller_footer_text, net_total, vat_total, gross_total, vat_total_nok, pdf_object_key, pdf_sha256, issued_at, issued_by_user_id, created_by_user_id, created_at, updated_at, revision FROM invoices.invoices
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR kind = $2::text)
  AND ($3::int IS NULL OR customer_id = $3::int)
  AND (($4::bigint IS NULL AND $5::text IS NULL)
       OR number = $4::bigint
       OR buyer_name ILIKE $5::text)
  AND ($6::date IS NULL OR issue_date >= $6::date)
  AND ($7::date IS NULL OR issue_date <= $7::date)
ORDER BY number DESC NULLS FIRST, id DESC
LIMIT $9 OFFSET $8
`

type ListInvoicesParams struct {
	Status        *string
	Kind          *string
	CustomerID    *int32
	SearchNumber  *int64
	SearchPattern *string
	IssuedFrom    pgtype.Date
	IssuedTo      pgtype.Date
	PageOffset    int32
	PageSize      int32
}

// ListInvoices is one page of GET /invoices (D4): drafts first, then by number
// descending, the id breaking ties so a page never shifts under a reader.
// search is a number (exact) or a buyer-name pattern; a draft has no buyer
// snapshot and is found through customer_id instead.
func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]InvoicesInvoice, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.Status,
		arg.Kind,
		arg.CustomerID,
		arg.SearchNumber,
		arg.SearchPattern,
		arg.IssuedFrom,
		arg.IssuedTo,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesInvoice
	for rows.Next() {
		var i InvoicesInvoice
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Number,
			&i.CustomerID,
			&i.CreditsInvoiceID,
			&i.IssueDate,
			&i.DeliveryDate,
			&i.DeliveryFrom,
			&i.DeliveryTo,
			&i.DeliveryAddressLine1,
			&i.DeliveryAddressLine2,
			&i.DeliveryPostalCode,
			&i.DeliveryCity,
			&i.DeliveryCountry,
			&i.PaymentTermsDays,
			&i.DueDate,
			&i.Currency,
			&i.ExchangeRate,
			&i.ExchangeRateDate,
			&i.YourReference,
			&i.OurReference,
			&i.OrderReference,
			&i.Note,
			&i.InternalNote,
			&i.BuyerCustomerNumber,
			&i.BuyerType,
			&i.BuyerName,
			&i.BuyerOrganisationNumber,
			&i.BuyerForeignID,
			&i.BuyerAddressLine1,
			&i.BuyerAddressLine2,
			&i.BuyerPostalCode,
			&i.BuyerCity,
			&i.BuyerRegion,
			&i.BuyerCountry,
			&i.BuyerPeppolID,
			&i.BuyerGln,
			&i.BuyerLanguage,
			&i.SellerLegalName,
			&i.SellerOrganisationNumber,
			&i.SellerVatRegistered,
			&i.SellerInForetaksregisteret,
			&i.SellerAddressLine1,
			&i.SellerAddressLine2,
			&i.SellerPostalCode,
			&i.SellerCity,
			&i.SellerCountry,
			&i.SellerBankAccount,
			&i.SellerIban,
			&i.SellerBic,
			&i.SellerEmail,
			&i.SellerFooterText,
			&i.NetTotal,
			&i.VatTotal,
			&i.GrossTotal,
			&i.VatTotalNok,
			&i.PdfObjectKey,
			&i.PdfSha256,
			&i.IssuedAt,
			&i.IssuedByUserID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvoice = `-- name: LockInvoice :one
SELECT id, kind, status, number, customer_id, credits_invoice_id, issue_date, delivery_date, delivery_from, delivery_to, delivery_address_line1, delivery_address_line2, delivery_postal_code, delivery_city, delivery_country, payment_terms_days, due_date, currency, exchange_rate, exchange_rate_date, your_reference, our_reference, order_reference, note, internal_note, buyer_customer_number, buyer_type, buyer_name, buyer_organisation_number, buyer_foreign_id, buyer_address_line1, buyer_address_line2, buyer_postal_code, buyer_city, buyer_region, buyer_country, buyer_peppol_id, buyer_gln, buyer_language, seller_legal_name, seller_organisation_number, seller_vat_registered, seller_in_foretaksregisteret, seller_address_line1, seller_address_line2, seller_postal_code, seller_city, seller_country, seller_bank_account, seller_iban, seller_bic, seller_email, seller_footer_text, net_total, vat_total, gross_total, vat_total_nok, pdf_object_key, pdf_sha256, issued_at, issued_by_user_id, created_by_user_id, created_at, updated_at, revision FROM invoices.invoices WHERE id = $1 FOR UPDATE
`

// LockInvoice takes a document FOR UPDATE: a draft save, a delete and an issue
// hold it to their commit. It is always the first lock an issue takes (D6).
func (q *Queries) LockInvoice(ctx context.Context, id int64) (InvoicesInvoice, error) {
	row := q.db.QueryRow(ctx, lockInvoice, id)
	var i InvoicesInvoice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Number,
		&i.CustomerID,
		&i.CreditsInvoiceID,
		&i.IssueDate,
		&i.DeliveryDate,
		&i.DeliveryFrom,
		&i.DeliveryTo,
		&i.DeliveryAddressLine1,
		&i.DeliveryAddressLine2,
		&i.DeliveryPostalCode,
		&i.DeliveryCity,
		&i.DeliveryCountry,
		&i.PaymentTermsDays,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.YourReference,
		&i.OurReference,
		&i.OrderReference,
		&i.Note,
		&i.InternalNote,
		&i.BuyerCustomerNumber,
		&i.BuyerType,
		&i.BuyerName,
		&i.BuyerOrganisationNumber,
		&i.BuyerForeignID,
		&i.BuyerAddressLine1,
		&i.BuyerAddressLine2,
		&i.BuyerPostalCode,
		&i.BuyerCity,
		&i.BuyerRegion,
		&i.BuyerCountry,
		&i.BuyerPeppolID,
		&i.BuyerGln,
		&i.BuyerLanguage,
		&i.SellerLegalName,
		&i.SellerOrganisationNumber,
		&i.SellerVatRegistered,
		&i.SellerInForetaksregisteret,
		&i.SellerAddressLine1,
		&i.SellerAddressLine2,
		&i.SellerPostalCode,
		&i.SellerCity,
		&i.SellerCountry,
		&i.SellerBankAccount,
		&i.SellerIban,
		&i.SellerBic,
		&i.SellerEmail,
		&i.SellerFooterText,
		&i.NetTotal,
		&i.VatTotal,
		&i.GrossTotal,
		&i.VatTotalNok,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.IssuedAt,
		&i.IssuedByUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}

const updateDraft = `-- name: UpdateDraft :one
UPDATE invoices.invoices SET
    customer_id = $1,
    delivery_date = $2,
    delivery_from = $3,
    delivery_to = $4,
    delivery_address_line1 = $5,
    delivery_address_line2 = $6,
    delivery_postal_code = $7,
    delivery_city = $8,
    delivery_country = $9,
    payment_terms_days = $10,
    your_reference = $11,
    our_reference = $12,
    order_reference = $13,
    note = $14,
    internal_note = $15,
    net_total = $16,
    vat_total = $17,
    gross_total = $18,
    vat_total_nok = $19,
    updated_at = $20::timestamptz,
    revision = revision + 1
WHERE id = $21 AND status = 'draft'
RETURNING id, kind, status, number, customer_id, credits_invoice_id, issue_date, delivery_date, delivery_from, delivery_to, delivery_address_line1, delivery_address_line2, delivery_postal_code, delivery_city, delivery_country, payment_terms_days, due_date, currency, exchange_rate, exchange_rate_date, your_reference, our_reference, order_reference, note, internal_note, buyer_customer_number, buyer_type, buyer_name, buyer_organisation_number, buyer_foreign_id, buyer_address_line1, buyer_address_line2, buyer_postal_code, buyer_city, buyer_region, buyer_country, buyer_peppol_id, buyer_gln, buyer_language, seller_legal_name, seller_organisation_number, seller_vat_registered, seller_in_foretaksregisteret, seller_address_line1, seller_address_line2, seller_postal_code, seller_city, seller_country, seller_bank_account, seller_iban, seller_bic, seller_email, seller_footer_text, net_total, vat_total, gross_total, vat_total_nok, pdf_object_key, pdf_sha256, issued_at, issued_by_user_id, created_by_user_id, created_at, updated_at, revision
`

type UpdateDraftParams struct {
	CustomerID           int32
	DeliveryDate         pgtype.Date
	DeliveryFrom         pgtype.Date
	DeliveryTo           pgtype.Date
	DeliveryAddressLine1 *string
	DeliveryAddressLine2 *string
	DeliveryPostalCode   *string
	DeliveryCity         *string
	DeliveryCountry      *string
	PaymentTermsDays     *int32
	YourReference        string
	OurReference         string
	OrderReference       string
	Note                 string
	InternalNote         string
	NetTotal             pgtype.Numeric
	VatTotal             pgtype.Numeric
	GrossTotal           pgtype.Numeric
	VatTotalNok          pgtype.Numeric
	Now                  time.Time
	ID                   int64
}

// UpdateDraft replaces a draft's own fields and moves its revision on. The
// caller holds the row (LockInvoice) and has checked it is still a draft.
func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) (InvoicesInvoice, error) {
	row := q.db.QueryRow(ctx, updateDraft,
		arg.CustomerID,
		arg.DeliveryDate,
		arg.DeliveryFrom,
		arg.DeliveryTo,
		arg.DeliveryAddressLine1,
		arg.DeliveryAddressLine2,
		arg.DeliveryPostalCode,
		arg.DeliveryCity,
		arg.DeliveryCountry,
		arg.PaymentTermsDays,
		arg.YourReference,
		arg.OurReference,
		arg.OrderReference,
		arg.Note,
		arg.InternalNote,
		arg.NetTotal,
		arg.VatTotal,
		arg.GrossTotal,
		arg.VatTotalNok,
		arg.Now,
		arg.ID,
	)
	var i InvoicesInvoice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Number,
		&i.CustomerID,
		&i.CreditsInvoiceID,
		&i.IssueDate,
		&i.DeliveryDate,
		&i.DeliveryFrom,
		&i.DeliveryTo,
		&i.DeliveryAddressLine1,
		&i.DeliveryAddressLine2,
		&i.DeliveryPostalCode,
		&i.DeliveryCity,
		&i.DeliveryCountry,
		&i.PaymentTermsDays,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.ExchangeRateDate,
		&i.YourReference,
		&i.OurReference,
		&i.OrderReference,
		&i.Note,
		&i.InternalNote,
		&i.BuyerCustomerNumber,
		&i.BuyerType,
		&i.BuyerName,
		&i.BuyerOrganisationNumber,
		&i.BuyerForeignID,
		&i.BuyerAddressLine1,
		&i.BuyerAddressLine2,
		&i.BuyerPostalCode,
		&i.BuyerCity,
		&i.BuyerRegion,
		&i.BuyerCountry,
		&i.BuyerPeppolID,
		&i.BuyerGln,
		&i.BuyerLanguage,
		&i.SellerLegalName,
		&i.SellerOrganisationNumber,
		&i.SellerVatRegistered,
		&i.SellerInForetaksregisteret,
		&i.SellerAddressLine1,
		&i.SellerAddressLine2,
		&i.SellerPostalCode,
		&i.SellerCity,
		&i.SellerCountry,
		&i.SellerBankAccount,
		&i.SellerIban,
		&i.SellerBic,
		&i.SellerEmail,
		&i.SellerFooterText,
		&i.NetTotal,
		&i.VatTotal,
		&i.GrossTotal,
		&i.VatTotalNok,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.IssuedAt,
		&i.IssuedByUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
	)
	return i, err
}
