// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InvoicesCounter struct {
	CounterName string
	NextValue   int64
}

type InvoicesInvoice struct {
	ID                         int64
	Kind                       string
	Status                     string
	Number                     *int64
	CustomerID                 int32
	CreditsInvoiceID           *int64
	IssueDate                  pgtype.Date
	DeliveryDate               pgtype.Date
	DeliveryFrom               pgtype.Date
	DeliveryTo                 pgtype.Date
	DeliveryAddressLine1       *string
	DeliveryAddressLine2       *string
	DeliveryPostalCode         *string
	DeliveryCity               *string
	DeliveryCountry            *string
	PaymentTermsDays           *int32
	DueDate                    pgtype.Date
	Currency                   string
	ExchangeRate               pgtype.Numeric
	ExchangeRateDate           pgtype.Date
	YourReference              string
	OurReference               string
	OrderReference             string
	Note                       string
	InternalNote               string
	BuyerCustomerNumber        *int64
	BuyerType                  *string
	BuyerName                  *string
	BuyerOrganisationNumber    *string
	BuyerForeignID             *string
	BuyerAddressLine1          *string
	BuyerAddressLine2          *string
	BuyerPostalCode            *string
	BuyerCity                  *string
	BuyerRegion                *string
	BuyerCountry               *string
	BuyerPeppolID              *string
	BuyerGln                   *string
	BuyerLanguage              *string
	SellerLegalName            *string
	SellerOrganisationNumber   *string
	SellerVatRegistered        *bool
	SellerInForetaksregisteret *bool
	SellerAddressLine1         *string
	SellerAddressLine2         *string
	SellerPostalCode           *string
	SellerCity                 *string
	SellerCountry              *string
	SellerBankAccount          *string
	SellerIban                 *string
	SellerBic                  *string
	SellerEmail                *string
	SellerFooterText           *string
	NetTotal                   pgtype.Numeric
	VatTotal                   pgtype.Numeric
	GrossTotal                 pgtype.Numeric
	VatTotalNok                pgtype.Numeric
	PdfObjectKey               *string
	PdfSha256                  *string
	IssuedAt                   *time.Time
	IssuedByUserID             *uuid.UUID
	CreatedByUserID            uuid.UUID
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	Revision                   int32
}

type InvoicesLine struct {
	ID              int64
	InvoiceID       int64
	Position        int32
	Description     string
	Quantity        pgtype.Numeric
	Unit            string
	UnitPrice       pgtype.Numeric
	DiscountPercent pgtype.Numeric
	VatCodeID       int32
	CreditsLineID   *int64
	LineGross       pgtype.Numeric
	LineAllowance   pgtype.Numeric
	LineNet         pgtype.Numeric
	VatRatePercent  pgtype.Numeric
	VatCategory     *string
	SafTCode        *string
	ExemptionReason *string
}

type InvoicesSetting struct {
	ID                      int16
	LegalName               string
	OrganisationNumber      string
	VatRegistered           bool
	InForetaksregisteret    bool
	AddressLine1            string
	AddressLine2            string
	PostalCode              string
	City                    string
	Country                 string
	BankAccount             string
	Iban                    string
	Bic                     string
	Email                   string
	DefaultPaymentTermsDays int32
	DefaultCurrency         string
	FooterText              string
	SeriesStart             int64
	UpdatedAt               time.Time
	Revision                int32
}

type InvoicesVatCode struct {
	ID              int32
	Code            string
	Name            string
	SafTCode        string
	EhfCategory     string
	ExemptionReason *string
	Active          bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Revision        int32
}

type InvoicesVatCodeRate struct {
	ID          int32
	VatCodeID   int32
	RatePercent pgtype.Numeric
	ValidFrom   pgtype.Date
	ValidTo     pgtype.Date
	CreatedAt   time.Time
}

type InvoicesVatSummary struct {
	ID              int64
	InvoiceID       int64
	VatCategory     string
	RatePercent     pgtype.Numeric
	SafTCode        string
	ExemptionReason *string
	TaxableAmount   pgtype.Numeric
	VatAmount       pgtype.Numeric
	VatAmountNok    pgtype.Numeric
}
