// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminder_worker.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimReminder = `-- name: ClaimReminder :one

UPDATE invoices.reminders
SET lease_id = $1::text, lease_until = $2::timestamptz,
    message_id = coalesce(message_id, $3::text)
WHERE status = 'queued' AND id = (
    SELECT r.id FROM invoices.reminders r
    WHERE r.status = 'queued'
      AND r.next_attempt_at <= $4::timestamptz
      AND (r.lease_until IS NULL OR r.lease_until <= $4::timestamptz)
    ORDER BY r.next_attempt_at, r.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, invoice_id, run_id, print_batch_id, sequence, level, announces_collection, channel, recipient, language, created_at, created_by_user_id, sent_on, deadline, regime, principal_open, credited, fee_kind, fee, compensation, charges_earlier, interest, interest_waived, interest_paid, interest_from, interest_segments, inkassosats, total, charge_notes, pdf_object_key, pdf_sha256, message_id, sent_at, status, held_reason, attempts, next_attempt_at, first_attempt_at, lease_id, lease_until, last_error, failed_at, withdrawn_at, withdrawn_by_user_id, withdrawal_reason
`

type ClaimReminderParams struct {
	LeaseID    string
	LeaseUntil time.Time
	MessageID  string
	Now        time.Time
}

// The invoices-reminders worker and a letter's own operations (invoices
// payments and reminders design D10). A queued letter is claimed under a row
// lease, the shape of transmissions.sql's ClaimTransmission; every later
// write of the claim names its lease and the status the claim saw, and is a
// no-op when either changed. A letter's facts are written only while a claim
// holds it — or a print batch has it locked — and a failed attempt clears
// them with the lease, so a letter carrying facts under no live lease is
// never "being sent" (plan reading 45): status = 'queued' AND sent_on IS NOT
// NULL AND lease_until > @now.
// ClaimReminder leases the next queued letter due by @now whose lease, if
// any, has run out — free at exactly lease_until <= @now, the complement of
// "being sent"'s lease_until > @now, so no instant has a letter both
// claimable and unwithdrawable, or neither (Task 11's review). One
// conditional UPDATE over a SKIP LOCKED pick, so two workers never take one
// letter. The Message-ID is made by the claim and kept by every later one:
// set once, while queued (plan reading 52). No row is pgx.ErrNoRows.
func (q *Queries) ClaimReminder(ctx context.Context, arg ClaimReminderParams) (InvoicesReminder, error) {
	row := q.db.QueryRow(ctx, claimReminder,
		arg.LeaseID,
		arg.LeaseUntil,
		arg.MessageID,
		arg.Now,
	)
	var i InvoicesReminder
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.PrintBatchID,
		&i.Sequence,
		&i.Level,
		&i.AnnouncesCollection,
		&i.Channel,
		&i.Recipient,
		&i.Language,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.SentOn,
		&i.Deadline,
		&i.Regime,
		&i.PrincipalOpen,
		&i.Credited,
		&i.FeeKind,
		&i.Fee,
		&i.Compensation,
		&i.ChargesEarlier,
		&i.Interest,
		&i.InterestWaived,
		&i.InterestPaid,
		&i.InterestFrom,
		&i.InterestSegments,
		&i.Inkassosats,
		&i.Total,
		&i.ChargeNotes,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.MessageID,
		&i.SentAt,
		&i.Status,
		&i.HeldReason,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.FirstAttemptAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.FailedAt,
		&i.WithdrawnAt,
		&i.WithdrawnByUserID,
		&i.WithdrawalReason,
	)
	return i, err
}

const countReminders = `-- name: CountReminders :one
SELECT count(*)::int FROM invoices.reminders
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR channel = $2::text)
  AND ($3::bigint IS NULL OR invoice_id = $3::bigint)
  AND ($4::bigint IS NULL OR run_id = $4::bigint)
`

type CountRemindersParams struct {
	Status    *string
	Channel   *string
	InvoiceID *int64
	RunID     *int64
}

// CountReminders is how many letters ListReminders' filters match.
func (q *Queries) CountReminders(ctx context.Context, arg CountRemindersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReminders,
		arg.Status,
		arg.Channel,
		arg.InvoiceID,
		arg.RunID,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const creditedOn = `-- name: CreditedOn :one
SELECT coalesce(sum(gross_total), 0)::numeric AS credited
FROM invoices.invoices
WHERE credits_invoice_id = $1::bigint AND kind = 'credit_note' AND status = 'issued' AND issue_date <= $2::date
`

type CreditedOnParams struct {
	InvoiceID int64
	Day       pgtype.Date
}

// CreditedOn is what the invoice's issued credit notes took off it up to and
// including a letter's day: the letter prints it beside the principal, from
// its own row and the documents, the same every time it is rendered.
func (q *Queries) CreditedOn(ctx context.Context, arg CreditedOnParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, creditedOn, arg.InvoiceID, arg.Day)
	var credited pgtype.Numeric
	err := row.Scan(&credited)
	return credited, err
}

const failReminderAttempt = `-- name: FailReminderAttempt :execrows
UPDATE invoices.reminders
SET attempts = attempts + 1, next_attempt_at = $1::timestamptz, last_error = $2::text,
    first_attempt_at = coalesce(first_attempt_at, $3::timestamptz),
    lease_id = NULL, lease_until = NULL,
    sent_on = NULL, deadline = NULL, regime = NULL, principal_open = NULL, fee_kind = NULL, fee = NULL,
    compensation = NULL, charges_earlier = NULL, interest = NULL, interest_waived = NULL, interest_paid = NULL,
    interest_from = NULL, interest_segments = NULL, inkassosats = NULL, total = NULL, charge_notes = NULL,
    pdf_object_key = NULL, pdf_sha256 = NULL
WHERE id = $4 AND lease_id = $5::text AND status = 'queued'
`

type FailReminderAttemptParams struct {
	NextAttemptAt time.Time
	LastError     *string
	Now           time.Time
	ID            int64
	LeaseID       string
}

// FailReminderAttempt counts a failed attempt (D10): attempts + 1, the next
// at the backoff, the reason, and the lease and the facts cleared — so a
// stale sent_on never makes the letter look "being sent" (plan reading 45)
// and it may be withdrawn again until the next claim.
func (q *Queries) FailReminderAttempt(ctx context.Context, arg FailReminderAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, failReminderAttempt,
		arg.NextAttemptAt,
		arg.LastError,
		arg.Now,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReminder = `-- name: GetReminder :one
SELECT id, invoice_id, run_id, print_batch_id, sequence, level, announces_collection, channel, recipient, language, created_at, created_by_user_id, sent_on, deadline, regime, principal_open, credited, fee_kind, fee, compensation, charges_earlier, interest, interest_waived, interest_paid, interest_from, interest_segments, inkassosats, total, charge_notes, pdf_object_key, pdf_sha256, message_id, sent_at, status, held_reason, attempts, next_attempt_at, first_attempt_at, lease_id, lease_until, last_error, failed_at, withdrawn_at, withdrawn_by_user_id, withdrawal_reason FROM invoices.reminders WHERE id = $1
`

func (q *Queries) GetReminder(ctx context.Context, id int64) (InvoicesReminder, error) {
	row := q.db.QueryRow(ctx, getReminder, id)
	var i InvoicesReminder
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.PrintBatchID,
		&i.Sequence,
		&i.Level,
		&i.AnnouncesCollection,
		&i.Channel,
		&i.Recipient,
		&i.Language,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.SentOn,
		&i.Deadline,
		&i.Regime,
		&i.PrincipalOpen,
		&i.Credited,
		&i.FeeKind,
		&i.Fee,
		&i.Compensation,
		&i.ChargesEarlier,
		&i.Interest,
		&i.InterestWaived,
		&i.InterestPaid,
		&i.InterestFrom,
		&i.InterestSegments,
		&i.Inkassosats,
		&i.Total,
		&i.ChargeNotes,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.MessageID,
		&i.SentAt,
		&i.Status,
		&i.HeldReason,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.FirstAttemptAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.FailedAt,
		&i.WithdrawnAt,
		&i.WithdrawnByUserID,
		&i.WithdrawalReason,
	)
	return i, err
}

const listReminders = `-- name: ListReminders :many
SELECT id, invoice_id, run_id, print_batch_id, sequence, level, announces_collection, channel, recipient, language, created_at, created_by_user_id, sent_on, deadline, regime, principal_open, credited, fee_kind, fee, compensation, charges_earlier, interest, interest_waived, interest_paid, interest_from, interest_segments, inkassosats, total, charge_notes, pdf_object_key, pdf_sha256, message_id, sent_at, status, held_reason, attempts, next_attempt_at, first_attempt_at, lease_id, lease_until, last_error, failed_at, withdrawn_at, withdrawn_by_user_id, withdrawal_reason FROM invoices.reminders
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR channel = $2::text)
  AND ($3::bigint IS NULL OR invoice_id = $3::bigint)
  AND ($4::bigint IS NULL OR run_id = $4::bigint)
ORDER BY id DESC
LIMIT $6 OFFSET $5
`

type ListRemindersParams struct {
	Status     *string
	Channel    *string
	InvoiceID  *int64
	RunID      *int64
	PageOffset int32
	PageSize   int32
}

// ListReminders is one page of the letters (plan reading 12), filtered by
// status, channel, invoice and run, the newest first.
func (q *Queries) ListReminders(ctx context.Context, arg ListRemindersParams) ([]InvoicesReminder, error) {
	rows, err := q.db.Query(ctx, listReminders,
		arg.Status,
		arg.Channel,
		arg.InvoiceID,
		arg.RunID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesReminder
	for rows.Next() {
		var i InvoicesReminder
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.RunID,
			&i.PrintBatchID,
			&i.Sequence,
			&i.Level,
			&i.AnnouncesCollection,
			&i.Channel,
			&i.Recipient,
			&i.Language,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.SentOn,
			&i.Deadline,
			&i.Regime,
			&i.PrincipalOpen,
			&i.Credited,
			&i.FeeKind,
			&i.Fee,
			&i.Compensation,
			&i.ChargesEarlier,
			&i.Interest,
			&i.InterestWaived,
			&i.InterestPaid,
			&i.InterestFrom,
			&i.InterestSegments,
			&i.Inkassosats,
			&i.Total,
			&i.ChargeNotes,
			&i.PdfObjectKey,
			&i.PdfSha256,
			&i.MessageID,
			&i.SentAt,
			&i.Status,
			&i.HeldReason,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.FirstAttemptAt,
			&i.LeaseID,
			&i.LeaseUntil,
			&i.LastError,
			&i.FailedAt,
			&i.WithdrawnAt,
			&i.WithdrawnByUserID,
			&i.WithdrawalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderFailed = `-- name: MarkReminderFailed :execrows
UPDATE invoices.reminders
SET status = 'failed', failed_at = $1::timestamptz, attempts = attempts + 1,
    last_error = $2::text, lease_id = NULL, lease_until = NULL,
    sent_on = NULL, deadline = NULL, regime = NULL, principal_open = NULL, fee_kind = NULL, fee = NULL,
    compensation = NULL, charges_earlier = NULL, interest = NULL, interest_waived = NULL, interest_paid = NULL,
    interest_from = NULL, interest_segments = NULL, inkassosats = NULL, total = NULL, charge_notes = NULL,
    pdf_object_key = NULL, pdf_sha256 = NULL
WHERE id = $3 AND lease_id = $4::text AND status = 'queued'
`

type MarkReminderFailedParams struct {
	FailedAt  time.Time
	LastError *string
	ID        int64
	LeaseID   string
}

// MarkReminderFailed is a letter still unsent 48 hours after its first
// attempt (D10): failed, with the attempt counted, the reason, and the lease
// and the facts cleared. Attention names it; a retry puts it back.
func (q *Queries) MarkReminderFailed(ctx context.Context, arg MarkReminderFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReminderFailed,
		arg.FailedAt,
		arg.LastError,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markReminderSent = `-- name: MarkReminderSent :one
UPDATE invoices.reminders
SET status = 'sent', sent_at = $1::timestamptz, lease_id = NULL, lease_until = NULL, held_reason = NULL,
    last_error = NULL
WHERE id = $2 AND lease_id = $3::text AND status = 'queued'
RETURNING id, invoice_id, run_id, print_batch_id, sequence, level, announces_collection, channel, recipient, language, created_at, created_by_user_id, sent_on, deadline, regime, principal_open, credited, fee_kind, fee, compensation, charges_earlier, interest, interest_waived, interest_paid, interest_from, interest_segments, inkassosats, total, charge_notes, pdf_object_key, pdf_sha256, message_id, sent_at, status, held_reason, attempts, next_attempt_at, first_attempt_at, lease_id, lease_until, last_error, failed_at, withdrawn_at, withdrawn_by_user_id, withdrawal_reason
`

type MarkReminderSentParams struct {
	SentAt  time.Time
	ID      int64
	LeaseID string
}

// MarkReminderSent is the letter mailed (D10 step 4): sent at the claim's
// time, the lease released. The caller holds the invoice and then the
// letter. No row is pgx.ErrNoRows: another claim, or a withdrawal after the
// lease ran out, moved it.
func (q *Queries) MarkReminderSent(ctx context.Context, arg MarkReminderSentParams) (InvoicesReminder, error) {
	row := q.db.QueryRow(ctx, markReminderSent, arg.SentAt, arg.ID, arg.LeaseID)
	var i InvoicesReminder
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.PrintBatchID,
		&i.Sequence,
		&i.Level,
		&i.AnnouncesCollection,
		&i.Channel,
		&i.Recipient,
		&i.Language,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.SentOn,
		&i.Deadline,
		&i.Regime,
		&i.PrincipalOpen,
		&i.Credited,
		&i.FeeKind,
		&i.Fee,
		&i.Compensation,
		&i.ChargesEarlier,
		&i.Interest,
		&i.InterestWaived,
		&i.InterestPaid,
		&i.InterestFrom,
		&i.InterestSegments,
		&i.Inkassosats,
		&i.Total,
		&i.ChargeNotes,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.MessageID,
		&i.SentAt,
		&i.Status,
		&i.HeldReason,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.FirstAttemptAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.FailedAt,
		&i.WithdrawnAt,
		&i.WithdrawnByUserID,
		&i.WithdrawalReason,
	)
	return i, err
}

const rescheduleReminderUncounted = `-- name: RescheduleReminderUncounted :execrows
UPDATE invoices.reminders
SET next_attempt_at = $1::timestamptz, held_reason = $2::text,
    lease_id = NULL, lease_until = NULL,
    sent_on = NULL, deadline = NULL, regime = NULL, principal_open = NULL, fee_kind = NULL, fee = NULL,
    compensation = NULL, charges_earlier = NULL, interest = NULL, interest_waived = NULL, interest_paid = NULL,
    interest_from = NULL, interest_segments = NULL, inkassosats = NULL, total = NULL, charge_notes = NULL,
    pdf_object_key = NULL, pdf_sha256 = NULL
WHERE id = $3 AND lease_id = $4::text AND status = 'queued'
`

type RescheduleReminderUncountedParams struct {
	NextAttemptAt time.Time
	HeldReason    *string
	ID            int64
	LeaseID       string
}

// RescheduleReminderUncounted puts a claimed letter back without counting
// the try (plan readings 17, 46): an hour out when its rates or regime
// review are missing, held_reason saying why, which attention reads; at
// once, held_reason NULL, when Oslo midnight passed before its send, so its
// facts are judged again on the new day. Neither attempts nor
// first_attempt_at moves, so waiting never runs into the 48 hours. The lease
// and the facts are cleared.
func (q *Queries) RescheduleReminderUncounted(ctx context.Context, arg RescheduleReminderUncountedParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleReminderUncounted,
		arg.NextAttemptAt,
		arg.HeldReason,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryReminder = `-- name: RetryReminder :one
UPDATE invoices.reminders
SET status = 'queued', next_attempt_at = $1::timestamptz, first_attempt_at = NULL, attempts = 0, failed_at = NULL
WHERE id = $2 AND status = 'failed'
RETURNING id, invoice_id, run_id, print_batch_id, sequence, level, announces_collection, channel, recipient, language, created_at, created_by_user_id, sent_on, deadline, regime, principal_open, credited, fee_kind, fee, compensation, charges_earlier, interest, interest_waived, interest_paid, interest_from, interest_segments, inkassosats, total, charge_notes, pdf_object_key, pdf_sha256, message_id, sent_at, status, held_reason, attempts, next_attempt_at, first_attempt_at, lease_id, lease_until, last_error, failed_at, withdrawn_at, withdrawn_by_user_id, withdrawal_reason
`

type RetryReminderParams struct {
	Now time.Time
	ID  int64
}

// RetryReminder puts a failed letter back in the queue (D10): due at once,
// its 48 hours and its backoff begun again. The caller holds the letter.
func (q *Queries) RetryReminder(ctx context.Context, arg RetryReminderParams) (InvoicesReminder, error) {
	row := q.db.QueryRow(ctx, retryReminder, arg.Now, arg.ID)
	var i InvoicesReminder
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.PrintBatchID,
		&i.Sequence,
		&i.Level,
		&i.AnnouncesCollection,
		&i.Channel,
		&i.Recipient,
		&i.Language,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.SentOn,
		&i.Deadline,
		&i.Regime,
		&i.PrincipalOpen,
		&i.Credited,
		&i.FeeKind,
		&i.Fee,
		&i.Compensation,
		&i.ChargesEarlier,
		&i.Interest,
		&i.InterestWaived,
		&i.InterestPaid,
		&i.InterestFrom,
		&i.InterestSegments,
		&i.Inkassosats,
		&i.Total,
		&i.ChargeNotes,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.MessageID,
		&i.SentAt,
		&i.Status,
		&i.HeldReason,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.FirstAttemptAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.FailedAt,
		&i.WithdrawnAt,
		&i.WithdrawnByUserID,
		&i.WithdrawalReason,
	)
	return i, err
}

const setReminderPDF = `-- name: SetReminderPDF :execrows
UPDATE invoices.reminders SET pdf_object_key = $1::text, pdf_sha256 = $2::text
WHERE id = $3 AND lease_id = $4::text AND status = 'queued'
`

type SetReminderPDFParams struct {
	PdfObjectKey string
	PdfSha256    string
	ID           int64
	LeaseID      string
}

// SetReminderPDF records the PDF a claim rendered and stored, before it is
// mailed — the object the mail carries.
func (q *Queries) SetReminderPDF(ctx context.Context, arg SetReminderPDFParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReminderPDF,
		arg.PdfObjectKey,
		arg.PdfSha256,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const withdrawClaimedReminder = `-- name: WithdrawClaimedReminder :execrows
UPDATE invoices.reminders
SET status = 'withdrawn', withdrawn_at = $1::timestamptz, withdrawal_reason = $2::text,
    lease_id = NULL, lease_until = NULL, held_reason = NULL,
    sent_on = NULL, deadline = NULL, regime = NULL, principal_open = NULL, fee_kind = NULL, fee = NULL,
    compensation = NULL, charges_earlier = NULL, interest = NULL, interest_waived = NULL, interest_paid = NULL,
    interest_from = NULL, interest_segments = NULL, inkassosats = NULL, total = NULL, charge_notes = NULL,
    pdf_object_key = NULL, pdf_sha256 = NULL
WHERE id = $3 AND lease_id = $4::text AND status = 'queued'
`

type WithdrawClaimedReminderParams struct {
	WithdrawnAt      time.Time
	WithdrawalReason string
	ID               int64
	LeaseID          string
}

// WithdrawClaimedReminder is the dispatch's re-judge withdrawing the letter
// it holds (D10): the module's reason code and no user (plan reading 44),
// the lease and any facts of an earlier attempt cleared — a letter that was
// never sent claims nothing.
func (q *Queries) WithdrawClaimedReminder(ctx context.Context, arg WithdrawClaimedReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, withdrawClaimedReminder,
		arg.WithdrawnAt,
		arg.WithdrawalReason,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const withdrawReminder = `-- name: WithdrawReminder :one
UPDATE invoices.reminders
SET status = 'withdrawn', withdrawn_at = $1::timestamptz, withdrawn_by_user_id = $2,
    withdrawal_reason = $3::text, held_reason = NULL
WHERE id = $4 AND status IN ('queued', 'awaiting_print', 'printed', 'failed')
RETURNING id, invoice_id, run_id, print_batch_id, sequence, level, announces_collection, channel, recipient, language, created_at, created_by_user_id, sent_on, deadline, regime, principal_open, credited, fee_kind, fee, compensation, charges_earlier, interest, interest_waived, interest_paid, interest_from, interest_segments, inkassosats, total, charge_notes, pdf_object_key, pdf_sha256, message_id, sent_at, status, held_reason, attempts, next_attempt_at, first_attempt_at, lease_id, lease_until, last_error, failed_at, withdrawn_at, withdrawn_by_user_id, withdrawal_reason
`

type WithdrawReminderParams struct {
	WithdrawnAt       time.Time
	WithdrawnByUserID *uuid.UUID
	WithdrawalReason  string
	ID                int64
}

// WithdrawReminder is a person's withdrawal (D10): their reason and their
// id. The caller holds the letter alone (D18) and has judged under that
// lock that it may be withdrawn — queued, awaiting print, printed or
// failed, and not being sent.
func (q *Queries) WithdrawReminder(ctx context.Context, arg WithdrawReminderParams) (InvoicesReminder, error) {
	row := q.db.QueryRow(ctx, withdrawReminder,
		arg.WithdrawnAt,
		arg.WithdrawnByUserID,
		arg.WithdrawalReason,
		arg.ID,
	)
	var i InvoicesReminder
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.PrintBatchID,
		&i.Sequence,
		&i.Level,
		&i.AnnouncesCollection,
		&i.Channel,
		&i.Recipient,
		&i.Language,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.SentOn,
		&i.Deadline,
		&i.Regime,
		&i.PrincipalOpen,
		&i.Credited,
		&i.FeeKind,
		&i.Fee,
		&i.Compensation,
		&i.ChargesEarlier,
		&i.Interest,
		&i.InterestWaived,
		&i.InterestPaid,
		&i.InterestFrom,
		&i.InterestSegments,
		&i.Inkassosats,
		&i.Total,
		&i.ChargeNotes,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.MessageID,
		&i.SentAt,
		&i.Status,
		&i.HeldReason,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.FirstAttemptAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.FailedAt,
		&i.WithdrawnAt,
		&i.WithdrawnByUserID,
		&i.WithdrawalReason,
	)
	return i, err
}

const writeLetterFacts = `-- name: WriteLetterFacts :one
UPDATE invoices.reminders
SET sent_on = $1::date, deadline = $2::date, regime = $3::text,
    principal_open = $4, fee_kind = $5::text,
    fee = $6::numeric, compensation = $7::numeric,
    charges_earlier = $8, interest = $9, interest_waived = $10,
    interest_paid = $11, interest_from = $12::date,
    interest_segments = $13::jsonb, inkassosats = $14::numeric,
    total = $15, charge_notes = $16::text[],
    pdf_object_key = NULL, pdf_sha256 = NULL, held_reason = NULL,
    first_attempt_at = CASE WHEN status = 'queued' THEN coalesce(first_attempt_at, $17::timestamptz) ELSE first_attempt_at END
WHERE id = $18 AND status IN ('queued', 'awaiting_print')
RETURNING id, invoice_id, run_id, print_batch_id, sequence, level, announces_collection, channel, recipient, language, created_at, created_by_user_id, sent_on, deadline, regime, principal_open, credited, fee_kind, fee, compensation, charges_earlier, interest, interest_waived, interest_paid, interest_from, interest_segments, inkassosats, total, charge_notes, pdf_object_key, pdf_sha256, message_id, sent_at, status, held_reason, attempts, next_attempt_at, first_attempt_at, lease_id, lease_until, last_error, failed_at, withdrawn_at, withdrawn_by_user_id, withdrawal_reason
`

type WriteLetterFactsParams struct {
	SentOn           pgtype.Date
	Deadline         pgtype.Date
	Regime           string
	PrincipalOpen    pgtype.Numeric
	FeeKind          string
	Fee              pgtype.Numeric
	Compensation     pgtype.Numeric
	ChargesEarlier   pgtype.Numeric
	Interest         pgtype.Numeric
	InterestWaived   pgtype.Numeric
	InterestPaid     pgtype.Numeric
	InterestFrom     pgtype.Date
	InterestSegments []byte
	Inkassosats      pgtype.Numeric
	Total            pgtype.Numeric
	ChargeNotes      []string
	Now              time.Time
	ID               int64
}

// WriteLetterFacts writes a letter's facts as the engine judged them on its
// sending day — the dispatch's today, a print batch's postOn — and clears
// held_reason and any PDF of an earlier attempt: the PDF is rendered from
// these facts. A queued letter's first attempt is stamped once. The caller
// holds the invoice and then the letter (D18) and has judged the letter's
// status and lease under those locks.
func (q *Queries) WriteLetterFacts(ctx context.Context, arg WriteLetterFactsParams) (InvoicesReminder, error) {
	row := q.db.QueryRow(ctx, writeLetterFacts,
		arg.SentOn,
		arg.Deadline,
		arg.Regime,
		arg.PrincipalOpen,
		arg.FeeKind,
		arg.Fee,
		arg.Compensation,
		arg.ChargesEarlier,
		arg.Interest,
		arg.InterestWaived,
		arg.InterestPaid,
		arg.InterestFrom,
		arg.InterestSegments,
		arg.Inkassosats,
		arg.Total,
		arg.ChargeNotes,
		arg.Now,
		arg.ID,
	)
	var i InvoicesReminder
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.RunID,
		&i.PrintBatchID,
		&i.Sequence,
		&i.Level,
		&i.AnnouncesCollection,
		&i.Channel,
		&i.Recipient,
		&i.Language,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.SentOn,
		&i.Deadline,
		&i.Regime,
		&i.PrincipalOpen,
		&i.Credited,
		&i.FeeKind,
		&i.Fee,
		&i.Compensation,
		&i.ChargesEarlier,
		&i.Interest,
		&i.InterestWaived,
		&i.InterestPaid,
		&i.InterestFrom,
		&i.InterestSegments,
		&i.Inkassosats,
		&i.Total,
		&i.ChargeNotes,
		&i.PdfObjectKey,
		&i.PdfSha256,
		&i.MessageID,
		&i.SentAt,
		&i.Status,
		&i.HeldReason,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.FirstAttemptAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.FailedAt,
		&i.WithdrawnAt,
		&i.WithdrawnByUserID,
		&i.WithdrawalReason,
	)
	return i, err
}
