// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ruleinput.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const ruleChargePayments = `-- name: RuleChargePayments :many
SELECT id, invoice_id, paid_on, amount, currency, source, bank_transaction_id, reference, note, registered_by_user_id, registered_at, removed_at, removed_by_user_id, removal_reason FROM invoices.charge_payments
WHERE invoice_id = ANY($1::bigint[]) AND removed_at IS NULL
ORDER BY invoice_id, paid_on, id
`

// RuleChargePayments is the live charge payments of the invoices, in the
// order the money arrived.
func (q *Queries) RuleChargePayments(ctx context.Context, ids []int64) ([]InvoicesChargePayment, error) {
	rows, err := q.db.Query(ctx, ruleChargePayments, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesChargePayment
	for rows.Next() {
		var i InvoicesChargePayment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.PaidOn,
			&i.Amount,
			&i.Currency,
			&i.Source,
			&i.BankTransactionID,
			&i.Reference,
			&i.Note,
			&i.RegisteredByUserID,
			&i.RegisteredAt,
			&i.RemovedAt,
			&i.RemovedByUserID,
			&i.RemovalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleCredits = `-- name: RuleCredits :many
SELECT credits_invoice_id::bigint AS invoice_id, issue_date, gross_total
FROM invoices.invoices
WHERE credits_invoice_id = ANY($1::bigint[]) AND kind = 'credit_note' AND status = 'issued'
ORDER BY credits_invoice_id, id
`

type RuleCreditsRow struct {
	InvoiceID  int64
	IssueDate  pgtype.Date
	GrossTotal pgtype.Numeric
}

// RuleCredits is the issued credit notes of the invoices: the live ones —
// a draft credits nothing.
func (q *Queries) RuleCredits(ctx context.Context, ids []int64) ([]RuleCreditsRow, error) {
	rows, err := q.db.Query(ctx, ruleCredits, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleCreditsRow
	for rows.Next() {
		var i RuleCreditsRow
		if err := rows.Scan(&i.InvoiceID, &i.IssueDate, &i.GrossTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleDeliveries = `-- name: RuleDeliveries :many
SELECT m.invoice_id, 'manual'::text AS kind, NULL::timestamptz AS at, m.delivered_on AS delivered_on,
       m.kind::text AS manual_kind
FROM invoices.manual_deliveries m
WHERE m.invoice_id = ANY($1::bigint[]) AND m.removed_at IS NULL
UNION ALL
SELECT d.invoice_id, 'email'::text, d.sent_at, NULL::date, ''::text
FROM invoices.deliveries d
WHERE d.invoice_id = ANY($1::bigint[])
UNION ALL
SELECT t.invoice_id, 'ehf'::text, t.delivered_at, NULL::date, ''::text
FROM invoices.transmissions t
WHERE t.invoice_id = ANY($1::bigint[]) AND t.status = 'delivered'
`

type RuleDeliveriesRow struct {
	InvoiceID   int64
	Kind        string
	At          *time.Time
	DeliveredOn pgtype.Date
	ManualKind  string
}

// RuleDeliveries is every live delivery of the invoices the engine's delivery
// fact reads (D8; plan reading 34) — the one definition of a qualifying
// delivery, which deliveriesOf reads too, for one invoice: each e-mail by
// when it was sent, each delivered EHF transmission by when it was delivered
// — at, whose Oslo day the caller derives, never this statement — and each
// manual delivery not removed by its delivered_on. A failed, queued or
// cancelled transmission and a removed manual record are not deliveries.
// manual_kind is a manual record's own kind (handed_over or posted), which
// the collection file names; ” for the others.
func (q *Queries) RuleDeliveries(ctx context.Context, ids []int64) ([]RuleDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, ruleDeliveries, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleDeliveriesRow
	for rows.Next() {
		var i RuleDeliveriesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.Kind,
			&i.At,
			&i.DeliveredOn,
			&i.ManualKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleHandoffs = `-- name: RuleHandoffs :many
SELECT invoice_id FROM invoices.collection_handoffs
WHERE invoice_id = ANY($1::bigint[]) AND withdrawn_on IS NULL
ORDER BY invoice_id
`

// RuleHandoffs is the invoices among ids with a live hand-off.
func (q *Queries) RuleHandoffs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, ruleHandoffs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var invoice_id int64
		if err := rows.Scan(&invoice_id); err != nil {
			return nil, err
		}
		items = append(items, invoice_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleHolds = `-- name: RuleHolds :many
SELECT invoice_id,
       bool_or(lifted_at IS NULL)::boolean AS on_hold,
       bool_or(lifted_at IS NOT NULL AND charges_allowed = false)::boolean AS charges_barred
FROM invoices.invoice_holds
WHERE invoice_id = ANY($1::bigint[])
GROUP BY invoice_id
ORDER BY invoice_id
`

type RuleHoldsRow struct {
	InvoiceID     int64
	OnHold        bool
	ChargesBarred bool
}

// RuleHolds is, per invoice with a hold, whether one is live and whether a
// lift barred charges (charges_allowed false — for good, D11).
func (q *Queries) RuleHolds(ctx context.Context, ids []int64) ([]RuleHoldsRow, error) {
	rows, err := q.db.Query(ctx, ruleHolds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleHoldsRow
	for rows.Next() {
		var i RuleHoldsRow
		if err := rows.Scan(&i.InvoiceID, &i.OnHold, &i.ChargesBarred); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleInvoices = `-- name: RuleInvoices :many

SELECT id, customer_id, buyer_type, buyer_organisation_number, buyer_foreign_id,
       issue_date, due_date, gross_total
FROM invoices.invoices
WHERE id = ANY($1::bigint[]) AND kind = 'invoice' AND status = 'issued'
ORDER BY id
`

type RuleInvoicesRow struct {
	ID                      int64
	CustomerID              int32
	BuyerType               *string
	BuyerOrganisationNumber *string
	BuyerForeignID          *string
	IssueDate               pgtype.Date
	DueDate                 pgtype.Date
	GrossTotal              pgtype.Numeric
}

// The rule-input loader (invoices payments and reminders design D8): every
// fact the reminder engine judges an invoice on, read for many invoices at
// once — each statement over id = ANY(@ids), so a list of any length reads
// the same handful of statements. ruleinput.go maps the rows onto
// reminderrules.Input; no other code builds one (plan reading 2).
// RuleInvoices is the issued invoices among ids with the snapshot the engine
// reads: the buyer, the issue and due dates, the gross, and the customer
// whose policy applies. A draft or a credit note is not one. The buyer's
// language is not the engine's: the letter's dispatch reads it from the
// invoice row it holds locked.
func (q *Queries) RuleInvoices(ctx context.Context, ids []int64) ([]RuleInvoicesRow, error) {
	rows, err := q.db.Query(ctx, ruleInvoices, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleInvoicesRow
	for rows.Next() {
		var i RuleInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.BuyerType,
			&i.BuyerOrganisationNumber,
			&i.BuyerForeignID,
			&i.IssueDate,
			&i.DueDate,
			&i.GrossTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleLetters = `-- name: RuleLetters :many
SELECT id, invoice_id, run_id, print_batch_id, sequence, level, announces_collection, channel, recipient, language, created_at, created_by_user_id, sent_on, deadline, regime, principal_open, credited, fee_kind, fee, compensation, charges_earlier, interest, interest_waived, interest_paid, interest_from, interest_segments, inkassosats, total, charge_notes, pdf_object_key, pdf_sha256, message_id, sent_at, status, held_reason, attempts, next_attempt_at, first_attempt_at, lease_id, lease_until, last_error, failed_at, withdrawn_at, withdrawn_by_user_id, withdrawal_reason FROM invoices.reminders
WHERE invoice_id = ANY($1::bigint[])
ORDER BY invoice_id, sequence, id
`

// RuleLetters is every letter of the invoices, in any status, by sequence:
// the engine tells the sent from the ones in flight itself.
func (q *Queries) RuleLetters(ctx context.Context, ids []int64) ([]InvoicesReminder, error) {
	rows, err := q.db.Query(ctx, ruleLetters, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesReminder
	for rows.Next() {
		var i InvoicesReminder
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.RunID,
			&i.PrintBatchID,
			&i.Sequence,
			&i.Level,
			&i.AnnouncesCollection,
			&i.Channel,
			&i.Recipient,
			&i.Language,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.SentOn,
			&i.Deadline,
			&i.Regime,
			&i.PrincipalOpen,
			&i.Credited,
			&i.FeeKind,
			&i.Fee,
			&i.Compensation,
			&i.ChargesEarlier,
			&i.Interest,
			&i.InterestWaived,
			&i.InterestPaid,
			&i.InterestFrom,
			&i.InterestSegments,
			&i.Inkassosats,
			&i.Total,
			&i.ChargeNotes,
			&i.PdfObjectKey,
			&i.PdfSha256,
			&i.MessageID,
			&i.SentAt,
			&i.Status,
			&i.HeldReason,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.FirstAttemptAt,
			&i.LeaseID,
			&i.LeaseUntil,
			&i.LastError,
			&i.FailedAt,
			&i.WithdrawnAt,
			&i.WithdrawnByUserID,
			&i.WithdrawalReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rulePayments = `-- name: RulePayments :many
SELECT p.invoice_id, p.paid_on, p.amount, t.ordered_on
FROM invoices.payments p
LEFT JOIN invoices.bank_transactions t ON t.id = p.bank_transaction_id
WHERE p.invoice_id = ANY($1::bigint[]) AND p.removed_at IS NULL
ORDER BY p.invoice_id, p.paid_on, p.id
`

type RulePaymentsRow struct {
	InvoiceID int64
	PaidOn    pgtype.Date
	Amount    pgtype.Numeric
	OrderedOn pgtype.Date
}

// RulePayments is the live payments of the invoices, each with its bank
// line's ordered_on (OCR's oppdragsdato; NULL for a manual payment and for
// camt, reading 32), the deadline-met rule's day.
func (q *Queries) RulePayments(ctx context.Context, ids []int64) ([]RulePaymentsRow, error) {
	rows, err := q.db.Query(ctx, rulePayments, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RulePaymentsRow
	for rows.Next() {
		var i RulePaymentsRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.PaidOn,
			&i.Amount,
			&i.OrderedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rulePolicies = `-- name: RulePolicies :many
SELECT i.id AS invoice_id, p.mode
FROM invoices.invoices i
JOIN invoices.customer_reminder_policies p ON p.customer_id = i.customer_id
WHERE i.id = ANY($1::bigint[])
ORDER BY i.id
`

type RulePoliciesRow struct {
	InvoiceID int64
	Mode      string
}

// RulePolicies is the reminder policy of each invoice's customer, for the
// invoices whose customer has one; no row is normal (D7).
func (q *Queries) RulePolicies(ctx context.Context, ids []int64) ([]RulePoliciesRow, error) {
	rows, err := q.db.Query(ctx, rulePolicies, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RulePoliciesRow
	for rows.Next() {
		var i RulePoliciesRow
		if err := rows.Scan(&i.InvoiceID, &i.Mode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ruleWaivers = `-- name: RuleWaivers :many
SELECT id, invoice_id, reminder_id, kind, amount, interest_through, reason, note, waived_by_user_id, waived_at FROM invoices.charge_waivers
WHERE invoice_id = ANY($1::bigint[])
ORDER BY invoice_id, id
`

// RuleWaivers is every charge waiver of the invoices; a waiver is never
// removed, so every row counts.
func (q *Queries) RuleWaivers(ctx context.Context, ids []int64) ([]InvoicesChargeWaiver, error) {
	rows, err := q.db.Query(ctx, ruleWaivers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesChargeWaiver
	for rows.Next() {
		var i InvoicesChargeWaiver
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.ReminderID,
			&i.Kind,
			&i.Amount,
			&i.InterestThrough,
			&i.Reason,
			&i.Note,
			&i.WaivedByUserID,
			&i.WaivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
