// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transmissions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeTransmissionExists = `-- name: ActiveTransmissionExists :one
SELECT EXISTS (
    SELECT 1 FROM invoices.transmissions
    WHERE invoice_id = $1 AND status IN ('queued', 'submitted', 'delivered', 'unconfirmed')
) AS active
`

// ActiveTransmissionExists is whether a live transmission blocks a new send:
// the predicate of ux_transmissions_active.
func (q *Queries) ActiveTransmissionExists(ctx context.Context, invoiceID int64) (bool, error) {
	row := q.db.QueryRow(ctx, activeTransmissionExists, invoiceID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const activeTransmissionsCount = `-- name: ActiveTransmissionsCount :one
SELECT count(*) FROM invoices.transmissions WHERE status IN ('queued', 'submitted', 'unconfirmed')
`

// ActiveTransmissionsCount is how many transmissions the credentials still
// serve (D7): a DELETE or a provider switch is refused while any is queued,
// submitted or unconfirmed.
func (q *Queries) ActiveTransmissionsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, activeTransmissionsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const anyAwaitingEvents = `-- name: AnyAwaitingEvents :one
SELECT EXISTS (
    SELECT 1 FROM invoices.transmissions
    WHERE status = 'submitted'
       OR (status = 'unconfirmed' AND (
             next_attempt_at <> 'infinity'::timestamptz
             OR (provider_ref IS NULL AND queued_at + interval '14 days' > $1::timestamptz)))
       OR (status = 'queued' AND submit_attempted_at IS NOT NULL)
) AS awaiting
`

// AnyAwaitingEvents is whether the events worker has anything to drain for:
// a submitted row, a queued one whose marker is set, or an unconfirmed one
// still probed or recently queued without a reference. An unconfirmed row
// parked at 'infinity' with a reference waits for a person. One parked
// without a reference (parked the moment it became unconfirmed) can be
// resolved by the machine only through an event matched by its key, so it is
// listened for until fourteen days after its queueing: the 48-hour cap, the
// seven days submitted, and some days of the life of an event. An event for any
// row still in the queue is applied whenever a drain runs.
func (q *Queries) AnyAwaitingEvents(ctx context.Context, now time.Time) (bool, error) {
	row := q.db.QueryRow(ctx, anyAwaitingEvents, now)
	var awaiting bool
	err := row.Scan(&awaiting)
	return awaiting, err
}

const applyEventDelivered = `-- name: ApplyEventDelivered :execrows
UPDATE invoices.transmissions SET
    status = 'delivered', delivered_at = $1::timestamptz, next_attempt_at = $1::timestamptz,
    provider_ref = COALESCE(provider_ref, NULLIF($2::text, '')),
    resolution_note = CASE WHEN status = 'unconfirmed' THEN $3 ELSE resolution_note END,
    poll_attempts = 0, last_error = NULL
WHERE (idempotency_key = $4
       OR (provider_ref = $2::text AND provider_ref IS NOT NULL AND $2::text <> ''))
  AND status IN ('queued', 'submitted', 'unconfirmed')
`

type ApplyEventDeliveredParams struct {
	Now            time.Time
	ProviderRef    *string
	MachineNote    *string
	IdempotencyKey uuid.UUID
}

// ApplyEventDelivered applies a "succeeded" event from the provider's queue
// (D9), idempotently and without a lease: the row is matched by its provider
// reference, or by its idempotency key when it never learned the reference,
// which it then takes. 0 rows is an event for a row already final, or not
// ours. An empty reference never matches and is never stored.
func (q *Queries) ApplyEventDelivered(ctx context.Context, arg ApplyEventDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyEventDelivered,
		arg.Now,
		arg.ProviderRef,
		arg.MachineNote,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyEventFailed = `-- name: ApplyEventFailed :execrows
UPDATE invoices.transmissions SET
    status = 'failed', failed_at = $1::timestamptz, last_error = $2,
    provider_ref = COALESCE(provider_ref, NULLIF($3::text, '')),
    resolution_note = CASE WHEN status = 'unconfirmed' THEN $4 ELSE resolution_note END
WHERE (idempotency_key = $5
       OR (provider_ref = $3::text AND provider_ref IS NOT NULL AND $3::text <> ''))
  AND status IN ('queued', 'submitted', 'unconfirmed')
`

type ApplyEventFailedParams struct {
	Now            time.Time
	LastError      *string
	ProviderRef    *string
	MachineNote    *string
	IdempotencyKey uuid.UUID
}

// ApplyEventFailed applies a "failed" or "no_action_taken" event the same way.
func (q *Queries) ApplyEventFailed(ctx context.Context, arg ApplyEventFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyEventFailed,
		arg.Now,
		arg.LastError,
		arg.ProviderRef,
		arg.MachineNote,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelCustomerUnattemptedTransmissions = `-- name: CancelCustomerUnattemptedTransmissions :execrows
UPDATE invoices.transmissions SET status = 'cancelled', cancelled_at = $1::timestamptz
WHERE invoice_id IN (SELECT i.id FROM invoices.invoices i WHERE i.customer_id = $2)
  AND status = 'queued' AND submit_attempted_at IS NULL
`

type CancelCustomerUnattemptedTransmissionsParams struct {
	Now        time.Time
	CustomerID int32
}

// CancelCustomerUnattemptedTransmissions cancels, at an erase, every queued
// transmission of the customer's documents that was never attempted, leased
// or not (D12): a worker holding one stamps its marker only on a row still
// queued (MarkSubmitAttempted), so it finds the row cancelled and never
// posts it.
func (q *Queries) CancelCustomerUnattemptedTransmissions(ctx context.Context, arg CancelCustomerUnattemptedTransmissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelCustomerUnattemptedTransmissions, arg.Now, arg.CustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelUnattemptedTransmission = `-- name: CancelUnattemptedTransmission :execrows
UPDATE invoices.transmissions SET status = 'cancelled', cancelled_at = $1::timestamptz
WHERE id = $2 AND invoice_id = $3 AND status = 'queued' AND submit_attempted_at IS NULL
  AND (lease_until IS NULL OR lease_until < $1::timestamptz)
`

type CancelUnattemptedTransmissionParams struct {
	Now       time.Time
	ID        int64
	InvoiceID int64
}

// CancelUnattemptedTransmission cancels a queued row that was never attempted
// and is not leased (D9). 0 rows is 409 transmission_not_cancellable.
func (q *Queries) CancelUnattemptedTransmission(ctx context.Context, arg CancelUnattemptedTransmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelUnattemptedTransmission, arg.Now, arg.ID, arg.InvoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimTransmission = `-- name: ClaimTransmission :one
UPDATE invoices.transmissions SET lease_id = $1, lease_until = $2::timestamptz
WHERE id = (
    SELECT t.id FROM invoices.transmissions t
    WHERE ((t.status = 'queued' AND (NOT $3::boolean OR t.queued_at + interval '48 hours' < $4::timestamptz))
           OR t.status IN ('submitted', 'unconfirmed')
           OR (t.status = 'delivered' AND t.evidence_object_key IS NULL AND t.provider_ref IS NOT NULL))
      AND t.next_attempt_at <= $4::timestamptz
      AND (t.lease_until IS NULL OR t.lease_until < $4::timestamptz)
    ORDER BY t.next_attempt_at, t.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, invoice_id, provider, idempotency_key, sender_participant, receiver_participant, document_type, process_id, ubl_object_key, ubl_sha256, pdf_sha256, status, provider_ref, evidence_object_key, evidence_sha256, submit_attempts, poll_attempts, next_attempt_at, submit_attempted_at, lease_id, lease_until, last_error, lookup_registered, lookup_can_receive, lookup_at, queued_at, submitted_at, delivered_at, failed_at, cancelled_at, resolved_by_user_id, resolution_note, created_by_user_id
`

type ClaimTransmissionParams struct {
	LeaseID    *string
	LeaseUntil time.Time
	SkipQueued bool
	Now        time.Time
}

// ClaimTransmission leases the next due row (D9): in flight, or delivered with
// a reference and no evidence yet — ix_transmissions_due's predicate — due by
// @now, and not leased by a worker whose lease still runs. One conditional
// UPDATE over a SKIP LOCKED pick, so two workers never take one row. No row
// is pgx.ErrNoRows: nothing is due. @skip_queued leaves every queued row
// alone, unleased, short of the 48-hour age cap: an installation whose
// Peppol lookup is disabled still probes and stores evidence and still caps
// a queued row by its age (a cap makes no call), but never submits (D9).
func (q *Queries) ClaimTransmission(ctx context.Context, arg ClaimTransmissionParams) (InvoicesTransmission, error) {
	row := q.db.QueryRow(ctx, claimTransmission,
		arg.LeaseID,
		arg.LeaseUntil,
		arg.SkipQueued,
		arg.Now,
	)
	var i InvoicesTransmission
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Provider,
		&i.IdempotencyKey,
		&i.SenderParticipant,
		&i.ReceiverParticipant,
		&i.DocumentType,
		&i.ProcessID,
		&i.UblObjectKey,
		&i.UblSha256,
		&i.PdfSha256,
		&i.Status,
		&i.ProviderRef,
		&i.EvidenceObjectKey,
		&i.EvidenceSha256,
		&i.SubmitAttempts,
		&i.PollAttempts,
		&i.NextAttemptAt,
		&i.SubmitAttemptedAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.LookupRegistered,
		&i.LookupCanReceive,
		&i.LookupAt,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CancelledAt,
		&i.ResolvedByUserID,
		&i.ResolutionNote,
		&i.CreatedByUserID,
	)
	return i, err
}

const everyTransmissionOfDocuments = `-- name: EveryTransmissionOfDocuments :many
SELECT id, invoice_id, provider, idempotency_key, sender_participant, receiver_participant, document_type, process_id, ubl_object_key, ubl_sha256, pdf_sha256, status, provider_ref, evidence_object_key, evidence_sha256, submit_attempts, poll_attempts, next_attempt_at, submit_attempted_at, lease_id, lease_until, last_error, lookup_registered, lookup_can_receive, lookup_at, queued_at, submitted_at, delivered_at, failed_at, cancelled_at, resolved_by_user_id, resolution_note, created_by_user_id FROM invoices.transmissions
WHERE invoice_id = ANY($1::bigint[])
ORDER BY invoice_id, id
`

// EveryTransmissionOfDocuments is every transmission of a set of documents,
// each document's oldest first: a person's export (D12).
func (q *Queries) EveryTransmissionOfDocuments(ctx context.Context, invoiceIds []int64) ([]InvoicesTransmission, error) {
	rows, err := q.db.Query(ctx, everyTransmissionOfDocuments, invoiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesTransmission
	for rows.Next() {
		var i InvoicesTransmission
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Provider,
			&i.IdempotencyKey,
			&i.SenderParticipant,
			&i.ReceiverParticipant,
			&i.DocumentType,
			&i.ProcessID,
			&i.UblObjectKey,
			&i.UblSha256,
			&i.PdfSha256,
			&i.Status,
			&i.ProviderRef,
			&i.EvidenceObjectKey,
			&i.EvidenceSha256,
			&i.SubmitAttempts,
			&i.PollAttempts,
			&i.NextAttemptAt,
			&i.SubmitAttemptedAt,
			&i.LeaseID,
			&i.LeaseUntil,
			&i.LastError,
			&i.LookupRegistered,
			&i.LookupCanReceive,
			&i.LookupAt,
			&i.QueuedAt,
			&i.SubmittedAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.CancelledAt,
			&i.ResolvedByUserID,
			&i.ResolutionNote,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransmission = `-- name: GetTransmission :one
SELECT id, invoice_id, provider, idempotency_key, sender_participant, receiver_participant, document_type, process_id, ubl_object_key, ubl_sha256, pdf_sha256, status, provider_ref, evidence_object_key, evidence_sha256, submit_attempts, poll_attempts, next_attempt_at, submit_attempted_at, lease_id, lease_until, last_error, lookup_registered, lookup_can_receive, lookup_at, queued_at, submitted_at, delivered_at, failed_at, cancelled_at, resolved_by_user_id, resolution_note, created_by_user_id FROM invoices.transmissions WHERE id = $1
`

// GetTransmission re-reads one row by id.
func (q *Queries) GetTransmission(ctx context.Context, id int64) (InvoicesTransmission, error) {
	row := q.db.QueryRow(ctx, getTransmission, id)
	var i InvoicesTransmission
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Provider,
		&i.IdempotencyKey,
		&i.SenderParticipant,
		&i.ReceiverParticipant,
		&i.DocumentType,
		&i.ProcessID,
		&i.UblObjectKey,
		&i.UblSha256,
		&i.PdfSha256,
		&i.Status,
		&i.ProviderRef,
		&i.EvidenceObjectKey,
		&i.EvidenceSha256,
		&i.SubmitAttempts,
		&i.PollAttempts,
		&i.NextAttemptAt,
		&i.SubmitAttemptedAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.LookupRegistered,
		&i.LookupCanReceive,
		&i.LookupAt,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CancelledAt,
		&i.ResolvedByUserID,
		&i.ResolutionNote,
		&i.CreatedByUserID,
	)
	return i, err
}

const insertTransmission = `-- name: InsertTransmission :one

INSERT INTO invoices.transmissions (
    invoice_id, provider, idempotency_key, sender_participant, receiver_participant,
    document_type, process_id, ubl_object_key, ubl_sha256, pdf_sha256,
    next_attempt_at, lookup_registered, lookup_can_receive, lookup_at, queued_at, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11::timestamptz, $12, $13, $14::timestamptz, $11::timestamptz, $15
)
RETURNING id, invoice_id, provider, idempotency_key, sender_participant, receiver_participant, document_type, process_id, ubl_object_key, ubl_sha256, pdf_sha256, status, provider_ref, evidence_object_key, evidence_sha256, submit_attempts, poll_attempts, next_attempt_at, submit_attempted_at, lease_id, lease_until, last_error, lookup_registered, lookup_can_receive, lookup_at, queued_at, submitted_at, delivered_at, failed_at, cancelled_at, resolved_by_user_id, resolution_note, created_by_user_id
`

type InsertTransmissionParams struct {
	InvoiceID           int64
	Provider            string
	IdempotencyKey      uuid.UUID
	SenderParticipant   string
	ReceiverParticipant string
	DocumentType        string
	ProcessID           string
	UblObjectKey        string
	UblSha256           string
	PdfSha256           string
	Now                 time.Time
	LookupRegistered    bool
	LookupCanReceive    bool
	LookupAt            time.Time
	CreatedByUserID     uuid.UUID
}

// The EHF transmissions (EHF and KID design D8-D10): the send's insert, the
// reads the document response and the list make, the invoices-ehf worker's
// claim and its lease-checked completions, the events worker's idempotent
// updates, cancel and resolve. Every time here is a parameter (@now) from
// Deps.Clock(), never SQL now(): the harness clock sits weeks from the
// database's, and a lease judged by now() would always look expired. The
// trigger tr_transmissions_immutable lets only the state columns change.
//
// Every completion of a claim is WHERE id = @id AND lease_id = @lease_id AND
// status = @status, @status the status the claim saw: a row the events worker
// moved meanwhile (it takes no lease) answers 0 rows, a no-op, never the
// trigger's refusal of a change to a final row. A completion that can move an
// unconfirmed row writes @machine_note as its resolution_note — the machine's
// resolution, with no user — and leaves the note alone on any other row.
// InsertTransmission queues one transmission (D8), due at once. The trigger
// refuses a draft's and an anonymised customer's; ux_transmissions_active
// refuses a second live one for the same document (23505).
func (q *Queries) InsertTransmission(ctx context.Context, arg InsertTransmissionParams) (InvoicesTransmission, error) {
	row := q.db.QueryRow(ctx, insertTransmission,
		arg.InvoiceID,
		arg.Provider,
		arg.IdempotencyKey,
		arg.SenderParticipant,
		arg.ReceiverParticipant,
		arg.DocumentType,
		arg.ProcessID,
		arg.UblObjectKey,
		arg.UblSha256,
		arg.PdfSha256,
		arg.Now,
		arg.LookupRegistered,
		arg.LookupCanReceive,
		arg.LookupAt,
		arg.CreatedByUserID,
	)
	var i InvoicesTransmission
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Provider,
		&i.IdempotencyKey,
		&i.SenderParticipant,
		&i.ReceiverParticipant,
		&i.DocumentType,
		&i.ProcessID,
		&i.UblObjectKey,
		&i.UblSha256,
		&i.PdfSha256,
		&i.Status,
		&i.ProviderRef,
		&i.EvidenceObjectKey,
		&i.EvidenceSha256,
		&i.SubmitAttempts,
		&i.PollAttempts,
		&i.NextAttemptAt,
		&i.SubmitAttemptedAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.LookupRegistered,
		&i.LookupCanReceive,
		&i.LookupAt,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CancelledAt,
		&i.ResolvedByUserID,
		&i.ResolutionNote,
		&i.CreatedByUserID,
	)
	return i, err
}

const latestPersonResolvedFailedTransmission = `-- name: LatestPersonResolvedFailedTransmission :one
SELECT id, invoice_id, provider, idempotency_key, sender_participant, receiver_participant, document_type, process_id, ubl_object_key, ubl_sha256, pdf_sha256, status, provider_ref, evidence_object_key, evidence_sha256, submit_attempts, poll_attempts, next_attempt_at, submit_attempted_at, lease_id, lease_until, last_error, lookup_registered, lookup_can_receive, lookup_at, queued_at, submitted_at, delivered_at, failed_at, cancelled_at, resolved_by_user_id, resolution_note, created_by_user_id FROM invoices.transmissions
WHERE invoice_id = $1 AND status = 'failed' AND resolved_by_user_id IS NOT NULL
ORDER BY id DESC LIMIT 1
`

// LatestPersonResolvedFailedTransmission is the newest of one document's
// transmissions that was unconfirmed and that a person resolved as failed,
// among all of the document's rows: its bytes may have reached the receiver,
// so every later send carries them (D4's reuse rule) — a reused send that is
// later cancelled leaves the next send carrying them still. No row is
// pgx.ErrNoRows: the send renders fresh.
func (q *Queries) LatestPersonResolvedFailedTransmission(ctx context.Context, invoiceID int64) (InvoicesTransmission, error) {
	row := q.db.QueryRow(ctx, latestPersonResolvedFailedTransmission, invoiceID)
	var i InvoicesTransmission
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Provider,
		&i.IdempotencyKey,
		&i.SenderParticipant,
		&i.ReceiverParticipant,
		&i.DocumentType,
		&i.ProcessID,
		&i.UblObjectKey,
		&i.UblSha256,
		&i.PdfSha256,
		&i.Status,
		&i.ProviderRef,
		&i.EvidenceObjectKey,
		&i.EvidenceSha256,
		&i.SubmitAttempts,
		&i.PollAttempts,
		&i.NextAttemptAt,
		&i.SubmitAttemptedAt,
		&i.LeaseID,
		&i.LeaseUntil,
		&i.LastError,
		&i.LookupRegistered,
		&i.LookupCanReceive,
		&i.LookupAt,
		&i.QueuedAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CancelledAt,
		&i.ResolvedByUserID,
		&i.ResolutionNote,
		&i.CreatedByUserID,
	)
	return i, err
}

const markDeliveredLeased = `-- name: MarkDeliveredLeased :execrows
UPDATE invoices.transmissions SET
    status = 'delivered', delivered_at = $1::timestamptz, next_attempt_at = $1::timestamptz,
    resolution_note = CASE WHEN status = 'unconfirmed' THEN $2 ELSE resolution_note END,
    poll_attempts = 0, last_error = NULL, lease_id = NULL, lease_until = NULL
WHERE id = $3 AND lease_id = $4 AND status = $5::text
`

type MarkDeliveredLeasedParams struct {
	Now         time.Time
	MachineNote *string
	ID          int64
	LeaseID     *string
	Status      string
}

// MarkDeliveredLeased records delivery a probe found (the evidence answered)
// on a submitted or unconfirmed row, with the evidence due at once in the
// next claim. resolved_by_user_id stays NULL: the machine resolved it.
func (q *Queries) MarkDeliveredLeased(ctx context.Context, arg MarkDeliveredLeasedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeliveredLeased,
		arg.Now,
		arg.MachineNote,
		arg.ID,
		arg.LeaseID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFailedLeased = `-- name: MarkFailedLeased :execrows
UPDATE invoices.transmissions SET
    status = 'failed', failed_at = $1::timestamptz, last_error = $2,
    resolution_note = CASE WHEN status = 'unconfirmed' THEN $3 ELSE resolution_note END,
    lease_id = NULL, lease_until = NULL
WHERE id = $4 AND lease_id = $5 AND status = $6::text
`

type MarkFailedLeasedParams struct {
	Now         time.Time
	LastError   *string
	MachineNote *string
	ID          int64
	LeaseID     *string
	Status      string
}

// MarkFailedLeased ends a claimed row (queued, submitted or unconfirmed) as
// failed with its (redacted) reason.
func (q *Queries) MarkFailedLeased(ctx context.Context, arg MarkFailedLeasedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFailedLeased,
		arg.Now,
		arg.LastError,
		arg.MachineNote,
		arg.ID,
		arg.LeaseID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSubmitAttempted = `-- name: MarkSubmitAttempted :execrows
UPDATE invoices.transmissions SET submit_attempted_at = $1::timestamptz
WHERE id = $2 AND lease_id = $3 AND status = 'queued'
`

type MarkSubmitAttemptedParams struct {
	Now     time.Time
	ID      int64
	LeaseID *string
}

// MarkSubmitAttempted stamps the crash marker immediately before the provider
// is called, auto-committed, under the claim's lease (D9).
func (q *Queries) MarkSubmitAttempted(ctx context.Context, arg MarkSubmitAttemptedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSubmitAttempted, arg.Now, arg.ID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSubmitted = `-- name: MarkSubmitted :execrows
UPDATE invoices.transmissions SET
    status = 'submitted', provider_ref = $1, submitted_at = $2::timestamptz,
    next_attempt_at = $3::timestamptz, poll_attempts = 0, last_error = NULL,
    lease_id = NULL, lease_until = NULL
WHERE id = $4 AND status = 'queued' AND lease_id = $5
`

type MarkSubmittedParams struct {
	ProviderRef   *string
	Now           time.Time
	NextAttemptAt time.Time
	ID            int64
	LeaseID       *string
}

// MarkSubmitted records the provider's acceptance with its reference, the
// first probe due at @next_attempt_at, and releases the lease.
func (q *Queries) MarkSubmitted(ctx context.Context, arg MarkSubmittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSubmitted,
		arg.ProviderRef,
		arg.Now,
		arg.NextAttemptAt,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSubmittedWithoutRef = `-- name: MarkSubmittedWithoutRef :execrows
UPDATE invoices.transmissions SET
    status = 'submitted', submitted_at = $1::timestamptz, next_attempt_at = $2::timestamptz,
    last_error = $3, lease_id = NULL, lease_until = NULL
WHERE id = $4 AND status = 'queued' AND lease_id = $5
`

type MarkSubmittedWithoutRefParams struct {
	Now           time.Time
	NextAttemptAt time.Time
	LastError     *string
	ID            int64
	LeaseID       *string
}

// MarkSubmittedWithoutRef is the 422 on a retry (D9): the submission may have
// gone through, so the row waits for the queue drain to resolve it by its
// idempotency key, rescheduled at @next_attempt_at and never probed.
func (q *Queries) MarkSubmittedWithoutRef(ctx context.Context, arg MarkSubmittedWithoutRefParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSubmittedWithoutRef,
		arg.Now,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUnconfirmedLeased = `-- name: MarkUnconfirmedLeased :execrows
UPDATE invoices.transmissions SET
    status = 'unconfirmed',
    next_attempt_at = CASE WHEN $1::boolean THEN 'infinity'::timestamptz ELSE $2::timestamptz END,
    last_error = $3,
    lease_id = NULL, lease_until = NULL
WHERE id = $4 AND lease_id = $5 AND status = $6::text
`

type MarkUnconfirmedLeasedParams struct {
	Park          bool
	NextAttemptAt time.Time
	LastError     *string
	ID            int64
	LeaseID       *string
	Status        string
}

// MarkUnconfirmedLeased hands a claimed row to a person (D9): the cap by age
// on a queued row whose marker is set, or seven days submitted. The worker
// keeps probing it at @next_attempt_at, or never when @park ('infinity':
// the row waits for a person).
func (q *Queries) MarkUnconfirmedLeased(ctx context.Context, arg MarkUnconfirmedLeasedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUnconfirmedLeased,
		arg.Park,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
		arg.LeaseID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queuedTransmissionsDue = `-- name: QueuedTransmissionsDue :one
SELECT count(*) FROM invoices.transmissions WHERE status = 'queued' AND next_attempt_at <= $1::timestamptz
`

// QueuedTransmissionsDue is how many queued rows are due by @now: what an
// installation whose Peppol lookup is disabled leaves alone, said once per
// cycle.
func (q *Queries) QueuedTransmissionsDue(ctx context.Context, now time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, queuedTransmissionsDue, now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const refreshTransmissionLookup = `-- name: RefreshTransmissionLookup :execrows
UPDATE invoices.transmissions SET
    lookup_registered = $1, lookup_can_receive = $2, lookup_at = $3::timestamptz
WHERE id = $4 AND lease_id = $5 AND status = 'queued'
`

type RefreshTransmissionLookupParams struct {
	LookupRegistered bool
	LookupCanReceive bool
	Now              time.Time
	ID               int64
	LeaseID          *string
}

// RefreshTransmissionLookup records a queued row's fresh receiver lookup,
// made in its claim when the old one is older than a day (D9).
func (q *Queries) RefreshTransmissionLookup(ctx context.Context, arg RefreshTransmissionLookupParams) (int64, error) {
	result, err := q.db.Exec(ctx, refreshTransmissionLookup,
		arg.LookupRegistered,
		arg.LookupCanReceive,
		arg.Now,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleLeased = `-- name: RescheduleLeased :execrows
UPDATE invoices.transmissions SET
    next_attempt_at = CASE WHEN $1::boolean THEN 'infinity'::timestamptz ELSE $2::timestamptz END,
    submit_attempts = submit_attempts + $3::integer,
    poll_attempts = poll_attempts + $4::integer,
    last_error = $5,
    lease_id = NULL, lease_until = NULL
WHERE id = $6 AND lease_id = $7 AND status = $8::text
`

type RescheduleLeasedParams struct {
	Park                bool
	NextAttemptAt       time.Time
	SubmitAttemptsDelta int32
	PollAttemptsDelta   int32
	LastError           *string
	ID                  int64
	LeaseID             *string
	Status              string
}

// RescheduleLeased puts a claimed row back for later: the backoff after a
// transport failure (submit_attempts + 1), the probe cadence (poll_attempts
// + 1), or an hour out after a refused key (neither counted). @park puts it
// at 'infinity' instead: an unconfirmed row the machine stops probing.
func (q *Queries) RescheduleLeased(ctx context.Context, arg RescheduleLeasedParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleLeased,
		arg.Park,
		arg.NextAttemptAt,
		arg.SubmitAttemptsDelta,
		arg.PollAttemptsDelta,
		arg.LastError,
		arg.ID,
		arg.LeaseID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveTransmission = `-- name: ResolveTransmission :execrows
UPDATE invoices.transmissions SET
    status = $1::text,
    delivered_at = CASE WHEN $1::text = 'delivered' THEN $2::timestamptz ELSE delivered_at END,
    failed_at = CASE WHEN $1::text = 'failed' THEN $2::timestamptz ELSE failed_at END,
    next_attempt_at = $2::timestamptz,
    resolved_by_user_id = $3, resolution_note = $4,
    lease_id = NULL, lease_until = NULL
WHERE id = $5 AND invoice_id = $6 AND status = 'unconfirmed'
  AND $1::text IN ('delivered', 'failed')
`

type ResolveTransmissionParams struct {
	Outcome          string
	Now              time.Time
	ResolvedByUserID *uuid.UUID
	ResolutionNote   *string
	ID               int64
	InvoiceID        int64
}

// ResolveTransmission is a person's verdict on an unconfirmed row (D9):
// delivered or failed, who and why. 0 rows is 409
// transmission_not_resolvable.
func (q *Queries) ResolveTransmission(ctx context.Context, arg ResolveTransmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveTransmission,
		arg.Outcome,
		arg.Now,
		arg.ResolvedByUserID,
		arg.ResolutionNote,
		arg.ID,
		arg.InvoiceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreSubmitAttempted = `-- name: RestoreSubmitAttempted :execrows
UPDATE invoices.transmissions SET submit_attempted_at = $1::timestamptz
WHERE id = $2 AND lease_id = $3 AND status = 'queued'
`

type RestoreSubmitAttemptedParams struct {
	Previous *time.Time
	ID       int64
	LeaseID  *string
}

// RestoreSubmitAttempted puts the crash marker back to its pre-claim value
// (NULL or the earlier stamp) when the outcome proves the provider did not
// take the document: a 401, a 403, a 429 or a refusal before any call.
func (q *Queries) RestoreSubmitAttempted(ctx context.Context, arg RestoreSubmitAttemptedParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreSubmitAttempted, arg.Previous, arg.ID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEvidenceLeased = `-- name: SetEvidenceLeased :execrows
UPDATE invoices.transmissions SET
    evidence_object_key = $1, evidence_sha256 = $2,
    last_error = NULL, lease_id = NULL, lease_until = NULL
WHERE id = $3 AND lease_id = $4 AND status = 'delivered' AND evidence_object_key IS NULL
`

type SetEvidenceLeasedParams struct {
	EvidenceObjectKey *string
	EvidenceSha256    *string
	ID                int64
	LeaseID           *string
}

// SetEvidenceLeased stores where a delivered row's evidence is, once; from
// then on the row is final.
func (q *Queries) SetEvidenceLeased(ctx context.Context, arg SetEvidenceLeasedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEvidenceLeased,
		arg.EvidenceObjectKey,
		arg.EvidenceSha256,
		arg.ID,
		arg.LeaseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transmissionsOf = `-- name: TransmissionsOf :many
SELECT id, invoice_id, provider, idempotency_key, sender_participant, receiver_participant, document_type, process_id, ubl_object_key, ubl_sha256, pdf_sha256, status, provider_ref, evidence_object_key, evidence_sha256, submit_attempts, poll_attempts, next_attempt_at, submit_attempted_at, lease_id, lease_until, last_error, lookup_registered, lookup_can_receive, lookup_at, queued_at, submitted_at, delivered_at, failed_at, cancelled_at, resolved_by_user_id, resolution_note, created_by_user_id FROM invoices.transmissions WHERE invoice_id = $1 ORDER BY id DESC
`

// TransmissionsOf is every transmission of one document, the newest first.
func (q *Queries) TransmissionsOf(ctx context.Context, invoiceID int64) ([]InvoicesTransmission, error) {
	rows, err := q.db.Query(ctx, transmissionsOf, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesTransmission
	for rows.Next() {
		var i InvoicesTransmission
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Provider,
			&i.IdempotencyKey,
			&i.SenderParticipant,
			&i.ReceiverParticipant,
			&i.DocumentType,
			&i.ProcessID,
			&i.UblObjectKey,
			&i.UblSha256,
			&i.PdfSha256,
			&i.Status,
			&i.ProviderRef,
			&i.EvidenceObjectKey,
			&i.EvidenceSha256,
			&i.SubmitAttempts,
			&i.PollAttempts,
			&i.NextAttemptAt,
			&i.SubmitAttemptedAt,
			&i.LeaseID,
			&i.LeaseUntil,
			&i.LastError,
			&i.LookupRegistered,
			&i.LookupCanReceive,
			&i.LookupAt,
			&i.QueuedAt,
			&i.SubmittedAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.CancelledAt,
			&i.ResolvedByUserID,
			&i.ResolutionNote,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transmissionsOfDocuments = `-- name: TransmissionsOfDocuments :many
SELECT DISTINCT ON (invoice_id) id, invoice_id, provider, idempotency_key, sender_participant, receiver_participant, document_type, process_id, ubl_object_key, ubl_sha256, pdf_sha256, status, provider_ref, evidence_object_key, evidence_sha256, submit_attempts, poll_attempts, next_attempt_at, submit_attempted_at, lease_id, lease_until, last_error, lookup_registered, lookup_can_receive, lookup_at, queued_at, submitted_at, delivered_at, failed_at, cancelled_at, resolved_by_user_id, resolution_note, created_by_user_id
FROM invoices.transmissions
WHERE invoice_id = ANY($1::bigint[])
ORDER BY invoice_id, id DESC
`

// TransmissionsOfDocuments is the newest transmission of each of a page of
// documents: the list's ehfStatus (D10).
func (q *Queries) TransmissionsOfDocuments(ctx context.Context, invoiceIds []int64) ([]InvoicesTransmission, error) {
	rows, err := q.db.Query(ctx, transmissionsOfDocuments, invoiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesTransmission
	for rows.Next() {
		var i InvoicesTransmission
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Provider,
			&i.IdempotencyKey,
			&i.SenderParticipant,
			&i.ReceiverParticipant,
			&i.DocumentType,
			&i.ProcessID,
			&i.UblObjectKey,
			&i.UblSha256,
			&i.PdfSha256,
			&i.Status,
			&i.ProviderRef,
			&i.EvidenceObjectKey,
			&i.EvidenceSha256,
			&i.SubmitAttempts,
			&i.PollAttempts,
			&i.NextAttemptAt,
			&i.SubmitAttemptedAt,
			&i.LeaseID,
			&i.LeaseUntil,
			&i.LastError,
			&i.LookupRegistered,
			&i.LookupCanReceive,
			&i.LookupAt,
			&i.QueuedAt,
			&i.SubmittedAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.CancelledAt,
			&i.ResolvedByUserID,
			&i.ResolutionNote,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
