// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHeldSourcesOf = `-- name: DeleteHeldSourcesOf :many
DELETE FROM invoices.line_sources
WHERE invoice_id = $1 AND state = 'held'
RETURNING source_kind, source_id
`

type DeleteHeldSourcesOfRow struct {
	SourceKind string
	SourceID   int64
}

// DeleteHeldSourcesOf drops every hold of a draft — a customer change (D2) —
// and answers what it released.
func (q *Queries) DeleteHeldSourcesOf(ctx context.Context, invoiceID int64) ([]DeleteHeldSourcesOfRow, error) {
	rows, err := q.db.Query(ctx, deleteHeldSourcesOf, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteHeldSourcesOfRow
	for rows.Next() {
		var i DeleteHeldSourcesOfRow
		if err := rows.Scan(&i.SourceKind, &i.SourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTimesheetRows = `-- name: DeleteTimesheetRows :exec
DELETE FROM invoices.timesheet_rows WHERE invoice_id = $1
`

// DeleteTimesheetRows clears a draft's timesheet: the flag turned off (D5).
func (q *Queries) DeleteTimesheetRows(ctx context.Context, invoiceID int64) error {
	_, err := q.db.Exec(ctx, deleteTimesheetRows, invoiceID)
	return err
}

const heldOnDrafts = `-- name: HeldOnDrafts :many
SELECT s.invoice_id, s.project_id, s.source_kind, count(*)::int AS held
FROM invoices.line_sources s
WHERE s.state = 'held' AND s.project_id = ANY($1::int[])
GROUP BY s.invoice_id, s.project_id, s.source_kind
ORDER BY s.project_id, s.source_kind, s.invoice_id
`

type HeldOnDraftsRow struct {
	InvoiceID  int64
	ProjectID  int32
	SourceKind string
	Held       int32
}

// HeldOnDrafts counts the held rows per draft, project and kind for the
// given projects: the view's heldOnDrafts (D3).
func (q *Queries) HeldOnDrafts(ctx context.Context, projectIds []int32) ([]HeldOnDraftsRow, error) {
	rows, err := q.db.Query(ctx, heldOnDrafts, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeldOnDraftsRow
	for rows.Next() {
		var i HeldOnDraftsRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.ProjectID,
			&i.SourceKind,
			&i.Held,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLineReleases = `-- name: InsertLineReleases :exec
INSERT INTO invoices.line_releases (invoice_id, credit_line_id, line_source_id)
SELECT $1::bigint, u.credit_line_id, u.line_source_id
FROM (
    SELECT unnest($2::bigint[]) AS credit_line_id, unnest($3::bigint[]) AS line_source_id
) AS u
ORDER BY u.line_source_id
`

type InsertLineReleasesParams struct {
	InvoiceID     int64
	CreditLineIds []int64
	LineSourceIds []int64
}

// InsertLineReleases records a credit note's releases (D8): each credit line
// (credit_line_ids[i]) and the original's source it released
// (line_source_ids[i]), in one statement.
func (q *Queries) InsertLineReleases(ctx context.Context, arg InsertLineReleasesParams) error {
	_, err := q.db.Exec(ctx, insertLineReleases, arg.InvoiceID, arg.CreditLineIds, arg.LineSourceIds)
	return err
}

const insertLineSources = `-- name: InsertLineSources :exec
INSERT INTO invoices.line_sources (
    line_id, invoice_id, source_kind, source_id, source_revision, source_subkind,
    project_id, quantity, amount, currency, source_date
)
SELECT u.line_id, $1::bigint, u.kind, u.id, u.revision, NULLIF(u.subkind, ''),
    u.project_id, u.quantity, u.amount, u.currency, u.source_date
FROM (
    SELECT unnest($2::bigint[]) AS line_id, unnest($3::text[]) AS kind,
        unnest($4::bigint[]) AS id, unnest($5::int[]) AS revision,
        unnest($6::text[]) AS subkind, unnest($7::int[]) AS project_id,
        unnest($8::numeric[]) AS quantity, unnest($9::numeric[]) AS amount,
        unnest($10::text[]) AS currency, unnest($11::date[]) AS source_date
) AS u
ORDER BY u.kind, u.id
`

type InsertLineSourcesParams struct {
	InvoiceID  int64
	LineIds    []int64
	Kinds      []string
	Ids        []int64
	Revisions  []int32
	Subkinds   []string
	ProjectIds []int32
	Quantities []pgtype.Numeric
	Amounts    []pgtype.Numeric
	Currencies []string
	Dates      []pgtype.Date
}

// InsertLineSources writes a document's sources held, in ONE statement
// ordered by (source_kind, source_id) (D2): two transactions inserting
// overlapping holds wait on ux_line_sources_live in the same order, so one
// fails with the unique violation and neither deadlocks. The arrays run in
// parallel; an empty subkind is NULL (only an expense carries one).
func (q *Queries) InsertLineSources(ctx context.Context, arg InsertLineSourcesParams) error {
	_, err := q.db.Exec(ctx, insertLineSources,
		arg.InvoiceID,
		arg.LineIds,
		arg.Kinds,
		arg.Ids,
		arg.Revisions,
		arg.Subkinds,
		arg.ProjectIds,
		arg.Quantities,
		arg.Amounts,
		arg.Currencies,
		arg.Dates,
	)
	return err
}

const insertTimesheetRows = `-- name: InsertTimesheetRows :exec
INSERT INTO invoices.timesheet_rows (
    invoice_id, position, source_id, person_label, entry_date, hours, work_type, description
)
SELECT $1::bigint, u.position, u.source_id, u.person_label, u.entry_date, u.hours,
    NULLIF(u.work_type, ''), u.description
FROM (
    SELECT unnest($2::int[]) AS position, unnest($3::bigint[]) AS source_id,
        unnest($4::text[]) AS person_label, unnest($5::date[]) AS entry_date,
        unnest($6::numeric[]) AS hours, unnest($7::text[]) AS work_type,
        unnest($8::text[]) AS description
) AS u
ORDER BY u.position
`

type InsertTimesheetRowsParams struct {
	InvoiceID    int64
	Positions    []int32
	SourceIds    []int64
	PersonLabels []string
	EntryDates   []pgtype.Date
	Hours        []pgtype.Numeric
	WorkTypes    []string
	Descriptions []string
}

// InsertTimesheetRows writes a draft's timesheet rows in one statement (D5):
// the arrays run in parallel; an empty work type is NULL. Never the entry's
// note.
func (q *Queries) InsertTimesheetRows(ctx context.Context, arg InsertTimesheetRowsParams) error {
	_, err := q.db.Exec(ctx, insertTimesheetRows,
		arg.InvoiceID,
		arg.Positions,
		arg.SourceIds,
		arg.PersonLabels,
		arg.EntryDates,
		arg.Hours,
		arg.WorkTypes,
		arg.Descriptions,
	)
	return err
}

const invoicedSourcesOfLines = `-- name: InvoicedSourcesOfLines :many
SELECT id, line_id, invoice_id, source_kind, source_id, source_revision, source_subkind, project_id, quantity, amount, currency, state, source_date FROM invoices.line_sources
WHERE line_id = ANY($1::bigint[]) AND state = 'invoiced'
ORDER BY source_kind, source_id
`

// InvoicedSourcesOfLines is the invoiced rows of the given lines: what a
// credit note that returns them in full releases (D8).
func (q *Queries) InvoicedSourcesOfLines(ctx context.Context, lineIds []int64) ([]InvoicesLineSource, error) {
	rows, err := q.db.Query(ctx, invoicedSourcesOfLines, lineIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesLineSource
	for rows.Next() {
		var i InvoicesLineSource
		if err := rows.Scan(
			&i.ID,
			&i.LineID,
			&i.InvoiceID,
			&i.SourceKind,
			&i.SourceID,
			&i.SourceRevision,
			&i.SourceSubkind,
			&i.ProjectID,
			&i.Quantity,
			&i.Amount,
			&i.Currency,
			&i.State,
			&i.SourceDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lineSourcesOf = `-- name: LineSourcesOf :many

SELECT s.id, s.line_id, s.invoice_id, s.source_kind, s.source_id, s.source_revision, s.source_subkind, s.project_id, s.quantity, s.amount, s.currency, s.state, s.source_date, l.position AS line_position
FROM invoices.line_sources s
JOIN invoices.lines l ON l.id = s.line_id
WHERE s.invoice_id = $1
ORDER BY l.position, s.source_kind, s.source_id
`

type LineSourcesOfRow struct {
	ID             int64
	LineID         int64
	InvoiceID      int64
	SourceKind     string
	SourceID       int64
	SourceRevision int32
	SourceSubkind  *string
	ProjectID      int32
	Quantity       pgtype.Numeric
	Amount         pgtype.Numeric
	Currency       string
	State          string
	SourceDate     pgtype.Date
	LinePosition   int32
}

// The work a document bills (invoices work design D2, D5, D8, D9): the line
// sources held from the draft, invoiced by the issue and released by the
// credit note that returns their line; the releases; the document's project;
// and the timesheet rows. A source's kind and id are opaque — the rows are
// other modules' (module-boundaries rule 4) — and a set is one statement:
// parallel arrays unnested side by side (equal lengths, so they zip).
// LineSourcesOf is one document's line sources with their line's position, in
// the lines' order and then by source.
func (q *Queries) LineSourcesOf(ctx context.Context, invoiceID int64) ([]LineSourcesOfRow, error) {
	rows, err := q.db.Query(ctx, lineSourcesOf, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LineSourcesOfRow
	for rows.Next() {
		var i LineSourcesOfRow
		if err := rows.Scan(
			&i.ID,
			&i.LineID,
			&i.InvoiceID,
			&i.SourceKind,
			&i.SourceID,
			&i.SourceRevision,
			&i.SourceSubkind,
			&i.ProjectID,
			&i.Quantity,
			&i.Amount,
			&i.Currency,
			&i.State,
			&i.SourceDate,
			&i.LinePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveSourcesElsewhere = `-- name: LiveSourcesElsewhere :many
SELECT s.source_kind, s.source_id, s.state, s.invoice_id, i.number, i.status
FROM invoices.line_sources s
JOIN invoices.invoices i ON i.id = s.invoice_id
WHERE s.state IN ('held', 'invoiced') AND s.invoice_id <> $1
  AND EXISTS (
    SELECT 1 FROM (SELECT unnest($2::text[]) AS kind, unnest($3::bigint[]) AS id) AS u
    WHERE u.kind = s.source_kind AND u.id = s.source_id)
ORDER BY s.id
`

type LiveSourcesElsewhereParams struct {
	InvoiceID int64
	Kinds     []string
	Ids       []int64
}

type LiveSourcesElsewhereRow struct {
	SourceKind string
	SourceID   int64
	State      string
	InvoiceID  int64
	Number     *int64
	Status     string
}

// LiveSourcesElsewhere is every held or invoiced row of the given sources
// (kinds[i], ids[i]) on a document other than invoice_id, with that
// document's number and status, the oldest first: what refuses a new hold
// with source_held_elsewhere (D2).
func (q *Queries) LiveSourcesElsewhere(ctx context.Context, arg LiveSourcesElsewhereParams) ([]LiveSourcesElsewhereRow, error) {
	rows, err := q.db.Query(ctx, liveSourcesElsewhere, arg.InvoiceID, arg.Kinds, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveSourcesElsewhereRow
	for rows.Next() {
		var i LiveSourcesElsewhereRow
		if err := rows.Scan(
			&i.SourceKind,
			&i.SourceID,
			&i.State,
			&i.InvoiceID,
			&i.Number,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveSourcesFor = `-- name: LiveSourcesFor :many
SELECT s.source_kind, s.source_id, s.state, s.invoice_id, i.number, i.status
FROM invoices.line_sources s
JOIN invoices.invoices i ON i.id = s.invoice_id
WHERE s.state IN ('held', 'invoiced')
  AND EXISTS (
    SELECT 1 FROM (SELECT unnest($1::text[]) AS kind, unnest($2::bigint[]) AS id) AS u
    WHERE u.kind = s.source_kind AND u.id = s.source_id)
ORDER BY s.source_kind, s.source_id
`

type LiveSourcesForParams struct {
	Kinds []string
	Ids   []int64
}

type LiveSourcesForRow struct {
	SourceKind string
	SourceID   int64
	State      string
	InvoiceID  int64
	Number     *int64
	Status     string
}

// LiveSourcesFor is every held or invoiced row of the given sources, with its
// document's number and status: the uninvoiced view lists such work as held,
// never selectable (D3).
func (q *Queries) LiveSourcesFor(ctx context.Context, arg LiveSourcesForParams) ([]LiveSourcesForRow, error) {
	rows, err := q.db.Query(ctx, liveSourcesFor, arg.Kinds, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveSourcesForRow
	for rows.Next() {
		var i LiveSourcesForRow
		if err := rows.Scan(
			&i.SourceKind,
			&i.SourceID,
			&i.State,
			&i.InvoiceID,
			&i.Number,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSourcesInvoiced = `-- name: MarkSourcesInvoiced :execrows
UPDATE invoices.line_sources SET state = 'invoiced'
WHERE invoice_id = $1 AND state = 'held'
`

// MarkSourcesInvoiced moves a draft's holds to invoiced in the issue's own
// step, while the document is still a draft — the one change the trigger
// allows there (D2).
func (q *Queries) MarkSourcesInvoiced(ctx context.Context, invoiceID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markSourcesInvoiced, invoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneTimesheetRows = `-- name: PruneTimesheetRows :execrows
DELETE FROM invoices.timesheet_rows
WHERE invoice_id = $1 AND source_id <> ALL($2::bigint[])
`

type PruneTimesheetRowsParams struct {
	InvoiceID int64
	Kept      []int64
}

// PruneTimesheetRows drops a draft's rows of hours it no longer holds (D5).
func (q *Queries) PruneTimesheetRows(ctx context.Context, arg PruneTimesheetRowsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneTimesheetRows, arg.InvoiceID, arg.Kept)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseSources = `-- name: ReleaseSources :many
UPDATE invoices.line_sources SET state = 'released'
WHERE id = ANY($1::bigint[]) AND state = 'invoiced'
RETURNING id, line_id, invoice_id, source_kind, source_id, source_revision, source_subkind, project_id, quantity, amount, currency, state, source_date
`

// ReleaseSources moves the given invoiced rows to released — the one change
// the trigger allows under an issued document (D2, D8) — and answers them.
func (q *Queries) ReleaseSources(ctx context.Context, ids []int64) ([]InvoicesLineSource, error) {
	rows, err := q.db.Query(ctx, releaseSources, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesLineSource
	for rows.Next() {
		var i InvoicesLineSource
		if err := rows.Scan(
			&i.ID,
			&i.LineID,
			&i.InvoiceID,
			&i.SourceKind,
			&i.SourceID,
			&i.SourceRevision,
			&i.SourceSubkind,
			&i.ProjectID,
			&i.Quantity,
			&i.Amount,
			&i.Currency,
			&i.State,
			&i.SourceDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasedHistoryOf = `-- name: ReleasedHistoryOf :many
SELECT s.source_kind, s.source_id, s.invoice_id AS original_invoice_id, o.number AS original_number,
    r.invoice_id AS credit_note_id, c.number AS credit_note_number
FROM invoices.line_sources s
JOIN invoices.invoices o ON o.id = s.invoice_id
JOIN invoices.line_releases r ON r.line_source_id = s.id
JOIN invoices.invoices c ON c.id = r.invoice_id
WHERE s.state = 'released'
  AND EXISTS (
    SELECT 1 FROM (SELECT unnest($1::text[]) AS kind, unnest($2::bigint[]) AS id) AS u
    WHERE u.kind = s.source_kind AND u.id = s.source_id)
ORDER BY c.issued_at DESC, r.id DESC
`

type ReleasedHistoryOfParams struct {
	Kinds []string
	Ids   []int64
}

type ReleasedHistoryOfRow struct {
	SourceKind        string
	SourceID          int64
	OriginalInvoiceID int64
	OriginalNumber    *int64
	CreditNoteID      int64
	CreditNoteNumber  *int64
}

// ReleasedHistoryOf is, for the given sources, each released row's original
// invoice and the credit note that released it, newest first: the note the
// wizard suggests when it pulls released work again (D8).
func (q *Queries) ReleasedHistoryOf(ctx context.Context, arg ReleasedHistoryOfParams) ([]ReleasedHistoryOfRow, error) {
	rows, err := q.db.Query(ctx, releasedHistoryOf, arg.Kinds, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleasedHistoryOfRow
	for rows.Next() {
		var i ReleasedHistoryOfRow
		if err := rows.Scan(
			&i.SourceKind,
			&i.SourceID,
			&i.OriginalInvoiceID,
			&i.OriginalNumber,
			&i.CreditNoteID,
			&i.CreditNoteNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasesOf = `-- name: ReleasesOf :many
SELECT r.id, r.credit_line_id, r.line_source_id, s.source_kind, s.source_id,
    s.invoice_id AS original_invoice_id, s.line_id AS original_line_id
FROM invoices.line_releases r
JOIN invoices.line_sources s ON s.id = r.line_source_id
WHERE r.invoice_id = $1
ORDER BY s.source_kind, s.source_id
`

type ReleasesOfRow struct {
	ID                int64
	CreditLineID      int64
	LineSourceID      int64
	SourceKind        string
	SourceID          int64
	OriginalInvoiceID int64
	OriginalLineID    int64
}

// ReleasesOf is a credit note's releases with the sources they released.
func (q *Queries) ReleasesOf(ctx context.Context, invoiceID int64) ([]ReleasesOfRow, error) {
	rows, err := q.db.Query(ctx, releasesOf, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleasesOfRow
	for rows.Next() {
		var i ReleasesOfRow
		if err := rows.Scan(
			&i.ID,
			&i.CreditLineID,
			&i.LineSourceID,
			&i.SourceKind,
			&i.SourceID,
			&i.OriginalInvoiceID,
			&i.OriginalLineID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentProject = `-- name: SetDocumentProject :exec
UPDATE invoices.invoices
SET project_id = $1, project_reference = $2
WHERE id = $3
`

type SetDocumentProjectParams struct {
	ProjectID        *int32
	ProjectReference *string
	ID               int64
}

// SetDocumentProject writes the project a draft's work belongs to and its
// code, derived by every save (D9): both, or NULL when the work spans two
// projects or there is none.
func (q *Queries) SetDocumentProject(ctx context.Context, arg SetDocumentProjectParams) error {
	_, err := q.db.Exec(ctx, setDocumentProject, arg.ProjectID, arg.ProjectReference, arg.ID)
	return err
}

const timesheetRowsOf = `-- name: TimesheetRowsOf :many
SELECT id, invoice_id, position, source_id, person_label, entry_date, hours, work_type, description FROM invoices.timesheet_rows WHERE invoice_id = $1 ORDER BY position
`

// TimesheetRowsOf is a document's timesheet as printed (D5), in order.
func (q *Queries) TimesheetRowsOf(ctx context.Context, invoiceID int64) ([]InvoicesTimesheetRow, error) {
	rows, err := q.db.Query(ctx, timesheetRowsOf, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoicesTimesheetRow
	for rows.Next() {
		var i InvoicesTimesheetRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Position,
			&i.SourceID,
			&i.PersonLabel,
			&i.EntryDate,
			&i.Hours,
			&i.WorkType,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
