// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireDayLock = `-- name: AcquireDayLock :exec
SELECT pg_advisory_xact_lock($1::integer, hashtext($2::text))
`

type AcquireDayLockParams struct {
	LockClass int32
	DayKey    string
}

// AcquireDayLock is the serialisation point of every write that decides a
// person's day total (the 24-hour cap): a row lock cannot cover a create,
// because what two racing creates contend for is a row that does not exist
// yet. The lock is keyed on the person and the day, hashed into the second
// argument, and held for the rest of the transaction. A hash collision only
// serialises two unrelated days; it never lets two writes to one day pass.
// It is a two-argument advisory lock, a lock space of its own that can never
// collide with the single-argument ones.
func (q *Queries) AcquireDayLock(ctx context.Context, arg AcquireDayLockParams) error {
	_, err := q.db.Exec(ctx, acquireDayLock, arg.LockClass, arg.DayKey)
	return err
}

const countEntries = `-- name: CountEntries :one
SELECT count(*) FROM time.entries
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::boolean OR user_id = $3::uuid OR project_id = ANY($4::integer[]))
  AND ($5::date IS NULL
       OR entry_date BETWEEN $5::date AND $6::date)
  AND ($7::integer IS NULL OR project_id = $7::integer)
  AND ($8::text IS NULL OR status = $8::text)
`

type CountEntriesParams struct {
	UserID            *uuid.UUID
	SeeAll            bool
	CallerID          uuid.UUID
	ManagedProjectIds []int32
	WeekStart         pgtype.Date
	WeekEnd           pgtype.Date
	ProjectID         *int32
	Status            *string
}

// CountEntries counts what ListEntries pages through, under exactly the same
// predicate, so the total is the number of entries the caller may see and
// the last page is never empty. Visibility is a predicate of its own (the
// rule authorize.go's entryAccess applies to one entry): everything for
// see_all, the caller's own, and the entries on the projects the caller
// manages. The filters are optional — user_id NULL is everyone's, which the
// handler only allows with a project filter; week_start and week_end are a
// Monday and its Sunday.
func (q *Queries) CountEntries(ctx context.Context, arg CountEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntries,
		arg.UserID,
		arg.SeeAll,
		arg.CallerID,
		arg.ManagedProjectIds,
		arg.WeekStart,
		arg.WeekEnd,
		arg.ProjectID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM time.entries WHERE id = $1 AND status IN ('draft', 'rejected') AND user_id = $2
`

type DeleteEntryParams struct {
	ID     int64
	UserID uuid.UUID
}

// DeleteEntry removes an entry only while it is still the owner's to change
// (D10). The status and the owner are re-checked here rather than trusted
// from the row the handler read, so a submit that commits in between wins
// and the delete removes nothing, and the SQL enforces the whole rule
// a.CanEdit backstops rather than only the status half of it.
func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEntries = `-- name: GetEntries :many
SELECT id, user_id, project_id, billing_line_id, task_id, task_title, entry_date, hours, start_time, end_time, note, billable, bill_rate, bill_currency, cost_rate, cost_currency, rate_source, status, rejection_reason, submitted_at, approved_by_user_id, approved_at, invoiced_at, revision, created_at, updated_at, work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent FROM time.entries WHERE id = ANY($1::bigint[])
`

// GetEntries reads the entries in ids without locking them: what a batch
// reads before its transaction, to learn which projects it will need the
// caller's role on. An id with no entry is simply absent from the result.
func (q *Queries) GetEntries(ctx context.Context, ids []int64) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, getEntries, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.BillingLineID,
			&i.TaskID,
			&i.TaskTitle,
			&i.EntryDate,
			&i.Hours,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Billable,
			&i.BillRate,
			&i.BillCurrency,
			&i.CostRate,
			&i.CostCurrency,
			&i.RateSource,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ApprovedByUserID,
			&i.ApprovedAt,
			&i.InvoicedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkTypeID,
			&i.WorkTypeName,
			&i.BillMultiplierPercent,
			&i.CostMultiplierPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT id, user_id, project_id, billing_line_id, task_id, task_title, entry_date, hours, start_time, end_time, note, billable, bill_rate, bill_currency, cost_rate, cost_currency, rate_source, status, rejection_reason, submitted_at, approved_by_user_id, approved_at, invoiced_at, revision, created_at, updated_at, work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent FROM time.entries WHERE id = $1
`

// GetEntry fetches one entry by id. Who may see it is decided in Go
// (authorize.go), never here: a stranger's 404 has to be indistinguishable
// from an unknown id's, so the row is loaded first and discarded after.
func (q *Queries) GetEntry(ctx context.Context, id int64) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BillingLineID,
		&i.TaskID,
		&i.TaskTitle,
		&i.EntryDate,
		&i.Hours,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Billable,
		&i.BillRate,
		&i.BillCurrency,
		&i.CostRate,
		&i.CostCurrency,
		&i.RateSource,
		&i.Status,
		&i.RejectionReason,
		&i.SubmittedAt,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.InvoicedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkTypeID,
		&i.WorkTypeName,
		&i.BillMultiplierPercent,
		&i.CostMultiplierPercent,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO time.entries (
    user_id, project_id, billing_line_id, task_id, task_title, entry_date,
    hours, start_time, end_time, note, billable,
    bill_rate, bill_currency, cost_rate, cost_currency, rate_source,
    work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19, $20,
    $21::timestamptz, $21::timestamptz
)
RETURNING id, user_id, project_id, billing_line_id, task_id, task_title, entry_date, hours, start_time, end_time, note, billable, bill_rate, bill_currency, cost_rate, cost_currency, rate_source, status, rejection_reason, submitted_at, approved_by_user_id, approved_at, invoiced_at, revision, created_at, updated_at, work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent
`

type InsertEntryParams struct {
	UserID                uuid.UUID
	ProjectID             int32
	BillingLineID         *int32
	TaskID                *int32
	TaskTitle             *string
	EntryDate             pgtype.Date
	Hours                 pgtype.Numeric
	StartTime             pgtype.Time
	EndTime               pgtype.Time
	Note                  *string
	Billable              bool
	BillRate              pgtype.Numeric
	BillCurrency          *string
	CostRate              pgtype.Numeric
	CostCurrency          *string
	RateSource            string
	WorkTypeID            *int32
	WorkTypeName          *string
	BillMultiplierPercent pgtype.Numeric
	CostMultiplierPercent pgtype.Numeric
	Now                   time.Time
}

// InsertEntry creates a draft entry with its rates already resolved and
// snapshotted (D3), and its work type beside them (work types design D3: all
// four NULL for ordinary hours). created_at and updated_at are the same
// instant, supplied by the caller from Deps.Clock(); status and revision take
// the column defaults ('draft', 1).
func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.UserID,
		arg.ProjectID,
		arg.BillingLineID,
		arg.TaskID,
		arg.TaskTitle,
		arg.EntryDate,
		arg.Hours,
		arg.StartTime,
		arg.EndTime,
		arg.Note,
		arg.Billable,
		arg.BillRate,
		arg.BillCurrency,
		arg.CostRate,
		arg.CostCurrency,
		arg.RateSource,
		arg.WorkTypeID,
		arg.WorkTypeName,
		arg.BillMultiplierPercent,
		arg.CostMultiplierPercent,
		arg.Now,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BillingLineID,
		&i.TaskID,
		&i.TaskTitle,
		&i.EntryDate,
		&i.Hours,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Billable,
		&i.BillRate,
		&i.BillCurrency,
		&i.CostRate,
		&i.CostCurrency,
		&i.RateSource,
		&i.Status,
		&i.RejectionReason,
		&i.SubmittedAt,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.InvoicedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkTypeID,
		&i.WorkTypeName,
		&i.BillMultiplierPercent,
		&i.CostMultiplierPercent,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, user_id, project_id, billing_line_id, task_id, task_title, entry_date, hours, start_time, end_time, note, billable, bill_rate, bill_currency, cost_rate, cost_currency, rate_source, status, rejection_reason, submitted_at, approved_by_user_id, approved_at, invoiced_at, revision, created_at, updated_at, work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent FROM time.entries
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::boolean OR user_id = $3::uuid OR project_id = ANY($4::integer[]))
  AND ($5::date IS NULL
       OR entry_date BETWEEN $5::date AND $6::date)
  AND ($7::integer IS NULL OR project_id = $7::integer)
  AND ($8::text IS NULL OR status = $8::text)
ORDER BY entry_date DESC, id DESC
LIMIT $10 OFFSET $9
`

type ListEntriesParams struct {
	UserID            *uuid.UUID
	SeeAll            bool
	CallerID          uuid.UUID
	ManagedProjectIds []int32
	WeekStart         pgtype.Date
	WeekEnd           pgtype.Date
	ProjectID         *int32
	Status            *string
	PageOffset        int32
	PageSize          int32
}

// ListEntries is one page of CountEntries' entries, the latest day first and,
// within a day, the latest created first.
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.UserID,
		arg.SeeAll,
		arg.CallerID,
		arg.ManagedProjectIds,
		arg.WeekStart,
		arg.WeekEnd,
		arg.ProjectID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.BillingLineID,
			&i.TaskID,
			&i.TaskTitle,
			&i.EntryDate,
			&i.Hours,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Billable,
			&i.BillRate,
			&i.BillCurrency,
			&i.CostRate,
			&i.CostCurrency,
			&i.RateSource,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ApprovedByUserID,
			&i.ApprovedAt,
			&i.InvoicedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkTypeID,
			&i.WorkTypeName,
			&i.BillMultiplierPercent,
			&i.CostMultiplierPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEntries = `-- name: LockEntries :many
SELECT id, user_id, project_id, billing_line_id, task_id, task_title, entry_date, hours, start_time, end_time, note, billable, bill_rate, bill_currency, cost_rate, cost_currency, rate_source, status, rejection_reason, submitted_at, approved_by_user_id, approved_at, invoiced_at, revision, created_at, updated_at, work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent FROM time.entries
WHERE id = ANY($1::bigint[])
ORDER BY id
FOR UPDATE
`

// LockEntries reads the entries in ids and holds their rows until the
// transaction ends, in id order, so two batches over overlapping entries
// take their locks in the same order and cannot deadlock. An id with no
// entry is simply absent from the result.
func (q *Queries) LockEntries(ctx context.Context, ids []int64) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, lockEntries, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.BillingLineID,
			&i.TaskID,
			&i.TaskTitle,
			&i.EntryDate,
			&i.Hours,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Billable,
			&i.BillRate,
			&i.BillCurrency,
			&i.CostRate,
			&i.CostCurrency,
			&i.RateSource,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ApprovedByUserID,
			&i.ApprovedAt,
			&i.InvoicedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkTypeID,
			&i.WorkTypeName,
			&i.BillMultiplierPercent,
			&i.CostMultiplierPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEntry = `-- name: LockEntry :one
SELECT id, user_id, project_id, billing_line_id, task_id, task_title, entry_date, hours, start_time, end_time, note, billable, bill_rate, bill_currency, cost_rate, cost_currency, rate_source, status, rejection_reason, submitted_at, approved_by_user_id, approved_at, invoiced_at, revision, created_at, updated_at, work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent FROM time.entries WHERE id = $1 FOR UPDATE
`

// LockEntry reads one entry and holds its row until the transaction ends. An
// update decides everything it refuses on (the status, the revision) from
// this row, not from the one the handler read before the transaction, so a
// submit that committed in between is seen and wins.
func (q *Queries) LockEntry(ctx context.Context, id int64) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, lockEntry, id)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BillingLineID,
		&i.TaskID,
		&i.TaskTitle,
		&i.EntryDate,
		&i.Hours,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Billable,
		&i.BillRate,
		&i.BillCurrency,
		&i.CostRate,
		&i.CostCurrency,
		&i.RateSource,
		&i.Status,
		&i.RejectionReason,
		&i.SubmittedAt,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.InvoicedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkTypeID,
		&i.WorkTypeName,
		&i.BillMultiplierPercent,
		&i.CostMultiplierPercent,
	)
	return i, err
}

const submitEntries = `-- name: SubmitEntries :many
UPDATE time.entries SET
    status = 'submitted',
    submitted_at = $1::timestamptz,
    revision = revision + 1,
    updated_at = $1::timestamptz
WHERE id = ANY($2::bigint[]) AND status = 'draft'
RETURNING id, user_id, project_id, billing_line_id, task_id, task_title, entry_date, hours, start_time, end_time, note, billable, bill_rate, bill_currency, cost_rate, cost_currency, rate_source, status, rejection_reason, submitted_at, approved_by_user_id, approved_at, invoiced_at, revision, created_at, updated_at, work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent
`

type SubmitEntriesParams struct {
	Now time.Time
	Ids []int64
}

// SubmitEntries moves drafts to submitted (D2), freezing their rates (D3).
// The rows are already locked by the caller, which decided every one of them
// may be submitted; the status guard is the last line, not the rule.
func (q *Queries) SubmitEntries(ctx context.Context, arg SubmitEntriesParams) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, submitEntries, arg.Now, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.BillingLineID,
			&i.TaskID,
			&i.TaskTitle,
			&i.EntryDate,
			&i.Hours,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Billable,
			&i.BillRate,
			&i.BillCurrency,
			&i.CostRate,
			&i.CostCurrency,
			&i.RateSource,
			&i.Status,
			&i.RejectionReason,
			&i.SubmittedAt,
			&i.ApprovedByUserID,
			&i.ApprovedAt,
			&i.InvoicedAt,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkTypeID,
			&i.WorkTypeName,
			&i.BillMultiplierPercent,
			&i.CostMultiplierPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDayHours = `-- name: SumDayHours :one
SELECT COALESCE(SUM(hours), 0)::numeric(7,2) AS total
FROM time.entries
WHERE user_id = $1
  AND entry_date = $2
  AND ($3::bigint IS NULL OR id <> $3::bigint)
`

type SumDayHoursParams struct {
	UserID    uuid.UUID
	EntryDate pgtype.Date
	ExcludeID *int64
}

// SumDayHours is the hours a person has logged on one day, leaving out the
// entry being saved (exclude_id, NULL on a create), so the cap is checked
// against what the day will hold after the save.
func (q *Queries) SumDayHours(ctx context.Context, arg SumDayHoursParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumDayHours, arg.UserID, arg.EntryDate, arg.ExcludeID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE time.entries SET
    project_id = $1,
    billing_line_id = $2,
    task_id = $3,
    task_title = $4,
    entry_date = $5,
    hours = $6,
    start_time = $7,
    end_time = $8,
    note = $9,
    billable = $10,
    bill_rate = $11,
    bill_currency = $12,
    cost_rate = $13,
    cost_currency = $14,
    rate_source = $15,
    work_type_id = $16,
    work_type_name = $17,
    bill_multiplier_percent = $18,
    cost_multiplier_percent = $19,
    status = 'draft',
    rejection_reason = NULL,
    submitted_at = NULL,
    revision = revision + 1,
    updated_at = $20::timestamptz
WHERE id = $21 AND revision = $22 AND status IN ('draft', 'rejected') AND user_id = $23
RETURNING id, user_id, project_id, billing_line_id, task_id, task_title, entry_date, hours, start_time, end_time, note, billable, bill_rate, bill_currency, cost_rate, cost_currency, rate_source, status, rejection_reason, submitted_at, approved_by_user_id, approved_at, invoiced_at, revision, created_at, updated_at, work_type_id, work_type_name, bill_multiplier_percent, cost_multiplier_percent
`

type UpdateEntryParams struct {
	ProjectID             int32
	BillingLineID         *int32
	TaskID                *int32
	TaskTitle             *string
	EntryDate             pgtype.Date
	Hours                 pgtype.Numeric
	StartTime             pgtype.Time
	EndTime               pgtype.Time
	Note                  *string
	Billable              bool
	BillRate              pgtype.Numeric
	BillCurrency          *string
	CostRate              pgtype.Numeric
	CostCurrency          *string
	RateSource            string
	WorkTypeID            *int32
	WorkTypeName          *string
	BillMultiplierPercent pgtype.Numeric
	CostMultiplierPercent pgtype.Numeric
	Now                   time.Time
	ID                    int64
	Revision              int32
	UserID                uuid.UUID
}

// UpdateEntry replaces an entry's content with its rates resolved again (D3).
// The work type is snapshotted again with them (work types design D3).
// A save always leaves a draft: a rejected entry returns to draft with its
// rejection reason and its submission stamp cleared (design 4.2). The
// revision, the status and the owner are guarded again here, although the
// row is already locked, so that no caller can ever write over a revision it
// did not read, and the SQL enforces the whole rule a.CanEdit backstops
// rather than only the revision and status half of it.
func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ProjectID,
		arg.BillingLineID,
		arg.TaskID,
		arg.TaskTitle,
		arg.EntryDate,
		arg.Hours,
		arg.StartTime,
		arg.EndTime,
		arg.Note,
		arg.Billable,
		arg.BillRate,
		arg.BillCurrency,
		arg.CostRate,
		arg.CostCurrency,
		arg.RateSource,
		arg.WorkTypeID,
		arg.WorkTypeName,
		arg.BillMultiplierPercent,
		arg.CostMultiplierPercent,
		arg.Now,
		arg.ID,
		arg.Revision,
		arg.UserID,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.BillingLineID,
		&i.TaskID,
		&i.TaskTitle,
		&i.EntryDate,
		&i.Hours,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Billable,
		&i.BillRate,
		&i.BillCurrency,
		&i.CostRate,
		&i.CostCurrency,
		&i.RateSource,
		&i.Status,
		&i.RejectionReason,
		&i.SubmittedAt,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.InvoicedAt,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkTypeID,
		&i.WorkTypeName,
		&i.BillMultiplierPercent,
		&i.CostMultiplierPercent,
	)
	return i, err
}
