// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProduct = `-- name: ArchiveProduct :one
UPDATE products.products
SET status = 'Discontinued', updated_at = $1::timestamptz
WHERE id = $2
RETURNING id, name, description, category_id, type, status, tax_category_id, created_at, updated_at
`

type ArchiveProductParams struct {
	Now time.Time
	ID  int32
}

// ArchiveProduct is DeleteProductsById's status transition
// (ArchiveProductEndpoint.cs:28-32), applied only once the handler has
// confirmed the product is not already Discontinued.
func (q *Queries) ArchiveProduct(ctx context.Context, arg ArchiveProductParams) (ProductsProduct, error) {
	row := q.db.QueryRow(ctx, archiveProduct, arg.Now, arg.ID)
	var i ProductsProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.Type,
		&i.Status,
		&i.TaxCategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS(SELECT 1 FROM products.product_categories WHERE id = $1)
`

// CategoryExists is CreateCategoryEndpoint's parentId existence pre-check
// (:27-28).
func (q *Queries) CategoryExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, categoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryHasProducts = `-- name: CategoryHasProducts :one
SELECT EXISTS(SELECT 1 FROM products.products WHERE category_id = $1::int)
`

// CategoryHasProducts is DeleteCategoryEndpoint's second guard (:35-36).
func (q *Queries) CategoryHasProducts(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, categoryHasProducts, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryHasSubcategories = `-- name: CategoryHasSubcategories :one
SELECT EXISTS(SELECT 1 FROM products.product_categories WHERE parent_id = $1::int)
`

// CategoryHasSubcategories is DeleteCategoryEndpoint's first guard (:27-28).
// The explicit cast keeps id a plain (never-null) int32 in Go: it is always
// a real category's own id, even though it is compared against the
// nullable parent_id column.
func (q *Queries) CategoryHasSubcategories(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, categoryHasSubcategories, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categorySiblingNameExists = `-- name: CategorySiblingNameExists :one
SELECT EXISTS(
    SELECT 1 FROM products.product_categories
    WHERE parent_id IS NOT DISTINCT FROM $1 AND name = $2
)
`

type CategorySiblingNameExistsParams struct {
	ParentID *int32
	Name     string
}

// CategorySiblingNameExists is CreateCategoryEndpoint's duplicate-sibling
// check (:36-38). IS NOT DISTINCT FROM, not =, so two root categories
// (parent_id NULL on both sides) collide the same way the table's own
// NULLS NOT DISTINCT unique index does (products inventory §3).
func (q *Queries) CategorySiblingNameExists(ctx context.Context, arg CategorySiblingNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, categorySiblingNameExists, arg.ParentID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categorySiblingNameExistsExcluding = `-- name: CategorySiblingNameExistsExcluding :one
SELECT EXISTS(
    SELECT 1 FROM products.product_categories
    WHERE parent_id IS NOT DISTINCT FROM $1 AND name = $2 AND id != $3
)
`

type CategorySiblingNameExistsExcludingParams struct {
	ParentID *int32
	Name     string
	ID       int32
}

// CategorySiblingNameExistsExcluding is UpdateCategoryEndpoint's duplicate-
// sibling check, excluding the category being renamed (:66-68).
func (q *Queries) CategorySiblingNameExistsExcluding(ctx context.Context, arg CategorySiblingNameExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, categorySiblingNameExistsExcluding, arg.ParentID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countOtherVariantsOfProduct = `-- name: CountOtherVariantsOfProduct :one
SELECT count(*) FROM products.product_variants WHERE product_id = $1 AND id != $2
`

type CountOtherVariantsOfProductParams struct {
	ProductID int32
	ID        int32
}

// CountOtherVariantsOfProduct is DeleteProductVariantEndpoint's last-variant
// guard (:20-23): whether the product has any variant besides the one being
// deleted.
func (q *Queries) CountOtherVariantsOfProduct(ctx context.Context, arg CountOtherVariantsOfProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherVariantsOfProduct, arg.ProductID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProducts = `-- name: CountProducts :one
SELECT count(*)
FROM products.products p
WHERE ($1::text IS NULL OR p.status = $1::text)
  AND ($2::int[] IS NULL OR p.category_id = ANY($2::int[]))
  AND (NOT $3::bool OR p.category_id IS NULL)
  AND ($4::text IS NULL OR (
        p.name ILIKE $4::text OR
        (p.description IS NOT NULL AND p.description ILIKE $4::text) OR
        EXISTS (SELECT 1 FROM products.product_variants v
                 WHERE v.product_id = p.id
                   AND (v.sku ILIKE $4::text OR v.barcode = $5::text))
      ))
`

type CountProductsParams struct {
	Status        *string
	CategoryIds   []int32
	Uncategorized bool
	SearchPattern *string
	SearchExact   *string
}

// CountProducts is the total row count GetProductsEndpoint paginates over,
// the same filters the three ListProductsBy* queries below apply.
func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts,
		arg.Status,
		arg.CategoryIds,
		arg.Uncategorized,
		arg.SearchPattern,
		arg.SearchExact,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM products.product_categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteProductPrice = `-- name: DeleteProductPrice :exec
DELETE FROM products.product_prices WHERE id = $1
`

// DeleteProductPrice is DeleteProductPriceEndpoint's own delete (:29-30):
// no "last price" rule, a variant may end up with zero prices.
func (q *Queries) DeleteProductPrice(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProductPrice, id)
	return err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM products.product_variants WHERE id = $1
`

// DeleteProductVariant is DeleteProductVariantEndpoint's own delete
// (:25-26), run only once the last-variant guard above has passed.
func (q *Queries) DeleteProductVariant(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProductVariant, id)
	return err
}

const deleteTaxCategory = `-- name: DeleteTaxCategory :exec
DELETE FROM products.tax_categories WHERE id = $1
`

func (q *Queries) DeleteTaxCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTaxCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, parent_id FROM products.product_categories WHERE id = $1
`

// GetCategoryByID is GetCategoryEndpoint's/UpdateCategoryEndpoint's/
// DeleteCategoryEndpoint's own-row lookup (the full row, parent_id
// included — unlike GetCategoryRef, which only serves a product's embedded
// reference).
func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (ProductsProductCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i ProductsProductCategory
	err := row.Scan(&i.ID, &i.Name, &i.ParentID)
	return i, err
}

const getCategoryRef = `-- name: GetCategoryRef :one
SELECT id, name FROM products.product_categories WHERE id = $1
`

type GetCategoryRefRow struct {
	ID   int32
	Name string
}

// GetCategoryRef is the compact category reference a product embeds
// (ProductCategoryResponse), and doubles as the categoryId existence check
// CreateProductEndpoint/UpdateProductEndpoint run before saving: pgx.ErrNoRows
// means "does not exist".
func (q *Queries) GetCategoryRef(ctx context.Context, id int32) (GetCategoryRefRow, error) {
	row := q.db.QueryRow(ctx, getCategoryRef, id)
	var i GetCategoryRefRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPriceScoped = `-- name: GetPriceScoped :one
SELECT pr.id, pr.variant_id, pr.currency, pr.amount, pr.valid_from, pr.valid_to
FROM products.product_prices pr
JOIN products.product_variants v ON v.id = pr.variant_id
WHERE pr.id = $1 AND pr.variant_id = $2 AND v.product_id = $3
`

type GetPriceScopedParams struct {
	PriceID   int32
	VariantID int32
	ProductID int32
}

// GetPriceScoped is UpdateProductPriceEndpoint's/DeleteProductPriceEndpoint's
// doubly-scoped lookup: the price must belong to the given variant, and that
// variant to the given product (UpdateProductPriceEndpoint.cs:34-42,
// DeleteProductPriceEndpoint.cs:20-22).
func (q *Queries) GetPriceScoped(ctx context.Context, arg GetPriceScopedParams) (ProductsProductPrice, error) {
	row := q.db.QueryRow(ctx, getPriceScoped, arg.PriceID, arg.VariantID, arg.ProductID)
	var i ProductsProductPrice
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Currency,
		&i.Amount,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, category_id, type, status, tax_category_id, created_at, updated_at
FROM products.products
WHERE id = $1
`

// GetProductByID fetches one product's own row, no joins.
func (q *Queries) GetProductByID(ctx context.Context, id int32) (ProductsProduct, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i ProductsProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.Type,
		&i.Status,
		&i.TaxCategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductStatus = `-- name: GetProductStatus :one
SELECT status FROM products.products WHERE id = $1
`

// GetProductStatus is UpdateProductVariantEndpoint's fresh status read
// (:31-34), re-queried per request rather than trusting a cached value,
// since SKU immutability depends on it.
func (q *Queries) GetProductStatus(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getProductStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getTaxCategoryRef = `-- name: GetTaxCategoryRef :one
SELECT id, name, kind, rate FROM products.tax_categories WHERE id = $1
`

type GetTaxCategoryRefRow struct {
	ID   int32
	Name string
	Kind string
	Rate pgtype.Numeric
}

// GetTaxCategoryRef is the tax category a product embeds
// (ProductTaxCategoryResponse), and doubles as the taxCategoryId existence
// check CreateProductEndpoint/UpdateProductEndpoint run before saving.
func (q *Queries) GetTaxCategoryRef(ctx context.Context, id int32) (GetTaxCategoryRefRow, error) {
	row := q.db.QueryRow(ctx, getTaxCategoryRef, id)
	var i GetTaxCategoryRefRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Rate,
	)
	return i, err
}

const getVariantByProductAndID = `-- name: GetVariantByProductAndID :one
SELECT id, product_id, sku, barcode, unit, standard_cost, weight_kg, length_cm, width_cm, height_cm,
       option_values, created_at, updated_at
FROM products.product_variants
WHERE id = $1 AND product_id = $2
`

type GetVariantByProductAndIDParams struct {
	ID        int32
	ProductID int32
}

// GetVariantByProductAndID is the scoped lookup every variant/price handler
// performs first: a variant is always addressed through its product
// (UpdateProductVariantEndpoint.cs:23-25, DeleteProductVariantEndpoint.cs:14).
func (q *Queries) GetVariantByProductAndID(ctx context.Context, arg GetVariantByProductAndIDParams) (ProductsProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantByProductAndID, arg.ID, arg.ProductID)
	var i ProductsProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.StandardCost,
		&i.WeightKg,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
		&i.OptionValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one

INSERT INTO products.product_categories (name, parent_id)
VALUES ($1, $2)
RETURNING id, name, parent_id
`

type InsertCategoryParams struct {
	Name     string
	ParentID *int32
}

// Categories (Task 12, EP/Categories/*Endpoint.cs). GetCategoryRef and
// ListCategoryParents above already cover the compact ref a product embeds
// and the whole id->parentId adjacency list category CRUD reuses for
// existence checks and WouldCreateCycle.
// InsertCategory is CreateCategoryEndpoint.cs:46-53.
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (ProductsProductCategory, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.Name, arg.ParentID)
	var i ProductsProductCategory
	err := row.Scan(&i.ID, &i.Name, &i.ParentID)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products.products (
    name, description, category_id, type, status, tax_category_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7::timestamptz, $7::timestamptz
)
RETURNING id, name, description, category_id, type, status, tax_category_id, created_at, updated_at
`

type InsertProductParams struct {
	Name          string
	Description   *string
	CategoryID    *int32
	Type          string
	Status        string
	TaxCategoryID int32
	Now           time.Time
}

// InsertProduct creates a product row (CreateProductEndpoint.cs:86-101).
// created_at and updated_at are the same instant, supplied by the caller
// from Deps.Clock().
func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (ProductsProduct, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.Type,
		arg.Status,
		arg.TaxCategoryID,
		arg.Now,
	)
	var i ProductsProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.Type,
		&i.Status,
		&i.TaxCategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductPrice = `-- name: InsertProductPrice :one
INSERT INTO products.product_prices (variant_id, currency, amount, valid_from, valid_to)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, variant_id, currency, amount, valid_from, valid_to
`

type InsertProductPriceParams struct {
	VariantID int32
	Currency  string
	Amount    pgtype.Numeric
	ValidFrom *time.Time
	ValidTo   *time.Time
}

// InsertProductPrice appends a price row to a variant
// (AddProductPriceEndpoint.cs:49-50, UpdateProductPriceEndpoint applies its
// fields onto an existing row instead — see UpdatePrice below).
func (q *Queries) InsertProductPrice(ctx context.Context, arg InsertProductPriceParams) (ProductsProductPrice, error) {
	row := q.db.QueryRow(ctx, insertProductPrice,
		arg.VariantID,
		arg.Currency,
		arg.Amount,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i ProductsProductPrice
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Currency,
		&i.Amount,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const insertProductVariant = `-- name: InsertProductVariant :one
INSERT INTO products.product_variants (
    product_id, sku, barcode, unit, standard_cost, weight_kg, length_cm, width_cm, height_cm, option_values,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11::timestamptz, $11::timestamptz
)
RETURNING id, product_id, sku, barcode, unit, standard_cost, weight_kg, length_cm, width_cm, height_cm,
          option_values, created_at, updated_at
`

type InsertProductVariantParams struct {
	ProductID    int32
	Sku          string
	Barcode      *string
	Unit         string
	StandardCost pgtype.Numeric
	WeightKg     pgtype.Numeric
	LengthCm     pgtype.Numeric
	WidthCm      pgtype.Numeric
	HeightCm     pgtype.Numeric
	OptionValues []byte
	Now          time.Time
}

// InsertProductVariant creates a variant row scoped to product_id. Used both
// by product creation (one or more variants in one transaction) and by
// AddProductVariantEndpoint (one variant onto an existing product).
func (q *Queries) InsertProductVariant(ctx context.Context, arg InsertProductVariantParams) (ProductsProductVariant, error) {
	row := q.db.QueryRow(ctx, insertProductVariant,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.Unit,
		arg.StandardCost,
		arg.WeightKg,
		arg.LengthCm,
		arg.WidthCm,
		arg.HeightCm,
		arg.OptionValues,
		arg.Now,
	)
	var i ProductsProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.StandardCost,
		&i.WeightKg,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
		&i.OptionValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTaxCategory = `-- name: InsertTaxCategory :one

INSERT INTO products.tax_categories (name, kind, rate, created_at, updated_at)
VALUES ($1, $2, $3, $4::timestamptz, $4::timestamptz)
RETURNING id, name, kind, rate, created_at, updated_at
`

type InsertTaxCategoryParams struct {
	Name string
	Kind string
	Rate pgtype.Numeric
	Now  time.Time
}

// Tax categories (Task 12, EP/TaxCategories/*Endpoint.cs). GetTaxCategoryRef
// above already covers the compact ref a product embeds.
// InsertTaxCategory is CreateTaxCategoryEndpoint.cs:31-33 (TaxCategoryRequest.ToDomain).
func (q *Queries) InsertTaxCategory(ctx context.Context, arg InsertTaxCategoryParams) (ProductsTaxCategory, error) {
	row := q.db.QueryRow(ctx, insertTaxCategory,
		arg.Name,
		arg.Kind,
		arg.Rate,
		arg.Now,
	)
	var i ProductsTaxCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesOrdered = `-- name: ListCategoriesOrdered :many
SELECT id, name, parent_id FROM products.product_categories ORDER BY name, id
`

// ListCategoriesOrdered is GetCategoriesEndpoint.cs:20-24: the flat
// adjacency list, ordered by name then id.
func (q *Queries) ListCategoriesOrdered(ctx context.Context) ([]ProductsProductCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsProductCategory
	for rows.Next() {
		var i ProductsProductCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryParents = `-- name: ListCategoryParents :many
SELECT id, parent_id FROM products.product_categories
`

type ListCategoryParentsRow struct {
	ID       int32
	ParentID *int32
}

// ListCategoryParents is the whole id->parentId adjacency list GetProducts
// resolves categoryId+descendants filtering from in Go
// (ProductCategoryHierarchy.GetSelfAndDescendantIds), the same "catalog is
// assumed small, no pagination" premise the .NET code documents.
func (q *Queries) ListCategoryParents(ctx context.Context) ([]ListCategoryParentsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryParents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryParentsRow
	for rows.Next() {
		var i ListCategoryParentsRow
		if err := rows.Scan(&i.ID, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryProductCounts = `-- name: ListCategoryProductCounts :many
SELECT category_id AS id, count(*) AS count
FROM products.products
WHERE category_id IS NOT NULL
GROUP BY category_id
`

type ListCategoryProductCountsRow struct {
	ID    *int32
	Count int64
}

// ListCategoryProductCounts is GetCategoriesEndpoint.cs:26-30's direct
// (not subtree) product count per category; a category with none is
// simply absent from the result, GetValueOrDefault's 0 (categories.go
// fills the gap).
func (q *Queries) ListCategoryProductCounts(ctx context.Context) ([]ListCategoryProductCountsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryProductCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryProductCountsRow
	for rows.Next() {
		var i ListCategoryProductCountsRow
		if err := rows.Scan(&i.ID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryRefs = `-- name: ListCategoryRefs :many
SELECT id, name FROM products.product_categories WHERE id = ANY($1::int[])
`

type ListCategoryRefsRow struct {
	ID   int32
	Name string
}

// ListCategoryRefs batch-loads category references for a page of products
// (GetProductsEndpoint), avoiding one query per row.
func (q *Queries) ListCategoryRefs(ctx context.Context, ids []int32) ([]ListCategoryRefsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryRefs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryRefsRow
	for rows.Next() {
		var i ListCategoryRefsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesByVariant = `-- name: ListPricesByVariant :many
SELECT id, variant_id, currency, amount, valid_from, valid_to
FROM products.product_prices
WHERE variant_id = $1
ORDER BY currency, valid_from, id
`

// ListPricesByVariant lists one variant's price rows, ordered by currency
// then validFrom then id (GetProductPricesEndpoint.cs:25-31).
func (q *Queries) ListPricesByVariant(ctx context.Context, variantID int32) ([]ProductsProductPrice, error) {
	rows, err := q.db.Query(ctx, listPricesByVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsProductPrice
	for rows.Next() {
		var i ProductsProductPrice
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.Currency,
			&i.Amount,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesByVariantIDs = `-- name: ListPricesByVariantIDs :many
SELECT id, variant_id, currency, amount, valid_from, valid_to
FROM products.product_prices
WHERE variant_id = ANY($1::int[])
ORDER BY variant_id, currency, valid_from, id
`

// ListPricesByVariantIDs batch-loads prices for a page of products'
// variants (GetProductsEndpoint), same ordering as ListPricesByVariant.
func (q *Queries) ListPricesByVariantIDs(ctx context.Context, variantIds []int32) ([]ProductsProductPrice, error) {
	rows, err := q.db.Query(ctx, listPricesByVariantIDs, variantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsProductPrice
	for rows.Next() {
		var i ProductsProductPrice
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.Currency,
			&i.Amount,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByID = `-- name: ListProductsByID :many
SELECT p.id, p.name, p.description, p.category_id, p.type, p.status, p.tax_category_id, p.created_at, p.updated_at
FROM products.products p
WHERE ($1::text IS NULL OR p.status = $1::text)
  AND ($2::int[] IS NULL OR p.category_id = ANY($2::int[]))
  AND (NOT $3::bool OR p.category_id IS NULL)
  AND ($4::text IS NULL OR (
        p.name ILIKE $4::text OR
        (p.description IS NOT NULL AND p.description ILIKE $4::text) OR
        EXISTS (SELECT 1 FROM products.product_variants v
                 WHERE v.product_id = p.id
                   AND (v.sku ILIKE $4::text OR v.barcode = $5::text))
      ))
ORDER BY
    CASE WHEN NOT $6::bool THEN p.id END ASC,
    CASE WHEN $6::bool THEN p.id END DESC
LIMIT $8::int OFFSET $7::int
`

type ListProductsByIDParams struct {
	Status        *string
	CategoryIds   []int32
	Uncategorized bool
	SearchPattern *string
	SearchExact   *string
	Descending    bool
	RowOffset     int32
	PageSize      int32
}

// ListProductsByID is GetProducts's default sort (id, ascending unless
// descending is requested), one page of product rows
// (GetProductsEndpoint.cs:136-148's SortFields.Id branch).
func (q *Queries) ListProductsByID(ctx context.Context, arg ListProductsByIDParams) ([]ProductsProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByID,
		arg.Status,
		arg.CategoryIds,
		arg.Uncategorized,
		arg.SearchPattern,
		arg.SearchExact,
		arg.Descending,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsProduct
	for rows.Next() {
		var i ProductsProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.Type,
			&i.Status,
			&i.TaxCategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByName = `-- name: ListProductsByName :many
SELECT p.id, p.name, p.description, p.category_id, p.type, p.status, p.tax_category_id, p.created_at, p.updated_at
FROM products.products p
WHERE ($1::text IS NULL OR p.status = $1::text)
  AND ($2::int[] IS NULL OR p.category_id = ANY($2::int[]))
  AND (NOT $3::bool OR p.category_id IS NULL)
  AND ($4::text IS NULL OR (
        p.name ILIKE $4::text OR
        (p.description IS NOT NULL AND p.description ILIKE $4::text) OR
        EXISTS (SELECT 1 FROM products.product_variants v
                 WHERE v.product_id = p.id
                   AND (v.sku ILIKE $4::text OR v.barcode = $5::text))
      ))
ORDER BY
    CASE WHEN NOT $6::bool THEN p.name END ASC,
    CASE WHEN $6::bool THEN p.name END DESC,
    CASE WHEN NOT $6::bool THEN p.id END ASC,
    CASE WHEN $6::bool THEN p.id END DESC
LIMIT $8::int OFFSET $7::int
`

type ListProductsByNameParams struct {
	Status        *string
	CategoryIds   []int32
	Uncategorized bool
	SearchPattern *string
	SearchExact   *string
	Descending    bool
	RowOffset     int32
	PageSize      int32
}

// ListProductsByName is GetProducts's sortBy=name path: name first, id as
// the tie-break both directions (.NET's ThenBy(p => p.Id) /
// ThenByDescending(p => p.Id)).
func (q *Queries) ListProductsByName(ctx context.Context, arg ListProductsByNameParams) ([]ProductsProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByName,
		arg.Status,
		arg.CategoryIds,
		arg.Uncategorized,
		arg.SearchPattern,
		arg.SearchExact,
		arg.Descending,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsProduct
	for rows.Next() {
		var i ProductsProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.Type,
			&i.Status,
			&i.TaxCategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySku = `-- name: ListProductsBySku :many
SELECT p.id, p.name, p.description, p.category_id, p.type, p.status, p.tax_category_id, p.created_at, p.updated_at
FROM products.products p
LEFT JOIN (
    SELECT product_id, min(sku) AS min_sku, max(sku) AS max_sku
    FROM products.product_variants
    GROUP BY product_id
) v ON v.product_id = p.id
WHERE ($1::text IS NULL OR p.status = $1::text)
  AND ($2::int[] IS NULL OR p.category_id = ANY($2::int[]))
  AND (NOT $3::bool OR p.category_id IS NULL)
  AND ($4::text IS NULL OR (
        p.name ILIKE $4::text OR
        (p.description IS NOT NULL AND p.description ILIKE $4::text) OR
        EXISTS (SELECT 1 FROM products.product_variants pv
                 WHERE pv.product_id = p.id
                   AND (pv.sku ILIKE $4::text OR pv.barcode = $5::text))
      ))
ORDER BY
    CASE WHEN NOT $6::bool THEN v.min_sku END ASC,
    CASE WHEN $6::bool THEN v.max_sku END DESC,
    CASE WHEN NOT $6::bool THEN p.id END ASC,
    CASE WHEN $6::bool THEN p.id END DESC
LIMIT $8::int OFFSET $7::int
`

type ListProductsBySkuParams struct {
	Status        *string
	CategoryIds   []int32
	Uncategorized bool
	SearchPattern *string
	SearchExact   *string
	Descending    bool
	RowOffset     int32
	PageSize      int32
}

// ListProductsBySku is GetProducts's sortBy=sku path
// (GetProductsEndpoint.cs:144-145): ascending orders by each product's
// lowest-SKU variant, descending by its highest-SKU variant — not
// symmetric, but a faithful port of .NET's own asymmetry
// (query.OrderBy(Min) for asc, OrderByDescending(Max) for desc).
func (q *Queries) ListProductsBySku(ctx context.Context, arg ListProductsBySkuParams) ([]ProductsProduct, error) {
	rows, err := q.db.Query(ctx, listProductsBySku,
		arg.Status,
		arg.CategoryIds,
		arg.Uncategorized,
		arg.SearchPattern,
		arg.SearchExact,
		arg.Descending,
		arg.RowOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsProduct
	for rows.Next() {
		var i ProductsProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.Type,
			&i.Status,
			&i.TaxCategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxCategoriesOrdered = `-- name: ListTaxCategoriesOrdered :many
SELECT id, name, kind, rate FROM products.tax_categories ORDER BY name
`

type ListTaxCategoriesOrderedRow struct {
	ID   int32
	Name string
	Kind string
	Rate pgtype.Numeric
}

// ListTaxCategoriesOrdered is GetTaxCategoriesEndpoint.cs:15-19: ordered by
// name.
func (q *Queries) ListTaxCategoriesOrdered(ctx context.Context) ([]ListTaxCategoriesOrderedRow, error) {
	rows, err := q.db.Query(ctx, listTaxCategoriesOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaxCategoriesOrderedRow
	for rows.Next() {
		var i ListTaxCategoriesOrderedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Rate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxCategoryRefs = `-- name: ListTaxCategoryRefs :many
SELECT id, name, kind, rate FROM products.tax_categories WHERE id = ANY($1::int[])
`

type ListTaxCategoryRefsRow struct {
	ID   int32
	Name string
	Kind string
	Rate pgtype.Numeric
}

// ListTaxCategoryRefs batch-loads tax category references for a page of
// products (GetProductsEndpoint).
func (q *Queries) ListTaxCategoryRefs(ctx context.Context, ids []int32) ([]ListTaxCategoryRefsRow, error) {
	rows, err := q.db.Query(ctx, listTaxCategoryRefs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaxCategoryRefsRow
	for rows.Next() {
		var i ListTaxCategoryRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Rate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, sku, barcode, unit, standard_cost, weight_kg, length_cm, width_cm, height_cm,
       option_values, created_at, updated_at
FROM products.product_variants
WHERE product_id = $1
ORDER BY id
`

// ListVariantsByProduct lists one product's variants, ordered by id
// (GetProductVariantsEndpoint.cs:20-24).
func (q *Queries) ListVariantsByProduct(ctx context.Context, productID int32) ([]ProductsProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsProductVariant
	for rows.Next() {
		var i ProductsProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Unit,
			&i.StandardCost,
			&i.WeightKg,
			&i.LengthCm,
			&i.WidthCm,
			&i.HeightCm,
			&i.OptionValues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProductIDs = `-- name: ListVariantsByProductIDs :many
SELECT id, product_id, sku, barcode, unit, standard_cost, weight_kg, length_cm, width_cm, height_cm,
       option_values, created_at, updated_at
FROM products.product_variants
WHERE product_id = ANY($1::int[])
ORDER BY product_id, id
`

// ListVariantsByProductIDs batch-loads variants for a page of products
// (GetProductsEndpoint), ordered by product then id.
func (q *Queries) ListVariantsByProductIDs(ctx context.Context, productIds []int32) ([]ProductsProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProductIDs, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsProductVariant
	for rows.Next() {
		var i ProductsProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Unit,
			&i.StandardCost,
			&i.WeightKg,
			&i.LengthCm,
			&i.WidthCm,
			&i.HeightCm,
			&i.OptionValues,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productCreationBuckets = `-- name: ProductCreationBuckets :many
SELECT (created_at AT TIME ZONE 'UTC')::date AS day, count(*) AS value
FROM products.products
WHERE created_at >= $1::timestamptz AND created_at < $2::timestamptz
GROUP BY day
ORDER BY day
`

type ProductCreationBucketsParams struct {
	RangeFrom time.Time
	RangeTo   time.Time
}

type ProductCreationBucketsRow struct {
	Day   pgtype.Date
	Value int64
}

// ProductCreationBuckets is the timeseries's newProducts metric
// (ProductStatsEndpoints.cs:92-97): one row per UTC calendar day with at
// least one product created in [range_from, range_to).
func (q *Queries) ProductCreationBuckets(ctx context.Context, arg ProductCreationBucketsParams) ([]ProductCreationBucketsRow, error) {
	rows, err := q.db.Query(ctx, productCreationBuckets, arg.RangeFrom, arg.RangeTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCreationBucketsRow
	for rows.Next() {
		var i ProductCreationBucketsRow
		if err := rows.Scan(&i.Day, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS(SELECT 1 FROM products.products WHERE id = $1)
`

// ProductExists is AddProductVariantEndpoint's 404 pre-check
// (AddProductVariantEndpoint.cs:40-43).
func (q *Queries) ProductExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, productExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const productStatsSummaryCounts = `-- name: ProductStatsSummaryCounts :one

SELECT
    count(*) FILTER (WHERE status = 'Active') AS active,
    count(*) FILTER (WHERE status = 'Active' AND created_at < $1::timestamptz) AS active_at_period_start,
    count(*) FILTER (WHERE created_at >= $1::timestamptz AND created_at < $2::timestamptz) AS new_products,
    count(*) FILTER (WHERE created_at >= $3::timestamptz AND created_at < $1::timestamptz) AS previous_new_products
FROM products.products
`

type ProductStatsSummaryCountsParams struct {
	PeriodFrom   time.Time
	PeriodTo     time.Time
	PreviousFrom time.Time
}

type ProductStatsSummaryCountsRow struct {
	Active              int64
	ActiveAtPeriodStart int64
	NewProducts         int64
	PreviousNewProducts int64
}

// Stats (Task 12, EP/ProductStatsEndpoints.cs). Mirrors the customers
// module's own CustomerStatsSummaryCustomerCounts/CustomerCreationBuckets
// query shape, the completed broader template.
// ProductStatsSummaryCounts is ProductStatsEndpoints.Summary's four product
// counts (:42-49): previous_from..period_from is the immediately preceding
// window of the same length as [period_from, period_to).
func (q *Queries) ProductStatsSummaryCounts(ctx context.Context, arg ProductStatsSummaryCountsParams) (ProductStatsSummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, productStatsSummaryCounts, arg.PeriodFrom, arg.PeriodTo, arg.PreviousFrom)
	var i ProductStatsSummaryCountsRow
	err := row.Scan(
		&i.Active,
		&i.ActiveAtPeriodStart,
		&i.NewProducts,
		&i.PreviousNewProducts,
	)
	return i, err
}

const productStatusCounts = `-- name: ProductStatusCounts :many
SELECT status, count(*) AS value FROM products.products GROUP BY status
`

type ProductStatusCountsRow struct {
	Status string
	Value  int64
}

// ProductStatusCounts is ProductStatsEndpoints.Summary's current
// per-status counts (:51-54), every status present in the table.
func (q *Queries) ProductStatusCounts(ctx context.Context) ([]ProductStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, productStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductStatusCountsRow
	for rows.Next() {
		var i ProductStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productStatusCountsBefore = `-- name: ProductStatusCountsBefore :many
SELECT status, count(*) AS value
FROM products.products
WHERE created_at < $1::timestamptz
GROUP BY status
`

type ProductStatusCountsBeforeRow struct {
	Status string
	Value  int64
}

// ProductStatusCountsBefore is ProductStatsEndpoints.Summary's per-status
// counts as of period.From (:55-59), used to compute each status's delta.
func (q *Queries) ProductStatusCountsBefore(ctx context.Context, before time.Time) ([]ProductStatusCountsBeforeRow, error) {
	rows, err := q.db.Query(ctx, productStatusCountsBefore, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductStatusCountsBeforeRow
	for rows.Next() {
		var i ProductStatusCountsBeforeRow
		if err := rows.Scan(&i.Status, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taxCategoryHasProducts = `-- name: TaxCategoryHasProducts :one
SELECT EXISTS(SELECT 1 FROM products.products WHERE tax_category_id = $1)
`

// TaxCategoryHasProducts is DeleteTaxCategoryEndpoint's guard (:21-22).
func (q *Queries) TaxCategoryHasProducts(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, taxCategoryHasProducts, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const taxCategoryNameExists = `-- name: TaxCategoryNameExists :one
SELECT EXISTS(SELECT 1 FROM products.tax_categories WHERE name = $1)
`

// TaxCategoryNameExists is CreateTaxCategoryEndpoint's duplicate-name check
// (:23).
func (q *Queries) TaxCategoryNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, taxCategoryNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const taxCategoryNameExistsExcluding = `-- name: TaxCategoryNameExistsExcluding :one
SELECT EXISTS(SELECT 1 FROM products.tax_categories WHERE name = $1 AND id != $2)
`

type TaxCategoryNameExistsExcludingParams struct {
	Name string
	ID   int32
}

// TaxCategoryNameExistsExcluding is UpdateTaxCategoryEndpoint's
// duplicate-name check, excluding the category being renamed (:31-32).
func (q *Queries) TaxCategoryNameExistsExcluding(ctx context.Context, arg TaxCategoryNameExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, taxCategoryNameExistsExcluding, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE products.product_categories
SET name = $1, parent_id = $2
WHERE id = $3
RETURNING id, name, parent_id
`

type UpdateCategoryParams struct {
	Name     string
	ParentID *int32
	ID       int32
}

// UpdateCategory applies UpdateCategoryEndpoint's validated name/parentId
// (:76-78).
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (ProductsProductCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.ParentID, arg.ID)
	var i ProductsProductCategory
	err := row.Scan(&i.ID, &i.Name, &i.ParentID)
	return i, err
}

const updatePrice = `-- name: UpdatePrice :one
UPDATE products.product_prices
SET currency = $1, amount = $2, valid_from = $3, valid_to = $4
WHERE id = $5
RETURNING id, variant_id, currency, amount, valid_from, valid_to
`

type UpdatePriceParams struct {
	Currency  string
	Amount    pgtype.Numeric
	ValidFrom *time.Time
	ValidTo   *time.Time
	ID        int32
}

// UpdatePrice applies PUT .../prices/{priceId}'s validated fields in place
// (UpdateProductPriceEndpoint.cs:54-58).
func (q *Queries) UpdatePrice(ctx context.Context, arg UpdatePriceParams) (ProductsProductPrice, error) {
	row := q.db.QueryRow(ctx, updatePrice,
		arg.Currency,
		arg.Amount,
		arg.ValidFrom,
		arg.ValidTo,
		arg.ID,
	)
	var i ProductsProductPrice
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Currency,
		&i.Amount,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products.products
SET name = $1,
    description = $2,
    category_id = $3,
    type = $4,
    status = $5,
    tax_category_id = $6,
    updated_at = $7::timestamptz
WHERE id = $8
RETURNING id, name, description, category_id, type, status, tax_category_id, created_at, updated_at
`

type UpdateProductParams struct {
	Name          string
	Description   *string
	CategoryID    *int32
	Type          string
	Status        string
	TaxCategoryID int32
	UpdatedAt     time.Time
	ID            int32
}

// UpdateProduct applies PUT /products/{id}'s validated shared fields
// (UpdateProductEndpoint.cs:53-64). request.Variants is never read here
// (products inventory §7 oddity 2): the handler never passes variant data
// to this query.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (ProductsProduct, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.Type,
		arg.Status,
		arg.TaxCategoryID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ProductsProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.Type,
		&i.Status,
		&i.TaxCategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE products.product_variants
SET sku = $1,
    barcode = $2,
    unit = $3,
    standard_cost = $4,
    weight_kg = $5,
    length_cm = $6,
    width_cm = $7,
    height_cm = $8,
    option_values = $9,
    updated_at = $10::timestamptz
WHERE id = $11
RETURNING id, product_id, sku, barcode, unit, standard_cost, weight_kg, length_cm, width_cm, height_cm,
          option_values, created_at, updated_at
`

type UpdateProductVariantParams struct {
	Sku          string
	Barcode      *string
	Unit         string
	StandardCost pgtype.Numeric
	WeightKg     pgtype.Numeric
	LengthCm     pgtype.Numeric
	WidthCm      pgtype.Numeric
	HeightCm     pgtype.Numeric
	OptionValues []byte
	UpdatedAt    time.Time
	ID           int32
}

// UpdateProductVariant applies PUT .../variants/{variantId}'s validated
// fields (UpdateProductVariantEndpoint.cs:55-64).
func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductsProductVariant, error) {
	row := q.db.QueryRow(ctx, updateProductVariant,
		arg.Sku,
		arg.Barcode,
		arg.Unit,
		arg.StandardCost,
		arg.WeightKg,
		arg.LengthCm,
		arg.WidthCm,
		arg.HeightCm,
		arg.OptionValues,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ProductsProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.StandardCost,
		&i.WeightKg,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
		&i.OptionValues,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaxCategory = `-- name: UpdateTaxCategory :one
UPDATE products.tax_categories
SET name = $1, kind = $2, rate = $3, updated_at = $4::timestamptz
WHERE id = $5
RETURNING id, name, kind, rate, created_at, updated_at
`

type UpdateTaxCategoryParams struct {
	Name      string
	Kind      string
	Rate      pgtype.Numeric
	UpdatedAt time.Time
	ID        int32
}

// UpdateTaxCategory applies UpdateTaxCategoryEndpoint's validated fields
// (:40-43).
func (q *Queries) UpdateTaxCategory(ctx context.Context, arg UpdateTaxCategoryParams) (ProductsTaxCategory, error) {
	row := q.db.QueryRow(ctx, updateTaxCategory,
		arg.Name,
		arg.Kind,
		arg.Rate,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ProductsTaxCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const variantAnyBarcodeExists = `-- name: VariantAnyBarcodeExists :one
SELECT EXISTS(SELECT 1 FROM products.product_variants WHERE barcode IS NOT NULL AND barcode = ANY($1::text[]))
`

// VariantAnyBarcodeExists is CreateProductEndpoint's catalog-wide
// duplicate-barcode check for a whole batch of new variants at once
// (:60-61).
func (q *Queries) VariantAnyBarcodeExists(ctx context.Context, barcodes []string) (bool, error) {
	row := q.db.QueryRow(ctx, variantAnyBarcodeExists, barcodes)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const variantAnySkuExists = `-- name: VariantAnySkuExists :one
SELECT EXISTS(SELECT 1 FROM products.product_variants WHERE sku = ANY($1::text[]))
`

// VariantAnySkuExists is CreateProductEndpoint's catalog-wide duplicate-SKU
// check for a whole batch of new variants at once (:48-49).
func (q *Queries) VariantAnySkuExists(ctx context.Context, skus []string) (bool, error) {
	row := q.db.QueryRow(ctx, variantAnySkuExists, skus)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const variantBarcodeExists = `-- name: VariantBarcodeExists :one
SELECT EXISTS(SELECT 1 FROM products.product_variants WHERE barcode = $1)
`

// VariantBarcodeExists is AddProductVariantEndpoint's catalog-wide
// duplicate-barcode check for a single new variant (:51).
func (q *Queries) VariantBarcodeExists(ctx context.Context, barcode *string) (bool, error) {
	row := q.db.QueryRow(ctx, variantBarcodeExists, barcode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const variantBarcodeExistsExcluding = `-- name: VariantBarcodeExistsExcluding :one
SELECT EXISTS(SELECT 1 FROM products.product_variants WHERE barcode = $1 AND id != $2)
`

type VariantBarcodeExistsExcludingParams struct {
	Barcode *string
	ID      int32
}

// VariantBarcodeExistsExcluding is UpdateProductVariantEndpoint's
// duplicate-barcode check, excluding the variant being updated (:50), which
// runs unconditionally even when the SKU did not change.
func (q *Queries) VariantBarcodeExistsExcluding(ctx context.Context, arg VariantBarcodeExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, variantBarcodeExistsExcluding, arg.Barcode, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const variantSkuExists = `-- name: VariantSkuExists :one
SELECT EXISTS(SELECT 1 FROM products.product_variants WHERE sku = $1)
`

// VariantSkuExists is AddProductVariantEndpoint's catalog-wide duplicate-SKU
// check for a single new variant (:46).
func (q *Queries) VariantSkuExists(ctx context.Context, sku string) (bool, error) {
	row := q.db.QueryRow(ctx, variantSkuExists, sku)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const variantSkuExistsExcluding = `-- name: VariantSkuExistsExcluding :one
SELECT EXISTS(SELECT 1 FROM products.product_variants WHERE sku = $1 AND id != $2)
`

type VariantSkuExistsExcludingParams struct {
	Sku string
	ID  int32
}

// VariantSkuExistsExcluding is UpdateProductVariantEndpoint's duplicate-SKU
// check, excluding the variant being renamed (:44).
func (q *Queries) VariantSkuExistsExcluding(ctx context.Context, arg VariantSkuExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, variantSkuExistsExcluding, arg.Sku, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
