import type { InvoiceDocument, InvoiceList } from "../api/invoices";
import type { InvoiceJournal } from "../api/journal";
import type { InvoicesMeta } from "../api/meta";
import type { InvoiceSettings } from "../api/settings";
import type { VatCode } from "../api/vat-codes";

/**
 * GET /meta as the server sends it — a wire literal: a complete seller, mail
 * available, the caller may create, issue, register payments and send, and
 * today is 2026-09-12 in Oslo.
 */
export const meta = (overrides: Partial<InvoicesMeta> = {}): InvoicesMeta => ({
  currency: "NOK",
  defaultPaymentTermsDays: 14,
  sellerComplete: true,
  missingSellerFields: [],
  anythingIssued: true,
  seriesStart: 1,
  storageAvailable: true,
  mailAvailable: true,
  today: "2026-09-12",
  vatCodes: [
    { id: 1, code: "3", name: "Utgående mva 25 %", safTCode: "3", ehfCategory: "S", ratePercent: 25 },
    { id: 2, code: "31", name: "Utgående mva 15 %", safTCode: "31", ehfCategory: "S", ratePercent: 15 },
    {
      id: 5,
      code: "5",
      name: "Fritatt innenlands 0 %",
      safTCode: "5",
      ehfCategory: "Z",
      exemptionReason: "Fritatt for merverdiavgift",
      ratePercent: 0,
    },
  ],
  capabilities: { canCreate: true, canIssue: true, canManage: false, canRegisterPayments: true, canSend: true },
  ...overrides,
});

/** An invoice draft for Acme with three lines of 33.33 at 25 %, as the server answers it. */
export const draft = (overrides: Partial<InvoiceDocument> = {}): InvoiceDocument => ({
  id: 1001,
  kind: "invoice",
  status: "draft",
  state: "draft",
  customerId: 2001,
  customerName: "Acme AS",
  deliveryDate: "2026-09-10",
  paymentTermsDays: 30,
  currency: "NOK",
  exchangeRate: 1,
  yourReference: "PO-77",
  ourReference: "Ola Nordmann",
  orderReference: "",
  note: "",
  internalNote: "",
  netTotal: 99.99,
  vatTotal: 25,
  grossTotal: 124.99,
  vatTotalNok: 25,
  lines: [1, 2, 3].map((position) => ({
    id: 5000 + position,
    position,
    description: `Tredjedel ${position}`,
    quantity: 1,
    unit: "timer",
    unitPrice: 33.33,
    discountPercent: 0,
    vatCodeId: 1,
    lineGross: 33.33,
    lineAllowance: 0,
    lineNet: 33.33,
  })),
  vatSummaries: [
    { vatCategory: "S", ratePercent: 25, safTCode: "3", taxableAmount: 99.99, vatAmount: 25, vatAmountNok: 25 },
  ],
  warnings: [],
  allowedIssueDates: ["2026-09-12"],
  createdAt: "2026-09-12T10:00:00Z",
  updatedAt: "2026-09-12T10:00:00Z",
  revision: 3,
  ...overrides,
});

/** The same invoice, issued as number 1000, nothing credited or paid yet: open. */
export const issued = (overrides: Partial<InvoiceDocument> = {}): InvoiceDocument => {
  const base = draft();
  return {
    ...base,
    status: "issued",
    state: "open",
    number: 1000,
    issueDate: "2026-09-12",
    dueDate: "2026-10-12",
    exchangeRateDate: "2026-09-12",
    customerName: "Acme Norge AS",
    issuedAt: "2026-09-12T10:30:00Z",
    issuedByUserId: "0b6e4c1a-5f7d-4d8e-9a3b-2c1d0e9f8a7b",
    buyer: {
      customerNumber: 10001,
      type: "business",
      name: "Acme Norge AS",
      organisationNumber: "923609016",
      addressLine1: "Kundeveien 2",
      postalCode: "0150",
      city: "Oslo",
      country: "NO",
      peppolId: "0192:923609016",
      gln: "7080000000001",
      language: "nb",
    },
    seller: {
      legalName: "Kraft-Verket AS",
      organisationNumber: "974760673",
      vatRegistered: true,
      inForetaksregisteret: true,
      addressLine1: "Storgata 1",
      addressLine2: "",
      postalCode: "0155",
      city: "Oslo",
      country: "NO",
      bankAccount: "15032080119",
      iban: "",
      bic: "",
      email: "faktura@kraft-verket.no",
      footerText: "",
    },
    lines: base.lines.map((l) => ({ ...l, vatRatePercent: 25, vatCategory: "S", safTCode: "3" })),
    allowedIssueDates: undefined,
    pdfStored: true,
    creditedAmount: 0,
    uncreditedAmount: 124.99,
    creditNotes: [],
    paidAmount: 0,
    openAmount: 124.99,
    payments: [],
    deliveries: [],
    sendDefaults: { recipient: "faktura@acme.no", warnings: ["buyer_norwegian_business"] },
    revision: 4,
    ...overrides,
  };
};

/**
 * Invoice 1000 as the server sends it once money has come in — a wire literal:
 * issued on 1 September, due on 1 October, 124.99 with one live payment of 50
 * and one of 20 removed with its reason, so 74.99 is open; sent twice, the
 * second time to an override; and the Send dialog's defaults for a sender.
 */
export const partlyPaid = (overrides: Partial<InvoiceDocument> = {}): InvoiceDocument => ({
  id: 1001,
  kind: "invoice",
  status: "issued",
  state: "partially_paid",
  number: 1000,
  customerId: 2001,
  customerName: "Acme Norge AS",
  issueDate: "2026-09-01",
  dueDate: "2026-10-01",
  deliveryDate: "2026-08-31",
  paymentTermsDays: 30,
  currency: "NOK",
  exchangeRate: 1,
  exchangeRateDate: "2026-09-01",
  yourReference: "PO-77",
  ourReference: "Ola Nordmann",
  orderReference: "",
  note: "",
  internalNote: "",
  netTotal: 99.99,
  vatTotal: 25,
  grossTotal: 124.99,
  vatTotalNok: 25,
  lines: [
    {
      id: 5001,
      position: 1,
      description: "Konsulenttimer",
      quantity: 1,
      unit: "timer",
      unitPrice: 99.99,
      discountPercent: 0,
      vatCodeId: 1,
      vatRatePercent: 25,
      vatCategory: "S",
      safTCode: "3",
      lineGross: 99.99,
      lineAllowance: 0,
      lineNet: 99.99,
    },
  ],
  vatSummaries: [
    { vatCategory: "S", ratePercent: 25, safTCode: "3", taxableAmount: 99.99, vatAmount: 25, vatAmountNok: 25 },
  ],
  warnings: [],
  buyer: {
    customerNumber: 10001,
    type: "business",
    name: "Acme Norge AS",
    organisationNumber: "923609016",
    addressLine1: "Kundeveien 2",
    postalCode: "0150",
    city: "Oslo",
    country: "NO",
    language: "nb",
  },
  seller: {
    legalName: "Kraft-Verket AS",
    organisationNumber: "974760673",
    vatRegistered: true,
    inForetaksregisteret: true,
    addressLine1: "Storgata 1",
    addressLine2: "",
    postalCode: "0155",
    city: "Oslo",
    country: "NO",
    bankAccount: "15032080119",
    iban: "",
    bic: "",
    email: "faktura@kraft-verket.no",
    footerText: "",
  },
  issuedAt: "2026-09-01T09:00:00Z",
  issuedByUserId: "0b6e4c1a-5f7d-4d8e-9a3b-2c1d0e9f8a7b",
  pdfStored: true,
  creditedAmount: 0,
  uncreditedAmount: 124.99,
  creditNotes: [],
  paidAmount: 50,
  openAmount: 74.99,
  payments: [
    {
      id: 1001,
      paidOn: "2026-09-05",
      amount: 20,
      currency: "NOK",
      reference: "Feil KID",
      note: "",
      registeredAt: "2026-09-05T08:00:00Z",
      registeredByUserId: "0b6e4c1a-5f7d-4d8e-9a3b-2c1d0e9f8a7b",
      removedAt: "2026-09-06T08:00:00Z",
      removedByUserId: "0b6e4c1a-5f7d-4d8e-9a3b-2c1d0e9f8a7b",
      removalReason: "Registrert på feil faktura",
    },
    {
      id: 1002,
      paidOn: "2026-09-10",
      amount: 50,
      currency: "NOK",
      reference: "Bank 4471",
      note: "Første avdrag",
      registeredAt: "2026-09-10T12:00:00Z",
      registeredByUserId: "0b6e4c1a-5f7d-4d8e-9a3b-2c1d0e9f8a7b",
    },
  ],
  deliveries: [
    {
      id: 1001,
      recipient: "faktura@acme.no",
      sentAt: "2026-09-01T09:05:00Z",
      sentByUserId: "0b6e4c1a-5f7d-4d8e-9a3b-2c1d0e9f8a7b",
      subject: "Faktura 1000 fra Kraft-Verket AS",
    },
    {
      id: 1002,
      recipient: "regnskap@acme.no",
      sentAt: "2026-09-11T10:00:00Z",
      sentByUserId: "0b6e4c1a-5f7d-4d8e-9a3b-2c1d0e9f8a7b",
      subject: "Faktura 1000 fra Kraft-Verket AS",
    },
  ],
  sendDefaults: { recipient: "faktura@acme.no", preference: "email", warnings: ["buyer_norwegian_business"] },
  createdAt: "2026-08-31T10:00:00Z",
  updatedAt: "2026-09-01T09:00:00Z",
  revision: 4,
  ...overrides,
});

/** A credit-note draft of invoice 1000, crediting its first line. */
export const creditDraft = (overrides: Partial<InvoiceDocument> = {}): InvoiceDocument => {
  const base = draft();
  return {
    ...base,
    id: 1002,
    kind: "credit_note",
    paymentTermsDays: undefined,
    customerName: "Acme Norge AS",
    buyer: {
      customerNumber: 10001,
      type: "business",
      name: "Acme Norge AS",
      organisationNumber: "923609016",
      language: "nb",
    },
    lines: [{ ...base.lines[0], id: 6001, creditsLineId: 5001 }],
    netTotal: 33.33,
    vatTotal: 8.33,
    grossTotal: 41.66,
    vatTotalNok: 8.33,
    vatSummaries: [
      { vatCategory: "S", ratePercent: 25, safTCode: "3", taxableAmount: 33.33, vatAmount: 8.33, vatAmountNok: 8.33 },
    ],
    credits: { id: 1001, number: 1000, issueDate: "2026-09-12" },
    revision: 1,
    ...overrides,
  };
};

/** A page of the list: a draft, then two issued documents. */
export const listPage = (overrides: Partial<InvoiceList["pagination"]> = {}): InvoiceList => ({
  data: [
    {
      id: 1003,
      kind: "invoice",
      status: "draft",
      state: "draft",
      customerId: 2002,
      customerName: "Kari Nordmann",
      currency: "NOK",
      grossTotal: 0,
    },
    {
      id: 1002,
      kind: "credit_note",
      status: "issued",
      state: "issued",
      number: 1001,
      customerId: 2001,
      customerName: "Acme Norge AS",
      issueDate: "2026-09-12",
      currency: "NOK",
      grossTotal: 41.66,
      creditsInvoiceId: 1001,
    },
    {
      id: 1001,
      kind: "invoice",
      status: "issued",
      state: "open",
      number: 1000,
      customerId: 2001,
      customerName: "Acme Norge AS",
      issueDate: "2026-09-12",
      dueDate: "2026-10-12",
      currency: "NOK",
      grossTotal: 124.99,
      openAmount: 124.99,
    },
  ],
  pagination: {
    page: 1,
    pageSize: 25,
    totalCount: 3,
    totalPages: 1,
    hasNextPage: false,
    hasPreviousPage: false,
    ...overrides,
  },
});

/**
 * GET /vat-codes as the server sends it: every code, inactive ones included.
 * Code 3 is at 25 % with a change to 26 % from 2027, not yet in force; code 9
 * is no longer offered but still has a period covering today.
 */
export const vatCodes = (): VatCode[] => [
  {
    id: 1,
    code: "3",
    name: "Utgående mva 25 %",
    safTCode: "3",
    ehfCategory: "S",
    active: true,
    inUse: true,
    revision: 1,
    rates: [
      { id: 1001, ratePercent: 25, validFrom: "2026-01-01", validTo: "2026-12-31" },
      { id: 1002, ratePercent: 26, validFrom: "2027-01-01" },
    ],
  },
  {
    id: 2,
    code: "31",
    name: "Utgående mva 15 %",
    safTCode: "31",
    ehfCategory: "S",
    active: true,
    inUse: false,
    revision: 1,
    rates: [{ id: 1003, ratePercent: 15, validFrom: "2026-01-01" }],
  },
  {
    id: 5,
    code: "5",
    name: "Fritatt innenlands 0 %",
    safTCode: "5",
    ehfCategory: "Z",
    exemptionReason: "Fritatt for merverdiavgift",
    active: true,
    inUse: false,
    revision: 1,
    rates: [{ id: 1005, ratePercent: 0, validFrom: "2026-01-01" }],
  },
  {
    id: 9,
    code: "3G",
    name: "Gammel sats",
    safTCode: "3",
    ehfCategory: "S",
    active: false,
    inUse: true,
    revision: 2,
    rates: [{ id: 1009, ratePercent: 25, validFrom: "2020-01-01" }],
  },
];

/** The settings as the server sends them: a seller lacking two fields, the series locked. */
export const settings = (overrides: Partial<InvoiceSettings> = {}): InvoiceSettings => ({
  legalName: "Kraft-Verket AS",
  organisationNumber: "974760673",
  vatRegistered: true,
  inForetaksregisteret: true,
  addressLine1: "Storgata 1",
  addressLine2: "",
  postalCode: "",
  city: "Oslo",
  country: "NO",
  bankAccount: "",
  iban: "",
  bic: "",
  email: "faktura@kraft-verket.no",
  defaultPaymentTermsDays: 14,
  defaultCurrency: "NOK",
  footerText: "",
  seriesStart: 1000,
  seriesLocked: true,
  peppolId: null,
  kidLength: null,
  kidAlgorithm: null,
  missingSellerFields: ["postalCode", "bankAccount"],
  warnings: [],
  revision: 5,
  updatedAt: "2026-09-12T10:00:00Z",
  ...overrides,
});

/** A month's journal: numbers 1000 to 1002, a credit note signed negative. */
export const journal = (overrides: Partial<InvoiceJournal> = {}): InvoiceJournal => ({
  data: [
    {
      id: 1,
      number: 1000,
      kind: "invoice",
      issueDate: "2026-09-02",
      currency: "NOK",
      buyerName: "Acme Norge AS",
      netTotal: 1000,
      vatTotal: 250,
      grossTotal: 1250,
      vatSummaries: [{ safTCode: "3", category: "S", ratePercent: 25, taxableAmount: 1000, vatAmount: 250 }],
    },
    {
      id: 2,
      number: 1001,
      kind: "invoice",
      issueDate: "2026-09-05",
      currency: "NOK",
      buyerName: "Kari Nordmann",
      netTotal: 200,
      vatTotal: 0,
      grossTotal: 200,
      vatSummaries: [{ safTCode: "5", category: "Z", ratePercent: 0, taxableAmount: 200, vatAmount: 0 }],
    },
    {
      id: 3,
      number: 1002,
      kind: "credit_note",
      issueDate: "2026-09-10",
      currency: "NOK",
      buyerName: "Acme Norge AS",
      netTotal: -400,
      vatTotal: -100,
      grossTotal: -500,
      creditsNumber: 1000,
      vatSummaries: [{ safTCode: "3", category: "S", ratePercent: 25, taxableAmount: -400, vatAmount: -100 }],
    },
  ],
  pagination: { page: 1, pageSize: 25, totalCount: 3, totalPages: 1, hasNextPage: false, hasPreviousPage: false },
  totals: {
    byCode: [
      { safTCode: "3", category: "S", ratePercent: 25, taxableAmount: 600, vatAmount: 150 },
      { safTCode: "5", category: "Z", ratePercent: 0, taxableAmount: 200, vatAmount: 0 },
    ],
    netTotal: 800,
    vatTotal: 150,
    grossTotal: 950,
  },
  gaps: [],
  gapsTruncated: false,
  seriesStart: 1000,
  counterLast: 1002,
  highestIssued: 1002,
  checkedFrom: 1000,
  checkedTo: 1002,
  ...overrides,
});
