// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTaskComments = `-- name: CountTaskComments :one
SELECT count(*) FROM projects.task_comments WHERE task_id = $1
`

// CountTaskComments is ListTaskComments' total, for the page envelope.
func (q *Queries) CountTaskComments(ctx context.Context, taskID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countTaskComments, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTaskComment = `-- name: DeleteTaskComment :execrows
DELETE FROM projects.task_comments WHERE id = $1 AND task_id = $2
`

type DeleteTaskCommentParams struct {
	ID     int64
	TaskID int32
}

// DeleteTaskComment removes one comment of one task. The row count is what
// decides the 404: two deletes racing must not both answer 204.
func (q *Queries) DeleteTaskComment(ctx context.Context, arg DeleteTaskCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskComment, arg.ID, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskComment = `-- name: GetTaskComment :one
SELECT id, task_id, author_user_id, body, created_at, edited_at FROM projects.task_comments WHERE id = $1 AND task_id = $2
`

type GetTaskCommentParams struct {
	ID     int64
	TaskID int32
}

// GetTaskComment is one comment of one task: the read that settles both
// whether the comment is there and who wrote it, which is what decides who may
// change or remove it.
func (q *Queries) GetTaskComment(ctx context.Context, arg GetTaskCommentParams) (ProjectsTaskComment, error) {
	row := q.db.QueryRow(ctx, getTaskComment, arg.ID, arg.TaskID)
	var i ProjectsTaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const insertTaskComment = `-- name: InsertTaskComment :one
INSERT INTO projects.task_comments (task_id, author_user_id, body, created_at)
VALUES ($1, $2, $3, $4::timestamptz)
RETURNING id, task_id, author_user_id, body, created_at, edited_at
`

type InsertTaskCommentParams struct {
	TaskID       int32
	AuthorUserID uuid.UUID
	Body         string
	Now          time.Time
}

// InsertTaskComment writes one comment. created_at is supplied by the caller
// from Deps.Clock(); edited_at stays null, which is what "nobody has rewritten
// this" means on the wire.
func (q *Queries) InsertTaskComment(ctx context.Context, arg InsertTaskCommentParams) (ProjectsTaskComment, error) {
	row := q.db.QueryRow(ctx, insertTaskComment,
		arg.TaskID,
		arg.AuthorUserID,
		arg.Body,
		arg.Now,
	)
	var i ProjectsTaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const listTaskComments = `-- name: ListTaskComments :many

SELECT id, task_id, author_user_id, body, created_at, edited_at FROM projects.task_comments
WHERE task_id = $1
ORDER BY created_at, id
LIMIT $3 OFFSET $2
`

type ListTaskCommentsParams struct {
	TaskID     int32
	PageOffset int32
	PageSize   int32
}

// The comment queries (design §3.1, §4.1). A task's comments are its own
// history — which is why a task writes nothing to the project timeline — so
// they are read oldest first and paged the way the timeline is.
//
// author_user_id is opaque here, exactly as assignee_user_id is on a task: no
// query in this module joins identity's schema, so a comment's author is named
// afterwards through contracts.UserDirectory, in one call for the whole page.
//
// Every comment query is scoped by task_id as well as by id, because a comment
// is addressed under the task in its path: a comment of another task must
// answer the same bare 404 an unknown one does.
// ListTaskComments is one page of a task's comments, oldest first, in the
// order ix_task_comments_task_id_created_at is built for. The id breaks ties:
// two comments can share an instant, and they must still come back in a stable
// order, the first written first.
func (q *Queries) ListTaskComments(ctx context.Context, arg ListTaskCommentsParams) ([]ProjectsTaskComment, error) {
	rows, err := q.db.Query(ctx, listTaskComments, arg.TaskID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsTaskComment
	for rows.Next() {
		var i ProjectsTaskComment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskComment = `-- name: UpdateTaskComment :one
UPDATE projects.task_comments SET
    body = $1,
    edited_at = $2::timestamptz
WHERE id = $3 AND task_id = $4
RETURNING id, task_id, author_user_id, body, created_at, edited_at
`

type UpdateTaskCommentParams struct {
	Body   string
	Now    time.Time
	ID     int64
	TaskID int32
}

// UpdateTaskComment rewrites one comment and stamps when it happened, so a
// reader can tell a comment that was changed from one that was not. The author
// is never rewritten: only the author reaches this statement.
func (q *Queries) UpdateTaskComment(ctx context.Context, arg UpdateTaskCommentParams) (ProjectsTaskComment, error) {
	row := q.db.QueryRow(ctx, updateTaskComment,
		arg.Body,
		arg.Now,
		arg.ID,
		arg.TaskID,
	)
	var i ProjectsTaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}
