// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counters.sql

package store

import (
	"context"
)

const nextCounterValue = `-- name: NextCounterValue :one
INSERT INTO projects.counters (counter_name, next_value)
VALUES ($1, 1001)
ON CONFLICT (counter_name) DO UPDATE SET next_value = projects.counters.next_value + 1
RETURNING (next_value - 1)::bigint AS allocated
`

// NextCounterValue allocates the next value of a named counter, the same
// gapless-per-counter upsert customers uses: the first call for a counter
// allocates 1000 — project codes count from KVEM1000, not KVEM1 — and every
// later call allocates one more, so two concurrent creates can never
// allocate the same value, even if one of them later rolls back.
//
// next_value always holds the next number nobody has taken yet: the first
// call returns 1000 and leaves 1001 behind, the second returns 1001 and
// leaves 1002. That is what lets the code suggestion read next_value
// directly, without allocating, and treat an absent row as 1000; only a
// create advances it, whatever code that create actually used.
func (q *Queries) NextCounterValue(ctx context.Context, counterName string) (int64, error) {
	row := q.db.QueryRow(ctx, nextCounterValue, counterName)
	var allocated int64
	err := row.Scan(&allocated)
	return allocated, err
}

const peekCounterValue = `-- name: PeekCounterValue :one
SELECT next_value FROM projects.counters WHERE counter_name = $1
`

// PeekCounterValue reads a counter's next_value without allocating: the
// code suggestion's own read (design §4.2), which must never advance what a
// real create later allocates. A counter nobody has allocated from yet has
// no row at all, which the caller (not this query) treats as 1000 —
// NextCounterValue's own first-call value.
func (q *Queries) PeekCounterValue(ctx context.Context, counterName string) (int64, error) {
	row := q.db.QueryRow(ctx, peekCounterValue, counterName)
	var next_value int64
	err := row.Scan(&next_value)
	return next_value, err
}
