// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTaskOrderLock = `-- name: AcquireTaskOrderLock :exec
SELECT pg_advisory_xact_lock($1::integer, $2::integer)
`

type AcquireTaskOrderLockParams struct {
	LockClass int32
	ProjectID int32
}

// AcquireTaskOrderLock is the serialisation point of every write that decides
// a position inside one project: a create appending after its siblings, and a
// move renumbering them. A row lock cannot cover a create — the number two
// concurrent creates race for is the gap after the last row, and a gap has no
// row to lock — so the lock is taken on the project instead, for the rest of
// the transaction. It is a two-argument advisory lock, which is a lock space
// of its own: it can never collide with identity's single-argument ones.
func (q *Queries) AcquireTaskOrderLock(ctx context.Context, arg AcquireTaskOrderLockParams) error {
	_, err := q.db.Exec(ctx, acquireTaskOrderLock, arg.LockClass, arg.ProjectID)
	return err
}

const countSubtasks = `-- name: CountSubtasks :one
SELECT count(*) FROM projects.tasks WHERE parent_task_id = $1
`

// CountSubtasks is D6's depth rule, asked of the task that is being moved: a
// task with subtasks of its own cannot become a subtask, because that would
// nest three levels deep.
func (q *Queries) CountSubtasks(ctx context.Context, parentTaskID *int32) (int64, error) {
	row := q.db.QueryRow(ctx, countSubtasks, parentTaskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM projects.tasks WHERE id = $1
`

// DeleteTask removes one task. Its subtasks, checklist items and comments go
// with it through the foreign keys' ON DELETE CASCADE (migration 00009), so
// nothing is left pointing at a task that is gone. The row count is what
// decides the 404: two deletes racing must not both answer 204.
func (q *Queries) DeleteTask(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one

SELECT id, project_id, parent_task_id, title, description, status, assignee_user_id, start_date, due_date, estimate_hours, position, completed_at, created_by_user_id, revision, created_at, updated_at FROM projects.tasks WHERE id = $1
`

// The task queries (design §3.1, §4.1). Three things run through them: a
// task is always read with the two aggregates the contract embeds (its
// checklist progress and its comment count), the sibling group — a project's
// top-level tasks, or one task's subtasks — is the unit ordering is decided
// in, and every write that decides a position takes the project's ordering
// lock first (AcquireTaskOrderLock).
//
// The aggregates are lateral subqueries rather than a join with a GROUP BY so
// that one query answers a whole project's tree without multiplying rows:
// a task with three checklist items and two comments is still one row.
// GetTask fetches one task by id, with none of its aggregates: it is the read
// that resolves which project a /projects/tasks/{taskId} request is about, and
// an unknown task and a task on an invisible project answer the same bare 404,
// so the row is loaded first and discarded after (projects.go's GetProject
// does the same for a project).
func (q *Queries) GetTask(ctx context.Context, id int32) (ProjectsTask, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i ProjectsTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeUserID,
		&i.StartDate,
		&i.DueDate,
		&i.EstimateHours,
		&i.Position,
		&i.CompletedAt,
		&i.CreatedByUserID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskWithCounts = `-- name: GetTaskWithCounts :one
SELECT t.id, t.project_id, t.parent_task_id, t.title, t.description, t.status, t.assignee_user_id, t.start_date, t.due_date, t.estimate_hours, t.position, t.completed_at, t.created_by_user_id, t.revision, t.created_at, t.updated_at,
       coalesce(c.total, 0)::integer    AS checklist_total,
       coalesce(c.done, 0)::integer     AS checklist_done,
       coalesce(m.comments, 0)::integer AS comment_count
FROM projects.tasks t
LEFT JOIN LATERAL (
    SELECT count(*) AS total, count(*) FILTER (WHERE i.done) AS done
    FROM projects.task_checklist_items i WHERE i.task_id = t.id
) c ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS comments
    FROM projects.task_comments k WHERE k.task_id = t.id
) m ON true
WHERE t.id = $1
`

type GetTaskWithCountsRow struct {
	ProjectsTask   ProjectsTask
	ChecklistTotal int32
	ChecklistDone  int32
	CommentCount   int32
}

// GetTaskWithCounts is one task in the shape the contract answers with: the
// row plus its checklist progress and comment count. It is what an update or
// a move renders its answer from, since neither touches those children but
// both must report them.
func (q *Queries) GetTaskWithCounts(ctx context.Context, id int32) (GetTaskWithCountsRow, error) {
	row := q.db.QueryRow(ctx, getTaskWithCounts, id)
	var i GetTaskWithCountsRow
	err := row.Scan(
		&i.ProjectsTask.ID,
		&i.ProjectsTask.ProjectID,
		&i.ProjectsTask.ParentTaskID,
		&i.ProjectsTask.Title,
		&i.ProjectsTask.Description,
		&i.ProjectsTask.Status,
		&i.ProjectsTask.AssigneeUserID,
		&i.ProjectsTask.StartDate,
		&i.ProjectsTask.DueDate,
		&i.ProjectsTask.EstimateHours,
		&i.ProjectsTask.Position,
		&i.ProjectsTask.CompletedAt,
		&i.ProjectsTask.CreatedByUserID,
		&i.ProjectsTask.Revision,
		&i.ProjectsTask.CreatedAt,
		&i.ProjectsTask.UpdatedAt,
		&i.ChecklistTotal,
		&i.ChecklistDone,
		&i.CommentCount,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO projects.tasks (
    project_id, parent_task_id, title, description, status, assignee_user_id,
    start_date, due_date, estimate_hours, position, completed_at,
    created_by_user_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13::timestamptz, $13::timestamptz
)
RETURNING id, project_id, parent_task_id, title, description, status, assignee_user_id, start_date, due_date, estimate_hours, position, completed_at, created_by_user_id, revision, created_at, updated_at
`

type InsertTaskParams struct {
	ProjectID       int32
	ParentTaskID    *int32
	Title           string
	Description     *string
	Status          string
	AssigneeUserID  *uuid.UUID
	StartDate       pgtype.Date
	DueDate         pgtype.Date
	EstimateHours   pgtype.Numeric
	Position        int32
	CompletedAt     *time.Time
	CreatedByUserID uuid.UUID
	Now             time.Time
}

// InsertTask creates one task. created_at and updated_at are the same instant
// on creation, supplied by the caller from Deps.Clock(); status and revision
// are given explicitly since a body may carry a status, and position is the
// number computed under the project's ordering lock.
func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (ProjectsTask, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ProjectID,
		arg.ParentTaskID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeUserID,
		arg.StartDate,
		arg.DueDate,
		arg.EstimateHours,
		arg.Position,
		arg.CompletedAt,
		arg.CreatedByUserID,
		arg.Now,
	)
	var i ProjectsTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeUserID,
		&i.StartDate,
		&i.DueDate,
		&i.EstimateHours,
		&i.Position,
		&i.CompletedAt,
		&i.CreatedByUserID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMyOpenTasks = `-- name: ListMyOpenTasks :many
SELECT t.id, t.project_id, t.parent_task_id, t.title, t.description, t.status, t.assignee_user_id, t.start_date, t.due_date, t.estimate_hours, t.position, t.completed_at, t.created_by_user_id, t.revision, t.created_at, t.updated_at,
       p.code AS project_code,
       p.name AS project_name,
       coalesce(c.total, 0)::integer    AS checklist_total,
       coalesce(c.done, 0)::integer     AS checklist_done,
       coalesce(m.comments, 0)::integer AS comment_count
FROM projects.tasks t
JOIN projects.projects p ON p.id = t.project_id
LEFT JOIN LATERAL (
    SELECT count(*) AS total, count(*) FILTER (WHERE i.done) AS done
    FROM projects.task_checklist_items i WHERE i.task_id = t.id
) c ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS comments
    FROM projects.task_comments k WHERE k.task_id = t.id
) m ON true
WHERE t.assignee_user_id = $1::uuid
  AND t.status <> 'done'
  AND projects.visible(p.id, $1, $2::boolean)
ORDER BY t.due_date NULLS LAST, p.code, t.position, t.id
`

type ListMyOpenTasksParams struct {
	UserID uuid.UUID
	SeeAll bool
}

type ListMyOpenTasksRow struct {
	ProjectsTask   ProjectsTask
	ProjectCode    string
	ProjectName    string
	ChecklistTotal int32
	ChecklistDone  int32
	CommentCount   int32
}

// ListMyOpenTasks is design §4.1's "my tasks": every task assigned to the
// caller that is not done, on a project the caller can see. Visibility is the
// query's own predicate through projects.visible — the same function the
// project list and every stats query use — rather than a filter applied to the
// rows afterwards, so a task on a project the caller lost their role on simply
// does not come back.
//
// The order is the one the list is read in: what is due first, then by project
// so one project's tasks stay together, then by the order inside it.
func (q *Queries) ListMyOpenTasks(ctx context.Context, arg ListMyOpenTasksParams) ([]ListMyOpenTasksRow, error) {
	rows, err := q.db.Query(ctx, listMyOpenTasks, arg.UserID, arg.SeeAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyOpenTasksRow
	for rows.Next() {
		var i ListMyOpenTasksRow
		if err := rows.Scan(
			&i.ProjectsTask.ID,
			&i.ProjectsTask.ProjectID,
			&i.ProjectsTask.ParentTaskID,
			&i.ProjectsTask.Title,
			&i.ProjectsTask.Description,
			&i.ProjectsTask.Status,
			&i.ProjectsTask.AssigneeUserID,
			&i.ProjectsTask.StartDate,
			&i.ProjectsTask.DueDate,
			&i.ProjectsTask.EstimateHours,
			&i.ProjectsTask.Position,
			&i.ProjectsTask.CompletedAt,
			&i.ProjectsTask.CreatedByUserID,
			&i.ProjectsTask.Revision,
			&i.ProjectsTask.CreatedAt,
			&i.ProjectsTask.UpdatedAt,
			&i.ProjectCode,
			&i.ProjectName,
			&i.ChecklistTotal,
			&i.ChecklistDone,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT t.id, t.project_id, t.parent_task_id, t.title, t.description, t.status, t.assignee_user_id, t.start_date, t.due_date, t.estimate_hours, t.position, t.completed_at, t.created_by_user_id, t.revision, t.created_at, t.updated_at,
       coalesce(c.total, 0)::integer    AS checklist_total,
       coalesce(c.done, 0)::integer     AS checklist_done,
       coalesce(m.comments, 0)::integer AS comment_count
FROM projects.tasks t
LEFT JOIN LATERAL (
    SELECT count(*) AS total, count(*) FILTER (WHERE i.done) AS done
    FROM projects.task_checklist_items i WHERE i.task_id = t.id
) c ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS comments
    FROM projects.task_comments k WHERE k.task_id = t.id
) m ON true
WHERE t.project_id = $1
  AND ($2::text IS NULL OR t.status = $2)
  AND ($3::uuid IS NULL OR t.assignee_user_id = $3)
ORDER BY (t.parent_task_id IS NOT NULL), t.position, t.id
`

type ListProjectTasksParams struct {
	ProjectID      int32
	Status         *string
	AssigneeUserID *uuid.UUID
}

type ListProjectTasksRow struct {
	ProjectsTask   ProjectsTask
	ChecklistTotal int32
	ChecklistDone  int32
	CommentCount   int32
}

// ListProjectTasks is a whole project's tasks, aggregates included, in one
// query: the tree is assembled in Go from these rows, so a project with fifty
// tasks costs one round trip and not one per parent.
//
// The order is what the tree is built from: top-level tasks first, then
// subtasks, each group by position. Both filters are optional, and an absent
// one filters nothing.
func (q *Queries) ListProjectTasks(ctx context.Context, arg ListProjectTasksParams) ([]ListProjectTasksRow, error) {
	rows, err := q.db.Query(ctx, listProjectTasks, arg.ProjectID, arg.Status, arg.AssigneeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectTasksRow
	for rows.Next() {
		var i ListProjectTasksRow
		if err := rows.Scan(
			&i.ProjectsTask.ID,
			&i.ProjectsTask.ProjectID,
			&i.ProjectsTask.ParentTaskID,
			&i.ProjectsTask.Title,
			&i.ProjectsTask.Description,
			&i.ProjectsTask.Status,
			&i.ProjectsTask.AssigneeUserID,
			&i.ProjectsTask.StartDate,
			&i.ProjectsTask.DueDate,
			&i.ProjectsTask.EstimateHours,
			&i.ProjectsTask.Position,
			&i.ProjectsTask.CompletedAt,
			&i.ProjectsTask.CreatedByUserID,
			&i.ProjectsTask.Revision,
			&i.ProjectsTask.CreatedAt,
			&i.ProjectsTask.UpdatedAt,
			&i.ChecklistTotal,
			&i.ChecklistDone,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskWithSubtasks = `-- name: ListTaskWithSubtasks :many
SELECT t.id, t.project_id, t.parent_task_id, t.title, t.description, t.status, t.assignee_user_id, t.start_date, t.due_date, t.estimate_hours, t.position, t.completed_at, t.created_by_user_id, t.revision, t.created_at, t.updated_at,
       coalesce(c.total, 0)::integer    AS checklist_total,
       coalesce(c.done, 0)::integer     AS checklist_done,
       coalesce(m.comments, 0)::integer AS comment_count
FROM projects.tasks t
LEFT JOIN LATERAL (
    SELECT count(*) AS total, count(*) FILTER (WHERE i.done) AS done
    FROM projects.task_checklist_items i WHERE i.task_id = t.id
) c ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS comments
    FROM projects.task_comments k WHERE k.task_id = t.id
) m ON true
WHERE t.id = $1 OR t.parent_task_id = $1
ORDER BY (t.id <> $1), t.position, t.id
`

type ListTaskWithSubtasksRow struct {
	ProjectsTask   ProjectsTask
	ChecklistTotal int32
	ChecklistDone  int32
	CommentCount   int32
}

// ListTaskWithSubtasks is one task and the subtasks under it, aggregates
// included, in one query — the single-task read. The task itself sorts first
// (its own id is not "not the id asked for"), so the caller never has to look
// for it among its children.
func (q *Queries) ListTaskWithSubtasks(ctx context.Context, id int32) ([]ListTaskWithSubtasksRow, error) {
	rows, err := q.db.Query(ctx, listTaskWithSubtasks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskWithSubtasksRow
	for rows.Next() {
		var i ListTaskWithSubtasksRow
		if err := rows.Scan(
			&i.ProjectsTask.ID,
			&i.ProjectsTask.ProjectID,
			&i.ProjectsTask.ParentTaskID,
			&i.ProjectsTask.Title,
			&i.ProjectsTask.Description,
			&i.ProjectsTask.Status,
			&i.ProjectsTask.AssigneeUserID,
			&i.ProjectsTask.StartDate,
			&i.ProjectsTask.DueDate,
			&i.ProjectsTask.EstimateHours,
			&i.ProjectsTask.Position,
			&i.ProjectsTask.CompletedAt,
			&i.ProjectsTask.CreatedByUserID,
			&i.ProjectsTask.Revision,
			&i.ProjectsTask.CreatedAt,
			&i.ProjectsTask.UpdatedAt,
			&i.ChecklistTotal,
			&i.ChecklistDone,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTask = `-- name: LockTask :one
SELECT id, project_id, parent_task_id, title, description, status, assignee_user_id, start_date, due_date, estimate_hours, position, completed_at, created_by_user_id, revision, created_at, updated_at FROM projects.tasks WHERE id = $1 FOR UPDATE
`

// LockTask is GetTask with the row held for the rest of the transaction: an
// update decides its completed_at stamp from the status the row actually has,
// and a move decides both sibling groups from the parent it actually has.
// Deciding either from a read taken before the transaction would let another
// writer move it in between.
func (q *Queries) LockTask(ctx context.Context, id int32) (ProjectsTask, error) {
	row := q.db.QueryRow(ctx, lockTask, id)
	var i ProjectsTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeUserID,
		&i.StartDate,
		&i.DueDate,
		&i.EstimateHours,
		&i.Position,
		&i.CompletedAt,
		&i.CreatedByUserID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const maxSiblingPosition = `-- name: MaxSiblingPosition :one
SELECT coalesce(max(position), 0)::integer FROM projects.tasks
WHERE project_id = $1
  AND parent_task_id IS NOT DISTINCT FROM $2::integer
`

type MaxSiblingPositionParams struct {
	ProjectID    int32
	ParentTaskID *int32
}

// MaxSiblingPosition is the number a create appends after, 0 for the first
// task of a group. IS NOT DISTINCT FROM is what makes "the project's top-level
// tasks" (parent_task_id IS NULL) one sibling group like any other rather than
// a second query.
func (q *Queries) MaxSiblingPosition(ctx context.Context, arg MaxSiblingPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxSiblingPosition, arg.ProjectID, arg.ParentTaskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const renumberTasks = `-- name: RenumberTasks :exec
UPDATE projects.tasks t
SET position = v.ord::integer, updated_at = $1::timestamptz
FROM unnest($2::integer[]) WITH ORDINALITY AS v(id, ord)
WHERE t.id = v.id AND t.position <> v.ord::integer
`

type RenumberTasksParams struct {
	Now time.Time
	Ids []int32
}

// RenumberTasks writes a sibling group's order back as 1..n in one statement:
// ids is the group in its new order and WITH ORDINALITY is the number each one
// takes. A row already carrying its number is left alone, so a move that only
// reordered part of a group does not touch the rest of it.
func (q *Queries) RenumberTasks(ctx context.Context, arg RenumberTasksParams) error {
	_, err := q.db.Exec(ctx, renumberTasks, arg.Now, arg.Ids)
	return err
}

const setTaskParent = `-- name: SetTaskParent :exec
UPDATE projects.tasks SET
    parent_task_id = $1::integer,
    updated_at = $2::timestamptz
WHERE id = $3
`

type SetTaskParentParams struct {
	ParentTaskID *int32
	Now          time.Time
	ID           int32
}

// SetTaskParent moves a task between sibling groups. It writes no position:
// the number is RenumberTasks', which runs over the whole group afterwards, so
// there is never a moment where two siblings both claim one number.
func (q *Queries) SetTaskParent(ctx context.Context, arg SetTaskParentParams) error {
	_, err := q.db.Exec(ctx, setTaskParent, arg.ParentTaskID, arg.Now, arg.ID)
	return err
}

const siblingTaskIDs = `-- name: SiblingTaskIDs :many
SELECT id FROM projects.tasks
WHERE project_id = $1
  AND parent_task_id IS NOT DISTINCT FROM $2::integer
ORDER BY position, id
FOR UPDATE
`

type SiblingTaskIDsParams struct {
	ProjectID    int32
	ParentTaskID *int32
}

// SiblingTaskIDs is one sibling group in its current order, every row held for
// the rest of the transaction. The move reorders this list in Go and writes it
// back with RenumberTasks, so what it renumbers is exactly what it read.
func (q *Queries) SiblingTaskIDs(ctx context.Context, arg SiblingTaskIDsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, siblingTaskIDs, arg.ProjectID, arg.ParentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE projects.tasks SET
    title = $1,
    description = $2,
    status = $3,
    assignee_user_id = $4,
    start_date = $5,
    due_date = $6,
    estimate_hours = $7,
    completed_at = $8,
    revision = revision + 1,
    updated_at = $9::timestamptz
WHERE id = $10 AND revision = $11
RETURNING id, project_id, parent_task_id, title, description, status, assignee_user_id, start_date, due_date, estimate_hours, position, completed_at, created_by_user_id, revision, created_at, updated_at
`

type UpdateTaskParams struct {
	Title          string
	Description    *string
	Status         string
	AssigneeUserID *uuid.UUID
	StartDate      pgtype.Date
	DueDate        pgtype.Date
	EstimateHours  pgtype.Numeric
	CompletedAt    *time.Time
	Now            time.Time
	ID             int32
	Revision       int32
}

// UpdateTask applies one edit, guarded by the revision the caller read (design
// §3). A revision that has moved on matches no row, which is the handler's
// 409: the second writer never silently overwrites the first. Where the task
// sits is not part of an update — position and parent_task_id are the move's,
// so that an edit saved from an open drawer cannot undo somebody's reordering.
func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (ProjectsTask, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeUserID,
		arg.StartDate,
		arg.DueDate,
		arg.EstimateHours,
		arg.CompletedAt,
		arg.Now,
		arg.ID,
		arg.Revision,
	)
	var i ProjectsTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentTaskID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeUserID,
		&i.StartDate,
		&i.DueDate,
		&i.EstimateHours,
		&i.Position,
		&i.CompletedAt,
		&i.CreatedByUserID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
