import type { CatalogResources } from "@vantigo/frontend-shell";

type HostTranslationFunction = (key: string) => string;

export const hostBuiltInRoleTranslationKeys = {
  User: { displayNameKey: "admin.userRole", descriptionKey: "admin.userRoleDescription" },
  Owner: { displayNameKey: "admin.ownerRole", descriptionKey: "admin.ownerRoleDescription" },
} as const;

export const getHostBuiltInRoleTranslation = (role: string) =>
  hostBuiltInRoleTranslationKeys[role as keyof typeof hostBuiltInRoleTranslationKeys];

export const translateHostRole = (role: string, t: HostTranslationFunction, fallback = role): string => {
  const translation = getHostBuiltInRoleTranslation(role);
  return translation ? t(translation.displayNameKey) : fallback;
};

export const translateHostRoleDescription = (role: string, fallback: string, t: HostTranslationFunction): string => {
  const translation = getHostBuiltInRoleTranslation(role);
  return translation ? t(translation.descriptionKey) : fallback;
};

export const hostPermissionTranslationKeys = {
  "identity:manage": {
    moduleKey: "admin.permission.module.identity",
    categoryKey: "admin.permission.category.administration",
    displayNameKey: "admin.permission.identityManage",
    descriptionKey: "admin.permission.identityManageDescription",
  },
  "customers:view": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.customers",
    displayNameKey: "admin.permission.customersView",
    descriptionKey: "admin.permission.customersViewDescription",
  },
  "customers:create": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.customers",
    displayNameKey: "admin.permission.customersCreate",
    descriptionKey: "admin.permission.customersCreateDescription",
  },
  "customers:update": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.customers",
    displayNameKey: "admin.permission.customersUpdate",
    descriptionKey: "admin.permission.customersUpdateDescription",
  },
  "customers:delete": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.customers",
    displayNameKey: "admin.permission.customersDelete",
    descriptionKey: "admin.permission.customersDeleteDescription",
  },
  "customers:legal-identity-view": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.legalIdentity",
    displayNameKey: "admin.permission.customersLegalIdentityView",
    descriptionKey: "admin.permission.customersLegalIdentityViewDescription",
  },
  "customers:legal-identity-manage": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.legalIdentity",
    displayNameKey: "admin.permission.customersLegalIdentityManage",
    descriptionKey: "admin.permission.customersLegalIdentityManageDescription",
  },
  "customers:contacts-view": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.contacts",
    displayNameKey: "admin.permission.customersContactsView",
    descriptionKey: "admin.permission.customersContactsViewDescription",
  },
  "customers:contacts-manage": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.contacts",
    displayNameKey: "admin.permission.customersContactsManage",
    descriptionKey: "admin.permission.customersContactsManageDescription",
  },
  "customers:associations-view": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.associations",
    displayNameKey: "admin.permission.customersAssociationsView",
    descriptionKey: "admin.permission.customersAssociationsViewDescription",
  },
  "customers:associations-manage": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.associations",
    displayNameKey: "admin.permission.customersAssociationsManage",
    descriptionKey: "admin.permission.customersAssociationsManageDescription",
  },
  "customers:timeline-view": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.timeline",
    displayNameKey: "admin.permission.customersTimelineView",
    descriptionKey: "admin.permission.customersTimelineViewDescription",
  },
  "customers:timeline-manage": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.timeline",
    displayNameKey: "admin.permission.customersTimelineManage",
    descriptionKey: "admin.permission.customersTimelineManageDescription",
  },
  "customers:lookup-view": {
    moduleKey: "admin.permission.module.customers",
    categoryKey: "admin.permission.category.lookup",
    displayNameKey: "admin.permission.customersLookupView",
    descriptionKey: "admin.permission.customersLookupViewDescription",
  },
  "communications:conversations-view": {
    moduleKey: "admin.permission.module.communications",
    categoryKey: "admin.permission.category.communications",
    displayNameKey: "admin.permission.communicationsConversationsView",
    descriptionKey: "admin.permission.communicationsConversationsViewDescription",
  },
  "communications:conversations-reply": {
    moduleKey: "admin.permission.module.communications",
    categoryKey: "admin.permission.category.communications",
    displayNameKey: "admin.permission.communicationsConversationsReply",
    descriptionKey: "admin.permission.communicationsConversationsReplyDescription",
  },
  "communications:conversations-manage": {
    moduleKey: "admin.permission.module.communications",
    categoryKey: "admin.permission.category.communications",
    displayNameKey: "admin.permission.communicationsConversationsManage",
    descriptionKey: "admin.permission.communicationsConversationsManageDescription",
  },
  "communications:channels-manage": {
    moduleKey: "admin.permission.module.communications",
    categoryKey: "admin.permission.category.communications",
    displayNameKey: "admin.permission.communicationsChannelsManage",
    descriptionKey: "admin.permission.communicationsChannelsManageDescription",
  },
  "communications:suppressions-manage": {
    moduleKey: "admin.permission.module.communications",
    categoryKey: "admin.permission.category.communications",
    displayNameKey: "admin.permission.communicationsSuppressionsManage",
    descriptionKey: "admin.permission.communicationsSuppressionsManageDescription",
  },
  "products:products-view": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.products",
    displayNameKey: "admin.permission.productsProductsView",
    descriptionKey: "admin.permission.productsProductsViewDescription",
  },
  "products:products-manage": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.products",
    displayNameKey: "admin.permission.productsProductsManage",
    descriptionKey: "admin.permission.productsProductsManageDescription",
  },
  "products:variants-view": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.variants",
    displayNameKey: "admin.permission.productsVariantsView",
    descriptionKey: "admin.permission.productsVariantsViewDescription",
  },
  "products:variants-manage": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.variants",
    displayNameKey: "admin.permission.productsVariantsManage",
    descriptionKey: "admin.permission.productsVariantsManageDescription",
  },
  "products:pricing-view": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.pricing",
    displayNameKey: "admin.permission.productsPricingView",
    descriptionKey: "admin.permission.productsPricingViewDescription",
  },
  "products:pricing-manage": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.pricing",
    displayNameKey: "admin.permission.productsPricingManage",
    descriptionKey: "admin.permission.productsPricingManageDescription",
  },
  "products:categories-view": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.categories",
    displayNameKey: "admin.permission.productsCategoriesView",
    descriptionKey: "admin.permission.productsCategoriesViewDescription",
  },
  "products:categories-manage": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.categories",
    displayNameKey: "admin.permission.productsCategoriesManage",
    descriptionKey: "admin.permission.productsCategoriesManageDescription",
  },
  "products:tax-categories-view": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.taxCategories",
    displayNameKey: "admin.permission.productsTaxCategoriesView",
    descriptionKey: "admin.permission.productsTaxCategoriesViewDescription",
  },
  "products:tax-categories-manage": {
    moduleKey: "admin.permission.module.products",
    categoryKey: "admin.permission.category.taxCategories",
    displayNameKey: "admin.permission.productsTaxCategoriesManage",
    descriptionKey: "admin.permission.productsTaxCategoriesManageDescription",
  },
  "energy:metering-points-view": {
    moduleKey: "admin.permission.module.energy",
    categoryKey: "admin.permission.category.energy",
    displayNameKey: "admin.permission.energyMeteringPointsView",
    descriptionKey: "admin.permission.energyMeteringPointsViewDescription",
  },
  "energy:metering-points-manage": {
    moduleKey: "admin.permission.module.energy",
    categoryKey: "admin.permission.category.energy",
    displayNameKey: "admin.permission.energyMeteringPointsManage",
    descriptionKey: "admin.permission.energyMeteringPointsManageDescription",
  },
  "energy:meters-view": {
    moduleKey: "admin.permission.module.energy",
    categoryKey: "admin.permission.category.energy",
    displayNameKey: "admin.permission.energyMetersView",
    descriptionKey: "admin.permission.energyMetersViewDescription",
  },
  "energy:meters-manage": {
    moduleKey: "admin.permission.module.energy",
    categoryKey: "admin.permission.category.energy",
    displayNameKey: "admin.permission.energyMetersManage",
    descriptionKey: "admin.permission.energyMetersManageDescription",
  },
  "energy:consumption-view": {
    moduleKey: "admin.permission.module.energy",
    categoryKey: "admin.permission.category.energy",
    displayNameKey: "admin.permission.energyConsumptionView",
    descriptionKey: "admin.permission.energyConsumptionViewDescription",
  },
  "energy:consumption-manage": {
    moduleKey: "admin.permission.module.energy",
    categoryKey: "admin.permission.category.energy",
    displayNameKey: "admin.permission.energyConsumptionManage",
    descriptionKey: "admin.permission.energyConsumptionManageDescription",
  },
  "energy:supply-periods-view": {
    moduleKey: "admin.permission.module.energy",
    categoryKey: "admin.permission.category.energy",
    displayNameKey: "admin.permission.energySupplyPeriodsView",
    descriptionKey: "admin.permission.energySupplyPeriodsViewDescription",
  },
  "energy:supply-periods-manage": {
    moduleKey: "admin.permission.module.energy",
    categoryKey: "admin.permission.category.energy",
    displayNameKey: "admin.permission.energySupplyPeriodsManage",
    descriptionKey: "admin.permission.energySupplyPeriodsManageDescription",
  },
  "projects:access": {
    moduleKey: "admin.permission.module.projects",
    categoryKey: "admin.permission.category.projects",
    displayNameKey: "admin.permission.projectsAccess",
    descriptionKey: "admin.permission.projectsAccessDescription",
  },
  "projects:create": {
    moduleKey: "admin.permission.module.projects",
    categoryKey: "admin.permission.category.projects",
    displayNameKey: "admin.permission.projectsCreate",
    descriptionKey: "admin.permission.projectsCreateDescription",
  },
  "projects:view-all": {
    moduleKey: "admin.permission.module.projects",
    categoryKey: "admin.permission.category.projects",
    displayNameKey: "admin.permission.projectsViewAll",
    descriptionKey: "admin.permission.projectsViewAllDescription",
  },
  "projects:manage-all": {
    moduleKey: "admin.permission.module.projects",
    categoryKey: "admin.permission.category.projects",
    displayNameKey: "admin.permission.projectsManageAll",
    descriptionKey: "admin.permission.projectsManageAllDescription",
  },
  "projects:view-financials": {
    moduleKey: "admin.permission.module.projects",
    categoryKey: "admin.permission.category.projects",
    displayNameKey: "admin.permission.projectsViewFinancials",
    descriptionKey: "admin.permission.projectsViewFinancialsDescription",
  },
} as const;

export const getHostPermissionTranslation = (permissionKey: string) =>
  hostPermissionTranslationKeys[permissionKey as keyof typeof hostPermissionTranslationKeys];

export const translateHostPermissionKey = (
  permissionKey: string,
  t: HostTranslationFunction,
  fallback = permissionKey,
): string => {
  const translation = getHostPermissionTranslation(permissionKey);
  return translation ? t(translation.displayNameKey) : fallback;
};

export const translateHostPermissionModule = (
  permissionKey: string,
  module: string,
  t: HostTranslationFunction,
): string => {
  const translation = getHostPermissionTranslation(permissionKey);
  return translation ? t(translation.moduleKey) : module;
};

export const translateHostPermissionCategory = (
  permissionKey: string,
  category: string,
  t: HostTranslationFunction,
): string => {
  const translation = getHostPermissionTranslation(permissionKey);
  return translation ? t(translation.categoryKey) : category;
};

export const translateHostPermissionDescription = (
  permissionKey: string,
  description: string,
  t: HostTranslationFunction,
): string => {
  const translation = getHostPermissionTranslation(permissionKey);
  return translation ? t(translation.descriptionKey) : description;
};

const en = {
  "admin.dashboard": "Admin dashboard",
  "admin.overview": "A read-only overview of accounts and identity integrations.",
  "admin.statusLoadFailed": "Status could not be loaded",
  "admin.noConfiguration": "No configuration details are shown here.",
  "admin.people": "People",
  "admin.peopleDescription": "Manage team accounts, access, and sign-in security.",
  "admin.total": "Total",
  "admin.active": "Active",
  "admin.pendingInvitations": "Pending invitations",
  "admin.viewUsers": "View users",
  "admin.invitations": "Invitations",
  "admin.invitationsDescription": "Keep new team members moving through onboarding.",
  "admin.manageInvitations": "Manage invitations",
  "admin.accessControl": "Access control",
  "admin.accessControlDescription": "Review roles, assignments, and delegated administration.",
  "admin.manageRoles": "Manage roles & access",
  "admin.identityIntegrations": "Identity integrations",
  "admin.sso": "SSO",
  "admin.clientAuthentication": "Client authentication",
  "admin.managedByDeployment": "Managed by deployment",
  "admin.lastSsoUse": "Last successful SSO use",
  "admin.noSuccessfulSignIns": "No successful sign-ins yet",
  "admin.scim": "SCIM provisioning",
  "admin.status": "Status",
  "admin.lastAuthenticatedRequest": "Last authenticated request",
  "admin.noAuthenticatedRequests": "No authenticated requests yet",
  "admin.operationalActivity": "Operational activity",
  "admin.activityDescription":
    "This overview reports only non-sensitive identity activity. Credentials, authorities, and provider configuration details are intentionally not displayed.",
  "admin.users": "Users",
  "admin.usersDescription": "Manage access, roles, and sign-in security for your team.",
  "admin.addUser": "Add user",
  "admin.ssoShort": "SSO",
  "admin.admins": "Admins",
  "admin.userRole": "User",
  "admin.ownerRole": "Owner",
  "admin.userRoleDescription": "Standard user role with no permissions by default.",
  "admin.ownerRoleDescription": "Full installation access.",
  "admin.permission.module.identity": "Identity",
  "admin.permission.module.customers": "Customers",
  "admin.permission.module.communications": "Communications",
  "admin.permission.module.products": "Products",
  "admin.permission.module.energy": "Energy",
  "admin.permission.module.projects": "Projects",
  "admin.permission.category.administration": "Administration",
  "admin.permission.category.customers": "Customers",
  "admin.permission.category.legalIdentity": "Legal identity",
  "admin.permission.category.contacts": "Contacts",
  "admin.permission.category.associations": "Associations",
  "admin.permission.category.timeline": "Timeline",
  "admin.permission.category.lookup": "Lookup",
  "admin.permission.category.communications": "Communications",
  "admin.permission.category.products": "Products",
  "admin.permission.category.variants": "Variants",
  "admin.permission.category.pricing": "Pricing",
  "admin.permission.category.categories": "Categories",
  "admin.permission.category.taxCategories": "Tax categories",
  "admin.permission.category.energy": "Energy",
  "admin.permission.category.projects": "Projects",
  "admin.permission.identityManage": "Manage identity",
  "admin.permission.identityManageDescription": "Manage accounts, roles, and access.",
  "admin.permission.customersView": "View customers",
  "admin.permission.customersViewDescription": "View customer names, identifiers, and a sanitized activity summary.",
  "admin.permission.customersCreate": "Create customers",
  "admin.permission.customersCreateDescription": "Create customers without legal identity data.",
  "admin.permission.customersUpdate": "Update customers",
  "admin.permission.customersUpdateDescription": "Update customer names and basic non-sensitive details.",
  "admin.permission.customersDelete": "Delete customers",
  "admin.permission.customersDeleteDescription": "Delete customers and their customer-owned records.",
  "admin.permission.customersLegalIdentityView": "View legal identities",
  "admin.permission.customersLegalIdentityViewDescription": "View customer legal identity and registry attribution.",
  "admin.permission.customersLegalIdentityManage": "Manage legal identities",
  "admin.permission.customersLegalIdentityManageDescription": "Add, replace, or remove customer legal identity data.",
  "admin.permission.customersContactsView": "View contacts",
  "admin.permission.customersContactsViewDescription": "View contact names and contact details.",
  "admin.permission.customersContactsManage": "Manage contacts",
  "admin.permission.customersContactsManageDescription": "Create, update, and delete contacts.",
  "admin.permission.customersAssociationsView": "View customer associations",
  "admin.permission.customersAssociationsViewDescription": "View links between customers and contacts.",
  "admin.permission.customersAssociationsManage": "Manage customer associations",
  "admin.permission.customersAssociationsManageDescription": "Create, update, and remove customer-contact links.",
  "admin.permission.customersTimelineView": "View customer timeline",
  "admin.permission.customersTimelineViewDescription":
    "View customer timeline entries, notes, provenance, and revisions.",
  "admin.permission.customersTimelineManage": "Manage customer timeline",
  "admin.permission.customersTimelineManageDescription": "Create, update, and delete customer timeline entries.",
  "admin.permission.customersLookupView": "Use registry lookup",
  "admin.permission.customersLookupViewDescription": "Search the external business registry for legal identities.",
  "admin.permission.communicationsConversationsView": "View communications conversations",
  "admin.permission.communicationsConversationsViewDescription":
    "View conversations, messages, participants, bodies, attachments, and tags.",
  "admin.permission.communicationsConversationsReply": "Reply to communications conversations",
  "admin.permission.communicationsConversationsReplyDescription":
    "Create outbound conversation messages and queue them for delivery.",
  "admin.permission.communicationsConversationsManage": "Manage communications conversations",
  "admin.permission.communicationsConversationsManageDescription":
    "Assign, close, tag, and add internal notes to conversations.",
  "admin.permission.communicationsChannelsManage": "Manage communications channels",
  "admin.permission.communicationsChannelsManageDescription":
    "Create, update, and verify configured communication channels.",
  "admin.permission.communicationsSuppressionsManage": "Manage communications suppressions",
  "admin.permission.communicationsSuppressionsManageDescription":
    "View, create, and remove suppressed email addresses.",
  "admin.permission.productsProductsView": "View products",
  "admin.permission.productsProductsViewDescription": "View products and their details.",
  "admin.permission.productsProductsManage": "Manage products",
  "admin.permission.productsProductsManageDescription": "Create, update, and archive products.",
  "admin.permission.productsVariantsView": "View variants",
  "admin.permission.productsVariantsViewDescription": "View product variants.",
  "admin.permission.productsVariantsManage": "Manage variants",
  "admin.permission.productsVariantsManageDescription": "Create, update, and delete product variants.",
  "admin.permission.productsPricingView": "View pricing",
  "admin.permission.productsPricingViewDescription": "View product variant prices.",
  "admin.permission.productsPricingManage": "Manage pricing",
  "admin.permission.productsPricingManageDescription": "Create, update, and delete product variant prices.",
  "admin.permission.productsCategoriesView": "View categories",
  "admin.permission.productsCategoriesViewDescription": "View product categories.",
  "admin.permission.productsCategoriesManage": "Manage categories",
  "admin.permission.productsCategoriesManageDescription": "Create, update, and delete product categories.",
  "admin.permission.productsTaxCategoriesView": "View tax categories",
  "admin.permission.productsTaxCategoriesViewDescription": "View product tax categories.",
  "admin.permission.productsTaxCategoriesManage": "Manage tax categories",
  "admin.permission.productsTaxCategoriesManageDescription": "Create, update, and delete product tax categories.",
  "admin.permission.energyMeteringPointsView": "View energy metering points",
  "admin.permission.energyMeteringPointsViewDescription": "View energy metering point details and listings.",
  "admin.permission.energyMeteringPointsManage": "Manage energy metering points",
  "admin.permission.energyMeteringPointsManageDescription": "Create and update energy metering points.",
  "admin.permission.energyMetersView": "View energy meters",
  "admin.permission.energyMetersViewDescription": "View energy meter history for metering points.",
  "admin.permission.energyMetersManage": "Manage energy meters",
  "admin.permission.energyMetersManageDescription": "Replace meters installed at energy metering points.",
  "admin.permission.energyConsumptionView": "View energy consumption",
  "admin.permission.energyConsumptionViewDescription": "View energy consumption intervals and aggregates.",
  "admin.permission.energyConsumptionManage": "Manage energy consumption",
  "admin.permission.energyConsumptionManageDescription": "Add and replace manual energy consumption intervals.",
  "admin.permission.energySupplyPeriodsView": "View energy supply periods",
  "admin.permission.energySupplyPeriodsViewDescription": "View energy supply periods for metering points.",
  "admin.permission.energySupplyPeriodsManage": "Manage energy supply periods",
  "admin.permission.energySupplyPeriodsManageDescription": "Create, switch, end, and cancel energy supply periods.",
  "admin.permission.projectsAccess": "Use Projects",
  "admin.permission.projectsAccessDescription": "Use the Projects app and see the projects you hold a role in.",
  "admin.permission.projectsCreate": "Create projects",
  "admin.permission.projectsCreateDescription": "Create projects for customers or internal work.",
  "admin.permission.projectsViewAll": "View all projects",
  "admin.permission.projectsViewAllDescription": "See every project, not only the ones you hold a role in.",
  "admin.permission.projectsManageAll": "Manage all projects",
  "admin.permission.projectsManageAllDescription":
    "Manage every project, which also means seeing it and its financial fields.",
  "admin.permission.projectsViewFinancials": "View project financials",
  "admin.permission.projectsViewFinancialsDescription":
    "See fixed prices, budget amounts and line pricing on every project you can see.",
  "admin.accountExists": "An account already exists for this email address.",
  "admin.filterUsers": "Filter users by {{label}}",
  "admin.searchUsers": "Search users",
  "admin.searchNameEmail": "Search by name or email",
  "admin.usersLoadFailed": "Users could not be loaded",
  "admin.noUsersSearch": "No users match your search.",
  "admin.noFilteredUsers": "No {{filter}} users found.",
  "admin.noUsers": "No users yet.",
  "admin.avatar": "Avatar",
  "admin.access": "Access",
  "admin.twoFactor": "2FA",
  "admin.actions": "Actions",
  "admin.administratorDisabled": "Administrator-disabled",
  "admin.lockedOut": "Temporarily locked out",
  "admin.accountSelf": "This is your account. Manage it in",
  "admin.accountSettings": "Account settings",
  "admin.actionsFor": "Actions for {{user}}",
  "admin.editDetails": "Edit details",
  "admin.sendResetEmail": "Send reset email",
  "admin.setInitialPassword": "Set initial password",
  "admin.enableAccess": "Enable access",
  "admin.disableAccess": "Disable access",
  "admin.deleteUser": "Delete user",
  "admin.unnamedUser": "Unnamed user",
  "admin.noEmail": "No email address",
  "admin.editUser": "Edit user",
  "admin.addAUser": "Add a user",
  "admin.updateAccount": "Update this account’s details and role.",
  "admin.chooseStart": "Choose how this person should get started.",
  "admin.sendInvitation": "Send invitation",
  "admin.initialPasswordMode": "Set initial password",
  "admin.initialPasswordChosen": "The initial password is chosen by the administrator.",
  "admin.initialPassword": "Initial password",
  "admin.saveInitialPassword": "Save initial password",
  "admin.passwordHelp":
    "12+ characters with upper and lower case letters and a digit. The server remains the authority.",
  "admin.chooseInitialPassword": "Choose the initial password as an administrator. {{help}}",
  "admin.saveChange": "The change was saved successfully.",
  "admin.userUpdated": "User updated",
  "admin.invitationSent": "Invitation sent",
  "admin.userCreated": "User created",
  "admin.userSaveFailed": "User could not be saved",
  "admin.accessUpdated": "Access updated",
  "admin.userDeleted": "User deleted",
  "admin.accessChangeFailed": "Access change failed",
  "admin.resetSent": "Reset email sent",
  "admin.resetInstructions": "The user will receive instructions shortly.",
  "admin.resetFailed": "Reset email could not be sent",
  "admin.initialPasswordSaved": "Initial password saved",
  "admin.initialPasswordActive": "The administrator-chosen password is active now.",
  "admin.initialPasswordSaveFailed": "Initial password could not be saved",
  "admin.deleteUserQuestion": "Delete this user?",
  "admin.disableQuestion": "Disable access?",
  "admin.enableQuestion": "Enable access?",
  "admin.deleteWarning": "This permanently removes the account and cannot be undone.",
  "admin.willNoLongerSignIn": "{{user}} will no longer be able to sign in.",
  "admin.willSignInAgain": "{{user}} will be able to sign in again.",
  "admin.confirmAction": "{{action}}",
  "admin.passwordValidation": "Use 12+ characters with upper and lower case letters and a digit",
  "admin.invitationsDescriptionShort": "Track team invitations and keep access moving.",
  "admin.inviteSomeone": "Invite someone",
  "admin.searchInvitations": "Search invitations",
  "admin.invitationLoadFailed": "Invitations could not be loaded",
  "admin.noInvitationFilters": "No invitations match your filters.",
  "admin.recipient": "Recipient",
  "admin.createdExpires": "Created / expires",
  "admin.actionsForInvitation": "Actions for {{email}}",
  "admin.resend": "Resend",
  "admin.revoke": "Revoke",
  "admin.revokeInvitationQuestion": "Revoke invitation?",
  "admin.invitationWillNotWork": "{{email}} will no longer be able to use this invitation.",
  "admin.invitationRevoked": "Invitation revoked",
  "admin.invitationResent": "Invitation resent",
  "admin.invitationListUpdated": "The invitation list is up to date.",
  "admin.invitationRevokeFailed": "Invitation could not be revoked",
  "admin.invitationResendFailed": "Invitation could not be resent",
  "admin.rolesAccess": "Roles & access",
  "admin.rolesDescription": "Build additive permission sets and assign them safely to your team.",
  "admin.createCustomRole": "Create custom role",
  "admin.rolesAdministration": "Roles and access administration",
  "admin.roles": "Roles",
  "admin.assignments": "Assignments",
  "admin.delegations": "Delegations",
  "admin.rolePermissions": "Role permissions",
  "admin.rolePermissionsDescription":
    "Define reusable permission sets. Assigning a role to a person happens in Assignments.",
  "admin.managedCustom": "managed custom",
  "admin.protected": "Protected",
  "admin.edit": "Edit",
  "admin.deleteCustomRoleQuestion": "Delete custom role?",
  "admin.roleAssignmentsMayChange": "Assignments using this role may change.",
  "admin.deleteRole": "Delete role",
  "admin.outsideDelegation": "Outside current delegation boundary",
  "admin.userAssignments": "User assignments",
  "admin.userAssignmentsDescription":
    "Add or remove custom roles for a user. Roles outside your delegated scope are kept, and backend authority remains final.",
  "admin.assignmentScope": "Assignment scope",
  "admin.chooseOneScope": "Choose one scope",
  "admin.delegation": "Delegation {{id}}",
  "admin.selectUser": "Select a user",
  "admin.currentRoles": "Current roles",
  "admin.effectivePermissions": "Effective permissions:",
  "admin.allPermissions": "All permissions",
  "admin.none": "None",
  "admin.assignableRoles": "Assignable custom roles",
  "admin.reviewAccess": "Select a user to review effective access.",
  "admin.delegatedAdministration": "Delegated administration",
  "admin.delegatedDescription": "Grant scope-aware role administration without granting business data access.",
  "admin.delegateAdministration": "Delegate administration",
  "admin.ownerManagesDelegations":
    "Delegations are managed by the account owner. Your current access is limited to the scopes delegated to you.",
  "admin.activeBoundaries":
    "Active administrators and their boundaries appear here. Revoke access when the administration window ends.",
  "admin.revokeDelegationQuestion": "Revoke delegation?",
  "admin.removeDelegationBoundary": "This removes the delegated administration boundary.",
  "admin.editCustomRole": "Edit custom role",
  "admin.delegationScope": "Delegation scope",
  "admin.chooseScope": "Choose a scope",
  "admin.chooseScopePermissions": "Choose a qualifying delegation scope before selecting permissions.",
  "admin.internalName": "Internal name",
  "admin.description": "Description",
  "admin.sensitive": "Sensitive",
  "admin.saveRole": "Save role",
  "admin.delegateRoleAdministration": "Delegate role administration",
  "admin.delegateDescription":
    "This grants administration only, not business data access. You cannot delegate to yourself.",
  "admin.administrator": "Administrator",
  "admin.delegablePermissions": "Delegable permissions",
  "admin.stewardedRoles": "Stewarded custom roles",
  "admin.expiryOptional": "Expiry (optional)",
  "admin.expiryPlaceholder": "2027-01-31T00:00:00Z",
  "admin.mayCreateRoles": "May create custom roles",
  "admin.grantDelegation": "Grant delegation",
  "admin.roleUpdated": "Role updated",
  "admin.roleCreated": "Role created",
  "admin.roleSaved": "The role was saved successfully.",
  "admin.roleSaveFailed": "Role could not be saved",
  "admin.roleDeleteFailed": "Role could not be deleted",
  "admin.rolesAssigned": "Roles assigned",
  "admin.rolesOutsideScope": "Roles outside your delegated scope are kept.",
  "admin.rolesAssignFailed": "Roles could not be assigned",
  "admin.delegationGranted": "Delegation granted",
  "admin.delegationGrantMessage": "This grants administration only, not data access.",
  "admin.delegationGrantFailed": "Delegation could not be granted",
  "admin.delegationRevokeFailed": "Delegation could not be revoked",
  "admin.authUnavailable": "Authorization administration unavailable",
  "admin.accessUnavailable": "Access not available",
  "admin.cannotManageRoles": "Your account cannot manage roles and access.",
  "admin.nameValidation": "Use lowercase letters, numbers, and hyphens",
  "admin.displayNameValidation": "Enter a display name",
  "admin.descriptionValidation": "Enter a description",
  "admin.permissionValidation": "Select at least one permission",
  "admin.selectUserBeforeAccess": "Select a user before loading access.",
};

const nb: { [Key in keyof typeof en]: string } = {
  "admin.dashboard": "Administrasjonspanel",
  "admin.overview": "En skrivebeskyttet oversikt over kontoer og identitetsintegrasjoner.",
  "admin.statusLoadFailed": "Kunne ikke laste status",
  "admin.noConfiguration": "Ingen konfigurasjonsdetaljer vises her.",
  "admin.people": "Personer",
  "admin.peopleDescription": "Administrer teamkontoer, tilgang og innloggingssikkerhet.",
  "admin.total": "Totalt",
  "admin.active": "Aktive",
  "admin.pendingInvitations": "Ventende invitasjoner",
  "admin.viewUsers": "Vis brukere",
  "admin.invitations": "Invitasjoner",
  "admin.invitationsDescription": "Hjelp nye teammedlemmer gjennom oppstarten.",
  "admin.manageInvitations": "Administrer invitasjoner",
  "admin.accessControl": "Tilgangskontroll",
  "admin.accessControlDescription": "Se gjennom roller, tildelinger og delegert administrasjon.",
  "admin.manageRoles": "Administrer roller og tilgang",
  "admin.identityIntegrations": "Identitetsintegrasjoner",
  "admin.sso": "SSO",
  "admin.clientAuthentication": "Klientautentisering",
  "admin.managedByDeployment": "Administrert av distribusjonen",
  "admin.lastSsoUse": "Siste vellykkede SSO-bruk",
  "admin.noSuccessfulSignIns": "Ingen vellykkede innlogginger ennå",
  "admin.scim": "SCIM-klargjøring",
  "admin.status": "Status",
  "admin.lastAuthenticatedRequest": "Siste autentiserte forespørsel",
  "admin.noAuthenticatedRequests": "Ingen autentiserte forespørsler ennå",
  "admin.operationalActivity": "Operativ aktivitet",
  "admin.activityDescription":
    "Denne oversikten viser bare ikke-sensitiv identitetsaktivitet. Legitimasjon, autoriteter og leverandørkonfigurasjon vises med hensikt ikke.",
  "admin.users": "Brukere",
  "admin.usersDescription": "Administrer tilgang, roller og innloggingssikkerhet for teamet.",
  "admin.addUser": "Legg til bruker",
  "admin.ssoShort": "SSO",
  "admin.admins": "Administratorer",
  "admin.userRole": "Bruker",
  "admin.ownerRole": "Eier",
  "admin.userRoleDescription": "Standard brukerrolle uten tillatelser som standard.",
  "admin.ownerRoleDescription": "Full tilgang til installasjonen.",
  "admin.permission.module.identity": "Identitet",
  "admin.permission.module.customers": "Kunder",
  "admin.permission.module.communications": "Kommunikasjon",
  "admin.permission.module.products": "Produkter",
  "admin.permission.module.energy": "Energi",
  "admin.permission.module.projects": "Prosjekter",
  "admin.permission.category.administration": "Administrasjon",
  "admin.permission.category.customers": "Kunder",
  "admin.permission.category.legalIdentity": "Juridisk identitet",
  "admin.permission.category.contacts": "Kontakter",
  "admin.permission.category.associations": "Tilknytninger",
  "admin.permission.category.timeline": "Tidslinje",
  "admin.permission.category.lookup": "Oppslag",
  "admin.permission.category.communications": "Kommunikasjon",
  "admin.permission.category.products": "Produkter",
  "admin.permission.category.variants": "Varianter",
  "admin.permission.category.pricing": "Priser",
  "admin.permission.category.categories": "Kategorier",
  "admin.permission.category.taxCategories": "Avgiftskategorier",
  "admin.permission.category.energy": "Energi",
  "admin.permission.category.projects": "Prosjekter",
  "admin.permission.identityManage": "Administrer identitet",
  "admin.permission.identityManageDescription": "Administrer kontoer, roller og tilgang.",
  "admin.permission.customersView": "Se kunder",
  "admin.permission.customersViewDescription": "Se kundenavn, identifikatorer og et renset aktivitetssammendrag.",
  "admin.permission.customersCreate": "Opprett kunder",
  "admin.permission.customersCreateDescription": "Opprett kunder uten juridiske identitetsdata.",
  "admin.permission.customersUpdate": "Oppdater kunder",
  "admin.permission.customersUpdateDescription": "Oppdater kundenavn og grunnleggende ikke-sensitive detaljer.",
  "admin.permission.customersDelete": "Slett kunder",
  "admin.permission.customersDeleteDescription": "Slett kunder og kundeeide oppføringer.",
  "admin.permission.customersLegalIdentityView": "Se juridiske identiteter",
  "admin.permission.customersLegalIdentityViewDescription": "Se kundens juridiske identitet og registertilordning.",
  "admin.permission.customersLegalIdentityManage": "Administrer juridiske identiteter",
  "admin.permission.customersLegalIdentityManageDescription":
    "Legg til, erstatt eller fjern kundens juridiske identitetsdata.",
  "admin.permission.customersContactsView": "Se kontakter",
  "admin.permission.customersContactsViewDescription": "Se kontaktnavn og kontaktdetaljer.",
  "admin.permission.customersContactsManage": "Administrer kontakter",
  "admin.permission.customersContactsManageDescription": "Opprett, oppdater og slett kontakter.",
  "admin.permission.customersAssociationsView": "Se kundetilknytninger",
  "admin.permission.customersAssociationsViewDescription": "Se koblinger mellom kunder og kontakter.",
  "admin.permission.customersAssociationsManage": "Administrer kundetilknytninger",
  "admin.permission.customersAssociationsManageDescription":
    "Opprett, oppdater og fjern koblinger mellom kunder og kontakter.",
  "admin.permission.customersTimelineView": "Se kundens tidslinje",
  "admin.permission.customersTimelineViewDescription":
    "Se tidslinjeoppføringer, notater, opphav og revisjoner for kunden.",
  "admin.permission.customersTimelineManage": "Administrer kundens tidslinje",
  "admin.permission.customersTimelineManageDescription": "Opprett, oppdater og slett tidslinjeoppføringer for kunden.",
  "admin.permission.customersLookupView": "Bruk registeroppslag",
  "admin.permission.customersLookupViewDescription":
    "Søk i det eksterne foretaksregisteret etter juridiske identiteter.",
  "admin.permission.communicationsConversationsView": "Se kommunikasjonssamtaler",
  "admin.permission.communicationsConversationsViewDescription":
    "Se samtaler, meldinger, deltakere, brødtekst, vedlegg og etiketter.",
  "admin.permission.communicationsConversationsReply": "Svar på kommunikasjonssamtaler",
  "admin.permission.communicationsConversationsReplyDescription":
    "Opprett utgående samtalemeldinger og legg dem i kø for levering.",
  "admin.permission.communicationsConversationsManage": "Administrer kommunikasjonssamtaler",
  "admin.permission.communicationsConversationsManageDescription":
    "Tildel, lukk, sett etiketter og legg til interne notater i samtaler.",
  "admin.permission.communicationsChannelsManage": "Administrer kommunikasjonskanaler",
  "admin.permission.communicationsChannelsManageDescription":
    "Opprett, oppdater og bekreft konfigurerte kommunikasjonskanaler.",
  "admin.permission.communicationsSuppressionsManage": "Administrer e-postblokkeringer",
  "admin.permission.communicationsSuppressionsManageDescription": "Se, opprett og fjern blokkerte e-postadresser.",
  "admin.permission.productsProductsView": "Se produkter",
  "admin.permission.productsProductsViewDescription": "Se produkter og detaljene deres.",
  "admin.permission.productsProductsManage": "Administrer produkter",
  "admin.permission.productsProductsManageDescription": "Opprett, oppdater og arkiver produkter.",
  "admin.permission.productsVariantsView": "Se varianter",
  "admin.permission.productsVariantsViewDescription": "Se produktvarianter.",
  "admin.permission.productsVariantsManage": "Administrer varianter",
  "admin.permission.productsVariantsManageDescription": "Opprett, oppdater og slett produktvarianter.",
  "admin.permission.productsPricingView": "Se priser",
  "admin.permission.productsPricingViewDescription": "Se priser for produktvarianter.",
  "admin.permission.productsPricingManage": "Administrer priser",
  "admin.permission.productsPricingManageDescription": "Opprett, oppdater og slett priser for produktvarianter.",
  "admin.permission.productsCategoriesView": "Se kategorier",
  "admin.permission.productsCategoriesViewDescription": "Se produktkategorier.",
  "admin.permission.productsCategoriesManage": "Administrer kategorier",
  "admin.permission.productsCategoriesManageDescription": "Opprett, oppdater og slett produktkategorier.",
  "admin.permission.productsTaxCategoriesView": "Se avgiftskategorier",
  "admin.permission.productsTaxCategoriesViewDescription": "Se avgiftskategorier for produkter.",
  "admin.permission.productsTaxCategoriesManage": "Administrer avgiftskategorier",
  "admin.permission.productsTaxCategoriesManageDescription":
    "Opprett, oppdater og slett avgiftskategorier for produkter.",
  "admin.permission.energyMeteringPointsView": "Se energimålepunkter",
  "admin.permission.energyMeteringPointsViewDescription": "Se detaljer og lister over energimålepunkter.",
  "admin.permission.energyMeteringPointsManage": "Administrer energimålepunkter",
  "admin.permission.energyMeteringPointsManageDescription": "Opprett og oppdater energimålepunkter.",
  "admin.permission.energyMetersView": "Se energimålere",
  "admin.permission.energyMetersViewDescription": "Se historikk for energimålere ved målepunkter.",
  "admin.permission.energyMetersManage": "Administrer energimålere",
  "admin.permission.energyMetersManageDescription": "Bytt ut målere installert ved energimålepunkter.",
  "admin.permission.energyConsumptionView": "Se energiforbruk",
  "admin.permission.energyConsumptionViewDescription": "Se intervaller og aggregater for energiforbruk.",
  "admin.permission.energyConsumptionManage": "Administrer energiforbruk",
  "admin.permission.energyConsumptionManageDescription": "Legg til og erstatt manuelle energiforbruksintervaller.",
  "admin.permission.energySupplyPeriodsView": "Se energileveranseperioder",
  "admin.permission.energySupplyPeriodsViewDescription": "Se energileveranseperioder for målepunkter.",
  "admin.permission.energySupplyPeriodsManage": "Administrer energileveranseperioder",
  "admin.permission.energySupplyPeriodsManageDescription": "Opprett, bytt, avslutt og avbryt energileveranseperioder.",
  "admin.permission.projectsAccess": "Bruk Prosjekter",
  "admin.permission.projectsAccessDescription": "Bruk Prosjekter-appen og se prosjektene du har en rolle i.",
  "admin.permission.projectsCreate": "Opprett prosjekter",
  "admin.permission.projectsCreateDescription": "Opprett prosjekter for kunder eller internt arbeid.",
  "admin.permission.projectsViewAll": "Se alle prosjekter",
  "admin.permission.projectsViewAllDescription": "Se alle prosjekter, ikke bare dem du har en rolle i.",
  "admin.permission.projectsManageAll": "Administrer alle prosjekter",
  "admin.permission.projectsManageAllDescription":
    "Administrer alle prosjekter, som også betyr å se dem og de økonomiske feltene deres.",
  "admin.permission.projectsViewFinancials": "Se prosjektøkonomi",
  "admin.permission.projectsViewFinancialsDescription":
    "Se fastpriser, budsjettbeløp og linjepriser på alle prosjekter du kan se.",
  "admin.accountExists": "Det finnes allerede en konto for denne e-postadressen.",
  "admin.filterUsers": "Filtrer brukere etter {{label}}",
  "admin.searchUsers": "Søk etter brukere",
  "admin.searchNameEmail": "Søk etter navn eller e-post",
  "admin.usersLoadFailed": "Kunne ikke laste brukere",
  "admin.noUsersSearch": "Ingen brukere samsvarer med søket.",
  "admin.noFilteredUsers": "Fant ingen {{filter}} brukere.",
  "admin.noUsers": "Ingen brukere ennå.",
  "admin.avatar": "Profilbilde",
  "admin.access": "Tilgang",
  "admin.twoFactor": "2FA",
  "admin.actions": "Handlinger",
  "admin.administratorDisabled": "Deaktivert av administrator",
  "admin.lockedOut": "Midlertidig utestengt",
  "admin.accountSelf": "Dette er kontoen din. Administrer den i",
  "admin.accountSettings": "Kontoinnstillinger",
  "admin.actionsFor": "Handlinger for {{user}}",
  "admin.editDetails": "Rediger detaljer",
  "admin.sendResetEmail": "Send e-post for tilbakestilling",
  "admin.setInitialPassword": "Angi startpassord",
  "admin.enableAccess": "Aktiver tilgang",
  "admin.disableAccess": "Deaktiver tilgang",
  "admin.deleteUser": "Slett bruker",
  "admin.unnamedUser": "Navnløs bruker",
  "admin.noEmail": "Ingen e-postadresse",
  "admin.editUser": "Rediger bruker",
  "admin.addAUser": "Legg til en bruker",
  "admin.updateAccount": "Oppdater kontoens detaljer og rolle.",
  "admin.chooseStart": "Velg hvordan denne personen skal komme i gang.",
  "admin.sendInvitation": "Send invitasjon",
  "admin.initialPasswordMode": "Angi startpassord",
  "admin.initialPasswordChosen": "Startpassordet velges av administratoren.",
  "admin.initialPassword": "Startpassord",
  "admin.saveInitialPassword": "Lagre startpassord",
  "admin.passwordHelp": "12+ tegn med store og små bokstaver samt et siffer. Serveren er den endelige autoriteten.",
  "admin.chooseInitialPassword": "Velg startpassordet som administrator. {{help}}",
  "admin.saveChange": "Endringen ble lagret.",
  "admin.userUpdated": "Bruker oppdatert",
  "admin.invitationSent": "Invitasjon sendt",
  "admin.userCreated": "Bruker opprettet",
  "admin.userSaveFailed": "Kunne ikke lagre brukeren",
  "admin.accessUpdated": "Tilgang oppdatert",
  "admin.userDeleted": "Bruker slettet",
  "admin.accessChangeFailed": "Tilgangsendringen mislyktes",
  "admin.resetSent": "E-post for tilbakestilling sendt",
  "admin.resetInstructions": "Brukeren mottar snart instruksjoner.",
  "admin.resetFailed": "Kunne ikke sende e-post for tilbakestilling",
  "admin.initialPasswordSaved": "Startpassord lagret",
  "admin.initialPasswordActive": "Administratorens valgte passord er aktivt nå.",
  "admin.initialPasswordSaveFailed": "Kunne ikke lagre startpassordet",
  "admin.deleteUserQuestion": "Slett denne brukeren?",
  "admin.disableQuestion": "Deaktivere tilgang?",
  "admin.enableQuestion": "Aktivere tilgang?",
  "admin.deleteWarning": "Dette fjerner kontoen permanent og kan ikke angres.",
  "admin.willNoLongerSignIn": "{{user}} vil ikke lenger kunne logge inn.",
  "admin.willSignInAgain": "{{user}} vil kunne logge inn igjen.",
  "admin.confirmAction": "{{action}}",
  "admin.passwordValidation": "Bruk 12+ tegn med store og små bokstaver samt et siffer",
  "admin.invitationsDescriptionShort": "Følg teaminvitasjoner og hold tilgangen i gang.",
  "admin.inviteSomeone": "Inviter noen",
  "admin.searchInvitations": "Søk etter invitasjoner",
  "admin.invitationLoadFailed": "Kunne ikke laste invitasjoner",
  "admin.noInvitationFilters": "Ingen invitasjoner samsvarer med filtrene.",
  "admin.recipient": "Mottaker",
  "admin.createdExpires": "Opprettet / utløper",
  "admin.actionsForInvitation": "Handlinger for {{email}}",
  "admin.resend": "Send på nytt",
  "admin.revoke": "Tilbakekall",
  "admin.revokeInvitationQuestion": "Tilbakekalle invitasjonen?",
  "admin.invitationWillNotWork": "{{email}} vil ikke lenger kunne bruke denne invitasjonen.",
  "admin.invitationRevoked": "Invitasjon tilbakekalt",
  "admin.invitationResent": "Invitasjon sendt på nytt",
  "admin.invitationListUpdated": "Invitasjonslisten er oppdatert.",
  "admin.invitationRevokeFailed": "Kunne ikke tilbakekalle invitasjonen",
  "admin.invitationResendFailed": "Kunne ikke sende invitasjonen på nytt",
  "admin.rolesAccess": "Roller og tilgang",
  "admin.rolesDescription": "Bygg additive tillatelsessett og tildel dem trygt til teamet.",
  "admin.createCustomRole": "Opprett egendefinert rolle",
  "admin.rolesAdministration": "Administrasjon av roller og tilgang",
  "admin.roles": "Roller",
  "admin.assignments": "Tildelinger",
  "admin.delegations": "Delegeringer",
  "admin.rolePermissions": "Rolletillatelser",
  "admin.rolePermissionsDescription":
    "Definer gjenbrukbare tillatelsessett. Roller tildeles personer under Tildelinger.",
  "admin.managedCustom": "egendefinerte under administrasjon",
  "admin.protected": "Beskyttet",
  "admin.edit": "Rediger",
  "admin.deleteCustomRoleQuestion": "Slette egendefinert rolle?",
  "admin.roleAssignmentsMayChange": "Tildelinger som bruker denne rollen kan endres.",
  "admin.deleteRole": "Slett rolle",
  "admin.outsideDelegation": "Utenfor gjeldende delegeringsgrense",
  "admin.userAssignments": "Brukertildelinger",
  "admin.userAssignmentsDescription":
    "Legg til eller fjern egendefinerte roller for en bruker. Roller utenfor ditt delegerte område beholdes, og backend-autoriteten er endelig.",
  "admin.assignmentScope": "Tildelingsområde",
  "admin.chooseOneScope": "Velg ett område",
  "admin.delegation": "Delegering {{id}}",
  "admin.selectUser": "Velg en bruker",
  "admin.currentRoles": "Gjeldende roller",
  "admin.effectivePermissions": "Effektive tillatelser:",
  "admin.allPermissions": "Alle tillatelser",
  "admin.none": "Ingen",
  "admin.assignableRoles": "Tildelbare egendefinerte roller",
  "admin.reviewAccess": "Velg en bruker for å se effektiv tilgang.",
  "admin.delegatedAdministration": "Delegert administrasjon",
  "admin.delegatedDescription": "Gi områdebevisst rolleadministrasjon uten å gi tilgang til virksomhetsdata.",
  "admin.delegateAdministration": "Deleger administrasjon",
  "admin.ownerManagesDelegations":
    "Delegeringer administreres av kontoeieren. Din nåværende tilgang er begrenset til områdene som er delegert til deg.",
  "admin.activeBoundaries":
    "Aktive administratorer og grensene deres vises her. Tilbakekall tilgang når administrasjonsperioden er over.",
  "admin.revokeDelegationQuestion": "Tilbakekalle delegering?",
  "admin.removeDelegationBoundary": "Dette fjerner grensen for delegert administrasjon.",
  "admin.editCustomRole": "Rediger egendefinert rolle",
  "admin.delegationScope": "Delegeringsområde",
  "admin.chooseScope": "Velg et område",
  "admin.chooseScopePermissions": "Velg et kvalifiserende delegeringsområde før du velger tillatelser.",
  "admin.internalName": "Internt navn",
  "admin.description": "Beskrivelse",
  "admin.sensitive": "Sensitiv",
  "admin.saveRole": "Lagre rolle",
  "admin.delegateRoleAdministration": "Deleger rolleadministrasjon",
  "admin.delegateDescription":
    "Dette gir bare administrasjon, ikke tilgang til virksomhetsdata. Du kan ikke delegere til deg selv.",
  "admin.administrator": "Administrator",
  "admin.delegablePermissions": "Delegerbare tillatelser",
  "admin.stewardedRoles": "Forvaltede egendefinerte roller",
  "admin.expiryOptional": "Utløp (valgfritt)",
  "admin.expiryPlaceholder": "2027-01-31T00:00:00Z",
  "admin.mayCreateRoles": "Kan opprette egendefinerte roller",
  "admin.grantDelegation": "Gi delegering",
  "admin.roleUpdated": "Rolle oppdatert",
  "admin.roleCreated": "Rolle opprettet",
  "admin.roleSaved": "Rollen ble lagret.",
  "admin.roleSaveFailed": "Kunne ikke lagre rollen",
  "admin.roleDeleteFailed": "Kunne ikke slette rollen",
  "admin.rolesAssigned": "Roller tildelt",
  "admin.rolesOutsideScope": "Roller utenfor ditt delegerte område beholdes.",
  "admin.rolesAssignFailed": "Kunne ikke tildele roller",
  "admin.delegationGranted": "Delegering gitt",
  "admin.delegationGrantMessage": "Dette gir bare administrasjon, ikke datatilgang.",
  "admin.delegationGrantFailed": "Kunne ikke gi delegering",
  "admin.delegationRevokeFailed": "Kunne ikke tilbakekalle delegeringen",
  "admin.authUnavailable": "Administrasjon av autorisasjon er ikke tilgjengelig",
  "admin.accessUnavailable": "Tilgang ikke tilgjengelig",
  "admin.cannotManageRoles": "Kontoen din kan ikke administrere roller og tilgang.",
  "admin.nameValidation": "Bruk små bokstaver, tall og bindestreker",
  "admin.displayNameValidation": "Skriv inn et visningsnavn",
  "admin.descriptionValidation": "Skriv inn en beskrivelse",
  "admin.permissionValidation": "Velg minst én tillatelse",
  "admin.selectUserBeforeAccess": "Velg en bruker før tilgang lastes.",
};

export const adminCatalog = { en, nb } as const satisfies CatalogResources;
