import type { CatalogResources } from "@vantigo/frontend-shell";

const en = {
  "auth.verifySignIn": "Verify your sign-in",
  "auth.welcomeBack": "Welcome back",
  "auth.authenticatorRecoveryCode": "Enter your authenticator or recovery code.",
  "auth.signInContinue": "Sign in to continue to {{app}}.",
  "auth.identityProviderError":
    "Your identity provider could not complete sign-in. Try again or use another sign-in method.",
  "auth.securityCode": "Security code",
  "auth.verify": "Verify",
  "auth.useAnotherMethod": "Use another sign-in method",
  "auth.signIn": "Sign in",
  "auth.signInWithPasskey": "Sign in with a passkey",
  "auth.passkeyUnsupported": "Passkeys are not supported on this device or browser.",
  "auth.passkeySignInCancelled": "Passkey sign-in was cancelled.",
  "auth.passkeySignInFailed": "Passkey sign-in could not be completed.",
  "auth.forgotPassword": "Forgot your password?",
  "auth.checkingMethods": "Checking available sign-in methods…",
  "auth.continueWith": "Continue with {{provider}}",
  "auth.oidcUnavailable": "OIDC sign-in is unavailable.",
  "auth.setupUnavailable": "Setup unavailable",
  "auth.setupUnavailableDescription": "This {{app}} installation has already been set up.",
  "auth.goToSignIn": "Go to sign in",
  "auth.checkingSetup": "Checking setup availability…",
  "auth.setupTitle": "Set up {{app}}",
  "auth.setupDescription":
    "Create the first Owner account for this installation. It becomes the full administrator, with every permission and access to system administration.",
  "auth.createOwner": "Create Owner account",
  "auth.alreadyAccount": "Already have an account? Sign in",
  "auth.validEmail": "Enter a valid email address",
  "auth.enterName": "Enter your name",
  "auth.enterPassword": "Enter a password",
  "auth.setupFailed": "Setup could not be completed",
  "auth.resetTitle": "Reset your password",
  "auth.resetDescription": "Enter your email and, if an account matches, we’ll send a reset link.",
  "auth.checkInbox": "Check your inbox for next steps. This message is the same whether or not an account exists.",
  "auth.sendReset": "Send reset link",
  "auth.chooseNewPassword": "Choose a new password",
  "auth.newPassword": "New password",
  "auth.invalidReset": "This reset link is invalid or expired.",
  "auth.passwordReset": "Your password has been reset. You can sign in now.",
  "auth.resetPassword": "Reset password",
  "auth.joinApp": "Join {{app}}",
  "auth.invalidInvitation": "This invitation is invalid or expired.",
  "auth.invitationFor": "Invitation for {{email}}",
  "auth.createAccount": "Create account",
  "auth.invitationUnavailable": "This invitation is invalid or no longer available.",
};

const nb: { [Key in keyof typeof en]: string } = {
  "auth.verifySignIn": "Bekreft innloggingen",
  "auth.welcomeBack": "Velkommen tilbake",
  "auth.authenticatorRecoveryCode": "Skriv inn autentiserings- eller gjenopprettingskoden.",
  "auth.signInContinue": "Logg inn for å fortsette til {{app}}.",
  "auth.identityProviderError":
    "Identitetsleverandøren kunne ikke fullføre innloggingen. Prøv igjen eller bruk en annen innloggingsmetode.",
  "auth.securityCode": "Sikkerhetskode",
  "auth.verify": "Bekreft",
  "auth.useAnotherMethod": "Bruk en annen innloggingsmetode",
  "auth.signIn": "Logg inn",
  "auth.signInWithPasskey": "Logg inn med en passnøkkel",
  "auth.passkeyUnsupported": "Passnøkler støttes ikke på denne enheten eller i denne nettleseren.",
  "auth.passkeySignInCancelled": "Innlogging med passnøkkel ble avbrutt.",
  "auth.passkeySignInFailed": "Innlogging med passnøkkel kunne ikke fullføres.",
  "auth.forgotPassword": "Glemt passordet?",
  "auth.checkingMethods": "Sjekker tilgjengelige innloggingsmetoder…",
  "auth.continueWith": "Fortsett med {{provider}}",
  "auth.oidcUnavailable": "OIDC-innlogging er ikke tilgjengelig.",
  "auth.setupUnavailable": "Oppsett er ikke tilgjengelig",
  "auth.setupUnavailableDescription": "Denne {{app}}-installasjonen er allerede satt opp.",
  "auth.goToSignIn": "Gå til innlogging",
  "auth.checkingSetup": "Sjekker om oppsett er tilgjengelig…",
  "auth.setupTitle": "Sett opp {{app}}",
  "auth.setupDescription":
    "Opprett den første eierkontoen for denne installasjonen. Den blir full administrator, med alle rettigheter og tilgang til systemadministrasjon.",
  "auth.createOwner": "Opprett eierkonto",
  "auth.alreadyAccount": "Har du allerede en konto? Logg inn",
  "auth.validEmail": "Skriv inn en gyldig e-postadresse",
  "auth.enterName": "Skriv inn navnet ditt",
  "auth.enterPassword": "Skriv inn et passord",
  "auth.setupFailed": "Oppsettet kunne ikke fullføres",
  "auth.resetTitle": "Tilbakestill passordet",
  "auth.resetDescription":
    "Skriv inn e-postadressen din. Hvis en konto samsvarer, sender vi en lenke for tilbakestilling.",
  "auth.checkInbox": "Sjekk innboksen for neste steg. Denne meldingen er den samme enten en konto finnes eller ikke.",
  "auth.sendReset": "Send lenke for tilbakestilling",
  "auth.chooseNewPassword": "Velg et nytt passord",
  "auth.newPassword": "Nytt passord",
  "auth.invalidReset": "Denne lenken for tilbakestilling er ugyldig eller utløpt.",
  "auth.passwordReset": "Passordet er tilbakestilt. Du kan logge inn nå.",
  "auth.resetPassword": "Tilbakestill passord",
  "auth.joinApp": "Bli med i {{app}}",
  "auth.invalidInvitation": "Denne invitasjonen er ugyldig eller utløpt.",
  "auth.invitationFor": "Invitasjon for {{email}}",
  "auth.createAccount": "Opprett konto",
  "auth.invitationUnavailable": "Denne invitasjonen er ugyldig eller ikke lenger tilgjengelig.",
};

export const authCatalog = { en, nb } as const satisfies CatalogResources;
