import type { CatalogResources } from "@vantigo/frontend-shell";

const en = {
  "customer.overviewTab": "Overview",
  "customer.energyTab": "Energy",
  "customer.projectsTab": "Projects",
  "customer.openInInbox": "Open in inbox",
  "customer.views": "Customer views",
  "customer.overview360.title": "Customer 360",
  "customer.overview360.openProjects": "Open projects",
  "customer.overview360.openProjectsHint": "of {{count}} projects",
  "customer.overview360.openProjectsTruncatedHint": "of the first {{count}} projects",
  "customer.overview360.unbilledHours": "Unbilled hours",
  "customer.overview360.hoursValue": "{{hours}} h",
  "customer.overview360.expensesReady": "Expenses ready to invoice",
  "customer.overview360.lastActivity": "Last activity",
  "customer.overview360.lastActivityTimeline": "On the timeline",
  "customer.overview360.lastActivityWork": "Logged work",
  "customer.overview360.lastActivityExpense": "Expense",
  "customer.overview360.noActivity": "Nothing recorded yet",
  "customer.overview360.code": "Code",
  "customer.overview360.name": "Name",
  "customer.overview360.status": "Status",
  "customer.overview360.lastWork": "Last work",
  "customer.overview360.statusActive": "Active",
};

const nb: { [Key in keyof typeof en]: string } = {
  "customer.overviewTab": "Oversikt",
  "customer.energyTab": "Energi",
  "customer.projectsTab": "Prosjekter",
  "customer.openInInbox": "Åpne i innboksen",
  "customer.views": "Kundevisninger",
  "customer.overview360.title": "Kunde 360",
  "customer.overview360.openProjects": "Åpne prosjekter",
  "customer.overview360.openProjectsHint": "av {{count}} prosjekter",
  "customer.overview360.openProjectsTruncatedHint": "av de første {{count}} prosjektene",
  "customer.overview360.unbilledHours": "Ufakturerte timer",
  "customer.overview360.hoursValue": "{{hours}} t",
  "customer.overview360.expensesReady": "Utlegg klare til fakturering",
  "customer.overview360.lastActivity": "Siste aktivitet",
  "customer.overview360.lastActivityTimeline": "På tidslinjen",
  "customer.overview360.lastActivityWork": "Ført arbeid",
  "customer.overview360.lastActivityExpense": "Utlegg",
  "customer.overview360.noActivity": "Ingenting registrert ennå",
  "customer.overview360.code": "Kode",
  "customer.overview360.name": "Navn",
  "customer.overview360.status": "Status",
  "customer.overview360.lastWork": "Sist ført",
  "customer.overview360.statusActive": "Aktiv",
};

export const customerCatalog = { en, nb } as const satisfies CatalogResources;
