import type { CatalogResources } from "@vantigo/frontend-shell";

const en = {
  "dashboard.title": "Dashboard",
  "dashboard.customers": "Customers",
  "dashboard.communications": "Communications",
  "dashboard.products": "Products",
  "dashboard.chooseModule": "Choose a module to get started.",
  "dashboard.manageCustomers": "Manage customers and contacts.",
  "dashboard.reviewMessages": "Review and send messages.",
  "dashboard.manageProducts": "Manage products, prices and categories.",
  "dashboard.energy": "Energy",
  "dashboard.projects": "Projects",
  "dashboard.manageProjects": "Manage projects, people and billing.",
  "dashboard.time": "Time",
  "dashboard.manageTime": "Log hours, submit weeks and approve them.",
  "dashboard.manageEnergy": "Manage metering points and meters.",
  "dashboard.open": "Open",
  "dashboard.greeting": "Welcome back, {{name}}",
  "dashboard.7d": "7d",
  "dashboard.30d": "30d",
  "dashboard.90d": "90d",
  "dashboard.12m": "12m",
  "dashboard.custom": "Custom",
  "dashboard.dateRange": "Date range",
  "dashboard.selectDateRange": "Select date range",
  "dashboard.newCustomers": "New customers",
  "dashboard.customersKpiHint": "Added in this period",
  "dashboard.openConversations": "Open conversations",
  "dashboard.newConversations": "New conversations",
  "dashboard.newConversationsHint": "{{count}} new in this period",
  "dashboard.activeProducts": "Active products",
  "dashboard.newProducts": "New products",
  "dashboard.newProductsHint": "{{count}} new in this period",
  "dashboard.activeProjects": "Active projects",
  "dashboard.newProjects": "New projects",
  "dashboard.hoursThisWeek": "Hours this week",
  "dashboard.hoursLogged": "Hours logged",
  "dashboard.awaitingApprovalHint": "{{count}} waiting for your approval",
  "dashboard.timeWeekUnsubmitted": "Your week of {{date}} is not submitted",
  "dashboard.timeApprovalWaiting": "Hours from the week of {{date}} are waiting for your approval",
  "dashboard.readyMilestonesHint": "{{count}} milestones ready to invoice",
  "dashboard.projectBudgetWarning": "{{name}} has used most of its budget",
  "dashboard.projectBudgetExceeded": "{{name}} is over budget",
  "dashboard.projectMilestoneReady": "'{{name}}' is ready to invoice",
  "dashboard.projectMilestoneOverdue": "'{{name}}' is past its planned date",
  "dashboard.consumption": "Consumption",
  "dashboard.energyKpiHint": "Energy used in this period",
  "dashboard.vsPrevious": "vs previous period",
  "dashboard.trend": "Performance trend",
  "dashboard.selectMetric": "Select metric",
  "dashboard.noTrendData": "No trend data available",
  "dashboard.openModule": "Open module",
  "dashboard.needsAttention": "Needs attention",
  "dashboard.needsAttentionDescription": "Items that may need a follow-up",
  "dashboard.allClear": "All clear",
  "dashboard.conversationStatus": "Conversation status",
  "dashboard.productStatus": "Product status",
  "dashboard.activity": "Activity",
  "dashboard.activityDescription": "Recent activity from enabled modules",
  "dashboard.noActivity": "No recent activity",
  "dashboard.noWidgetData": "No data available",
  "dashboard.modules": "Modules",
  "dashboard.closed": "Closed",
  "dashboard.new": "New",
  "dashboard.setup": "Finish your setup",
  "dashboard.setupDescription": "A few quick steps will get your workspace ready.",
  "dashboard.setupComplete": "complete",
  "dashboard.addFirstCustomer": "Add your first customer",
  "dashboard.connectChannel": "Connect a mailbox or channel",
  "dashboard.createProduct": "Create a product",
  "dashboard.configureMetering": "Configure a metering point",
  "dashboard.createFirstProject": "Start your first project",
  "dashboard.quickActions": "Quick actions",
  "dashboard.createCustomer": "Create customer",
  "dashboard.composeMessage": "Compose message",
  "dashboard.addProduct": "Add product",
  "dashboard.createProject": "Create project",
  "dashboard.createTask": "Create task",
  "dashboard.logTime": "Log time",
};

const nb: { [Key in keyof typeof en]: string } = {
  "dashboard.title": "Kontrollpanel",
  "dashboard.customers": "Kunder",
  "dashboard.communications": "Kommunikasjon",
  "dashboard.products": "Produkter",
  "dashboard.chooseModule": "Velg en modul for å komme i gang.",
  "dashboard.manageCustomers": "Administrer kunder og kontakter.",
  "dashboard.reviewMessages": "Se gjennom og send meldinger.",
  "dashboard.manageProducts": "Administrer produkter, priser og kategorier.",
  "dashboard.energy": "Energi",
  "dashboard.projects": "Prosjekter",
  "dashboard.manageProjects": "Administrer prosjekter, personer og fakturering.",
  "dashboard.time": "Timer",
  "dashboard.manageTime": "Før timer, lever uker og godkjenn dem.",
  "dashboard.manageEnergy": "Administrer målepunkter og målere.",
  "dashboard.open": "Åpne",
  "dashboard.greeting": "Velkommen tilbake, {{name}}",
  "dashboard.7d": "7d",
  "dashboard.30d": "30d",
  "dashboard.90d": "90d",
  "dashboard.12m": "12m",
  "dashboard.custom": "Tilpasset",
  "dashboard.dateRange": "Datoperiode",
  "dashboard.selectDateRange": "Velg datoperiode",
  "dashboard.newCustomers": "Nye kunder",
  "dashboard.customersKpiHint": "Lagt til i denne perioden",
  "dashboard.openConversations": "Åpne samtaler",
  "dashboard.newConversations": "Nye samtaler",
  "dashboard.newConversationsHint": "{{count}} nye i denne perioden",
  "dashboard.activeProducts": "Aktive produkter",
  "dashboard.newProducts": "Nye produkter",
  "dashboard.newProductsHint": "{{count}} nye i denne perioden",
  "dashboard.activeProjects": "Aktive prosjekter",
  "dashboard.newProjects": "Nye prosjekter",
  "dashboard.hoursThisWeek": "Timer denne uken",
  "dashboard.hoursLogged": "Førte timer",
  "dashboard.awaitingApprovalHint": "{{count}} venter på din godkjenning",
  "dashboard.timeWeekUnsubmitted": "Uken din fra {{date}} er ikke levert",
  "dashboard.timeApprovalWaiting": "Timer fra uken som starter {{date}} venter på din godkjenning",
  "dashboard.readyMilestonesHint": "{{count}} milepæler klare til fakturering",
  "dashboard.projectBudgetWarning": "{{name}} har brukt opp mesteparten av budsjettet",
  "dashboard.projectBudgetExceeded": "{{name}} har gått over budsjett",
  "dashboard.projectMilestoneReady": "«{{name}}» er klar til fakturering",
  "dashboard.projectMilestoneOverdue": "«{{name}}» har passert planlagt dato",
  "dashboard.consumption": "Forbruk",
  "dashboard.energyKpiHint": "Energi brukt i denne perioden",
  "dashboard.vsPrevious": "mot forrige periode",
  "dashboard.trend": "Utvikling",
  "dashboard.selectMetric": "Velg måling",
  "dashboard.noTrendData": "Ingen utviklingsdata tilgjengelig",
  "dashboard.openModule": "Åpne modul",
  "dashboard.needsAttention": "Trenger oppfølging",
  "dashboard.needsAttentionDescription": "Elementer som kan trenge oppfølging",
  "dashboard.allClear": "Alt i orden",
  "dashboard.conversationStatus": "Samtalestatus",
  "dashboard.productStatus": "Produktstatus",
  "dashboard.activity": "Aktivitet",
  "dashboard.activityDescription": "Nylig aktivitet fra aktiverte moduler",
  "dashboard.noActivity": "Ingen nylig aktivitet",
  "dashboard.noWidgetData": "Ingen data tilgjengelig",
  "dashboard.modules": "Moduler",
  "dashboard.closed": "Lukket",
  "dashboard.new": "Ny",
  "dashboard.setup": "Fullfør oppsettet",
  "dashboard.setupDescription": "Noen få trinn gjør arbeidsområdet klart.",
  "dashboard.setupComplete": "fullført",
  "dashboard.addFirstCustomer": "Legg til din første kunde",
  "dashboard.connectChannel": "Koble til en postkasse eller kanal",
  "dashboard.createProduct": "Opprett et produkt",
  "dashboard.configureMetering": "Konfigurer et målepunkt",
  "dashboard.createFirstProject": "Start ditt første prosjekt",
  "dashboard.quickActions": "Hurtighandlinger",
  "dashboard.createCustomer": "Opprett kunde",
  "dashboard.composeMessage": "Skriv melding",
  "dashboard.addProduct": "Legg til produkt",
  "dashboard.createProject": "Opprett prosjekt",
  "dashboard.createTask": "Opprett oppgave",
  "dashboard.logTime": "Før timer",
};

export const dashboardCatalog = { en, nb } as const satisfies CatalogResources;
