import type { CatalogResources } from "@vantigo/frontend-shell";

const en = {
  noAccessTitle: "No modules available",
  noAccessBody: "Your account has no access to any modules in this workspace yet.",
  errorBack: "Go back",
  errorHome: "Go home",
  errorTechnicalDetails: "Technical details",
  notFoundTitle: "Page not found",
  notFoundBody: "The page you requested could not be found.",
  forbiddenTitle: "Access denied",
  forbiddenBody: "You do not have permission to view this page.",
  unexpectedErrorTitle: "Something went wrong",
  unexpectedErrorBody: "The page could not be loaded. Try again or return home.",
  errorRetry: "Try again",
  offlineTitle: "You are offline",
  offlineBody: "Check your internet connection and try again.",
  sessionExpiredTitle: "Your session has expired",
  sessionExpiredBody: "Sign in again to continue.",
  sessionSignInAgain: "Sign in again",
  maintenanceTitle: "Temporarily unavailable",
  maintenanceBody: "Vantigo is undergoing maintenance. Please try again later.",
  developmentDetails: "Development details",
  devBadge: "DEV",
  devCause: "Cause",
  devApiError: "API error",
  devCopied: "Copied",
  devCopyMarkdown: "Copy all as markdown",
  errorIdLabel: "Error ID",
  contactAdministrator: "Contact your administrator for access.",
};

const nb: { [Key in keyof typeof en]: string } = {
  noAccessTitle: "Ingen moduler tilgjengelig",
  noAccessBody: "Kontoen din har ikke tilgang til noen moduler i dette arbeidsområdet ennå.",
  errorBack: "Gå tilbake",
  errorHome: "Gå til startsiden",
  errorTechnicalDetails: "Tekniske detaljer",
  notFoundTitle: "Siden ble ikke funnet",
  notFoundBody: "Siden du ba om, ble ikke funnet.",
  forbiddenTitle: "Tilgang nektet",
  forbiddenBody: "Du har ikke tillatelse til å se denne siden.",
  unexpectedErrorTitle: "Noe gikk galt",
  unexpectedErrorBody: "Siden kunne ikke lastes inn. Prøv igjen eller gå hjem.",
  errorRetry: "Prøv igjen",
  offlineTitle: "Du er frakoblet",
  offlineBody: "Kontroller internettilkoblingen og prøv igjen.",
  sessionExpiredTitle: "Økten din har utløpt",
  sessionExpiredBody: "Logg inn igjen for å fortsette.",
  sessionSignInAgain: "Logg inn igjen",
  maintenanceTitle: "Midlertidig utilgjengelig",
  maintenanceBody: "Vantigo gjennomgår vedlikehold. Prøv igjen senere.",
  developmentDetails: "Utviklingsdetaljer",
  devBadge: "DEV",
  devCause: "Årsak",
  devApiError: "API-feil",
  devCopied: "Kopiert",
  devCopyMarkdown: "Kopier alt som markdown",
  errorIdLabel: "Feil-ID",
  contactAdministrator: "Kontakt administratoren din for tilgang.",
};

export const errorCatalog = { en, nb } as const satisfies CatalogResources;
