import type { CatalogResources } from "@vantigo/frontend-shell";

const en = {
  "navigation.dashboard": "Dashboard",
  "navigation.home": "Home",
  "navigation.customers": "Customers",
  "navigation.contacts": "Contacts",
  "navigation.followUps": "Follow-ups",
  "navigation.communications": "Communications",
  "navigation.inbox": "Inbox",
  "navigation.channels": "Channels",
  "navigation.suppressions": "Suppressions",
  "navigation.products": "Products",
  "navigation.categories": "Categories",
  "navigation.taxCategories": "Tax categories",
  "navigation.projects": "Projects",
  "navigation.project": "Project",
  "navigation.myTasks": "My tasks",
  "navigation.projectsEconomy": "Project economy",
  "navigation.time": "Time",
  "navigation.myWeek": "My week",
  "navigation.approvals": "Approvals",
  "navigation.people": "People",
  "navigation.timeSettings": "Time settings",
  "navigation.expenses": "Expenses",
  "navigation.myExpenses": "My expenses",
  "navigation.expenseApprovals": "Expense approvals",
  "navigation.reimbursements": "Reimbursements",
  "navigation.expensesSettings": "Expense settings",
  "navigation.energy": "Energy",
  "navigation.meteringPoints": "Metering points",
  "navigation.meteringPoint": "Metering point",
  "navigation.accountSection": "Your account",
  "navigation.settings": "Settings",
  "navigation.profile": "Profile",
  "navigation.security": "Security",
  "navigation.workspaceSection": "Workspace",
  "navigation.workspaceAdmin": "Workspace admin",
  "navigation.overview": "Overview",
  "navigation.users": "Users",
  "navigation.invitations": "Invitations",
  "navigation.rolesAccess": "Roles & access",
  "navigation.systemSection": "System",
  "navigation.systemAdmin": "System admin",
  "navigation.notEnabled": "Not enabled",
  "navigation.open": "Open {{label}}",
  "navigation.search": "Search customers, contacts...",
  "navigation.navigation": "Navigation",
  "navigation.customer": "Customer",
  "navigation.noContactDetails": "No contact details",
  "navigation.nothingFound": "Nothing found...",
  "navigation.quickActions": "Quick actions",
};

const nb: { [Key in keyof typeof en]: string } = {
  "navigation.dashboard": "Kontrollpanel",
  "navigation.home": "Hjem",
  "navigation.customers": "Kunder",
  "navigation.contacts": "Kontakter",
  "navigation.followUps": "Oppfølginger",
  "navigation.communications": "Kommunikasjon",
  "navigation.inbox": "Innboks",
  "navigation.channels": "Kanaler",
  "navigation.suppressions": "Blokkeringer",
  "navigation.products": "Produkter",
  "navigation.categories": "Kategorier",
  "navigation.taxCategories": "Avgiftskategorier",
  "navigation.projects": "Prosjekter",
  "navigation.project": "Prosjekt",
  "navigation.myTasks": "Mine oppgaver",
  "navigation.projectsEconomy": "Prosjektøkonomi",
  "navigation.time": "Timer",
  "navigation.myWeek": "Min uke",
  "navigation.approvals": "Godkjenning",
  "navigation.people": "Personer",
  "navigation.timeSettings": "Timeinnstillinger",
  "navigation.expenses": "Utlegg",
  "navigation.myExpenses": "Mine utlegg",
  "navigation.expenseApprovals": "Godkjenning av utlegg",
  "navigation.reimbursements": "Refusjoner",
  "navigation.expensesSettings": "Utleggsinnstillinger",
  "navigation.energy": "Energi",
  "navigation.meteringPoints": "Målepunkter",
  "navigation.meteringPoint": "Målepunkt",
  "navigation.accountSection": "Din konto",
  "navigation.settings": "Innstillinger",
  "navigation.profile": "Profil",
  "navigation.security": "Sikkerhet",
  "navigation.workspaceSection": "Arbeidsområde",
  "navigation.workspaceAdmin": "Administrer arbeidsområde",
  "navigation.overview": "Oversikt",
  "navigation.users": "Brukere",
  "navigation.invitations": "Invitasjoner",
  "navigation.rolesAccess": "Roller og tilgang",
  "navigation.systemSection": "System",
  "navigation.systemAdmin": "Systemadministrasjon",
  "navigation.notEnabled": "Ikke aktivert",
  "navigation.open": "Åpne {{label}}",
  "navigation.search": "Søk etter kunder, kontakter...",
  "navigation.navigation": "Navigasjon",
  "navigation.customer": "Kunde",
  "navigation.noContactDetails": "Ingen kontaktdetaljer",
  "navigation.nothingFound": "Ingenting funnet...",
  "navigation.quickActions": "Hurtighandlinger",
};

export const navigationCatalog = { en, nb } as const satisfies CatalogResources;
