import type { CatalogResources } from "@vantigo/frontend-shell";

type TranslationFunction = (key: string) => string;

export const systemModuleTranslationKeys = {
  communications: "systemAdmin.module.communications",
  customers: "systemAdmin.module.customers",
  energy: "systemAdmin.module.energy",
  products: "systemAdmin.module.products",
} as const;

export const translateSystemModule = (module: string, t: TranslationFunction): string => {
  const key = systemModuleTranslationKeys[module as keyof typeof systemModuleTranslationKeys];
  return key ? t(key) : module;
};

const en = {
  "systemAdmin.settings": "Settings",
  "systemAdmin.manageWorkspace": "Manage this workspace.",
  "systemAdmin.overview": "Overview",
  "systemAdmin.users": "Users",
  "systemAdmin.invitations": "Invitations",
  "systemAdmin.roles": "Roles",
  "systemAdmin.settingsSection": "Settings section",
  "systemAdmin.tenantControlPlaneUnavailable": "Tenant control plane unavailable",
  "systemAdmin.controlPlane": "Control plane",
  "systemAdmin.title": "System admin",
  "systemAdmin.description": "Manage tenants, modules, identity, and offboarding.",
  "systemAdmin.newTenant": "New tenant",
  "systemAdmin.totalTenants": "Total tenants",
  "systemAdmin.active": "Active",
  "systemAdmin.activeStatus": "Active",
  "systemAdmin.suspended": "Suspended",
  "systemAdmin.suspendedStatus": "Suspended",
  "systemAdmin.tenants": "Tenants",
  "systemAdmin.searchNameSlug": "Search name or slug",
  "systemAdmin.name": "Name",
  "systemAdmin.slug": "Slug",
  "systemAdmin.status": "Status",
  "systemAdmin.modules": "Modules",
  "systemAdmin.members": "Members",
  "systemAdmin.sso": "SSO",
  "systemAdmin.configured": "Configured",
  "systemAdmin.notConfigured": "Not configured",
  "systemAdmin.tenant": "Tenant",
  "systemAdmin.loadingTenant": "Loading tenant…",
  "systemAdmin.general": "General",
  "systemAdmin.enabledModules": "Enabled modules: {{modules}}",
  "systemAdmin.none": "None",
  "systemAdmin.membersAndSso": "Members: {{members}} · SSO: {{sso}}",
  "systemAdmin.statusDescription": "Suspending prevents normal tenant use. Reactivation restores it.",
  "systemAdmin.suspendTenant": "Suspend tenant",
  "systemAdmin.reactivateTenant": "Reactivate tenant",
  "systemAdmin.dangerZone": "Danger zone",
  "systemAdmin.offboardingDescription":
    "Export and purge are deferred to system orchestration. The backend will process them asynchronously.",
  "systemAdmin.requestExport": "Request export",
  "systemAdmin.purgeToken": "Purge token",
  "systemAdmin.saveToken": "Save this token: {{token}}",
  "systemAdmin.typePurge": "Type {{confirmation}}",
  "systemAdmin.requestPurge": "Request purge",
  "systemAdmin.confirmStatusChange": "Confirm status change",
  "systemAdmin.changeStatusQuestion": "Change this tenant's status?",
  "systemAdmin.confirm": "Confirm",
  "systemAdmin.tenantCreated": "Tenant created",
  "systemAdmin.invitationTokenShownOnce": "Invitation token shown once",
  "systemAdmin.copyLinkNow": "Copy this link now:",
  "systemAdmin.openTenant": "Open tenant",
  "systemAdmin.identity": "Identity",
  "systemAdmin.lowercaseUrlSafeSlug": "Lowercase URL-safe slug",
  "systemAdmin.moduleSelection": "Modules",
  "systemAdmin.administrator": "Admin",
  "systemAdmin.inviteByEmail": "Invite by email",
  "systemAdmin.existingUserId": "Existing user ID",
  "systemAdmin.email": "Email",
  "systemAdmin.displayName": "Display name",
  "systemAdmin.userId": "User ID",
  "systemAdmin.reviewTenant": "Review {{name}} ({{slug}}) with {{count}} modules.",
  "systemAdmin.back": "Back",
  "systemAdmin.next": "Next",
  "systemAdmin.createTenant": "Create tenant",
  "systemAdmin.module.communications": "Communications",
  "systemAdmin.module.customers": "Customers",
  "systemAdmin.module.energy": "Energy",
  "systemAdmin.module.products": "Products",
};

const nb: { [Key in keyof typeof en]: string } = {
  "systemAdmin.settings": "Innstillinger",
  "systemAdmin.manageWorkspace": "Administrer dette arbeidsområdet.",
  "systemAdmin.overview": "Oversikt",
  "systemAdmin.users": "Brukere",
  "systemAdmin.invitations": "Invitasjoner",
  "systemAdmin.roles": "Roller",
  "systemAdmin.settingsSection": "Innstillingsseksjon",
  "systemAdmin.tenantControlPlaneUnavailable": "Kontrollplanet for leietakere er utilgjengelig",
  "systemAdmin.controlPlane": "Kontrollplan",
  "systemAdmin.title": "Systemadministrator",
  "systemAdmin.description": "Administrer leietakere, moduler, identitet og avvikling.",
  "systemAdmin.newTenant": "Ny leietaker",
  "systemAdmin.totalTenants": "Totalt antall leietakere",
  "systemAdmin.active": "Aktive",
  "systemAdmin.activeStatus": "Aktiv",
  "systemAdmin.suspended": "Suspenderte",
  "systemAdmin.suspendedStatus": "Suspendert",
  "systemAdmin.tenants": "Leietakere",
  "systemAdmin.searchNameSlug": "Søk etter navn eller slug",
  "systemAdmin.name": "Navn",
  "systemAdmin.slug": "Slug",
  "systemAdmin.status": "Status",
  "systemAdmin.modules": "Moduler",
  "systemAdmin.members": "Medlemmer",
  "systemAdmin.sso": "SSO",
  "systemAdmin.configured": "Konfigurert",
  "systemAdmin.notConfigured": "Ikke konfigurert",
  "systemAdmin.tenant": "Leietaker",
  "systemAdmin.loadingTenant": "Laster inn leietaker…",
  "systemAdmin.general": "Generelt",
  "systemAdmin.enabledModules": "Aktiverte moduler: {{modules}}",
  "systemAdmin.none": "Ingen",
  "systemAdmin.membersAndSso": "Medlemmer: {{members}} · SSO: {{sso}}",
  "systemAdmin.statusDescription": "Suspendering hindrer normal bruk av leietakeren. Reaktivering gjenoppretter den.",
  "systemAdmin.suspendTenant": "Suspender leietaker",
  "systemAdmin.reactivateTenant": "Reaktiver leietaker",
  "systemAdmin.dangerZone": "Faresone",
  "systemAdmin.offboardingDescription":
    "Eksport og sletting håndteres av systemorkestrering. Backend behandler dem asynkront.",
  "systemAdmin.requestExport": "Be om eksport",
  "systemAdmin.purgeToken": "Slettingstoken",
  "systemAdmin.saveToken": "Lagre dette tokenet: {{token}}",
  "systemAdmin.typePurge": "Skriv {{confirmation}}",
  "systemAdmin.requestPurge": "Be om sletting",
  "systemAdmin.confirmStatusChange": "Bekreft statusendring",
  "systemAdmin.changeStatusQuestion": "Endre statusen til denne leietakeren?",
  "systemAdmin.confirm": "Bekreft",
  "systemAdmin.tenantCreated": "Leietaker opprettet",
  "systemAdmin.invitationTokenShownOnce": "Invitasjonstokenet vises bare én gang",
  "systemAdmin.copyLinkNow": "Kopier denne lenken nå:",
  "systemAdmin.openTenant": "Åpne leietaker",
  "systemAdmin.identity": "Identitet",
  "systemAdmin.lowercaseUrlSafeSlug": "Slug med små bokstaver, trygg for URL-er",
  "systemAdmin.moduleSelection": "Moduler",
  "systemAdmin.administrator": "Administrator",
  "systemAdmin.inviteByEmail": "Inviter via e-post",
  "systemAdmin.existingUserId": "ID for eksisterende bruker",
  "systemAdmin.email": "E-post",
  "systemAdmin.displayName": "Visningsnavn",
  "systemAdmin.userId": "Bruker-ID",
  "systemAdmin.reviewTenant": "Se gjennom {{name}} ({{slug}}) med {{count}} moduler.",
  "systemAdmin.back": "Tilbake",
  "systemAdmin.next": "Neste",
  "systemAdmin.createTenant": "Opprett leietaker",
  "systemAdmin.module.communications": "Kommunikasjon",
  "systemAdmin.module.customers": "Kunder",
  "systemAdmin.module.energy": "Energi",
  "systemAdmin.module.products": "Produkter",
};

export const systemAdminCatalog = { en, nb } as const satisfies CatalogResources;
