// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEntries = `-- name: CountEntries :one
SELECT count(*) FROM expenses.entries e
LEFT JOIN expenses.claims c ON c.id = e.claim_id
WHERE ($1::boolean
       OR e.user_id = $2::uuid
       OR (e.project_id IS NOT NULL AND e.project_id = ANY($3::integer[])))
  AND ($4::uuid IS NULL OR e.user_id = $4::uuid)
  AND ($5::integer IS NULL OR e.project_id = $5::integer)
  AND ($6::bigint IS NULL OR e.claim_id = $6::bigint)
  AND ($7::boolean IS NULL OR (e.claim_id IS NULL) = $7::boolean)
  AND ($8::text IS NULL OR COALESCE(c.status, e.status) = $8::text)
  AND ($9::text IS NULL OR e.kind = $9::text)
  AND ($10::date IS NULL OR e.entry_date >= $10::date)
  AND ($11::date IS NULL OR e.entry_date <= $11::date)
  AND ($12::boolean IS NULL
       OR (COALESCE(c.reimbursed_at, e.reimbursed_at) IS NOT NULL) = $12::boolean)
  AND ($13::boolean IS NOT TRUE
       OR (COALESCE(c.status, e.status) = 'approved'
           AND e.billable
           AND e.kind <> 'per_diem'
           AND e.bill_amount IS NOT NULL
           AND e.invoiced_at IS NULL))
`

type CountEntriesParams struct {
	SeeAll            bool
	CallerID          uuid.UUID
	ManagedProjectIds []int32
	UserID            *uuid.UUID
	ProjectID         *int32
	ClaimID           *int64
	Standalone        *bool
	Status            *string
	Kind              *string
	FromDate          pgtype.Date
	ToDate            pgtype.Date
	Reimbursed        *bool
	ToInvoice         *bool
}

// CountEntries counts what ListEntries pages through, under exactly the same
// predicate, so the total is the number of expenses the caller may see and the
// last page is never empty. Visibility is a predicate of its own — the rule
// authorize.go applies to one entry: everything for see_all (expenses:view-all,
// expenses:approve, expenses:manage), the caller's own, and everything on the
// projects the caller manages, whose ids are resolved through the project
// directory before the query rather than filtered after it. A claim's line
// carries its claim's owner and its claim's project, so the same predicate
// makes a line visible exactly when its claim is.
//
// The status and the reimbursed filters read the **unit** the entry belongs
// to, which for a line is its claim (unitOf in authorize.go) — the status the
// line is rendered with, so the filter and the rendering can never disagree.
// standalone and claim_id narrow the list to one side of that distinction; an
// absent standalone leaves both in, so the list a client that knows nothing of
// claims asks for is exactly the list it always got.
//
// to_invoice is the "ready to invoice" predicate, word for word the one
// ProjectExpenseGroups counts its ready_count by: the unit is approved, the
// line is billable, it is not a per diem day, it carries a bill amount and
// nobody has invoiced it yet.
// The two must stay the same sentence — the project page shows the figure as
// the header of this very list — so a change to one is a change to both.
// Note it reads the *unit's* status, which is why the claim join matters here
// too: ix_entries_to_invoice's predicate before 00014 was on the entry's own
// column, so a trip's line (whose column stays at 'draft') could never be
// found through it.
//
// It narrows only when it is true. false is the filter left out — the reading
// an unticked checkbox has — so IS NOT TRUE, not IS NULL: the clause then has
// one meaning whatever reaches it, and no caller can ask for "everything that
// is not ready", which is a page nobody wants and a promise nobody made.
func (q *Queries) CountEntries(ctx context.Context, arg CountEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntries,
		arg.SeeAll,
		arg.CallerID,
		arg.ManagedProjectIds,
		arg.UserID,
		arg.ProjectID,
		arg.ClaimID,
		arg.Standalone,
		arg.Status,
		arg.Kind,
		arg.FromDate,
		arg.ToDate,
		arg.Reimbursed,
		arg.ToInvoice,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM expenses.entries
WHERE expenses.entries.id = $1
  -- The unit's status again, for the reason UpdateEntry reads it: a line's own
  -- column says nothing, and the claim's row is held before this runs.
  AND COALESCE(
        (SELECT c.status FROM expenses.claims c WHERE c.id = expenses.entries.claim_id),
        expenses.entries.status) IN ('draft', 'rejected')
  AND ($2::boolean OR expenses.entries.user_id = $3::uuid)
`

type DeleteEntryParams struct {
	ID       int64
	AnyOwner bool
	UserID   uuid.UUID
}

// DeleteEntry removes an expense only while it is still its owner's to change.
// The status and who may write are re-checked here rather than trusted from
// the row the handler read, so a submit that commits in between wins and the
// delete removes nothing. any_owner is expenses:manage, which deletes anyone's
// draft.
func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntry, arg.ID, arg.AnyOwner, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEntry = `-- name: GetEntry :one
SELECT id, user_id, created_by_user_id, claim_id, kind, entry_date, description, category_id, supplier, paid_by, currency, gross_amount, vat_amount, distance_km, from_place, to_place, passengers, rate, passenger_rate, rate_overridden_by_user_id, rate_table_value, passenger_rate_table_value, project_id, billing_line_id, billable, markup_percent, bill_rate_per_km, bill_amount, status, submitted_at, decided_at, decided_by_user_id, rejection_reason, reimbursed_at, reimbursed_by_user_id, reimbursement_reference, reimbursement_date, invoiced_at, invoiced_by_user_id, invoice_reference, revision, created_at, updated_at, per_diem_type, breakfast_covered, lunch_covered, dinner_covered, meal_breakfast_percent, meal_lunch_percent, meal_dinner_percent, supplier_invoice_number, supplier_due_date FROM expenses.entries WHERE id = $1
`

// GetEntry fetches one expense by id. Who may see it is decided in Go
// (authorize.go), never here: an outsider's 404 has to be indistinguishable
// from an unknown id's, so the row is loaded first and discarded after.
func (q *Queries) GetEntry(ctx context.Context, id int64) (ExpensesEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i ExpensesEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.ClaimID,
		&i.Kind,
		&i.EntryDate,
		&i.Description,
		&i.CategoryID,
		&i.Supplier,
		&i.PaidBy,
		&i.Currency,
		&i.GrossAmount,
		&i.VatAmount,
		&i.DistanceKm,
		&i.FromPlace,
		&i.ToPlace,
		&i.Passengers,
		&i.Rate,
		&i.PassengerRate,
		&i.RateOverriddenByUserID,
		&i.RateTableValue,
		&i.PassengerRateTableValue,
		&i.ProjectID,
		&i.BillingLineID,
		&i.Billable,
		&i.MarkupPercent,
		&i.BillRatePerKm,
		&i.BillAmount,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecidedByUserID,
		&i.RejectionReason,
		&i.ReimbursedAt,
		&i.ReimbursedByUserID,
		&i.ReimbursementReference,
		&i.ReimbursementDate,
		&i.InvoicedAt,
		&i.InvoicedByUserID,
		&i.InvoiceReference,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerDiemType,
		&i.BreakfastCovered,
		&i.LunchCovered,
		&i.DinnerCovered,
		&i.MealBreakfastPercent,
		&i.MealLunchPercent,
		&i.MealDinnerPercent,
		&i.SupplierInvoiceNumber,
		&i.SupplierDueDate,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO expenses.entries (
    user_id, created_by_user_id, claim_id, kind, entry_date, description,
    category_id, supplier, paid_by, currency, gross_amount, vat_amount,
    distance_km, from_place, to_place, passengers, rate, passenger_rate,
    per_diem_type, breakfast_covered, lunch_covered, dinner_covered,
    meal_breakfast_percent, meal_lunch_percent, meal_dinner_percent,
    project_id, billing_line_id, billable, markup_percent, bill_rate_per_km, bill_amount,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22,
    $23, $24, $25,
    $26, $27, $28, $29, $30, $31,
    $32::timestamptz, $32::timestamptz
)
RETURNING id, user_id, created_by_user_id, claim_id, kind, entry_date, description, category_id, supplier, paid_by, currency, gross_amount, vat_amount, distance_km, from_place, to_place, passengers, rate, passenger_rate, rate_overridden_by_user_id, rate_table_value, passenger_rate_table_value, project_id, billing_line_id, billable, markup_percent, bill_rate_per_km, bill_amount, status, submitted_at, decided_at, decided_by_user_id, rejection_reason, reimbursed_at, reimbursed_by_user_id, reimbursement_reference, reimbursement_date, invoiced_at, invoiced_by_user_id, invoice_reference, revision, created_at, updated_at, per_diem_type, breakfast_covered, lunch_covered, dinner_covered, meal_breakfast_percent, meal_lunch_percent, meal_dinner_percent, supplier_invoice_number, supplier_due_date
`

type InsertEntryParams struct {
	UserID               uuid.UUID
	CreatedByUserID      uuid.UUID
	ClaimID              *int64
	Kind                 string
	EntryDate            pgtype.Date
	Description          string
	CategoryID           *int32
	Supplier             *string
	PaidBy               *string
	Currency             string
	GrossAmount          pgtype.Numeric
	VatAmount            pgtype.Numeric
	DistanceKm           pgtype.Numeric
	FromPlace            *string
	ToPlace              *string
	Passengers           int16
	Rate                 pgtype.Numeric
	PassengerRate        pgtype.Numeric
	PerDiemType          *string
	BreakfastCovered     bool
	LunchCovered         bool
	DinnerCovered        bool
	MealBreakfastPercent pgtype.Numeric
	MealLunchPercent     pgtype.Numeric
	MealDinnerPercent    pgtype.Numeric
	ProjectID            *int32
	BillingLineID        *int32
	Billable             bool
	MarkupPercent        pgtype.Numeric
	BillRatePerKm        pgtype.Numeric
	BillAmount           pgtype.Numeric
	Now                  time.Time
}

// InsertEntry records one expense as a draft, with every amount already
// computed in Go from exact decimals (money.go) — the columns' own scale
// never rounds anything a second time. created_at and updated_at are the same
// instant, supplied by the caller from Deps.Clock(); status and revision take
// the column defaults ('draft', 1). created_by_user_id is whoever made the
// request, which is not always user_id, the person the expense concerns.
// claim_id is the travel claim the expense is a line of, NULL for a standalone
// one; a line's own status column stays 'draft' and is never read, because
// everything status-shaped about it is the claim's (see unitOf in
// authorize.go).
func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (ExpensesEntry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.UserID,
		arg.CreatedByUserID,
		arg.ClaimID,
		arg.Kind,
		arg.EntryDate,
		arg.Description,
		arg.CategoryID,
		arg.Supplier,
		arg.PaidBy,
		arg.Currency,
		arg.GrossAmount,
		arg.VatAmount,
		arg.DistanceKm,
		arg.FromPlace,
		arg.ToPlace,
		arg.Passengers,
		arg.Rate,
		arg.PassengerRate,
		arg.PerDiemType,
		arg.BreakfastCovered,
		arg.LunchCovered,
		arg.DinnerCovered,
		arg.MealBreakfastPercent,
		arg.MealLunchPercent,
		arg.MealDinnerPercent,
		arg.ProjectID,
		arg.BillingLineID,
		arg.Billable,
		arg.MarkupPercent,
		arg.BillRatePerKm,
		arg.BillAmount,
		arg.Now,
	)
	var i ExpensesEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.ClaimID,
		&i.Kind,
		&i.EntryDate,
		&i.Description,
		&i.CategoryID,
		&i.Supplier,
		&i.PaidBy,
		&i.Currency,
		&i.GrossAmount,
		&i.VatAmount,
		&i.DistanceKm,
		&i.FromPlace,
		&i.ToPlace,
		&i.Passengers,
		&i.Rate,
		&i.PassengerRate,
		&i.RateOverriddenByUserID,
		&i.RateTableValue,
		&i.PassengerRateTableValue,
		&i.ProjectID,
		&i.BillingLineID,
		&i.Billable,
		&i.MarkupPercent,
		&i.BillRatePerKm,
		&i.BillAmount,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecidedByUserID,
		&i.RejectionReason,
		&i.ReimbursedAt,
		&i.ReimbursedByUserID,
		&i.ReimbursementReference,
		&i.ReimbursementDate,
		&i.InvoicedAt,
		&i.InvoicedByUserID,
		&i.InvoiceReference,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerDiemType,
		&i.BreakfastCovered,
		&i.LunchCovered,
		&i.DinnerCovered,
		&i.MealBreakfastPercent,
		&i.MealLunchPercent,
		&i.MealDinnerPercent,
		&i.SupplierInvoiceNumber,
		&i.SupplierDueDate,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT e.id, e.user_id, e.created_by_user_id, e.claim_id, e.kind, e.entry_date, e.description, e.category_id, e.supplier, e.paid_by, e.currency, e.gross_amount, e.vat_amount, e.distance_km, e.from_place, e.to_place, e.passengers, e.rate, e.passenger_rate, e.rate_overridden_by_user_id, e.rate_table_value, e.passenger_rate_table_value, e.project_id, e.billing_line_id, e.billable, e.markup_percent, e.bill_rate_per_km, e.bill_amount, e.status, e.submitted_at, e.decided_at, e.decided_by_user_id, e.rejection_reason, e.reimbursed_at, e.reimbursed_by_user_id, e.reimbursement_reference, e.reimbursement_date, e.invoiced_at, e.invoiced_by_user_id, e.invoice_reference, e.revision, e.created_at, e.updated_at, e.per_diem_type, e.breakfast_covered, e.lunch_covered, e.dinner_covered, e.meal_breakfast_percent, e.meal_lunch_percent, e.meal_dinner_percent, e.supplier_invoice_number, e.supplier_due_date FROM expenses.entries e
LEFT JOIN expenses.claims c ON c.id = e.claim_id
WHERE ($1::boolean
       OR e.user_id = $2::uuid
       OR (e.project_id IS NOT NULL AND e.project_id = ANY($3::integer[])))
  AND ($4::uuid IS NULL OR e.user_id = $4::uuid)
  AND ($5::integer IS NULL OR e.project_id = $5::integer)
  AND ($6::bigint IS NULL OR e.claim_id = $6::bigint)
  AND ($7::boolean IS NULL OR (e.claim_id IS NULL) = $7::boolean)
  AND ($8::text IS NULL OR COALESCE(c.status, e.status) = $8::text)
  AND ($9::text IS NULL OR e.kind = $9::text)
  AND ($10::date IS NULL OR e.entry_date >= $10::date)
  AND ($11::date IS NULL OR e.entry_date <= $11::date)
  AND ($12::boolean IS NULL
       OR (COALESCE(c.reimbursed_at, e.reimbursed_at) IS NOT NULL) = $12::boolean)
  AND ($13::boolean IS NOT TRUE
       OR (COALESCE(c.status, e.status) = 'approved'
           AND e.billable
           AND e.kind <> 'per_diem'
           AND e.bill_amount IS NOT NULL
           AND e.invoiced_at IS NULL))
ORDER BY e.entry_date DESC, e.id DESC
LIMIT $15 OFFSET $14
`

type ListEntriesParams struct {
	SeeAll            bool
	CallerID          uuid.UUID
	ManagedProjectIds []int32
	UserID            *uuid.UUID
	ProjectID         *int32
	ClaimID           *int64
	Standalone        *bool
	Status            *string
	Kind              *string
	FromDate          pgtype.Date
	ToDate            pgtype.Date
	Reimbursed        *bool
	ToInvoice         *bool
	PageOffset        int32
	PageSize          int32
}

// ListEntries is one page of CountEntries' expenses, the latest day first and,
// within a day, the latest recorded first.
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ExpensesEntry, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.SeeAll,
		arg.CallerID,
		arg.ManagedProjectIds,
		arg.UserID,
		arg.ProjectID,
		arg.ClaimID,
		arg.Standalone,
		arg.Status,
		arg.Kind,
		arg.FromDate,
		arg.ToDate,
		arg.Reimbursed,
		arg.ToInvoice,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpensesEntry
	for rows.Next() {
		var i ExpensesEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedByUserID,
			&i.ClaimID,
			&i.Kind,
			&i.EntryDate,
			&i.Description,
			&i.CategoryID,
			&i.Supplier,
			&i.PaidBy,
			&i.Currency,
			&i.GrossAmount,
			&i.VatAmount,
			&i.DistanceKm,
			&i.FromPlace,
			&i.ToPlace,
			&i.Passengers,
			&i.Rate,
			&i.PassengerRate,
			&i.RateOverriddenByUserID,
			&i.RateTableValue,
			&i.PassengerRateTableValue,
			&i.ProjectID,
			&i.BillingLineID,
			&i.Billable,
			&i.MarkupPercent,
			&i.BillRatePerKm,
			&i.BillAmount,
			&i.Status,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.DecidedByUserID,
			&i.RejectionReason,
			&i.ReimbursedAt,
			&i.ReimbursedByUserID,
			&i.ReimbursementReference,
			&i.ReimbursementDate,
			&i.InvoicedAt,
			&i.InvoicedByUserID,
			&i.InvoiceReference,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PerDiemType,
			&i.BreakfastCovered,
			&i.LunchCovered,
			&i.DinnerCovered,
			&i.MealBreakfastPercent,
			&i.MealLunchPercent,
			&i.MealDinnerPercent,
			&i.SupplierInvoiceNumber,
			&i.SupplierDueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEntry = `-- name: LockEntry :one
SELECT id, user_id, created_by_user_id, claim_id, kind, entry_date, description, category_id, supplier, paid_by, currency, gross_amount, vat_amount, distance_km, from_place, to_place, passengers, rate, passenger_rate, rate_overridden_by_user_id, rate_table_value, passenger_rate_table_value, project_id, billing_line_id, billable, markup_percent, bill_rate_per_km, bill_amount, status, submitted_at, decided_at, decided_by_user_id, rejection_reason, reimbursed_at, reimbursed_by_user_id, reimbursement_reference, reimbursement_date, invoiced_at, invoiced_by_user_id, invoice_reference, revision, created_at, updated_at, per_diem_type, breakfast_covered, lunch_covered, dinner_covered, meal_breakfast_percent, meal_lunch_percent, meal_dinner_percent, supplier_invoice_number, supplier_due_date FROM expenses.entries WHERE id = $1 FOR UPDATE
`

// LockEntry reads one expense and holds its row until the transaction ends.
// An update decides everything it refuses on — the status, the revision —
// from this row, not from the one the handler read before the transaction, so
// a save that committed in between is seen and wins.
func (q *Queries) LockEntry(ctx context.Context, id int64) (ExpensesEntry, error) {
	row := q.db.QueryRow(ctx, lockEntry, id)
	var i ExpensesEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.ClaimID,
		&i.Kind,
		&i.EntryDate,
		&i.Description,
		&i.CategoryID,
		&i.Supplier,
		&i.PaidBy,
		&i.Currency,
		&i.GrossAmount,
		&i.VatAmount,
		&i.DistanceKm,
		&i.FromPlace,
		&i.ToPlace,
		&i.Passengers,
		&i.Rate,
		&i.PassengerRate,
		&i.RateOverriddenByUserID,
		&i.RateTableValue,
		&i.PassengerRateTableValue,
		&i.ProjectID,
		&i.BillingLineID,
		&i.Billable,
		&i.MarkupPercent,
		&i.BillRatePerKm,
		&i.BillAmount,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecidedByUserID,
		&i.RejectionReason,
		&i.ReimbursedAt,
		&i.ReimbursedByUserID,
		&i.ReimbursementReference,
		&i.ReimbursementDate,
		&i.InvoicedAt,
		&i.InvoicedByUserID,
		&i.InvoiceReference,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerDiemType,
		&i.BreakfastCovered,
		&i.LunchCovered,
		&i.DinnerCovered,
		&i.MealBreakfastPercent,
		&i.MealLunchPercent,
		&i.MealDinnerPercent,
		&i.SupplierInvoiceNumber,
		&i.SupplierDueDate,
	)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE expenses.entries SET
    kind = $1,
    entry_date = $2,
    description = $3,
    category_id = $4,
    supplier = $5,
    paid_by = $6,
    currency = $7,
    gross_amount = $8,
    vat_amount = $9,
    distance_km = $10,
    from_place = $11,
    to_place = $12,
    passengers = $13,
    rate = $14,
    passenger_rate = $15,
    per_diem_type = $16,
    breakfast_covered = $17,
    lunch_covered = $18,
    dinner_covered = $19,
    meal_breakfast_percent = $20,
    meal_lunch_percent = $21,
    meal_dinner_percent = $22,
    rate_overridden_by_user_id = NULL,
    rate_table_value = NULL,
    passenger_rate_table_value = NULL,
    project_id = $23,
    billing_line_id = $24,
    billable = $25,
    markup_percent = $26,
    bill_rate_per_km = $27,
    bill_amount = $28,
    status = 'draft',
    rejection_reason = NULL,
    submitted_at = NULL,
    decided_at = NULL,
    decided_by_user_id = NULL,
    revision = revision + 1,
    updated_at = $29::timestamptz
WHERE expenses.entries.id = $30
  AND expenses.entries.revision = $31
  -- The status guarded is the **unit's** (unitOf in authorize.go): a line
  -- inside a travel claim is editable exactly while its claim is, and its own
  -- column stays at its default 'draft'. The handler holds the claim's row lock
  -- before this runs, so the subquery reads the very row it judged.
  AND COALESCE(
        (SELECT c.status FROM expenses.claims c WHERE c.id = expenses.entries.claim_id),
        expenses.entries.status) IN ('draft', 'rejected')
  AND ($32::boolean OR expenses.entries.user_id = $33::uuid)
RETURNING id, user_id, created_by_user_id, claim_id, kind, entry_date, description, category_id, supplier, paid_by, currency, gross_amount, vat_amount, distance_km, from_place, to_place, passengers, rate, passenger_rate, rate_overridden_by_user_id, rate_table_value, passenger_rate_table_value, project_id, billing_line_id, billable, markup_percent, bill_rate_per_km, bill_amount, status, submitted_at, decided_at, decided_by_user_id, rejection_reason, reimbursed_at, reimbursed_by_user_id, reimbursement_reference, reimbursement_date, invoiced_at, invoiced_by_user_id, invoice_reference, revision, created_at, updated_at, per_diem_type, breakfast_covered, lunch_covered, dinner_covered, meal_breakfast_percent, meal_lunch_percent, meal_dinner_percent, supplier_invoice_number, supplier_due_date
`

type UpdateEntryParams struct {
	Kind                 string
	EntryDate            pgtype.Date
	Description          string
	CategoryID           *int32
	Supplier             *string
	PaidBy               *string
	Currency             string
	GrossAmount          pgtype.Numeric
	VatAmount            pgtype.Numeric
	DistanceKm           pgtype.Numeric
	FromPlace            *string
	ToPlace              *string
	Passengers           int16
	Rate                 pgtype.Numeric
	PassengerRate        pgtype.Numeric
	PerDiemType          *string
	BreakfastCovered     bool
	LunchCovered         bool
	DinnerCovered        bool
	MealBreakfastPercent pgtype.Numeric
	MealLunchPercent     pgtype.Numeric
	MealDinnerPercent    pgtype.Numeric
	ProjectID            *int32
	BillingLineID        *int32
	Billable             bool
	MarkupPercent        pgtype.Numeric
	BillRatePerKm        pgtype.Numeric
	BillAmount           pgtype.Numeric
	Now                  time.Time
	ID                   int64
	Revision             int32
	AnyOwner             bool
	UserID               uuid.UUID
}

// UpdateEntry replaces an expense's content, its amounts computed again (a
// draft follows the rate table until it is submitted). A save always leaves a
// draft: a rejected line returns to draft with its rejection and its decision
// cleared. The revision, the status and who may write are guarded again here,
// although the row is already locked, so that no caller can ever write over a
// revision it did not read.
func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (ExpensesEntry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.Kind,
		arg.EntryDate,
		arg.Description,
		arg.CategoryID,
		arg.Supplier,
		arg.PaidBy,
		arg.Currency,
		arg.GrossAmount,
		arg.VatAmount,
		arg.DistanceKm,
		arg.FromPlace,
		arg.ToPlace,
		arg.Passengers,
		arg.Rate,
		arg.PassengerRate,
		arg.PerDiemType,
		arg.BreakfastCovered,
		arg.LunchCovered,
		arg.DinnerCovered,
		arg.MealBreakfastPercent,
		arg.MealLunchPercent,
		arg.MealDinnerPercent,
		arg.ProjectID,
		arg.BillingLineID,
		arg.Billable,
		arg.MarkupPercent,
		arg.BillRatePerKm,
		arg.BillAmount,
		arg.Now,
		arg.ID,
		arg.Revision,
		arg.AnyOwner,
		arg.UserID,
	)
	var i ExpensesEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.ClaimID,
		&i.Kind,
		&i.EntryDate,
		&i.Description,
		&i.CategoryID,
		&i.Supplier,
		&i.PaidBy,
		&i.Currency,
		&i.GrossAmount,
		&i.VatAmount,
		&i.DistanceKm,
		&i.FromPlace,
		&i.ToPlace,
		&i.Passengers,
		&i.Rate,
		&i.PassengerRate,
		&i.RateOverriddenByUserID,
		&i.RateTableValue,
		&i.PassengerRateTableValue,
		&i.ProjectID,
		&i.BillingLineID,
		&i.Billable,
		&i.MarkupPercent,
		&i.BillRatePerKm,
		&i.BillAmount,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecidedByUserID,
		&i.RejectionReason,
		&i.ReimbursedAt,
		&i.ReimbursedByUserID,
		&i.ReimbursementReference,
		&i.ReimbursementDate,
		&i.InvoicedAt,
		&i.InvoicedByUserID,
		&i.InvoiceReference,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PerDiemType,
		&i.BreakfastCovered,
		&i.LunchCovered,
		&i.DinnerCovered,
		&i.MealBreakfastPercent,
		&i.MealLunchPercent,
		&i.MealDinnerPercent,
		&i.SupplierInvoiceNumber,
		&i.SupplierDueDate,
	)
	return i, err
}
