// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rates.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRate = `-- name: DeleteRate :execrows
DELETE FROM expenses.rates WHERE id = $1
`

// DeleteRate removes a row. Expenses it priced keep their snapshots.
func (q *Queries) DeleteRate(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const effectiveRate = `-- name: EffectiveRate :one
SELECT id, kind, valid_from, value, currency, source, created_at, updated_at FROM expenses.rates
WHERE kind = $1 AND valid_from <= $2
ORDER BY valid_from DESC
LIMIT 1
`

type EffectiveRateParams struct {
	Kind   string
	OnDate pgtype.Date
}

// EffectiveRate is the rate of one kind in force on a day (design §3.4): the
// latest row whose valid_from is on or before it. A kind with no such row
// answers no rows, which rateFor turns into the typed "no rate" result.
func (q *Queries) EffectiveRate(ctx context.Context, arg EffectiveRateParams) (ExpensesRate, error) {
	row := q.db.QueryRow(ctx, effectiveRate, arg.Kind, arg.OnDate)
	var i ExpensesRate
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ValidFrom,
		&i.Value,
		&i.Currency,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRate = `-- name: GetRate :one
SELECT id, kind, valid_from, value, currency, source, created_at, updated_at FROM expenses.rates WHERE id = $1
`

func (q *Queries) GetRate(ctx context.Context, id int32) (ExpensesRate, error) {
	row := q.db.QueryRow(ctx, getRate, id)
	var i ExpensesRate
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ValidFrom,
		&i.Value,
		&i.Currency,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRate = `-- name: InsertRate :one
INSERT INTO expenses.rates (kind, valid_from, value, currency, source, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6::timestamptz, $6::timestamptz)
RETURNING id, kind, valid_from, value, currency, source, created_at, updated_at
`

type InsertRateParams struct {
	Kind      string
	ValidFrom pgtype.Date
	Value     pgtype.Numeric
	Currency  *string
	Source    *string
	Now       time.Time
}

// InsertRate adds a rate row. A second row for the same kind and day raises
// 23505 on ux_rates_kind_valid_from, which the handler turns into the
// validFrom field error.
func (q *Queries) InsertRate(ctx context.Context, arg InsertRateParams) (ExpensesRate, error) {
	row := q.db.QueryRow(ctx, insertRate,
		arg.Kind,
		arg.ValidFrom,
		arg.Value,
		arg.Currency,
		arg.Source,
		arg.Now,
	)
	var i ExpensesRate
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ValidFrom,
		&i.Value,
		&i.Currency,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRates = `-- name: ListRates :many
SELECT id, kind, valid_from, value, currency, source, created_at, updated_at FROM expenses.rates ORDER BY kind, valid_from DESC
`

// ListRates is every dated rate, by kind and then the latest first. The
// client groups them per kind, so one flat list is all the settings screen
// needs.
func (q *Queries) ListRates(ctx context.Context) ([]ExpensesRate, error) {
	rows, err := q.db.Query(ctx, listRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpensesRate
	for rows.Next() {
		var i ExpensesRate
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ValidFrom,
			&i.Value,
			&i.Currency,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSeedRate = `-- name: RestoreSeedRate :execrows
INSERT INTO expenses.rates (kind, valid_from, value, currency, source, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6::timestamptz, $6::timestamptz)
ON CONFLICT (kind, valid_from) DO UPDATE SET
    value = EXCLUDED.value,
    currency = EXCLUDED.currency,
    source = EXCLUDED.source,
    updated_at = EXCLUDED.updated_at
`

type RestoreSeedRateParams struct {
	Kind      string
	ValidFrom pgtype.Date
	Value     pgtype.Numeric
	Currency  *string
	Source    *string
	Now       time.Time
}

// RestoreSeedRate writes one shipped row back as it shipped — the reset
// operation's whole write. A day the product ships is the product's: removed,
// it is created again; edited, it returns to its shipped value, currency and
// source label, keeping the row's id so anything that quotes it still finds
// it. Only the (kind, valid_from) pairs named by the seed table are touched,
// so the company's own rows, on their own days, are never in the conflict
// target and never change.
func (q *Queries) RestoreSeedRate(ctx context.Context, arg RestoreSeedRateParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreSeedRate,
		arg.Kind,
		arg.ValidFrom,
		arg.Value,
		arg.Currency,
		arg.Source,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRate = `-- name: UpdateRate :one
UPDATE expenses.rates SET
    valid_from = $1,
    value = $2,
    currency = $3,
    source = $4,
    updated_at = $5::timestamptz
WHERE id = $6
RETURNING id, kind, valid_from, value, currency, source, created_at, updated_at
`

type UpdateRateParams struct {
	ValidFrom pgtype.Date
	Value     pgtype.Numeric
	Currency  *string
	Source    *string
	Now       time.Time
	ID        int32
}

// UpdateRate replaces a row's day, value, currency and source; the kind stays
// the row's own. No row is an unknown id.
func (q *Queries) UpdateRate(ctx context.Context, arg UpdateRateParams) (ExpensesRate, error) {
	row := q.db.QueryRow(ctx, updateRate,
		arg.ValidFrom,
		arg.Value,
		arg.Currency,
		arg.Source,
		arg.Now,
		arg.ID,
	)
	var i ExpensesRate
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ValidFrom,
		&i.Value,
		&i.Currency,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
