// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSettings = `-- name: GetSettings :one
SELECT id, locked_before, default_currency, default_markup_percent, receipt_required_over, updated_at, time_zone FROM expenses.settings WHERE id = 1
`

// GetSettings reads the installation's single settings row (design §3.5). The
// migration writes it, so this always answers a row.
func (q *Queries) GetSettings(ctx context.Context) (ExpensesSetting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i ExpensesSetting
	err := row.Scan(
		&i.ID,
		&i.LockedBefore,
		&i.DefaultCurrency,
		&i.DefaultMarkupPercent,
		&i.ReceiptRequiredOver,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}

const resolveTimeZone = `-- name: ResolveTimeZone :one
WITH probe AS (
    SELECT $1::text AS zone, $2::timestamptz AS winter, $3::timestamptz AS summer
)
SELECT
    EXTRACT(EPOCH FROM ((winter AT TIME ZONE zone) - (winter AT TIME ZONE 'UTC')))::bigint AS winter_offset,
    EXTRACT(EPOCH FROM ((summer AT TIME ZONE zone) - (summer AT TIME ZONE 'UTC')))::bigint AS summer_offset
FROM probe
`

type ResolveTimeZoneParams struct {
	Name   string
	Winter time.Time
	Summer time.Time
}

type ResolveTimeZoneRow struct {
	WinterOffset int64
	SummerOffset int64
}

// ResolveTimeZone asks Postgres what a zone name *means*, by doing the very
// thing the claims list's filter will do with it. A business time zone is read
// by Go (every date derived from a claim's instants) *and* by Postgres (that
// same derivation in SQL), and the two carry their own tzdata: a name they read
// differently would be stored here and then quietly disagree with itself.
//
// Knowing the name is not enough, which is what this query used to ask. 'CET'
// is an IANA zone with summer time to Go and a fixed +01:00 **abbreviation** to
// Postgres, which resolves pg_timezone_abbrevs before pg_timezone_names — so
// both halves "know" it and they mean two different things for half the year.
// The answer here is therefore the offset Postgres puts the name at, at a
// winter instant and a summer one, which the caller compares with Go's. Two
// instants are enough because the disagreements are about summer time, and a
// zone that agrees in both January and July agrees about which side of local
// midnight an instant falls on all year.
//
// Both sides of each subtraction are timestamps without zone, so the interval
// is the offset itself; EXTRACT(EPOCH …) makes it the seconds Go's Zone()
// answers in. A name Postgres does not know raises 22023 rather than answering
// a row, which is exactly the signal the caller turns into the timeZone field
// error. The view pg_timezone_names would list the names more directly, but
// sqlc's catalog has no entry for it, and a query the generator cannot type is
// not one this module writes — and it would not answer this question anyway,
// since it lists 'CET' too.
func (q *Queries) ResolveTimeZone(ctx context.Context, arg ResolveTimeZoneParams) (ResolveTimeZoneRow, error) {
	row := q.db.QueryRow(ctx, resolveTimeZone, arg.Name, arg.Winter, arg.Summer)
	var i ResolveTimeZoneRow
	err := row.Scan(&i.WinterOffset, &i.SummerOffset)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE expenses.settings SET
    locked_before = $1,
    default_currency = $2,
    default_markup_percent = $3,
    receipt_required_over = $4,
    time_zone = $5,
    updated_at = $6::timestamptz
WHERE id = 1
RETURNING id, locked_before, default_currency, default_markup_percent, receipt_required_over, updated_at, time_zone
`

type UpdateSettingsParams struct {
	LockedBefore         pgtype.Date
	DefaultCurrency      string
	DefaultMarkupPercent pgtype.Numeric
	ReceiptRequiredOver  pgtype.Numeric
	TimeZone             string
	Now                  time.Time
}

// UpdateSettings replaces every setting at once; there is only ever the one
// row, written by the migration, so this never inserts.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (ExpensesSetting, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.LockedBefore,
		arg.DefaultCurrency,
		arg.DefaultMarkupPercent,
		arg.ReceiptRequiredOver,
		arg.TimeZone,
		arg.Now,
	)
	var i ExpensesSetting
	err := row.Scan(
		&i.ID,
		&i.LockedBefore,
		&i.DefaultCurrency,
		&i.DefaultMarkupPercent,
		&i.ReceiptRequiredOver,
		&i.UpdatedAt,
		&i.TimeZone,
	)
	return i, err
}
